### ISSUE TITLE
Allow easy installation

### ISSUE THREAD

**Issue by hcorion** [oilshell/oil#10]
I attempted to try and create an Arch Linux PKGBUILD for this project and realized that setup.py install only installs python libc, and not oil. Could this be fixed?

**Comment by andychu** [comment]
An Arch package would be great, but it's a little early for that.  As mentioned in issue #7 , cd isn't even working yet!

Right now OSH is passing on 248 tests and failing on 166:

http://www.oilshell.org/git-branch/master/11eaa05c/andy-home/spec/RESULTS.html

Once we get that closer to 95% or so, I think it will make sense to release an Oil 0.1, and then an Arch package will make sense.  I hope that will be in a couple months.

I will ping this bug then :)  Thanks for trying this.

**Comment by andychu** [comment]
It's now packaged as a C program rather than a Python program:

http://www.oilshell.org/blog/2017/07/23.html

Please try it and let me know what goes wrong!  :)
