### ISSUE TITLE
read builtin: backspace interpreted as ^?

### ISSUE THREAD

**Issue by mil** [oilshell/oil#1000]
In most normal shells like bash, ash, etc., backspace within `read` is interpreted normally and deletes the previous character.

In oil (tested against 0.9.3), within  `read`, backspace shows up as `^?`.

**Comment by andychu** [comment]
I believe this has something to do with 

https://github.com/oilshell/oil/commit/af5823bb500e3c841ae69714f719116677d03f81

I think we added ICANON for `read -d` ?

**Comment by andychu** [comment]
Yup the issue is that we **unconditionally** change the mode to ICANON.

bash behaves the same way with `-d` when you hit backspace

```
bash -c 'read -d , x'
```

Good catch!

**Comment by andychu** [comment]
Fixed -- will be out with the next release.  This turned out to be a simple problem

**Comment by mil** [comment]
Nice! Thanks for resolving, looking forward to next release

**Comment by mil** [comment]
Fixed as of 0.9.4 - thanks!
