### ISSUE TITLE
Add is-main builtin

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1011]
https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Feedback.20on.20Port.20to.20OSH.20.28oil-dev.20walkthrough.29/near/262191531

Yeah I need something like this a lot, what I usually do is

```
if test "$(basename $0)" = 'wild.sh'; then
  "$@"
fi
```

https://github.com/oilshell/oil/blob/master/test/wild.sh#L716

This is not great since if you rename the script you have to change `wild.sh`, etc.  Also you could have 2 scripts called `wild.sh`

Looking at the example Oil module, we don't have the main guard. I agree it's something we'll need for idiomatic Oil code

http://www.oilshell.org/release/latest/doc/oil-language-tour.html#appendix-example-of-an-oil-module

**Comment by andychu** [comment]
Brainstorming on this thread: https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Module.20Brainstorming

**Comment by andychu** [comment]
I realized there are actually 2 types of modules: the `runproc` ones that use $0 Dispatch, and ones that have a single `main` or `_main` proc (undispatched scripts)

**Comment by andychu** [comment]
I think `proc _main` and a special register `_is_main_module()` is the winner, and it can be combined with `runproc`

**Comment by andychu** [comment]
In the spirit of opening up the project to contribution, I created this dev-tutorial label.  I think this change will be small-ish and will be a good intro to the codebase.  It involves changing the following places:

- the `osh foo.sh` invocation, in `core/shell.py` (annoyance: we also have core/shell_native.py and core/oven.py)
- the `source` builtin
- the list of builtin functions for `_is_main_module()`
- `redefine_proc`  special case for `_main`
- the executor has to check `_is_main_module()` and then execute the `_main` proc


OK that's probably "medium" rather than "small", but could be approachable

**Comment by bar-g** [comment]
I'm not sure why anything more than a `runproc` modified as in #1696 would be needed, i.e. when `runproc` would not run the proc if being sourced (unless `--even-sourced` or `--only-sourced` args are passed).

```
#!/usr/bin/env ysh

proc init {
   mount /media/disk
   # append umount command to some future ysh internal list/dict typed exit trap variable, here
}
proc list(subdir) {
   ls /media/disk/$subdir
}
runproc --even-sourced init
runproc list media/disk/etc
```

**Comment by bar-g** [comment]
What I like about the `runproc` as "run guard" proposal is that it keeps things short and explicit, comprehensible even without comments and if executed from within more elaborated conditionals, without requiring any new or special syntax, i.e. just building on your idea of an idiomatic `runproc` declaration in YSH.

It ought to work with every and no naming convention for "*__main" procs.

I think `__name__ == '__main__'` seems obscure in comparison.

Downsides anyone?

**Comment by andychu** [comment]
`runproc --even-if-sourced` would solve the problem, though I feel it's a bit ad hoc

The obvious problem is that you might not want `runproc` as your main

Probably the easiest thing isj ust

```
if is-main { runproc @ARGV }

if is-main { main @ARGV }
```

Haven't thought about it too much lately

**Comment by bar-g** [comment]
> `runproc --even-if-sourced` would solve the problem, though I feel it's a bit ad hoc

Could be.
Especially since a more standard way to specifically execute a proc even if sourced (i.e. allways) seems to be to support `proc <command> @ARGV` in addition to  `@ARGV`, just as `buildin` and `command`.

> The obvious problem is that you might not want `runproc` as your main

Not sure what you mean.
Do you mean not a proc? Then, what about separating `run` and `proc`?:

> Probably the easiest thing is just
> 
> ```
> if is-main { runproc @ARGV }
>```

`ifrun proc @ARGV`
`ifrun proc my_main @ARGV`
`ifrun command my_submodule.sh @ARGV`
 
Other ideas: `asmain`, `ifmain`, `nosourced`, `source --no`, `unless-sourced`, ...?

But is there really a true notion of "run" and or "main", or is there only "if sourced"? Because (not) being sourced would continue to be true within procs. My use-case was "if not-sourced", and it could imagine it be useful even within procs, not sure about "is-main".

`if not sourced { proc my_main @ARGV}`?

Would there still be a need for `runproc`?

**Comment by andychu** [comment]
I think the two valid solutions are:

1. make a special name `_main`

```
proc _main {
  runproc @ARGV
}  
```

2. Add a builtin `is-main`

```
if is-main {
  runproc @ARGV
}
```

I kinda like the second, since it's explicit

If you don't care about this, then you just use

```
runproc @ARGV
```

Thoughts?

**Comment by andychu** [comment]
Oh, to answer the question `is-main` is equivalent to "not sourced"

We could also do

```
if ! is-sourced {
  runproc @ARGV
}
```

but that's longer

**Comment by andychu** [comment]
Well if `_sourced` is a string, then it would have to be

```
if test -z $_sourced { }   # kinda ugly, -z means zero length
```

Regarding `not` as an alias for `!` -- it's a little tricky, I think it would be a breaking change.   I agree most people don't know how to use `!` the right way, and it's also space sensitive, but I think we could just explain it more

`!` is consistent with `&& ||`, although those are both not used nearly as much in YSH

---

I'm a little on the fence about `module foo || return 0`

That could  be `if ! module foo { return 0 }` which is ugly

**Comment by bar-g** [comment]
Agreeing, `is-main` seems better suited. Thanks!

**Comment by andychu** [comment]
Just implemented this, thanks for the feedback!

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2023/09/release-0.18.0.html

Although there is a non-zero chance that I think

```
proc main {
}
```

as a magic word is better than

```
if is-main {
}
```

Due to feedback

https://old.reddit.com/r/oilshell/comments/16l3h0c/oils_0180_progress_on_all_fronts/


It depends on what works for tree-shaking, as I noted in this release post

Discuss on Zulip :)
