### ISSUE TITLE
Enforce the order of proc params

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1023]
Almost done, but we should probably enforce the order more exactly:

    untyped* rest? typed*

_Originally posted by @andychu in https://github.com/oilshell/oil/issues/984#issuecomment-979675436_

**Comment by andychu** [comment]
This should be done in recursive descent style:

1. while loop
2. if statment
3. while loop

**Comment by jcob-sikorski** [comment]
What ```untyped* rest? typed*``` specifically describes?

**Comment by andychu** [comment]
The code is here:

https://github.com/oilshell/oil/blob/master/oil_lang/expr_to_ast.py#L854

And there are spec tests here, which are run with `test/spec.sh oil-proc`

https://github.com/oilshell/oil/blob/master/spec/oil-proc.test.sh

But actually I found a pretty good place to put these tests.

So all these syntax errors are good.

https://github.com/oilshell/oil/blob/master/test/parse-errors.sh#L650

Let me know if that makes sense.  If you're familiar with recursive descent it should make sense, i.e.g translating the little grammar to imperative code.  

(This is how CPython works by the way (or used to work until the recent PEG change) -- it has a "transformer" that takes the homogeneous parse tree and creates a more typed AST.)


```
~/git/oilshell/oil$ test/parse-errors.sh proc_sig 

===== CASE: proc f[] { echo hi } =====


  proc f[] { echo hi }
       ^~
[ -c flag ]:1: Invalid proc name 'f['

===== CASE: proc : { echo hi } =====


  proc : { echo hi }
       ^
[ -c flag ]:1: Invalid proc name ':'

===== CASE: proc foo::bar { echo hi } =====


  proc foo::bar { echo hi }
          ^~
[ -c flag ]:1: Syntax error in expression (near Id.Expr_DColon)

```

**Comment by andychu** [comment]
And please feel free to join https://oilshell.zulipchat.com and ask any questions on `#oil-dev`

If you have problems with the instructions  / build or think it should be improved let me know

https://github.com/oilshell/oil/wiki/Contributing
