### ISSUE TITLE
Sourcing a directory causes osh to exit

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1043]
When running `source` or using `.` on a directory, osh exits completely. In bash, this is an error but the whole shell doesn't exit.

bash:

```
$ source Documents
bash: source: Documents: is a directory
$
```

osh:

```
$ source Documents
osh I/O error: Is a directory

[Process completed]
```

This is annoying as accidentally hitting enter at the wrong time can kill the whole shell.

```
$ osh --version
Oil version 0.9.5
Release Date: 2021-11-29 06:27:28+00:00
Arch: x86_64
OS: Darwin
Platform: Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64
Compiler: GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)
Interpreter: OVM
Interpreter version: 2.7.13
Bytecode: bytecode-opy.zip
```

**Comment by andychu** [comment]
Verified, thanks!  I will look at this

**Comment by andychu** [comment]
I should also note the Darwin port was contributed and might have weird bugs, e.g. #958 

which should go away with `oil-native`

But this is a good bug easily reproducible on Linux, thanks

**Comment by andychu** [comment]
Released! http://www.oilshell.org/release/0.9.6/

Thank you for the fix
