### ISSUE TITLE
Ditch Python 2.7, use Python 3.

### ISSUE THREAD

**Issue by gpshead** [oilshell/oil#105]
The title says it all.

**Comment by andychu** [comment]
OK I updated the main FAQ:

http://www.oilshell.org/blog/2018/01/28.html#toc_11

**Comment by mjpieters** [comment]
I can see that there were pain points with Python 3, but the larger issue is that support for Python 2 *ends* on 01-01-2020. That means no bug fixes, no security fixes. It may be an implementation detail, but you do now need a plan to move to a different implementation. Python 3 or something else.

**Comment by Abdur-rahmaanJ** [comment]
@mjpieters commented, weird ^^

**Comment by andychu** [comment]
FAQ updated again http://www.oilshell.org/blog/2018/03/04.html#faq
