### ISSUE TITLE
osh doesn't support -l (--login) flag

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1052]
This is a flag in bash that says to run it as if it is a login shell. It is used by https://github.com/purcell/exec-path-from-shell as an example to try and make sure any parts of the path that are expected to be set are set.

Based on how osh sources start up files, I think that the correct thing to do in this case would be either to do nothing or to set `$0` to `-osh` instead of just `osh` but do nothing else (I've definitely seen scripts that check if `$0` starts with `-` or not and do things based on that, but whether `osh` wants to support that kind of stuff or not is questionable).

**Comment by andychu** [comment]
Hm we do check if the first char is `-`, but apparently we don't do anything with that information!  I think it was just to not break if we are started as a login shell.

https://github.com/oilshell/oil/blob/master/bin/oil.py

I don't see that it affects $0:

```
$ bash  --login  -c 'echo $0'
bash
```

Should we just accept `--login` and -l` as a no-op?  That would be acceptable.  Or feel free to suggest any other behavior, including with tests (thanks for writing the failing spec test for redirect; I still plan to look at it)
