### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by wizard-28** [oilshell/oil#1057]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/567) to add Oil/OSH to our repository.

Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.

**Comment by andychu** [comment]
Thanks for the work on packaging Oil.  I made some comments on the PR.  I don't maintain any  of the packages but I'd like to keep track of them here:

https://github.com/oilshell/oil/wiki/Oil-Deployments

**Comment by wizard-28** [comment]
> Thanks for the work on packaging Oil. I made some comments on the PR. I don't maintain any of the packages but I'd like to keep track of them here:
> 
> https://github.com/oilshell/oil/wiki/Oil-Deployments

I've edited that page to include Pacstall instructions to install `oil`
