### ISSUE TITLE
build/dev.sh ubuntu-deps fails: Package 'python-pip' has no installation candidate

### ISSUE THREAD

**Issue by eliminmax** [oilshell/oil#1063]
The `python-pip` package was used for Python 2, but now that Python 2 has hit end-of-life, current versions of Ubuntu and Ubuntu-based systems are unlikely to include that package in their repositories. This causes `build/dev.sh ubuntu-deps` to fail on Pop!_OS 21.10, which includes the Ubuntu repos by default.

**Comment by andychu** [comment]
Thanks for the report, yes this is a problem.

Although the only thing we need pip for is flake8 and typing, which aren't strictly necessary to change the code.

https://github.com/oilshell/oil/blob/master/soil/deps-py.sh

I'm working on putting things in containers -- many notes on the `#containers `Zulip stream about this.

I think you should be able to build and run Oil just by skipping this, e.g. with `build/dev.sh minimal`

and perhaps `build/dev.sh all`, which requires a few more things.  Let me make another pass over the Contributing doc and to see if it needs updates

**Comment by andychu** [comment]
Hm looking at a comment in this function, what happens if you do `apt-get install python2-dev` on PopOS?

It looks like Ubuntu 20 does have it

https://packages.ubuntu.com/focal/python2-dev

I think that is the only one you really need to do `build/dev.sh minimal`.  Sorry for now it will be have to be worked around, but in the future we should have containers with all the dev tools that work on any distro.

```
  #   TODO: upgrade Ubuntu and change to python2-dev                                                                                                                                                               
  # gawk: used by spec-runner.sh for the special match() function.                                                                                                                                                 
  # time: used to collect the exit code and timing of a test                                                                                                                                                       
  # libreadline-dev: needed for the build/prepare.sh Python build.                                                                                                                                                 
  # cmake: for build/dev.sh yajl-release                                                                                                                                                                           
  set -x  # show what needs sudo                                                                                                                                                                                   
  sudo apt install \                                                                                                                                                                                               
    python-dev gawk libreadline-dev ninja-build cmake \                                                                                                                                                            
    python-pip python3-pip   

```

**Comment by eliminmax** [comment]
I edited **build/dev.sh** to replace `python-pip` with `python2-dev`, and reran the commands listed in the Contributors Quick Start page on the wiki, and it seemed to work fine.

**Comment by andychu** [comment]
Great thank you for letting me know!  I will keep this issue open until we have a better fix

Let me know if you run into any other problems or need help with the code

**Comment by pdebelak** [comment]
FYI since I'm setting up a computer after an OS re-install and running into this same issue. I needed to run:

```shell
sudo apt install -y \
  cmake \
  gawk \
  ninja-build \
  python2-dev \
  python3-pip
```

And then download pip2 via the get-pip.py script by running:

```shell
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python2 # feel free to not just pipe curl into python2 if you're not feeling brave
```

Then I could download the pip-based dependencies with:

```shell
pip2 install --user pyyaml typing flake8 pygments
pip3 install --user mypy
```

**Comment by andychu** [comment]
Ah thank you, this is helpful.  I didn't know that there was a bootstrap script for pip!

This is a good workaround for now.  For the long term I filed #1075 to allow using the CI containers (which is a continuation of #803, which saw a lot of progress recently)

Please keep me updated on all the local dev problems, this is useful :)  Ironically we are running into problems that shell has  (versioned dependencies) while writing a shell.  This should feed back into Oil itself, like #848

**Comment by andychu** [comment]
I removed python-pip from the setup script, which is now `build/py.sh ubuntu-deps`

https://github.com/oilshell/oil/blob/master/build/py.sh#L34

So that solves this in the short term

In the long term I'm keeping track of all these bugs labelled `dev-friction`, so please feel free to file more bugs if you have problems getting started
