### ISSUE TITLE
Tab completion does not suggest aliases or functions

### ISSUE THREAD

**Issue by eliminmax** [oilshell/oil#1064]
Tab completion appears to properly suggest builtins and external commands, but not aliases or functions. It appears that `compgen -A command` includes aliases, but they are not suggested

**Comment by andychu** [comment]
Hm yes it appears we differ from bash here, bash will complete aliases and functions even when you invoke with `bash --noprofile --norc`

I haven't touched this area of the code in awhile ...

Hm but looking at it I think there is a bug, not just unimplemented functionality, because  this part is supposed to do it .. hm

https://github.com/oilshell/oil/blob/master/osh/builtin_comp.py#L168



This is related to #544

**Comment by andychu** [comment]
Oh duh, I think the bug is that at startup we run the equivalent of `complete -A command`, but then when that code runs, the alias dictionary is empty, and so is the list of procs

So if you run it again, then it completes.  But that isn't the right behavior

**Comment by andychu** [comment]
Yeah so if I run `complete -E -A command` again after defining a function, it does find the function, but we shouldn't have to do that

https://github.com/oilshell/oil/blob/master/core/shell.py#L79

Thanks for the report!  Not sure exactly what the solution is yet

**Comment by andychu** [comment]
Ahh this bug was introduced by adding type annotations :-/  

https://github.com/oilshell/oil/commit/e06b6f27d8274df92591459512ef0544c817d2b7

I needed to make all the dicts conform to the same signature, so I made a copy with `list()`, which breaks the code!  The dict has to be mutable and shared!

**Comment by andychu** [comment]
This is now fixed, will be out with the next release.

Great report, thanks!

**Comment by eliminmax** [comment]
Thank you! I'm impressed with this project, and it was a great surprise to see how quickly you've responded to my issue reports. Best of luck!

**Comment by andychu** [comment]
Fixed in 0.9.7: https://www.oilshell.org/blog/2022/01/notes-themes.html
