### ISSUE TITLE
"Contributing" build instructions require functions removed in commit 3e7b4fc

### ISSUE THREAD

**Issue by eliminmax** [oilshell/oil#1066]
The [Three Kinds of Builds](https://github.com/oilshell/oil/wiki/Contributing#three-kinds-of-builds) section of the Contributing wiki page includes the following as part of the git repo -> release tarball process:
```sh
build/prepare.sh configure      # configure CPython
build/prepare.sh build-python   # compile CPython
```
The `configure` and `build-python` functions were removed in commit 3e7b4fc, so these steps fail.

**Comment by andychu** [comment]
Thanks, this was due to the container updates I mentioned.  Now it is:

```
soil/deps-tar.sh layer-cmark
soil/deps-tar.sh layer-re2c
soil/deps-tar.sh layer-cpython
```

Let me know if that works, I just did it  on a couple machines and it seems good

**Comment by andychu** [comment]
I think this is fixed, but if you have problems or questions let me know
