### ISSUE TITLE
Revisit SOURCE_NAME vs BASH_SOURCE (SOURCE_NAME is osh-specific)

### ISSUE THREAD

**Issue by BatmanAoD** [oilshell/oil#108]
There is no POSIX-compliant way for a shell script to determine the path of the script file itself. Issue #96 already addresses the issue of symlinks, but does not address sourced shell scripts. See the "how to handle sourced invocations" section's "tl;dr" [here](https://stackoverflow.com/a/29835459/1858225).

I have only ever needed this feature in Bash, so I am only familiar with using `$(BASH_SOURCE[0]}` to get the full script path. However, OSH doesn't yet implement `BASH_SOURCE` (although I assume that at some point it will need to, in order to support transitions away from Bash?).

Does OSH have support for any other way to get the path of a sourced script? If it's a solution that also works in `ksh` or `zsh`, so much the better.

**Comment by BatmanAoD** [comment]
Oops, I didn't see #96 before opening this. I'll edit to make this exclusively about *sourced* files, since the other one is exclusively about *symlinked* files.

**Comment by andychu** [comment]
I have seen `$BASH_SOURCE` a fair amount, so I think it makes sense to emulate it.

I did some research on BASH_SOURCE and the related FUNCNAME variables and so forth.  What really bugged me about them is that there is an off-by-one error in bash?  There are all these array variables that correspond to that stack:

- source file - BASH_SOURCE
- function - FUNCNAME
- line number - LINENO I think

But one of them is off by one!  That is why I made my own SOURCE_NAME, just for debugging:

https://github.com/oilshell/oil/blob/master/core/state.py#L728

However I may want to look into it again.  I just did the minimal thing to be able to debug scripts.  I didn't encounter any scripts that depend on BASH_SOURCE, but I won't be surprised if there are some.

**Comment by BatmanAoD** [comment]
Well, I use it regularly! The code is proprietary (unfortunately everything at my work is), though, so I can't share the scripts themselves.

Suffice to say that I have a number of scripts that need to use paths relative to the locations of the scripts themselves to do things like load auxiliary functions by sourcing other scripts. Near the top of every script I have:

```
##############################################################################
# Meta-info
##############################################################################
scriptpath="$(readlink -f "${BASH_SOURCE[0]}")"
scriptname=$(basename "${BASH_SOURCE[0]}")
```

**Comment by BatmanAoD** [comment]
For what it's worth, I've never used any index other than `0` into `BASH_SOURCE`. Maybe as a temporary measure we could just implement it as a single-element array?

**Comment by andychu** [comment]
Yeah I think we should have it.  I'll have to look into the thing that annoyed me, but that's not a reason to hold this up.

I already implement the FUNCNAME array variable, so it shouldn't be to hard to implement the $BASH_SOURCE array variable.

----

OK I was in the middle of writing about the special case for `${BASH_SOURCE[0]}`, and I agree that should be fine to start :)  I don't know how it interacts with various entry points though, like `-c` and `source`, etc.

**Comment by BatmanAoD** [comment]
Your `SOURCE_NAME` actually does exactly what I want. Actually, I prefer it to `BASH_SOURCE`, except for the tiny issue of Bash not supporting it... ah well.

Also, this may be worth opening another issue: `FUNCNAME` in Bash seems to have either `main` or `source` as its last element, depending on whether the script was sourced interactively or is run on its own. (There may be other conditions, I suppose; I haven't experimented extensively or researched it.) `osh` not to include this top-level name in the array.

**Comment by andychu** [comment]
Yes I want to revisit BASH_SOURCE vs SOURCE_NAME.  It's tricky to balance these design objectives:

- avoid inventing new things (at least for `osh`)
- avoid slavishly copying weird quirks of bash.  I found some quirks but maybe they aren't as bad as I thought.

Yes please open a bug for `FUNCNAME`.  I implemented the bare minimum to run debug Debian/Alpine scripts so it's not surprising there are problems.

**Comment by andychu** [comment]
note: there's also CALL_SOURCE in the code, but it's not documented

**Comment by andychu** [comment]
I removed SOURCE_NAME and CALL_SOURCE because I haven't used them.

So Oil just has bash-compatible stuff for now.  I haven't needed this in awhile but I expect that more debugging improvements in general will be useful.  But it needs feedback from people actually debugging
