### ISSUE TITLE
0.9.7 release issues

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1083]
https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Oil.200.2E9.2E7

Small issues

- [ ] mycpp/examples/strings started failing
- [x] publish `test/interactive`
- [ ] not sure if I care: 0.9.1 had stale benchmarks

**Comment by andychu** [comment]
Oops 0.9.8 came out but I didn't fix mycpp/examples/strings

**Comment by glyh** [comment]
I can't configure, make & install a release tarball that is generated by myself. Something in _build is missing.

**Comment by andychu** [comment]
Hm maybe start a thread on Zulip about this, or a new issue?  This isn't quite related to this issue

This sounds related to:

https://github.com/oilshell/oil/wiki/Contributing#three-kinds-of-builds

But it isn't well documented

However it does run in the continuous build, so it is automated and doesn't just work on one machine

**Comment by andychu** [comment]
- Hm the mycpp problem is actually a reporting problem with getting 0.0 for timing

- https://www.oilshell.org/release/0.9.7/benchmarks.wwz/mycpp-examples/
- https://www.oilshell.org/release/0.9.8/benchmarks.wwz/mycpp-examples/

Then the ratio doesn't divide well

**Comment by andychu** [comment]
Nothing really to do here

**Comment by andychu** [comment]
Nothing really to do here
