### ISSUE TITLE
Resolve symlinks to bash

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1097]
I symlink oil to bash on a folder X, which is prepended to my PATH, so that I can use osh instead of bash. However, it won't work. 

I found that oil and osh are actually symlinks to oil.ovm, so I guess making some changes to ovm so that it would recognize oil as oil, and anything else as osh would be good?

**Comment by glyh** [comment]
I could create shell scripts like:
```sh
#!/usr/bin/env sh
osh "$@"
```
But I don't like it this way because its another layer of dependency on sh, which is bash on many systems.

**Comment by andychu** [comment]
Hm can you give a repro for this?  e.g. what steps you took, what happens, and what you think should happen?  

I think you can symlink `oil.ovm` as bash, but I'm not sure if that's what you're trying to do

**Comment by glyh** [comment]
```sh
ln -s (which oil.ovm) bash
./bash
oil: Invalid applet name 'bash'.
```

**Comment by andychu** [comment]
OK this is reasonable to allow testing, I changed it so that anything that ends with `sh` including `sh` is equivalent to OSH.

If it's `oil` then it will behave like Oil, etc.

Thanks for the report

**Comment by andychu** [comment]
Out a couple weeks ago: https://www.oilshell.org/release/0.9.9/
