### ISSUE TITLE
shopt block syntax should accept oil:all

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1099]
As title. It would be great if there's some kind of mechanics to make them work together. e.g. through some module mechanics. Therefore user can use oil in their own scripting environment, yet depending on osh scripts from legacy environment.

**Comment by glyh** [comment]
I think this can be easily fixed by adding some options to the source command.

**Comment by andychu** [comment]
I don't recommend it, but you can do this already with something like

```
shopt --unset oil:all {
  source foo.sh
}
```

or vice versa

```
shopt --set  oil:all {
  source foo.oil
}
```

What I'd recommend instead is to simply invoke one script from the other.  You can invoke an OSH script from and Oil script and vice versa.  Using  the "$0 dispatch pattern"  would probably help.


Some more info: https://github.com/oilshell/oil/wiki/OSH-versus-Oil

**Comment by glyh** [comment]
This does not seem to be working, in my oilrc:
```
shopt --unset oil:all {
  source ./oshrc
}
```

**Comment by andychu** [comment]
Hm that is odd, it does seem like there is an issue using the block syntax

Both of these don't cause an error

```
osh -c 'shopt -s oil:all`
oil -c 'shopt -s oil:all`

```

But adding the block introduces an error.  I will look into it

**Comment by andychu** [comment]
Ah OK now I see why ... this is more like an oversight than a bug

I think that should work so you can interoperate between the two

**Comment by glyh** [comment]
How is this implemented? Is this hard coded to consume a block after it, or blocks are a basic type of oil that can be passed around in oil? I personally prefer the second way.

**Comment by andychu** [comment]
It's designed as a first class type, and should be part of the `value_t` enum in `core/runtime.asdl`

However it's not fully exposed to users right now.  #1025 is part of it

**Comment by andychu** [comment]
This came up here:

- #951 

Because config file evaluation need an implicit `shopt --set oil:all`

**Comment by andychu** [comment]
OK this will be out with the next release!

**Comment by andychu** [comment]
Release awhile ago: https://www.oilshell.org/blog/2022/07/release-0.11.0.html
