### ISSUE TITLE
`pwd` default behavior is `-P`, but other shells use `-L`

### ISSUE THREAD

**Issue by BatmanAoD** [oilshell/oil#110]
While working on #109, I discovered that in dash, bash, and mksh, `$PWD` is equivalent to `$(pwd -L)`, but in `bin/osh`, it's equivalent to `$(pwd -P)`. I believe the default should probably be changed to match the common behavior.

`-P` dereferences symlinks.

With  `/tmp/cd-symtarget` a directory and `/tmp/cd-symlink` a symlink to `cd-symtarget`, this is the behavior in most shells versus `osh`:

With `bash`:
```
bash$ cd /tmp/cd-symlink
bash$ pwd
/tmp/cd-symlink
bash$ pwd -P
/tmp/cd-symtarget
bash$ pwd -L
/tmp/cd-symlink
```

With `osh`:
```
osh$ cd /cd-symlink
osh$ pwd
/tmp/cd-symtarget
osh$ pwd -P
/tmp/cd-symtarget
osh$ pwd -L
/tmp/cd-symlink
```

**Comment by BatmanAoD** [comment]
...actually, it looks like `pwd` is not implemented by `osh`; on my system it's `/bin/pwd`. And indeed the man page states that `-P` is the default, not `-L`.

Looks like `bash`, `dash`, `zsh`, and `mksh` all implement it as a builtin, with the default behavior reversed. So for compatibility, I think `osh` probably needs to implement this as a builtin, too.

**Comment by andychu** [comment]
Yes, if all the shells agree, then `osh` should do the same thing!

If you want to take a stab at a new `pwd` builtin, I'd appreciate it :)
