### ISSUE TITLE
Missing location info

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1118]
- [ ] the `[` in `a[i]` for IndexError
  - expr.Subscript as only `expr` fields, we need a Token

Example from Zulip:

```
  for snippet in (snippets) {
    ^~~
'./nix-snippets.oil':96: fatal: Expected function to return a bool, int, float, or string.  Got <class 'pylib.collections_.OrderedDict'>
```

**Comment by andychu** [comment]
Hit this here: https://oilshell.zulipchat.com/#narrow/stream/264891-oil-help

- Also TODO: check error message on `$snippets['status']` vs `snippets['status']`.  I think it's confusing

**Comment by Melkor333** [comment]
Another example is the following:
```
#!/usr/bin/env oil

var content = [ 1, 2, 4 ]
var count = 0
while (count < $len(content)) {
  #var line = content[@count]
  write $[content[count]]
  setvar count += 1
}
```

The above script gives the error:
```
 ./test.oil 
  var count = 0
  ^~~
'./test.oil':3: fatal: Expected function to return a bool, int, float, or string.  Got <type 'builtin_function_or_method'>
```
which points to the wrong line... (the `$` in `$len(content)` is wrong)

**Comment by andychu** [comment]
Released, thanks for the great feedback!  https://www.oilshell.org/blog/2022/08/release-0.12.4.html
