### ISSUE TITLE
Document variable assignment to a JSON (Dict) attribute

### ISSUE THREAD

**Issue by kellyjonbrazil** [oilshell/oil#1129]
In the documentation it shows how to read JSON into a variable and write it out, but doesn't show how you can select a portion of the JSON and assign that to a variable as a scalar, array, or map.

https://github.com/oilshell/oil/blob/master/doc/json.md

I'm working on adding examples of how to use `jc` in alternative shells. I was able to assign JSON to a variable, but I'm not sure the recommended way to further filter the variable and assign that value to another variable. This is what I came up with:
```
$ dig www.google.com | jc --dig | json read myvar
$ json write (myvar[0]['answer'][0]['data']) | json read mydata
$ echo $mydata
64.233.185.104
```
https://github.com/kellyjonbrazil/jc/wiki/Using-jc-With-Different-Shells

Is this a good way to do it or is there a better way to slice the data once it is read into Oil?

**Comment by kellyjonbrazil** [comment]
Thank you!

**Comment by kellyjonbrazil** [comment]
I do have a followup question:

In my example above I'm basically converting the Oil variable `myvar` into JSON so I can filter it and read it into another Oil variable `mydata` via STDOUT. This seems inefficient. I was thinking I could do something like:
```
oil$ = myvar[0]['answer'][0]['data']
(Str)   '142.250.138.104'
oil$ mydata=myvar[0]['answer'][0]['data']
```
But this doesn't seem to work as it assigns the literal string `myvar[0][answer][0][data]` instead of the data that expression is pointing to:
```
oil$ echo $mydata
myvar[0][answer][0][data]
```
I've tried different variations/styles of setting variables but I can't seem to get what I'm looking for. Is there a way to do this natively without translating back and forth between JSON and passing to/from STDOUT?

**Comment by andychu** [comment]
Ahh so this is actually a side effect of fixing #937 in the most recent release release.

It used to be that we disallowed shell style assignment in Oil

```
a=b   #  LEGACY, no space
```

and allowed

```
a = 'b'  # Oil assignment, with spaces.  Disallow the previous style because it's too close
```

Now it has to be

```
const a = 'b'
```

So as a side effect now allow `a=b` again in `bin/oil`.

I think we can simply disallow it again ... But not allow `a = 'b'` either,

Thanks for the feedback!  I was thinking about this too

**Comment by kellyjonbrazil** [comment]
Beautiful - yes, the `var` keyword is what I needed, thanks!
```
oil$ var mydata = myvar[0]['answer'][0]['data']
oil$ echo $mydata
142.250.138.104
```

**Comment by andychu** [comment]
The doc is released:

https://www.oilshell.org/release/0.10.1/doc/json.html

https://oilshell.zulipchat.com/#narrow/stream/325160-oil-discuss-public/topic/Oil.200.2E10.2E1.20Released!

I have an idea for `shopt --set parse_only_oil` to disallow shell-style assignment.   Thanks for the feedback!

**Comment by andychu** [comment]
Let me know if you see anything else.  Generally the expression language is like Python 

This doc is not yet polished, but it gives a "diff" vs Python:

https://www.oilshell.org/release/latest/doc/oil-vs-python.html

**Comment by kellyjonbrazil** [comment]
I ended up turning this into a blog post. Let me know if you would like any updates to the Oil section. Thanks!

https://blog.kellybrazil.com/2022/05/19/working-with-json-in-various-shells/

**Comment by andychu** [comment]
Great post, thanks!  I'm slightly surprised  at how much convergence there is :) 

This reminds me a bit of issue #736 -- I feel like a shell could make it easier to install / try new tools without root access, and without messing with PATH.  That always seems to be a barrier for trying new tools

That and versioning of the tools
