### ISSUE TITLE
'data' should be allowed in expressions (soft keyword or remove it altogether)

### ISSUE THREAD

**Issue by kellyjonbrazil** [oilshell/oil#1131]
Hi there - not sure if this is working as designed or is a bug.

I can access attributes deep into a JSON document using traditional bracket notation:
```
$ json write (myvar[0]['answer'][0]['data'])
"64.233.185.104"
```
I can access the same data by using the `->` notation one time in the expression:
```
$ json write (myvar[0]->answer[0]['data'])
"64.233.185.104"
```
But it doesn't look like I can use the `->` notation more than once in the expression:
```
$ json write (myvar[0]->answer[0]->data)
  json write (myvar[0]->answer[0]->data)
                                   ^~~~
[ interactive ]:16: Syntax error in expression (near Id.Expr_Name)
```

**Comment by andychu** [comment]
Oof!  Thanks for the report.  This is because I made `data` a keyword at the top level, intended for a future dialect :-/    

Unintended side effect, let me think about what to do ...

At the very least it should only be an issue at the top level, not in an expression.

**Comment by andychu** [comment]
Oh so actually there is a workaround, you can do `answer[0]['data']`.

But  we should probably get rid of that keyword

**Comment by andychu** [comment]
Fixed with https://github.com/oilshell/oil/commit/eb7a4cfbbf307e85bc2afb1548ecf6580333726a

**Comment by andychu** [comment]
Release awhile ago: https://www.oilshell.org/blog/2022/07/release-0.11.0.html

Thank you for the report!  More feedback is welcome
