### ISSUE TITLE
Disallow shell style assignment in Oil

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1132]
From #1129 

This was a side effect of fixing #937 

`a=b` should be disallowed

what about `PYTHONPATH=foo myscript.py` ?  I guess allow that?  Although we had the `env` prefix too

I think `shvar` and `env` make sense as "parallel"

**Comment by andychu** [comment]
Noted by @kellyjonbrazil

**Comment by andychu** [comment]
Fixed https://github.com/oilshell/oil/commit/67161958d3aab4152cc4dd3629d06c99fc734f86

**Comment by bar-g** [comment]
Did you disable that common environment setting idiom like `PYTHONPATH=foo myscript.py`?

Because even fish is finally supporting it. It seems to be something that's just too commonly used by existing code when calling out for ever wanting it break with your shell.

After years of complains a newly run-up issue got accepted and implemented: https://github.com/fish-shell/fish-shell/issues/6048

**Comment by andychu** [comment]
Yes I did disallow it -- I've been going back and forth.

The idiom is supposed to be `env PYTHONPATH=foo myscript`.

In fish it was apparently `begin; set -lx FOO bar; cmd; end.` which is not good!

But they brought up the issue of **shell functions**.

### Solution?

One solution is to make `env` a builtin.  It's a POSIX command so I don't think that's horrible.  

And maybe we only enable in Oil?  In OSH env is external, and in Oil it's builtin?

But we don't have anything like that now.


### Interactive vs. Batch

Another response: You can always `shopt --set parse_sh_assign` in your `oshrc`/`oilrc`.

I agree that PYTHONPATH=foo is sort of "in the fingers".

But Oil is a little bit biased toward **Programs**.  And I don't think 3 extra characters is a dealbreaker for interactive.  Also I don't think shell functions are very common for interactive use!  (although they should be in Oil!)

------

So those are my thoughts -- comments appreciated

I agree that it will come up -- it's a prominent thing.

It's a little bit like my reluctance to change the redirect syntax ---  #832  parse_amp is probably punted.  Because people are used to that.

### Another Option: Make two options

- `parse_sh_assign`
- `parse_sh_env`



Sort of related to #851

**Comment by andychu** [comment]
Another issue is that it conflicts with config files  #951 , like

```
task mytask {
  user = 'bob'
  perms = 0o755
  TASK build {
    PYTHONPATH=. foo.py

    PYTHONPATH = '.'  # this is an assignment that differs by a space!!!  TOO SUBTLE

    env PYTHONPATH=. foo.py   # this is a better way of writing it
  }
}
```

**Comment by andychu** [comment]
We can discuss more on #1138 -- I think that is the right solution although I wouldn't say it's super high priority ...

**Comment by bar-g** [comment]
I didn't even think or notice `env` missing to support expression assignments, as I see it that's separate issue.

I think the underlying reason that the compatible (inline) shell-environment assignments are so important is, that it's a very common and basic unix (not just the newer bash or linux) command execution standard. It's simply the-way to do it, even in fish now. And it's not just in peoples fingers, it's in examples and every script there is to start arbitrary programs which couldn't (and shouldn't) care less under which shell they are run. Controlling webservers and scripts etc. (e.g. RAILS_ENV=production ...). And to ssh into some machine and finding the interactive shell to error on such basic things, I'm sure makes people go what that shell tripping me on this? Nah, any good.

Simply executing programs is different from scripting, and I guess the universal basics simply must work in every shell to get reasonably acceptable in the wild. 

Would there be a way to allow string assignments in interactive mode? Possibly somehow limited to the first-couple-of-words before the wrapped command?
Isn't it necessarily to special case this anyway, because the assignment needs to get exported but only for the duration (enviroment) of the current command line, and dropped again for the next command?
The fish merge thread also has some more comments https://github.com/fish-shell/fish-shell/pull/6287

**Comment by andychu** [comment]
Well as I mentioned there is a way to get it: `shopt --set parse_sh_assign` in your `oilrc`!

However there is also one interesting solution I can think of.  Allow it at the **top level** which is equivalent to **interactive**, and disallow it elsewhere.

```
PYTHONPATH=. foo.py   # this is an interactive session or a quick and dirty shell script!

job myjob {
  PYTHONPATH = '.'  # "bare assignment" the way to assign variables inside blocks

  PYTHONPATH=. foo.py   # SYNTAX ERROR here!  Too similar

  env PYTHONPATH=. foo.py   # this works

}
```

Of course there are many job specification that work like this (think YAML for CI services):

```
job myjob {
  env {
    PYTHONPATH = '.'
  }
  argv = %(foo.py)
}
```

So actually you will probably never have `PYTHONPATH=. foo.py` inside a block ...

### Areas Where the Top Level is Different

- `const` and `var` are also different at the top level, for REPL reasons.  So this has some precedent ...

**Comment by andychu** [comment]
Hmm this could also go for regular assignment

```
X=foo  # top level and interactive

proc p {
  X=foo   # disallowed in "real code"
}
```

So then we could actually **get rid** of the whole option?  However there is a problem with this.  It breaks the following invariant:

- If you have a script with no functions, then wrap your whole script in `main() { }` and then call `main @ARGV` at the end.  

I think of that as the first step to upgrade a shell script.  Modularize it into procs

**Comment by bar-g** [comment]
Your pip, etc. user package installer tools probably use it, too.

**Comment by bar-g** [comment]
Hm, pointing users to oilrc to impact their whole environment doesn't seem like realistic solution.

Top level sounds much more like it could be part of it.
What do other shells do. I guess they parse the command line to see if they need to execute only this single command that has assignments prepended with the modified environment.

**Comment by bar-g** [comment]
> the point is that setvar has typed data

Yes, important point to make oil work.
But my point here is to support compatible command execution (environments) even in oil.

**Comment by bar-g** [comment]
This has details: https://unix.stackexchange.com/a/56449

**Comment by bar-g** [comment]
In other words: Things that are part of the standard *nix command interface probably just need to be supported by any shell, for it to support running arbitrary programs, which may of course call commands in the standard ways.

The redirection syntax also seems to fall in this category.

Augmentations are possible, even beneficial for cleaned up syntax, or required to make new shell features work for specialized programs.
Whereas breaking/disabling the standard way would make the shell fundamentally incompatible.

**Comment by andychu** [comment]
Yeah I think this probably right.  I just edited the language design principles -- **avoid breaking the top level / interactive shell**

https://github.com/oilshell/oil/wiki/Language-Design-Principles

So my argument was always that OSH is the place where compatibility happens, and Oil is new and can break it.

But yeah I think the problem is that it's not clear whether to choose OSH or Oil for your interactive shell!  (Right now I use OSH.)

But in the future I want there to be no argument about which to use.  There should only be one ...

----

At the very least, there should be a higher bar for breaking the top level than things like for loops, etc.


I'd guess that `PATH=foo myprogram` is  more common than simply `X=Y`.  So maybe the latter can be broken but the former can't.

**Comment by bar-g** [comment]
> I'd guess that PATH=foo myprogram is more common than simply X=Y. So maybe the latter can be broken but the former can't.

Well, do existing programs execute mere assignments? I wouldn't now what for? So yes, I came to the same conclusion for the moment.

Is the former currently actually parsed as that special, temporarily, exported, inline, environment variable setting?

"Variable assignments shall be performed as follows:" (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01)

**Comment by qubidt** [comment]
> Also I don't think shell functions are very common for interactive use! (although they should be in Oil!)
 
they're *incredibly* common in zsh land (if I'm understanding your remark correctly). 

`env FOO=bar func` seems like a reasonable compromise to me, but I can't say I ever loved shells overloading and extending standard unix commands. Is this common in oil/osh? (I've been aware of oil for a while but only just started looking into it seriously)

**Comment by andychu** [comment]
In the latest version of Oil, `FOO=bar` is disallowed, but `PYTHONPATH=. myfunc` is allowed!  So there should be no issue here.

That comment was mostly about an older more restrictive design

Thanks for the feedback

**Comment by andychu** [comment]
Release awhile ago: https://www.oilshell.org/blog/2022/07/release-0.11.0.html
