### ISSUE TITLE
Rename oil:basic -> oil:upgrade

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1137]
From @bar-g  on #678 

Reason: I think `osh:strict` `oil:basic` `oil:all` has more consistency.   

`strict:all`  was meant to imply the prefix of `strict_errexit`.  However there is no `oil_` prefix!

So the current scheme doesn't make that much sense.

- I think `osh:strict` makes more sense because you're taking the OSH language and subsetting it.  It still runs under other shells.
- `oil:basic` makes sense because you're writing in the basic parts of the Oil language, without breaking things.
- `oil:all` is for new scripts.  You have everything

https://github.com/oilshell/oil/wiki/OSH-versus-Oil

----

I'm wary of breaking things -- especially since I'm using `strict:all` myself  !!!

However I think what we can do is:

1. Make `osh:strict` an alias for `strict:all` in the next release.  Should be easy.
2. Change all the docs
3. Change the wiki.
4. Maybe even correct the blog
5. And then like 6 months from now, since we're pre-1.0, just drop `strict:all` altogether.

It seems feasible and probably worth it for such a prominent feature

It's one of the first things you hit when you get started

**Comment by bar-g** [comment]
Yep, I find `osh:strict` provides better context, very appreciated plan, here.

I'm unsure if directions got flipped when you say `oil:basic` is "without breaking things". Can't simple word eval, for example, break `for word in $sentence` style loops? 

`oil:contained`, `oil:low-impact`, `oil:conservative`, `osh:conserved`, `osh:remains`, `osh:mostly`, `osh:still`? Same things like 10 years ago?

**Comment by andychu** [comment]
Yeah reading `oil:basic` as `oil:low-impact` is roughly correct.

Technically `if ( ls /tmp )` is valid shell -- it means run the condition in a subshell.  But almost nobody does that, so most people won't notice the breakage.  (I have seen it though.)

Likewise `cd {` already means "change to the directory `{`".  However there is an obviously better way to spell that which is `cd '{'` or `cd \{`.

So the changes in `oil:basic` are unlikely to break things, but they can.

It's for things we can improve in a roughly compatible way.

On the other hand `var` and `const` are unconditionally taken over, similar to how bash takes over `declare` and so forth.  (Again the change would be trivial -- quote it like `'var'`)

**Comment by andychu** [comment]
And Simple word eval is an exception I mentioned here: https://github.com/oilshell/oil/wiki/Language-Design-Principles

It's what beginning users generally expect, and there's no other syntax I could think of ...

**Comment by bar-g** [comment]
Thank you for explaning, good text, and things seem well thought out.

And here, you may even have said it:
> roughly compatible way

if we can dare to gloss it over a bit: `oil:compat` or `oil:compatish`?

**Comment by bar-g** [comment]
`oil:backcompat`

**Comment by bar-g** [comment]
`oil:oshcompat`

**Comment by bar-g** [comment]
Now I have some that could match your description of "tentatively everything that's not too hard on breakage".
`oil:soft`, `oil:softcore`, `oil:firstcut`, `oil:blend` `oil:safest` `oil:contigent`


However, from this listing there doesn't seem to be much missing:
https://www.oilshell.org/release/0.10.1/doc/oil-help.html#option
So `oil:basic` could convey kind of a misconception or understating.
  `oil:yes`, `oil:ok`, `oil:enabled`, `oil:partly`, `oil:ponder`, `oil:almost`,  `oil:major`, `oil:bulk`, `oil:coherent`, `oil:breakleast`?

**Comment by andychu** [comment]
Those don't seem that different than `oil:basic`.  Another one is 

    osh:strict oil:upgrade oil:all


I'm OK with `oil:basic`.

The only weird thing is that it sometimes (often?) makes sense to have `oil:basic` and `osh:strict` on at the same time.  

That gives you the correctness errors, but leaves out some of the cosmetic stuff like `parse_backslash` and `parse_bare_word`.


So I wonder if this reads OK

    shopt --set osh:strict oil:basic  # it is confusing?

Or if this is better:

    shopt --set strict:all oil:basic

Or:

    shopt --set strict:all oil:upgrade

**Comment by andychu** [comment]
So really a problem with `osh:strict` is that you may want strict errors, but you're not actually writing in "only" in  OSH!

**Comment by andychu** [comment]
Yeah I guess a simpler way to say is that the strict options are NOT just a part of OSH.  They are part of Oil too

`osh:strict` makes sense when it's on its own, but not combined with `oil:basic`

**Comment by bar-g** [comment]
Yeah, the current option can be explained well from the options part of things, but new users are not familiar with them at all first. And the steps provided with the option groups actually help to make it much less necessary to know all the options in detail.

Expecially the usage, location on the scale, and marginal difference between oil:basic and oil:all stayed unclear to me for long. 
That's where I found the combination of the terms in osh:strict & oil:allow to be helpful.

Making a table it became more obvious that osh:strict renaming may not be necessary to make the osh language obvious, and strict:all is quite good. Only something like `oil:allowed`, `oil:almost`, `oil:modest` or `oil:osh_ok` etc. may add some better sense above oil:basic, by maybe more correctly conveying its much broader support:



## (DRAFT) OSH shell option presets for common scripting adjusting tasks
|        task    | use  |
| -------------  | ------------- |
| run a script initially written for other shells (the default) | #!/bin/osh | 
| ...with all sourced files | #!/bin/osh </br> OSH_HIJACK_SHEBANG=osh |
| ...while allowing adding of oil idioms | #!/bin/osh </br> shopt --set `oil:allow` |
| ...while enforcing maximal robust code</br> (all strict options) | #!/bin/osh</br> shopt --set `strict:all` |
| allow oil as much as possible with</br> without disabling common shell warts for compatibility / minimal  </br>legacy script breakage (also useful to source libs?)</br> (intersection of osh&strict&oil) | #!/bin/osh </br>  shopt --set `strict:all` `oil:osh_ok` |
| use oil proper* (all of oil combined + disabling most warts)  | #!/bin/osh </br> shopt --set `oil:all` |
  
*The last variant is equivalent to starting oil proper by simply using  `#!/bin/oil`

**Comment by bar-g** [comment]
> osh:strict makes sense when it's on its own, but not combined with oil:basic

Yes, that's why I thought the combination of osh:strict with oil:allow was working better, but with the table I think strict:all is good.

**Comment by bar-g** [comment]
I think something like "seamless" might be able to explain quite well the trouble it makes to nail that thing down.

**Comment by bar-g** [comment]
I have now edited the table above quite a lot.

**Comment by bar-g** [comment]
By now, it seems to me `oil:basic` isn't basic at all, it seems to be already much more in reality (misconception?)

`oil:least_adjust` `oil:loweffort` `oil:lowhanging`...?

easymigrate, migrate_ok, quick_migrate, ...?
easyadapt, slippy, adaptfew, orthogonal, lowpendent ?
leastchanges, leastdisrupt,

`oil:all_slick` vs. `oil:complete`?

**Comment by andychu** [comment]
I think one option is `oil:upgrade`.  After all our slogan is "upgrade path from bash", so it's nice to use the same word.

And it is possibly one of the first things you hit.

I agree it's more than "basic" implies.

These all seem to make sense:

```
shopt --set strict:all
shopt --set oil:upgrade
shopt --set strict:all oil:upgrade  
shopt --set oil:all
```

**Comment by bar-g** [comment]
Looking at it again: That `oil:upgrade` isn't consistent with any other wording can actually be seen as being fine. It can be viewed as just a transitional setting. I've put it into the table above together with some more edits.

I'd strongly suggest to just put the "Oilshell Usage" table into the "getting-started" document (between Setup and Tips).

**Comment by bar-g** [comment]
Not sure about `inherit_errexit, it's not mentioned in the error-handling doc anymore, is it still necessary? Would it create incompatibilities if setting it with oil:upgrade?

**Comment by bar-g** [comment]
Ok, the two related documentation peaces already prepared for this change are:

Intro/mini-tour draft for the hompage
https://github.com/oilshell/oil/issues/1127#issuecomment-1133749799

Usage table
https://github.com/oilshell/oil/issues/1142

**Comment by andychu** [comment]
OK that was pretty easy!  We still have to update the wiki everywhere

`oil:basic` is accepted but will be deprecated in the future

**Comment by andychu** [comment]
Release awhile ago: https://www.oilshell.org/blog/2022/07/release-0.11.0.html
