### ISSUE TITLE
allow temp bindings even in bin/oil (PYTHONPATH=. foo.py)

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1140]
(came up in #1132)

>>> The standard *nix command interface probably just need to be supported by any shell, for it to support running arbitrary programs, which may of course call commands in the standard ways.
>>> 
>>> The redirection syntax also seems to fall in this category.
>>> 
>>> Augmentations are possible, even beneficial for cleaned up syntax, or required to make new shell features work for specialized programs.
>>> Whereas breaking/disabling the standard way would make the shell fundamentally incompatible.

>> just edited the language design principles -- avoid breaking the top level / interactive shell
>> https://github.com/oilshell/oil/wiki/Language-Design-Principles
>> I'd guess that PATH=foo myprogram is more common than simply X=Y. So maybe the latter can be broken but the former can't.

> do existing programs execute mere assignments? I wouldn't now what for? So yes, I came to the same conclusion for the moment.

EDIT:
=> Well, sole assignments may be used with this portable pattern:
```
MORE=yes
export MORE
myprogram
```

So yes, Oil would have to support the special-case handling for both sole shell assignments and combinations of a shell assignments with a command, but restrict it to only the top-level?

 - [ ] `MORE=yes` bare assignments
 - [ ] `MODE=production MORE=yes myprogram` inlined temporary environment assignment exports
~~`export QUIET=true mydispatcher` permanent environment export (also mentioned as not to get disabled in: https://github.com/oilshell/oil/issues/678)~~ Edit: export does not seem to work when inlined.

Special case hanling is described at: "Variable assignments shall be performed as follows:" (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01)

Some more context: https://unix.stackexchange.com/a/56449

Related: (augmenting) Adding support for typed oil expression assignments: https://github.com/oilshell/oil/issues/1138 "env builtin for Oil"

**Comment by andychu** [comment]
If we allow this then I think #1138 is not necessary

**Comment by andychu** [comment]
This is now done.  You can test it out with `git pull` and `build/dev.sh minimal` and `bin/oil` ... let me know if you have issues

**Comment by andychu** [comment]
Release awhile ago: https://www.oilshell.org/blog/2022/07/release-0.11.0.html

I mentioned your help several times in the announcement -- thank you!
