### ISSUE TITLE
expressions should be tagged oil:all

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1148]
Analogous to #1147 

I fixed this case in the last release:

```
var x = $(false)  # now command_sub_errexit is on
```

But there is still stuff like this:

```
$ bin/osh -c 'var x = "foo:bar"; IFS=:; var y = $(write -- $x); echo $y';
foo
bar
```

That is bad.  So I think it must be `oil:all`, not just `command_sub_errexit`

The issue is that `var y = $(write -- $x)` should behave the same way **regardless  of context**.  Following the **local reasoning** principle

**Comment by andychu** [comment]
Maybe this is not that bad.

I think the bottom line is that 

- Oil code should go in `.oil` files running `bin/oil`
- OSH code should go in `.osh` files , and have `shopt --set oil:upgrade` and possibly `strict:all`
- If you want them to **interoperate**, it should be done with **processes** !!  NOT mixing different options in the same interpreter.
  -  when you start a new process, the options at the top of the file work.

You should not `source` together files with different options.

**Comment by andychu** [comment]
So I think the bug here is that you started using:

```
var y = $(write -- $x)
```

WITHOUT adding `shopt --set oil:upgrade`.   That includes `simple_word_eval`.

You should do these AT THE SAME TIME:

- Start using var and proc
- Set `shopt --set oil:upgrade`  , for more error handling and so forth

It can't  be that seamless and "local" by nature

**Comment by bar-g** [comment]
What's the reason some basic oil syntax is enabled in osh by default?

**Comment by andychu** [comment]
Yup you are right!  I just came to the same conclusion.

We have to disable `var` / `proc` in `bin/osh` to obey the local reasoning principle!    

I was thinking about this a lot for the last hour  :)

I will file a bug

**Comment by andychu** [comment]
Closing in favor of #1149 

Thanks for the feedback -- this came out of thinking about the table and the upgrade path.

Because the table is confusing if you can use `var` and `const` without setting any options!   Then it feels like there are **two** different ways to upgrade.  There should only be one.

**Comment by bar-g** [comment]
Yeah, great! Looks like a nice clean up.

Wondering if your enable-oil-within proc idea could also turn into a nice upgrade/addition improvent.
