### ISSUE TITLE
Feature: shortcuts to turn on and off multiple strict modes

### ISSUE THREAD

**Issue by costincaraivan** [oilshell/oil#115]
You might have already thought about this, based on what I've read here: [Shell Options for Strict Behavior](http://www.oilshell.org/blog/2018/01/15.html#toc_8).

But, in case you haven't, I think it's a good idea if you add some generic strict modes. By that I mean that instead of activating

```
set -o strict-control-flow
set -o strict-array
set -o strict-dont-kill-the-cat
```

you do something like:

```set -o strict-mode=latest```

or

```set -o strict-mode=v1```

And in turn, those activate a bundle of strict mode settings, with "latest" having presumably all the strict modes available.

See Powershell's [Set-StrictMode](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode?view=powershell-6) for inspiration.

**Comment by andychu** [comment]
Yes, there should be something like this.  My thinking was a single option to turn them all on:

    set -o strict 
    set -o STRICT  # caps to show it has special semantics

**Comment by costincaraivan** [comment]
Well, to use what you said "against you" 😆 ...

> (4) Special variables look like $Status rather than $?. In oil code, we prefer readable names. A completion system that's configured well by default will make them easy to type.

For consistency, wouldn't it be slightly better to just use a longer, more readable name, instead? ``all-strict`` or something like it?

**Comment by costincaraivan** [comment]
It sounds reasonable. 

By the way, I'd like to add a slightly more off-topic comment: you're doing great work, both with Oil/OSH and with the blog. Keep it up!

I hope you enjoy and it and I just wanted to let you know that there's people out there appreciating your work and hoping it comes to fruition 👍

**Comment by andychu** [comment]
Thanks!  The best way to help it come to fruition now is to run it against your own scripts and report bugs!

I have tagged some things "help wanted" but I should probably tag more.

**Comment by andychu** [comment]
thinking of the following:

```
set -o all:strict  # all strict modes (reduce allowed behavior)
set -o all:sane  # all sane modes (change behavior in a non-compatible way but which will help the user avoid pitfalls)
set -o all:nice  # enable nice syntax extensions (although I'm not sure if we want this as a execution option)

set +o all:strict  # can turn them off too
```

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.6.0/

Documented in the manual

https://www.oilshell.org/release/0.6.0/doc/osh-manual.html#toc_3
