### ISSUE TITLE
replace try/finally with context managers through the codebase

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1163]
`mycpp` ignores `finally`, and we just get `try`, which leads to an obviously incorrect translation.

**Comment by andychu** [comment]
Looks like there are 14 instances of this:

```
$ metrics/source-code.sh osh-files |xargs grep 'finally:'
core/completion.py:    finally:
core/executor.py:    finally:
core/process.py:      finally:
core/process.py:        finally:  # TODO: use context manager
core/process.py:      finally:
osh/builtin_meta.py:    finally:
osh/builtin_misc.py:      finally:
osh/builtin_misc.py:      finally:  # TODO: Change this to a context manager.
osh/cmd_eval.py:    finally:
osh/cmd_eval.py:        finally:
osh/cmd_eval.py:            finally:
osh/cmd_eval.py:          finally:
osh/cmd_eval.py:        finally:
osh/cmd_eval.py:    finally:

```

**Comment by andychu** [comment]
@watk   It occurred to me that I should give you a heads up that this bug exists!  (I gave Jesse a heads up about it as well.)

Basically every `finally:` is a bug / mistranslation, because C++ doesn't have try/finally.  So we just ignore the finally now which causes a bug :-/

So now that the delta is down to 33, I'm pretty sure several of them must be related to this.  What we should do is rewrite them as context managers, which mycpp translates to C++ constructors/destructors, like

```
with ctx_Foo(...):   # __enter__ and _exit__
  DoSomething()
```

becomes

```
{
  ctx_Foo();   # set up in constructor; tear down in destructor
  DoSomething();
}
```

I wanted to do this myself since it's in the Python, but I suppose I should not hold the code too closely ...   This is no longer a pure C++ issue and sort of crosses the Python/C++ boundary

**Comment by watk** [comment]
Oh, wow. Good to know. I was debugging a strange osh_eval bug and now I wonder if it's this

**Comment by andychu** [comment]
OK if you need help with anything feel free to poke me here or on Zulip!

I think that a good portion of the remaining bugs must be due to this ... it's been on my TODO list for quite awhile, but so are many other things :-/

**Comment by andychu** [comment]
I removed a few so there are 9 left now ... Spec test numbers did not move though


```
$ metrics/source-code.sh osh-files |xargs grep 'finally:' 
core/completion.py:    finally:
core/executor.py:    finally:
core/process.py:      finally:
core/process.py:        finally:  # TODO: use context manager
core/process.py:      finally:
osh/builtin_meta.py:            finally:
osh/builtin_misc.py:      finally:
osh/builtin_misc.py:      finally:  # TODO: Change this to a context manager.
osh/cmd_eval.py:    finally:

```
