### ISSUE TITLE
Question: how to change `readline` mode interactively?

### ISSUE THREAD

**Issue by BatmanAoD** [oilshell/oil#117]
Does `osh` provide a way to change the `readline` input-mode?

In Bash, I typically do:

```
set -o vi
```

But in `osh`, I get:

```
osh$ set -o vi
usage error: Invalid option name 'vi'
```

**Comment by andychu** [comment]
Yes `osh` should support that.  It's an essential part of my bashrc :)

I don't know the if the readline APIs in Python will support it, but if so that would be a great contribution :)

**Comment by BatmanAoD** [comment]
Huh--looks like the readline implementation actually respects `~/.inputrc`, which for my purposes is probably sufficient for now (using `set editing-mode vi`).

Obviously it would be best if `set -o vi/emacs` also worked, so if I get some time I'll look into that...

**Comment by BatmanAoD** [comment]
How can the `ExecOpts` class check whether `readline` is available, without just attempting to import `readline` and handling the error gracefully?

It looks like it's pretty simple to just globally set the `readline` module configuration whenever `set -o vi` or `set -o emacs` is executed.

**Comment by andychu** [comment]
Hm how would you set it with this API?  https://docs.python.org/2/library/readline.html

When I look at bash, I see the following snippet in `builtins/set.def.  It sets `editing-mode` to `vi` or `emacs`.

But I don't see `rl_variable_bind` in Python.

To answer your other question, in `bin/oil.py` you can search for `_HAVE_READLINE`.  I use a dependency injection style, so most optional dependencies should be checked in `main()` and then passed down through to libraries.  Libraries generally shouldn't import optional dependencies.


```
#if defined (READLINE)
/* Magic.  This code `knows' how readline handles rl_editing_mode. */
static int
set_edit_mode (on_or_off, option_name)
     int on_or_off;
     char *option_name;
{
  int isemacs;

  if (on_or_off == FLAG_ON)
    {
      rl_variable_bind ("editing-mode", option_name);
```

**Comment by BatmanAoD** [comment]
It's the `readline.parse_and_bind` function. You just pass the string `"set editing-mode vi"` (or `emacs`). I've tested in my fork that this works dynamically (i.e. I have `set -o vi` working in my fork, *assuming* `readline` is installed).

It looks like `completion` doesn't exist without `readline`, and the `completion` value (whether an actual completion engine or `None`) is passed to the executor. But `set -o <val>` is handled in `state.py`, in the `ExecOpts`  class, which, as far as I've seen, doesn't appear to have direct access to the `completion` value. Any thoughts on how the `set -o` request should be propagated to some part of the code that already has `readline` available?

**Comment by andychu** [comment]
Yeah good question.  Although the Executor already has tons of params (instantiated at line 235 of `bin/oil.py`, it makes logical sense for it to have yet another readline param.

The executor dispatches to the builtins, and the `Set()` builtin should take a 4th param that is `readline`.  For now it could just be `None` or the module.  Later I might want to introduce a "role interface", but that might be overkill.

Does that make sense?

You can also just send the pull request and if it works for the readline case that's good enough.  I generally want to be advised about architectural changes and this is a slight (and necessary) one.

(The architecture is mostly steady, but another one is `alias`, because the aliases defined affect the parsing!  That is a new architectural dependency.)

**Comment by andychu** [comment]
Also I think the fallacy was that `completion` is the only module that depends on readline.  Builtins do too.  So at the top of `bin/oil.py`, it should look like:

    if HAVE_READLINE:
       import readline
    else:
       readline = None

**Comment by BatmanAoD** [comment]
Okay, I've submitted a PR. Instead of adding `readline` to `Set`, I set it as a member of the `ExecOpts` class.
