### ISSUE TITLE
Builtin variable `$-` does not indicate interactive mode

### ISSUE THREAD

**Issue by BatmanAoD** [oilshell/oil#118]
From [the Bash manual](https://www.tldp.org/LDP/abs/html/internalvariables.html#FLPREF):

> The builtin variable `$-` is apparently supposed to indicate the "flags passed to script".

> ⚠️ This was originally a ksh construct adopted into Bash, and unfortunately it does not seem to work reliably in Bash scripts. One possible use for it is to have a script self-test whether it is interactive.

I don't really understand what the various letters in the `$-` variable are supposed to mean (on my system in an interactive shell I get `himBH`), and based on the above quote it seems the Bash folks may not either (!). But my `.bashrc` does indeed rely on `i` being included in interactive mode, since that is apparently the recommended test for interactive mode.

In `osh`, it seems that the variable is empty unless the `-x` argument is given to `osh`, in which case it's equal to `x`:

```
> osh
osh$ echo $-

osh$ exit
> osh -x
osh$ echo $-
+ echo x
x
osh$ exit
> osh -i
osh$ echo $-

osh$ exit
```

I'm not sure if implementing actual `ksh`-compatible behavior is necessary, but it would be nice to be able to test whether `$-` contains `i`.

**Comment by BatmanAoD** [comment]
`-e` and `-u` are apparently also included in `$i` when passed to `osh`. (I am not actually familiar with shell-launching flags, so I don't know exactly what these mean.)

**Comment by andychu** [comment]
I don't understand all the implications of "interactive", but I fixed the minimal case, testing the case when you pass `-i` and also when you don't pass any file or `-c`.

Thanks for the report!  Keep them coming :)

**Comment by BatmanAoD** [comment]
Looks good!
