### ISSUE TITLE
mycpp examples should run in testgc mode without segfaults

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1190]
The testgc variant does GC_EVERY_ALLOC and so forth.

- Related: `core/qsn_qsn.h` binding.  We can probably use the more efficient version

https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Mysterious.20Segfault

**Comment by andychu** [comment]
- Some of this is #1209 , though there could be more bugs

**Comment by watk** [comment]
Just filed https://github.com/oilshell/oil/issues/1215 for mycpp/examples/cartesian

**Comment by andychu** [comment]
GC done
