### ISSUE TITLE
mycpp/examples use heap-allocated Tuple and crash

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1206]
But it doesn't have a GC header!     (which should be `OBJ_HEADER()` or `gc_heap::Obj`)

**Comment by andychu** [comment]
Questions: Does `bin/osh_eval` use heap-allocated tuples?  Yes probably.

Solutions:

1) Rewrite tuples to ASDl records
2) Support heap-allocated tuples with records

**Comment by jjbandit** [comment]
Yeah `osh_eval` definitely allocates lists of tuples.

**Comment by andychu** [comment]
There are several that do this:


- examples/tuple_return_value
- examples/test_cast

**Comment by andychu** [comment]
We use heap-allocated tuples in `cpp/leaky_frontend_match.h` as well :-/

**Comment by andychu** [comment]
https://github.com/oilshell/oil/commit/22096e5cbbe1962c3e9fe28594d90c032c21a558

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.12.7/
