### ISSUE TITLE
mycpp/examples have the obj.f(g()) problem and segfault

### ISSUE THREAD

**Issue by watk** [oilshell/oil#1215]
This is due to the `x.f(g())` problem here: https://github.com/oilshell/oil/blob/bf508728247d28f52bdd6466c22001dd23870a36/mycpp/examples/cartesian.py#L34

It translates to:
```
out->append(str_concat(ch, r));
```
out is registered as a stack root but this still segfaults! The value of out that is passed to append() is the old value. Not the new value after the call to str_concat() triggers a GC that updates it.

mycpp needs to generate something like this instead:
```
Str* s = str_concat(ch, r); // Also probably register s as a stack root.
out->append(s);
```

Related thread: https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Interactions.20Between.20C.2B.2B.20and.20GC/near/288763988

**Comment by andychu** [comment]
Yes thank you for tracking this down!   If you manually change it to two lines, does the entire example work in test mode and benchmark mode?  (https://github.com/oilshell/oil/wiki/Oil-Dev-Cheat-Sheet shows how to run in both modes)

i.e. is the only bug in examples/cartesian?

This was a reason we wanted the "Pea" rewrite.  mycpp might not be smart enough for this :-(

**Comment by watk** [comment]
Yep this fixes it in both modes. I'll take a look at the other examples!

**Comment by watk** [comment]
There are more instances of `obj.f(g())`  and `f(g(), h())` but looks like fixing them isn't sufficient to make any other example pass in testgc mode. they also have other problems like Alloc<Tuple>, etc.

**Comment by andychu** [comment]
Ah OK thanks... I wonder if it makes sense to put an `if 0:` or `if FIX_MYCPP` around some of this code to get them to pass?   

And then we can go back and re-enable it once we have the proper fixes?  I guess the fix will usually be for mycpp/Pea to either:


1. disallow the code and make us manually rewrite
2. transform the Python code to the C++ with the right properties/invariants

**Comment by andychu** [comment]
Multiple examples have this problem:

- examples/cartesian 
- examples/files does `f.write(chr(i + 65))`


Well at least the `testgc` mode catches it ...

**Comment by andychu** [comment]
Fixed with new manual GC points
