### ISSUE TITLE
osh_eval bug: Forking causes osh to jump backwards in the script it's executing

### ISSUE THREAD

**Issue by watk** [oilshell/oil#1233]
I ran into this while debugging a bigger example for a spec test. Easy to repro though:
```bash
> cat >/tmp/f.sh <<'EOF'
echo start
$(:)
echo end
EOF

> _bin/cxx-dbg/osh_eval /tmp/f.sh
start
end
end
```

I spent some time debugging this and figured out that the child process `lseek()s` backward on the file stream for the script that's running. And since the fd is shared with the parent, the parent shell's state gets messed up. I took a look in the debugger to figure out why on earth the seek was happening and it turns out that it's glibc's atexit handler for file streams:
```
libc.so.6!__lseek64(int fd, off64_t offset, int whence)
libc.so.6!_IO_new_file_sync(FILE * fp)
libc.so.6!_IO_default_setbuf(FILE * fp, char * p, ssize_t len))
libc.so.6!_IO_new_file_setbuf(FILE * fp, char * p, ssize_t len)
libc.so.6!_IO_unbuffer_all()
libc.so.6!_IO_cleanup()
libc.so.6!__run_exit_handlers(int status, struct exit_function_list ** listp, _Bool run_list_atexit, _Bool run_dtors)
libc.so.6!__GI_exit(int status) 
posix::_exit(int status) (/home/c/dev/oil/cpp/leaky_posix.h:103)
process::SubProgramThunk::Run(process::SubProgramThunk * const this) (/home/c/dev/oil/_build/cpp/osh_eval.cc:9757)
...
```

Funnily enough `process.py` calls `_exit()` (which doesn't run atexit handlers): https://github.com/oilshell/oil/blob/7995c46e6556b77e3e8b37f61d6623c4f0e5a578/core/process.py#L716
but that code is translated into `exit()`:
https://github.com/oilshell/oil/blob/dec6fa0b911e9a6d03f5359e33a7de857812de54/cpp/posix.h#L127-L129

So is it fine to just change this latter one to `_exit()`?

OOI I took a look at what bash does: a) it doesn't use `FILE*`'s so wouldn't have any `atexit` handlers, and b) it closes the script fd in the child:
https://github.com/bminor/bash/blob/15409324f1974d41c183904ad575da7188058c1c/jobs.c#L2230

**Comment by andychu** [comment]
Oh wow ... I didn't know glibc had an exit handler for file streams!    Eek

Sounds like we need to get rid of all the C I/O and use POSIX I/O.  This is related to #1201 which we just noticed with buffering issues

The reason it's like that because we have some polymorphism so using `FILE*` was convenient ... but no shells use `FILE*` and it's wrong in more than way ! :-/

Thank you for looking deeply into this!

----

I just fixed an exit code bug so we're up to 1610 !

http://travis-ci.oilshell.org/github-jobs/2022-07-19__15-02-55.wwz/_tmp/spec/cpp/osh-summary.html

**Comment by watk** [comment]
Ah I didn't realise no shells use FILE*. I discovered that this problem is covered in TLPI section "25.4 Interactions Between fork(), stdio Buffers, and _exit()":

> Instead of calling exit(), the child can call _exit(), so that it doesn’t flush stdio
> buffers. This technique exemplifies a more general principle: in an application
> that creates child processes, typically only one of the processes (most often the
> parent) should terminate via exit(), while the other processes should terminate
> via _exit(). This ensures that only one process calls exit handlers and flushes
> stdio buffers, which is usually desirable

And here's a stackoverflow deep dive into how this behaviour is specified by POSIX: https://stackoverflow.com/questions/50110992/why-does-forking-my-process-cause-the-file-to-be-read-infinitely

Anyway! Long story short, until `FILE*` gets replaced we can either:
1) `fflush` the stream before forking, and/or
2) only call `_exit` from the child

I'll send a PR for #2 regardless, since that's what the python code is already doing
