### ISSUE TITLE
Regex in a loop exits FATAL on second iteration

### ISSUE THREAD

**Issue by Melkor333** [oilshell/oil#1271]
The following script is supposed to run through just find finding no regex match, but instead it breaks on the second iteration:
```
cat test.oil 
#!/usr/bin/env oil

var content = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
var i = 0
while (i < len(content)) {
  var line = content[i]
  write $[content[i]]
  if (Str(line) ~ / s* 'imports' s* '=' s* .* /) {
    exit
  }
  setvar i += 1
}
```

The output is:
```
./test.oil 
1
2
FATAL: NotImplementedError('re__Primitive',)
```

The same happens in a `for` loop:
```
#!/usr/bin/env oil

var content = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
var i = 0
for line in (content) {
  write $line
  if (Str(line) ~ / s* 'imports' s* '=' s* .* /) {
    exit
  }
  setvar i += 1
}
```

**Comment by Melkor333** [comment]
I just figured out that removing the last `.*` fixes the error aswell

**Comment by andychu** [comment]
Thank you for the report!  Just fixed this

We did have a similar bug before, and I believe I handled all cases, so this should go away

----

The fundamental issue is that we mutate an eggex the first time it is evaluated.  Although I wonder if we should change that, hm.

**Comment by andychu** [comment]
OK yeah there is a more fundamental issue here which I reproduced, fix forthcoming!

**Comment by andychu** [comment]
Done, will be in the next release!

**Comment by andychu** [comment]
Released, thanks for the great feedback!  https://www.oilshell.org/blog/2022/08/release-0.12.4.html
