### ISSUE TITLE
Build error for x86_64: fanos.c needs -std=c99

### ISSUE THREAD

**Issue by irowebbn** [oilshell/oil#1281]
I ran ` ./configure --prefix /home/[user]/.local --datarootdir /home/[user]/.local/share` followed by `make`:

```
../native/fanos.c: In function ‘func_recv’:
../native/fanos.c:107:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 10; ++i) {
   ^
../native/fanos.c:107:3: note: use option -std=c99 or -std=gnu99 to compile your code
```

Seems like the Makefile needs to specify C99 or higher to correctly compile this file. I'm not familiar with the script that generates the Makefile, so I'm not sure where I would add this.

The default `cc` on my machine is `cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)`, and I'm using GNU Make 3.82.

**Comment by andychu** [comment]
Released, thanks for trying it!  https://www.oilshell.org/blog/2022/08/release-0.12.4.html
