### ISSUE TITLE
Creating a .md file in the root directory causes test failure

### ISSUE THREAD

**Issue by jjbandit** [oilshell/oil#1291]
Create any `.md` file in the root directory, run tests, enjoy fireworks

**Comment by andychu** [comment]
Aww geez, yeah there is a test for globbing that looks for markdown!

https://github.com/oilshell/oil/blob/master/cpp/leaky_binding_test.cc#L157

Combined with a function in `mycpp/common.sh` that  doesn't report errors

Sorry, fixing

**Comment by andychu** [comment]
Doh the Python version of this is here

- #272 

So it might be useful to have a container or something to avoid these failures

Although I think  #1292 was a big part of it

**Comment by andychu** [comment]
I fixed this for the immediate future, still need

- #1294
