### ISSUE TITLE
cpp/TEST.sh unit tests fail silently

### ISSUE THREAD

**Issue by jjbandit** [oilshell/oil#1292]
I did not discover #1291 for quite some time due to the test suite failing silently.

Personally, I prefer for tests to pass silently, and fail extremely loudly.

**Comment by jjbandit** [comment]
For reference, both "test runnners" fail silently
```
test/cpp-unit.sh soil-run
test/cpp-unit.sh all-tests
```

**Comment by andychu** [comment]
Sorry just fixed this.   I neglected to use a four line shell idiom here ... which OSH replaces with `try`

https://github.com/oilshell/oil/commit/92e20a7c2cf2eeaf75da7f652050bd601ea68b45



```
.id = 334
val = {
id = 331
val = -1
id = 333
val = ..
id = 331
val = 22
id = 334
val = }
..
Expected: 1
     Got: 2
F
FAIL libc_test: 1 != len(files) (cpp/leaky_binding_test.cc:159)
ts = 1662057127
.getcwd() =
/home/andy/git/oilshell/oil
strerror
Bad file descriptor
..stdin isatty = 1
.....
Total: 12 tests (1029 ticks, 0.001 sec), 56 assertions
Pass: 11, fail: 1, skip: 0.

FATAL: FAIL: _bin/cxx-dbg/cpp/leaky_binding_test failed with code 1
```

**Comment by andychu** [comment]
I fixed this for the immediate future, still need

- #1294
