### ISSUE TITLE
Remove LEAKY_ALLOCATOR

### ISSUE THREAD

**Issue by jjbandit** [oilshell/oil#1293]
@andychu I tried to do this this morning, but unfortunately the build still has too many special cases for test code for me to manage it in a timely manner.

The problem I ran into was not removing `LEAKY_ALLOCATOR` iteslf, but getting all of the tests that are still going through the old build pipeline to link successfully against the `gc_heap.cc` object.  Some require to now link against `gc_heap.o` (as opposed to not linking against it before), and some already link against it.  I could not find the proper places to add it which would add it to the tests that require it, but not add it a second time to the ones that already link against it.

My feeling is that a lot of the build code that accommodates the 'special' cases (like gc_bindings_test.cc) can just go into the regular build pipeline because the code to build them is now the same as the rest of the build targets.  ..?  There's a lot of complexity there so I might be wrong, but I *think* this should be close to true.

**Comment by andychu** [comment]
OK yeah I think this relies on removing OLDSTL files, and then removing the difference between GC_RUNTIME and OLDSTL_RUNTIME in the build

I will look at it

**Comment by andychu** [comment]
OK I actually got everything building with no OLDSTL runtime and no leaky allocator, but global `List<int>` cause the GC to go into an infinite loop!

Hmmm

**Comment by andychu** [comment]
OK this is done now
