### ISSUE TITLE
Python warning makes my editor jump around

### ISSUE THREAD

**Issue by jjbandit** [oilshell/oil#1295]
/usr/lib/python2.7/dist-packages/setuptools/dist.py|406| UserWarning: The version specified ('0.3.6-72686b0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

This is low priority, but it is pretty annoying that a clean build throws this warning and my editor jumps to the location every time.  If it's an easy solve I'd appreciate it if it could be silenced.

**Comment by andychu** [comment]
Fixed

https://github.com/oilshell/py-yajl/commit/615ed2a4776bea4344723591f95219db2e08262e


I think you will have to do `cd py-yajl; git pull` to get this change

wish we didn't have the submodule
