### ISSUE TITLE
make mycpp/examples pass under GC_EVERY_ALLOC

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1318]
Right now there are 5 failures

**Comment by andychu** [comment]
This is still an issue:


- #1206

**Comment by andychu** [comment]
@scallyw4g It occurred to me that probably 3 of the 5 failures are due to Tuples not having a GC header

So if we can use the `std::is_pointer` trick (probably with `offsetof()`), then that might save some work in both mycpp and the Oil interpreter !


- #1319

**Comment by scallyw4g** [comment]
4/5 are due to invalid GC headers, but only 1/5 of them is tuples.  I'll see what I can jig up for them this afternoon

**Comment by andychu** [comment]
After enabling ASAN in gcevery, we also see the `f(g(), h())` problem again:

https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/f.28g.28.29.2C.20h.28.29.29.20problem.20arises.20again.20!!!

**Comment by andychu** [comment]
Will be done with Return Value Rooting!

**Comment by andychu** [comment]
Done!
