### ISSUE TITLE
should mycpp disallow heap allocated tuples?

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1319]
Or Jesse mentioned doing templated `std::is_pointer()` check

Related:

- #1206

**Comment by scallyw4g** [comment]
Either we have to disallow them entirely (and change the example code) or support them.

I'm fine with whichever, but they're causing crashes in the examples

`_bin/cxx-gcevery/mycpp/examples/loops.mycpp`

**Comment by andychu** [comment]
I think since we're hitting this pretty hard we should try the `std::is_pointer` thing?  Do you think that will work?

**Comment by andychu** [comment]
https://github.com/oilshell/oil/commit/22096e5cbbe1962c3e9fe28594d90c032c21a558

fixed

**Comment by andychu** [comment]
Dupe of #1206
