### ISSUE TITLE
mycpp generates invalid StackRoot for integer loop index

### ISSUE THREAD

**Issue by scallyw4g** [oilshell/oil#1321]
in `_gen/mycpp/examples/containers.mycpp.cc` on line 231 mycpp generates a pointer to an int and registers it as a stack root.

**Comment by scallyw4g** [comment]
This causes a crash in the mycpp examples when turning on GC_EVERY_ALLOC for obvious reasons

**Comment by andychu** [comment]
Doh, yeah looks like the for loop code gen is buggy

This is probably not that hard to fix, thought I haven't looked at the code in awhile

Related to

- #1318

**Comment by andychu** [comment]
This morning I was thinking that 3 of the 5 failures are related to heap-allocated tuples (I think, because of assertion failure on the GC header)

And then we have this one

What about `loops`?  I think that was the other one?  Maybe you can root cause that one too

**Comment by andychu** [comment]
### Related Problem: Stack Roots on List Comprehensions

I'm looking through the hacky mycpp code, and this is a problem that may bite us

Probably need `mycpp/examples` coverage for this

**Comment by andychu** [comment]
OK I fixed this one, now there are 4 failures in mycpp/examples under gcevery

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.12.7/
