### ISSUE TITLE
mycpp should generate field masks for classes (e.g. DirStack in examples/scoped_resource)

### ISSUE THREAD

**Issue by scallyw4g** [oilshell/oil#1322]
`_bin/cxx-gcevery/mycpp/examples/scoped_resource.mycpp`

Crashing because we don't traverse the pointers in dirstack due to not having a sensible field mask

**Comment by andychu** [comment]
OK yeah this is a test case exposing

- #1164

**Comment by andychu** [comment]
This seems done, good and thorough test in `mycpp/examples/classes`

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.12.7/
