### ISSUE TITLE
Emit single backslash in eggex

### ISSUE THREAD

**Issue by tooeffayy** [oilshell/oil#1398]
What seemed like a simple exercise as converting a rather simple regex to eggex has led me to believe there is a bug in how backslashes are parsed.

`\\\1`

I cannot come up with a way to emit the above as any method I have tried for producing a single backslash always output two. What I'm trying to accomplish is escaping captured dots and hyphen in FQDNs with sed -E, the capture pattern works fine, it's just the above substitution pattern that is giving me trouble.

These emit double backslashes, ie \\\\
```
/ \\ /
/ r'\' /
/ $'\\' /
```
This emits four backslashes, ie \\\\\\\\
```
/ r'\\' /
```
Unexpected token or escaping the quote
```
/ \ /
/ $'\' /
```

I've looked through the eggex documentation but don't see anything noting peculiarities with how to handle a backslash which leads me to believe there is a bug or I'm completely missing something here. I'm on version 0.12.8.

**Comment by andychu** [comment]
Hm interesting

I think this is a feature not a bug :)  Because a single backslash is never a fully formed POSIX ERE 

```
$ egrep '\' *.md
grep: Trailing backslash

$ egrep '\\' *.md

```

What is the problem you're trying to solve?


The idea behind eggex is to give you a better and composable syntax for creating well-formed EREs

It's not for generating arbitrary text

**Comment by tooeffayy** [comment]
I'm trying to get an odd number of backslashes such as my example above. Not sure how else to produce `\1` for first capture group unless there is something for numbered groups but didn't see that in the docs either. If I did a named group, how would that work instead?

```
echo sam-ple.domain.com | sed -E 's/(\.|-)/\\\1/g
Output: 
sam\-ple\.domain\.com
```
I'm generating a blocklist of domains pulled from OISD and AdGuard to use with Unbound and implementing an override functionality for my script. If a domain is in the override file it gets converted to regex and fed to grep as a pattern to remove from actual domain blocklist.

```
... sed -E 's/(\.|-)/\\\1/g $HOST_OVERRIDE # Convert override domains to regex patterns
  | grep -f - -x -v /tmp/combined.list # Remove any matches from the combined list
  | sed "s/^/local-zone: \"/;s/\$/\" always_nxdomain/" # Format for unbound
  > $UNBOUND_CONF_PATH/blacklist.conf # Write to unbound config
  ;
```
It's a very simple example which absolutely doesn't need eggex but was something I noticed when I tried.

**Comment by andychu** [comment]
OK I think the issue is that `\1` is not regex syntax -- not an ERE -- it's a sed replacement pattern.  In Python that is true too.

So you should be able to use eggex for the pattern, and normal `sed` for the replacement string

Something like

```
sed -E "s/$my_eggex/my-replacement-\\1"
sed -E "s/$my_eggex/"'my-replacement-\1'  # single quotes and string joining
```

(not tested)

Does that make sense?

**Comment by tooeffayy** [comment]
Gotcha, thanks!
