### ISSUE TITLE
Arguments to functions like eval_hay() aren't checked

### ISSUE THREAD

**Issue by Melkor333** [oilshell/oil#1415]
I've started playing a bit with `hay` and found that the following simple hay statement can't be evaluated:

``` sh
oil$ cat oilparse.hay 
Scenario Test {
  TEST "basics" {
    echo Hello
    touch test
    ls
    rm test
  }
}
oil$ hay define Test
oil$ hay define Scenario
oil$ hay define Scenario/TEST
oil$ var s = parse_hay('oilparse.hay')
oil$ hay pp s
(hay_node children:[map Test (hay_node) Scenario (hay_node children:[map TEST (hay_node)])])
oil$ const q = eval_hay('oilparse.hay')
  const q = eval_hay('oilparse.hay')
        ^
[ interactive ]:6: fatal: Expression eval error: 'str' object has no attribute 'tag_'
```

Tested with version 0.12.8.

**Comment by andychu** [comment]
Thanks, I can repro this ... not sure what's going on yet but it definitely shouldn't crash like that!

**Comment by andychu** [comment]
Sorry for the big delay, I went and looked at this again, and realized that it's actually not a Hay issue per se, but a case of a bad error message.  The problem is that you should pass `s` to `eval_hay()`.

Sorry Hay has been on the back burner while we dig ourselves out of "translation debt", which is going well .   I mentioned your great feedback and Hay here:

https://www.oilshell.org/blog/2023/01/garbage-collector.html#whats-next

This generated more interest in Oil / Hay, although it still be might be prudent to wrap up a solid "OSH", and then users can become contributors Oil/Hay



---

FWIW this works for me:

```
hay define Test                                                                                                                                                                                                                                                                                                               
hay define Scenario                                                                                                                                                                                                                                                                                                           
hay define Scenario/TEST                                                                                                                                                                                                                                                                                                      
var s = parse_hay('oilparse.hay')                                                                                                                                                                                                                                                                                             
hay pp s                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                              
# const q = eval_hay('oilparse.hay')                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                              
const q = eval_hay(s)                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                              
= q                                                                                                                                                                                                                                                                                                                           
```

**Comment by andychu** [comment]
Also this is the underlying cause of the bad error

- #636

we have to break out dependence on Python for Oil


(That is what we just did for OSH)

**Comment by Melkor333** [comment]
Oh wow what a stupid mistake by myself, thanks for spotting it!
```
oil$ = q
(OrderedDict)   <'source': None, 'children': [<'type': 'Scenario', 'args': ['Test'], 'children': [<'type': 'TEST', 'args': ['basics'], 'location_str': 'oilparse.hay', 'location_start_line': 2, 'code_str': '                 \n    echo Hello\n    touch test\n    ls\n    rm test\n  '>], 'attrs': <>>]>
```

Looking perfectly! In my opinion we can close this issue for now, unless you want to keep it open for some reason.ing perfectly! In my opinion we can close this issue for now, unless you want to keep it open for some reason.

BTW: I loved to see your blog post, even when I didn't understand much. 😁 Great to see your improvements on the garbage collector!

**Comment by andychu** [comment]
There is a bug -- the error message needs to be fixed!  So I'll leave this open

Thanks for testing, again I feel a bit bad I haven't devoted enough attention to Oil/Hay in the last few months ... but I think having a solid OSH is "table stakes" and will hopefully attract more help!

**Comment by Melkor333** [comment]
No excuses, you're doing a great job! I'm actually thinking about pushing `osh` company internally as a possible tool to help in writing bash scripts.

Though python is already the "de facto" successor and bash shouldn't be used for much more than oneliners... And `osh` as a *replacement* sadly doesn't work because the code needs to run on customers debian/rhel/suse/whatnot systems which will not have `osh` for a few more years. Python is already on the edge of being "too new", respectively "might not be available"...
I guess the enterprise "classic" environment just isn't the best place for early adoption. Either something like Cloud Applications/Science or adoption by a deeply routed system (crossing the fingers for a good collaboration with autotools!) is probably easier to achieve :)
(I gladly receive inputs on this, though might wanna move this discussion to zulip)

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2023/09/release-0.18.0.html
