### ISSUE TITLE
configure error when trying to specify readline w/ `--readline`

### ISSUE THREAD

**Issue by abathur** [oilshell/oil#1467]
Went to update the Nix expression for Oil to try to build the oils-for-unix tarball and noticed this configure failure:

```console
configuring
configure flags: --prefix=/nix/store/9jl9anqvyp4nnjbvba703g8izlcqzsrf-oil-0.14.0 --datarootdir=/nix/store/9jl9anqvyp4nnjbvba703g8izlcqzsrf-oil-0.14.0 --with-readline --readline=/nix/store/5rvfmpyiic6w2gzw91gk10x4vr9yi9bv-readline-all
./configure ERROR: readline was not detected on the system (--with-readline passed).
```

It looks like it cropped up around 0.13.0, since the main nixpkgs update bot [started failing with a similar message on that update](https://r.ryantm.com/log/oil/2023-01-01.log)

I noticed that this section of the configure added in december is similar to the next one below, sans returns:
https://github.com/oilshell/oil/blob/623a893eeebcd124ca00ae5c84dbf9fadfaac8c8/configure#L364-L375

https://github.com/oilshell/oil/blob/623a893eeebcd124ca00ae5c84dbf9fadfaac8c8/configure#L203-L218

~patching it with `substituteInPlace configure --replace "echo '#define HAVE_READLINE 1'" "echo '#define HAVE_READLINE 1' && return 0"` produces a usable executable, at least. 

Associated Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/212891

**Comment by pdebelak** [comment]
This is still present in oil 0.14.1. There is also duplication between `detect_cpp` and `detect_readline`. `detect_readline` does the right thing but isn't called since `detect_cpp` fails if you pass `--with-readline` and `--readline`.

**Comment by andychu** [comment]
Oops, thanks for bumping this bug, and thanks for the original report!  Somehow it slipped by

Let me take a look at the PR

**Comment by a12l** [comment]
@andychu Have taken a look at this?

**Comment by andychu** [comment]
I think #1514 fixed it, but I forgot to close this bug

Are you still having a problem?

**Comment by abathur** [comment]
I was able to remove the workaround documented here from the Nix expression for Oil (which is currently using 0.16.0) and it built fine.

- will update with link to nixpkgs PR momentarily
