### ISSUE TITLE
Remove trailing spaces from all source files

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#148]
A lot of pull requests seem to come with spurious diffs because people have their editors configured to remove trailing spaces.  So we might as well do this.

Travis should fail if there are spaces?

**Comment by granttrec** [comment]
@andychu I think this is a good idea, I can do this if you want. No need for extra spaces in project files.

**Comment by andychu** [comment]
OK I think it is better to start it on `.py` and `.c` files.  Those were the main problems anyway.

I am not sure if any tests depend on whitespace in `.sh` files.  For example, in here docs the spaces are significant.  Changing `.sh` files could be done in another pass.

Make sure to run the tests after the change, e.g.

```
test/unit.sh all
test/spec.sh all
test/gold.sh all-passing  # also useful
```
