### ISSUE TITLE
Write a parser for a vmgen-like DSL

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#149]
Darius Bacon and I talked about doing an experiment to convert CPython to this style of VM:

https://github.com/ruby/ruby/blob/trunk/insns.def

https://github.com/darius/idel/blob/master/src/opcodes

A separate sub-project is to write a tiny parser for this kind of format.  Exact format is TBD, but I kind of like Ruby's format.

But I didn't like Ruby's parser for this format.  Besides being in Ruby (bad because it's an additional build dep), it was split over a dozen or so files with a lot of unneeded abstraction ?  

It's not clear to me how "detailed" the parse needs to be.  The C blocks are just opaque.  Is that also true of the types?  Are they just lines, or do we care about C expressions?  I suspect the former.

----

This will need to be co-developed with the VM itself, but I think making a first pass over it could be a good task for somebody who wants to learn how to write a parser.

`test/sh_spec.py` is a very similar DSL parser.

- The `spec/*.test.sh` format is is a DSL with bash blocks, and it happens to be valid bash.
- The VM DSL will have C blocks, which happens to be syntax-highlighted like C.

The main difference is that the spec format keeps everything in comments, so it's still valid bash.

**Comment by granttrec** [comment]
I'll take a look at this, what language to implement it in?

**Comment by andychu** [comment]
In retrospect this was premature, because I'm still working on the VM... It's hard to know what it will look like without manually writing the code it will generate.

removing labels...
