### ISSUE TITLE
popd directory stack empty differs from bash

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1500]
Ran into this while running `devtools/release.sh test-oil-tar T`

```
andy@lenny:~/git/oilshell/oil$ bash -c 'pushd /tmp; cd /; popd; pwd'
/tmp ~/git/oilshell/oil
~/git/oilshell/oil
/home/andy/git/oilshell/oil



andy@lenny:~/git/oilshell/oil$ bin/osh -c 'pushd /tmp; cd /; popd; pwd'
/tmp ~/git/oilshell/oil
  pushd /tmp; cd /; popd; pwd
                    ^~~~
[ -c flag ]:1: popd: directory stack is empty
/

```

**Comment by bar-g** [comment]
Um, just hit this, I don't seem to get to any classic pushd, cd, popd seqence working.
Might rather look like a bug or broken tag to me than divergence?

**Comment by andychu** [comment]
Ah OK thanks for the report!  Let's prioritize this

**Comment by andychu** [comment]
OK I think I see the issue

`cd /` in the middle of pushd/popd actually **replaces** an entry lower on the dir stack

**Comment by andychu** [comment]
OK I fixed this, it replaces the top of the dir stack

**Comment by bar-g** [comment]
Cool, I get to remove a workaround. Thanks! :-)

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2023/09/release-0.18.0.html
