### ISSUE TITLE
Cannot run deps/from-tar.sh layer-cmark

### ISSUE THREAD

**Issue by thamagorian** [oilshell/oil#1541]
while running deps/from-tar.sh layer-cmark from the oil folder, receives the following message
~/git/oil/_cache ~/git/oil
deps/from-tar.sh: line 68: 0.29.0.tar.gz: No such file or directory

**Comment by andychu** [comment]
Ah sorry about that, please do `deps-from-tar.sh download-cmark` first 

I will fix the instructions.  I've been trying to unify the dev build and CI build, which caused this problem


Let me know if you have other problems!

**Comment by thamagorian** [comment]
Thank you. that solved the issue and now it works fine.
