### ISSUE TITLE
Add oshrc.d and yshrc.d directories; discourage mutating bashrc pattern

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1548]
@Melkor333 implemented this

NOTE: It's `~/config/oil/oshrc.d` now, but it will change to `~/config/oils` !!  

This might be a pretty annoying breakage

So maybe we don't make a big deal of it yet

**Comment by Melkor333** [comment]
IMO we shouldn't make a big deal until the whole rc-loading is more neighbourly :)

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2023/05/release-0.15.0.html
