### ISSUE TITLE
`time` builtin `user`/`sys` time always zero

### ISSUE THREAD

**Issue by melvinw** [oilshell/oil#1552]
Noticed this while doing some random measurements. E.g., in `osh` we get:
```shell
$ time oil_lang/run.sh test-parse-osh-cpp > /dev/null
real    2.000
user    0.000
sys     0.000
```

But, `bash` gives:
```shell
$ time oil_lang/run.sh test-parse-osh-cpp > /dev/null

real    0m1.451s
user    0m1.183s
sys     0m0.273s
```

**Comment by melvinw** [comment]
Only `osh-cpp` seems to suffer from the `user`/`sys`-are-always-zero part. Both versions are unit-less, though.
```shell
$ time oil_lang/run.sh test-parse-osh-cpp > /dev/null
real    1.555
user    0.000
sys     0.003
```

**Comment by melvinw** [comment]
Relevant code:
https://github.com/oilshell/oil/blob/335f41cdd74f97b0479596f76a8582db4beb2604/cpp/core.cc#L179-L213
https://github.com/oilshell/oil/blob/335f41cdd74f97b0479596f76a8582db4beb2604/core/pyos.py#L219-L230

**Comment by andychu** [comment]
I fixed the main problem with https://github.com/oilshell/oil/commit/d2217df9e9d76db243edb59b13fb3f0a1f5a9b29

The output side is now #1553 

I kind of don't like the bash format, so I did some bike shedding

https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/time.20.2F.20times.20output.20bikeshedding

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2023/05/release-0.15.0.html
