### ISSUE TITLE
OSH build problems on multiple platforms

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#16]
Most of these are probably because I froze pyconfig.h with Alpine Linux / gcc / musl libc.

- [x] centos/7 (Vagrant)
  - Assuming same as Red Hat Linux: from e-mail, Red Hat 7.3 : stropts.h error
- [x] archlinux/archlinux (Vagrant)
  - not able to reproduce: https://lobste.rs/s/uhphnb/please_try_first_osh_release
- [x] 32-bit  ubuntu32 image (`SIZEOF_LONG` issue fixed)
- [x] 32-bit precise32 image (tested against older toolchain)
- [ ] 32-bit ARM - Pi Zero -- see below, bad assembly
- [ ] Ubuntu / aarch64 64-bit ARM (memcpy) https://www.reddit.com/r/ProgrammingLanguages/comments/6p31ej/please_try_the_first_osh_release/
- [ ] OpenBSD errors:
  - https://lobste.rs/s/uhphnb/please_try_first_osh_release
- [ ] Mac OS X - From e-mail, stat structure is not the same?

TODO: Run on faster virtualized armhf box!

**Comment by andychu** [comment]
OS X:

https://www.reddit.com/r/oilshell/comments/6p2tp0/please_try_the_first_osh_release/dkslcjm/

**Comment by andychu** [comment]
Fixed RedHat / CentOS issue here: https://github.com/oilshell/oil/commit/a8cd6031030d3e194f0c233cf42007587106664f

**Comment by obestwalter** [comment]
Hi @andychu - thanks for following this up. Good to here that the arch problem dissolved.

**Comment by andychu** [comment]
@obestwalter I'm not sure what happened since I didn't change anything.  I tested with this image:

https://app.vagrantup.com/archlinux/boxes/archlinux

It's possible you might still have the error on your box, but I guess we can see when I make a new release (should be soon.)

**Comment by andychu** [comment]
Works on ubuntu32 VM, but fails on Raspberry Pi Zero with:

```
$ time make
build/compile.sh build-opt _build/oil/ovm _build/oil/module_init.c _build/oil/main_name.c _build/oil/c-module-srcs.txt
~/src/oil-0.1.alpha1/Python-2.7.13 ~/src/oil-0.1.alpha1
/tmp/ccXch6z6.s: Assembler messages:
/tmp/ccXch6z6.s:26: Error: bad instruction `fnstcw [sp,#6]'
/tmp/ccXch6z6.s:44: Error: bad instruction `fldcw [sp,#6]'

real	16m1.890s
user	15m33.230s
sys	0m14.390s
~/src/oil-0.1.alpha1
cat _build/oil/ovm _build/oil/bytecode.zip > _bin/oil.ovm
cat: _build/oil/ovm: No such file or directory
Makefile:281: recipe for target '_bin/oil.ovm' failed
make: *** [_bin/oil.ovm] Error 1
make: *** Deleting file '_bin/oil.ovm'

real	16m2.092s
user	15m33.320s
sys	0m14.450s
```

**Comment by acg** [comment]
I [also reported this issue](https://lobste.rs/s/yexgqc/please_try_osh_0_1_release#c_odm8ax) but have since fixed it. Turns out changing your mind about prefix was the problem:

```sh
./configure
make
./configure --prefix ~
make
./install
osh  # aborts
```

```sh
# in a clean directory
./configure --prefix ~
make
./install
osh  # works
```

**Comment by andychu** [comment]
Ah that should work though, so it's still a bug!  I'll test it out.

**Comment by andychu** [comment]
@acg I'm having trouble reproducing this in the archlinux/archlinux Vagrant VM (although I don't think it should have anything to do with Arch if the bug is about changing `--prefix`.

The second you typed 'make', did it build anything?  For me it said

`make: Nothing to be done for 'default'.`

I can imagine there is a bug if the Makefile dependencies aren't right though.


```
... output of make ...
real    0m35.489s
user    0m33.984s
sys     0m1.465s
~/src/oil-0.1.0
cat _build/oil/ovm _build/oil/bytecode.zip > _bin/oil.ovm
chmod +x _bin/oil.ovm

[vagrant@archlinux oil-0.1.0]$ ./configure --prefix ~
m./configure: Wrote _build/detected-config.sh and _build/detected-config.h

[vagrant@archlinux oil-0.1.0]$ make
make: Nothing to be done for 'default'.

[vagrant@archlinux oil-0.1.0]$ ./install 
Installing to /home/vagrant/bin/oil.ovm
[vagrant@archlinux oil-0.1.0]$ osh
osh$ ^CCtrl-C
```

**Comment by andychu** [comment]
Nevermind I reproduced it.

The issue is that both make and install steps read `$PREFIX`.  And if they disagree then it crashes.  Doh!  

I will have to think about this.  I think it might be the result of some "optimization" I did over the autoconf model.

In autoconf the Makefile is generated, and it contains both the build and install steps.

Thanks for the report.


```
$ PATH=~/bin:$PATH
[vagrant@archlinux oil-0.1.0]$ osh
osh: Modules/main.c:347: Ovm_Main: Assertion `sts != -1' failed.
Aborted (core dumped)
```

**Comment by jshort** [comment]
Building python failed on MacOS Sierra:
```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libpython2.7.a(pymath.o) has no symbols
gcc  -u _PyMac_Error -o python.exe \
			Modules/python.o \
			libpython2.7.a -ldl  -framework CoreFoundation
./python.exe -E -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
running build
running build_ext
building dbm using ndbm
Traceback (most recent call last):
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/setup.py", line 2262, in <module>
    main()
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/setup.py", line 2257, in main
    'Lib/smtpd.py']
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/Lib/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/Lib/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/Lib/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/Lib/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/Lib/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/Lib/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/Lib/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/setup.py", line 182, in build_extensions
    missing = self.detect_modules()
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/setup.py", line 1699, in detect_modules
    addMacExtension('_CF', core_kwds, ['cf/pycfbridge.c'])
  File "/Users/jwshort/gitworkspaces/oil/Python-2.7.13/setup.py", line 1690, in addMacExtension
    raise RuntimeError("%s not found" % name)
RuntimeError: _CF not found
make: *** [sharedmods] Error 1
```

**Comment by andychu** [comment]
@jshort What command did you run?  Let's follow up on issue #70, which I created since OS X is different than other platforms (no free testing environment AFAICT).

**Comment by andychu** [comment]
There are now separate bugs for build issues on each platform, so I'm closing this one.  Please continue testing OSH on different platforms :)
