### ISSUE TITLE
`trap - SIGINT` behaves differently than `bash`

### ISSUE THREAD

**Issue by jsoo1** [oilshell/oil#1607]
As mentioned on zulip:
```ShellSession
$ echo $0
-osh
$ trap - SIGINT
$ # press C-c here
# osh exits
```
```ShellSession
$ echo $0
-osh
$ bash
$ trap - SIGINT
$ ^C
$ echo $0
bash
```

**Comment by andychu** [comment]
Thank you for reducing this test case, that's very helpful!   I reproduced this

**Comment by jsoo1** [comment]
Reading the posix trap manpage, I'm not sure what to make of it
> trap [action condition ...]
>
> DESCRIPTION
> 
> If action is '-', the shell > shall reset each condition > to the default value.

**Comment by andychu** [comment]
Released a few weeks ago - https://www.oilshell.org/blog/2023/06/release-0.16.0.html

Thanks again for testing, this is very useful!
