### ISSUE TITLE
try builtin shouldn't disallow command subs, i.e. with strict_errexit

### ISSUE THREAD

**Issue by AladW** [oilshell/oil#1608]
I'm trying to use `getopt(1)` with `shopt --set strict_errexit`, but can't find a way to use it with a custom error message on exit >0. Specifically:
```sh
#!/bin/osh
shopt --set strict_errexit
shopt --set oil:basic

var argv0 = 'test'
var opt_short = 'f'
var opt_long  = 'foo'

# fatal: Command subs not allowed here because status wouldn't be checked (strict_errexit).
try {
    var opts=$(getopt -o "$opt_short" -l "$opt_long" -n "$argv0" -- "$@")
}
# if (_status === 0) ...

# fatal: strict_errexit only allows simple commands in conditionals (got command.Sentence).
if ! opts=$(getopt -o "$opt_short" -l "$opt_long" -n "$argv0" -- "$@"); then
    write 'getopt failure'
    exit 1
fi

# errexit PID 134319: Command Sub exited with status 1
opts=$(getopt -o "$opt_short" -l "$opt_long" -n "$argv0" -- "$@")
write 'getopt failure' # message not reached
```
`oil --version` output:
```
Oil version 0.14.1
Release Date: 2023-02-14 02:36:53+00:00
Arch: x86_64
OS: Linux
Platform: #1 SMP PREEMPT_DYNAMIC Sat, 25 Feb 2023 11:02:38 +0000
Compiler: GCC 12.2.1 20230201
Interpreter: OVM
Interpreter version: 2.7.13
Bytecode: bytecode-opy.zip
```

**Comment by andychu** [comment]
Hi, thanks for trying it!  

I think this may be a bug in `try` ... it's being run with `ctx_ErrExit`, which is meant for `if myfunc` to disable command subs

So it is being too strict / overzealous


----

Unrelated: BTW `shopt --set oil:basic` is now `shopt --set oil:upgrade`, I actually removed it in newer versions

**Comment by andychu** [comment]
Released a few weeks ago - https://www.oilshell.org/blog/2023/06/release-0.16.0.html

Thanks for the testing!  I just realized I didn't mention you in this release notes, let me update them
