### ISSUE TITLE
Tilde expansion: word vs. expression mode

### ISSUE THREAD

**Issue by metov** [oilshell/oil#1625]
I am trying to create a variable from the home directory, but I can't get the tilde to expand.

```
# Should expand, doesn't
oil$ var x = "~/mail"; echo $x
~/mail

# This works though
oil$ var x = "$HOME/mail"; echo $x
/home/metov/mail
```

How do I get `~` to expand?

**Comment by andychu** [comment]
Great question!  This is something of a design issue

Right now my thoughts are $HOME and a new `homedir('bob')` function

```
var x = "$HOME/mail"    # as you found

var y = "$[homedir('bob'])/mail"   # like ~/bob/mail

# can also write it like this

var y = homedir('bob') ++ '/mail'

```

The issue is that `~bob` is a shell word, but the RHS of `=`, is a Python-like expression

Also in shell double quotes, `~` isn't respected, it's just literal

**Comment by andychu** [comment]
An option which I might hesitate to recommend is

```
$ bin/ysh -c ' var y = %( ~/bob/mail )[0]; echo $y'
/home/andy/bob/mail

```

So in short, there are many ways, but I'd like to settle on one recommendation

**Comment by metov** [comment]
Um, sorry if this is a dumb question but... Is it not an option to simply support `~` in expressions? (If I'm not mistaken, the RHS in `var ... =` syntax is called the "expression language")

I understand that there are some subtleties in how `~` is handled differently from variables like `$FOO`, *in bash*. But why should ysh follow bash in this pointless distinction? Why not just say that `~` is a variable exactly like `$FOO`, and just happens to look different?

Regarding the `homedir` and `%( ~ )[0]` options - I think those wouldn't really work. We already have `$HOME`, which already works in expressions. Those two alternatives are both harder to type and impose greater cognitive overhead than `$HOME`. I think that `~` has been popular historically because it is a very easy to type shortcut for a very common value.

**Comment by andychu** [comment]
To support `~` and `~bob`, would have to remove Python- and C-style bitwise operators (and I actually left them out at one point):

```
var x = ~bob  # bitwise negation

var x = ~   # syntax error
```

The `~` operator isn't used much, but `|` is reasonably common

The more pressing issue to me is that I wouldn't really like this syntax

```
var x = ~bob ++ mystr
```

It would be better if it were somehow a quoted string

```
var x = ~'bob' ++ mystr
```

But that isn't too different than a function

```
var x = homedir('bob') ++ mystr
```

**Comment by andychu** [comment]
Overall I agree that `~/src` and `~bob/src` are  nice because they're familiar , but generally we want to reduce "punning" where the same symbol means 2 things, depending on context

It's already true that these things are different:

```
echo ~
echo "~"
```

but these are usually the same

```
echo $x
echo "$x"
```

One possibility I thought of was 

```
echo $~
echo $~bob
echo "$~"
echo "$~bob"
```

but that seems too unfamiliar

I think `$HOME` will solve 90% of the problem, but there's also the `~bob` problem

**Comment by andychu** [comment]
I thought about this a bit more, and I think the best answer is

```
declare x=~bob/mail

readonly y=~alice/src

```

They already exist and work

Personally I would use 

```
const x = "$HOME/src"
```

for most cases.  We  should document this in teh "Quirks" doc.

----

A solution I thought of but ruled out is to disambiguate by forcing it to be a prefix of a quoted string


```
const x = ~bob/'mail'
var y  = ~alice/"src/$dir"

const a = ~bob''
```

But a problem is that the rules are a bit too subtle in shell:

```
$ bash -c 'echo ~andy""'
~andy

$ bash -c 'echo ~andy'
/home/andy

$ echo ~andy/''
/home/andy/

$ echo ~andy/""
/home/andy/
```


The quotes actually break the expansion in the first case!     There has to be a `/` divider that's unquoted

**Comment by metov** [comment]
Thank you - that clears it up a bit! I guess I was too used to bash etc treating everything as a string. I see now that it gets complicated since we actually have types in YSH.

Seems hard to come up with a good way of supporting the old style `X=~bob` syntax of bash.

**Comment by andychu** [comment]
Thanks for the feedback, this is now documented

There probably won't be a path type -- this post goes into the design and philosophical reasons behind that: https://www.oilshell.org/blog/2023/06/ysh-design.html
