### ISSUE TITLE
All types should have bool(x) ,    'foo' or 'bar' should work

### ISSUE THREAD

**Issue by metov** [oilshell/oil#1627]
I have a convenience script to make it easier to open VS Codium, which I do very often:
```
#!/usr/bin/env oil
#
# Launch codium.
#
# Without parameters, it will attempt to start with a sensible workspace.
#  * If you are in a git folder, it will open at git root
#  * Otherwise, it will open at the current folder

const GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
const WORK_DIR=$(pwd)

const WS_DIR = GIT_ROOT or WORK_DIR

codium $WS_DIR
```

This script used to work great. However, after a recent update, it now dies with:
```
$ cod
  const WS_DIR = GIT_ROOT or WORK_DIR
        ^~~~~~
'.../cod':12: fatal: Expected Bool
```

Because expression syntax is not yet comprehensively documented, and because it so closely resembles Python, I had assumed that Python-style `may_be_null or fallback_value` would be valid oil syntax, which it was for quite some time. However, coincidentally around the time of the rename, it stopped working, so I guess it's not valid ysh syntax :)

I'm guessing that the issue here is that since I've used `or` the expression evaluates to a boolean. Is it possible to preserve the old behavior of returning the first truthy value like in Python?

**Comment by andychu** [comment]
Thanks this is a good catch, I think it's due to some recent refactoring around divorcing us from the Python interpreter #636 

I'm not sure exactly what we will do -- I like the `or` idiom too, and I agree Python users will expect it

Though I also think there is a wart in Python because    empty string and None or often confused, and it can cause subtle bugs.  I think there were a few of those in Oils itself

For now I think you might have to use a ternary

```
const WS_DIR = GIT_ROOT if len(GIT_ROOT) else WORK_DIR
```

which is longer but at least clear

Although then you might also wonder why it's not:

```
const WS_DIR = GIT_ROOT if GIT_ROOT else WORK_DIR
```

I will look into why this changed

**Comment by andychu** [comment]
I just tested JavaScript and its `||` behaves like Python, so yeah I think we need to retain this idiom

Thanks for the feedback!

in the meantime hopefully the ternary if will work

**Comment by andychu** [comment]
@metov This is now fixed, thank you for the report

I also fixed

- #1605 

and documented

- #1625 

FAQ here - http://travis-ci.oilshell.org/github-jobs/4147/ovm-tarball.wwz/_release/VERSION/doc/ysh-faq.html

These fixes will be out with the next release, but you can always download a tarball from the CI.  If the tests pass then it is pretty much as good as a release:

http://travis-ci.oilshell.org/github-jobs/4147/

C++ http://travis-ci.oilshell.org/github-jobs/4147/cpp-small.wwz/_release/oils-for-unix.tar

Python http://travis-ci.oilshell.org/github-jobs/4147/ovm-tarball.wwz/_release/oil.tar

---

Let me know if you see other issues or have other feedback!  Thank you

**Comment by andychu** [comment]
Released a few weeks ago: https://www.oilshell.org/blog/2023/06/release-0.16.0.html
