### ISSUE TITLE
YSH echo $x  should always be correct, disallow -e -n

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1634]
This somewhat goes against our https://github.com/oilshell/oil/wiki/Language-Design-Principles

But I think it makes the language better

It's a little bit like `*p` in Go, an exception to the rules

**Comment by bar-g** [comment]
Thanks!
So, if I understand correctly, simple_echo should now work nicer with simple_eval and in ysh (often used parts of the short shell lang syntax are now made to work well):
`echo This $foo is nicer than $bar.`

---

I'm just not sure where you mean going against which language design principle.

Together with renaming simple_echo to `strict_echo` (https://github.com/oilshell/oil/issues/1117) I think the breaking change makes good sense . Because "strict_echo" is much better in hinting towards the removed gets-parsed-as-arg pitfalls. (And without changing/introducing new `--` syntax.)


Maybe it has to do with `write`:

Concerning the
> "Where Oil duplicates functionality from OSH (like arithmetic), it has to be significantly better.":

Maybe `writeln` as a synonym for `write --sep ' ' ` could be a significant lift for the ysh writing goodness.

`write -n` is already a synonym,  so programmatic switching of that behaviour may already be covered by something like `write maybe($newline_opt)`

So, is `write -e` a similarly needed synonym to be better than OSH? Can the string language be switched programmatically?

**Comment by bar-g** [comment]
Hm,  as @metov wrote https://github.com/oilshell/oil/issues/1605#issuecomment-1537560282, seems to boil down to wheighing the change consequences of either adding  `--` (and possibly --end, --sep, etc.) to echo, or a breaking new `write` syntax.

**Comment by bar-g** [comment]
Uh, as it does not prevent shell pitfalls, what's possible might  still rather be just a `robust_echo` for OSH, and`a conveniece `optless_echo` for YSH. (Making best use of what echo coding can reliably do.)

**Comment by andychu** [comment]
Well I think we should get feedback from real programs on the current YSH behavior, which I think is pretty good.  I think of it is like this:

- `write` does everything you want, but the syntax can be long sometimes
- `echo $x` is a shortcut for `write -- $x`
- `echo $x $y` is a shortcut for `write --sep ' ' -- $x $y`

Regarding the breakage, I think it's justified because correct shell scripts (like GNU autoconf) don't use `echo $x` at all!

Instead they use

```
printf '%s\n' "$x"
```

which is correct but even more verbose

**Comment by bar-g** [comment]
Yes, I think I can fully agree with the new type of "simple_echo" for YSH. Thinking of echo as a handy write-shortcut in YSH can be helpful.
And it doesn't rule out at all that some nice shortcuts could be found in the future, that work well even within the `write` command.  (So "significantly better" can even be applied some more to it. ;-)

Concerning my "strange feeling" around the latest echo change, I think some understanding just dawned on me, though: 

I think having two options are well worth it, the old "simple_echo" behavior can allow and ensure robust usage of `echo` in OSH (and $'shell'), and the new behavior can work well with YSH.

So, I'm thinking of opening an issue to **(re)introduce old simple_echo as strict_echo**, what do you think?
Going for two tools, each best for their job?

**Comment by bar-g** [comment]
Hm, possibly only the new behaviour is the one and only true `strict_echo`.

I think then the smoothest upgrade path could be to just naming it as such, together with "officially" adding some `[pitfall free: add quoting, -e => $' ' , -n => printf '%s\n' "$x", or write in YSH]` to the hints section in its error message.

**Comment by andychu** [comment]
Hm what would a new option do?  I don't see any need for it

I think the existing options cover all bases

---

We may expose the AST for people to write their own lint tools, there is a Zulip thread about "Exporting the AST"

Basically we are trying to cut down the scope of the project, and not take on all problems.  Some problems can be solved by simply switching to YSH :)

**Comment by bar-g** [comment]
Ok, playing around with the new one-and-only "strict_echo" I so find it could be pretty good, if augmented with some reasoning and helping hints in the error messages.

As a side product playing also brought up a nice, better motivating example for `write`, showing off how it plays much better regarding feature composition, as in indent-safe multi line writing:
```
... write
    "Hello world"
    "Hello oils"
    "Hello indent-safe writing without repetitive echoing."
;
```

**Comment by andychu** [comment]
Yup that is one way to write it; another way with Python-style multi-line strings

```
write '''
  Hello world
  Hello oils
  Hello
  '''  # indentation of closing quote is stripped from all lines; first newline removed too
```

**Comment by bar-g** [comment]
BTW: I really appreciate your thorough going about options, and replies with much insights from years of shell comparision. I hope you are also ok with my way of scrutinizing things from time to time, that had left behind questions on my part. Hope they can help you smoothing out the experience by better naming,  and adding helpful hints and examples to docs and especially error messages, so exactly where the questions arise for the users.

**Comment by andychu** [comment]
Released a few weeks ago: https://www.oilshell.org/blog/2023/06/release-0.16.0.html
