### ISSUE TITLE
bug: abort on special characters following '!'

### ISSUE THREAD

**Issue by citriqa** [oilshell/oil#1640]
entering a line that includes for example `!$` or `!^` aborts the shell (thanks to 475b065aa27f55932648f9ade3d50ec7639c671b)

version: osh (oils-for-unix) 0.15.0, compiled --with-readline using gcc 12.2.0 for x86_64-linux

**Comment by andychu** [comment]
Now fixed -- great bug report thank you!  Every commit makes a tarball, so you can get one from here:

http://travis-ci.oilshell.org/github-jobs/4171/

cpp-small -> make-tar -> Results

http://travis-ci.oilshell.org/github-jobs/4171/cpp-small.wwz/_release/oils-for-unix.tar

**Comment by andychu** [comment]
Released a few weeks ago: https://www.oilshell.org/blog/2023/06/release-0.16.0.html

Thanks for the testing!
