### ISSUE TITLE
Bash Applet

### ISSUE THREAD

**Issue by spitfire94** [oilshell/oil#1650]
The base executable should react differently when being called `bash`, as it does with `osh` and `ysh`. It should discard or respect bash CLI options and startup files. Possibly disable `errexit` by default, and set other expected options; a shell option group might be desirable for this. Also install a symlink for `/bin/bash`, if it doesn't already exist. 

My rational is a simpler and better behaved upgrade of runtime shells and command runners. Specifically outright overriding `bash` within `nixpkgs`, because `--noprofile` is often used. Only problem might be completion scripts, if `bashInteractive` depends on the overridden `bash`.

**Comment by andychu** [comment]
It currently behaves like `osh` if `argv[0]` ends with `sh`, and is designed to be compatible with bash

It supports a bunch of bash flags

It's generally more helpful to file a specific issue that will help get a certain program running, with a repro -- as is I'm not sure what's actionable here

**Comment by andychu** [comment]
generally speaking we try to avoid blowing up the test matrix -- there's no real reason that osh can't have the bash behavior deemed necessary
