### ISSUE TITLE
oils-native: fatal: Undefined variable 'abc'

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1652]
0.16.0 native on aarch64

```
$ysh
ysh$ const abc = 'one'
ysh$ echo $abc
  echo $abc
        ^~~
[ interactive ]:2: fatal: Undefined variable 'abc'
```

**Comment by bar-g** [comment]
(With `osh`and "ordinary shell" code I havn't noticed problems since compiling 0.16.0., 
only with the improved, "yet shell" code.)

**Comment by bar-g** [comment]
Ha, that nicely fits "every nice feature" it has: pitfall free, familiar to programmers, ... yet it's a shell. => (the 'yet' shell `ysh` :-)

**Comment by bar-g** [comment]
Maybe relevant, pasting again the warning I got when compiling (https://github.com/oilshell/oil/issues/1615#issuecomment-1586281244):

```
mycpp/gc_list.h:271:20: 'status' may be used uninitialized.
  271 |  slab_->items_[i] = item;
      |  ~~~~~~~~~~~~~~~~~^~~~~~
```
After compilation I repacked the compiled oils package to avoid recompiling again, and have installed that package again on a freshly installed system.

**Comment by bar-g** [comment]
Ah, ok, but unfortunate that it brings up misleading error messages and issue trouble, though. 

So, still a not fully working yet-shell, but growing ;-)
Back to the oil-* package, for now.

**Comment by bar-g** [comment]
Almost forgot to let you know: Playing with `osh` of native build it already did feel like the real thing, the speedup is really noticeable even in interactive mode on the arm board.

**Comment by andychu** [comment]
```
ysh ysh-0.19.0$ const abc = "one"
ysh ysh-0.19.0$ echo $abc
one
```

This was fixed awhile ago!
