### ISSUE TITLE
HOST_NAME_MAX doesn't appear to be defined in macos

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1656]
I was able to overcome this by adding `#define HOST_NAME_MAX _POSIX_HOST_NAME_MAX` to the top of `cpp/libc.cc`, but that should probably be done with some sort of `#ifndef` thing.

**Comment by andychu** [comment]
Hm it appears that's the right fix

https://reviews.freebsd.org/D30062

----

This message was confusing me

https://lists.gnu.org/archive/html/bug-gnulib/2009-08/msg00108.html

Also I looked at CPython's socketmodule.c -- the max host name is simply 1024

But I think `_POSIX_HOST_NAME_MAX` is right

---

Actually maybe we can use that all the time, like this patch - https://reviews.freebsd.org/R11:a33ecd73b409488686af2342b8d143923805a984

Let me try it on Linux

**Comment by andychu** [comment]
OK this seems to work, thanks!  You can try the tarball when it appears here

http://travis-ci.oilshell.org/github-jobs/

**Comment by andychu** [comment]
Released, announcement forthcoming - https://www.oilshell.org/release/0.17.0/
