### ISSUE TITLE
READLINE_DIR is not used in build/ninja-rules-cpp.sh

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1657]
If you pass `--readline=/path/to/readline` to `configure`, then `build/ninja-rules.cpp.sh` should add `-I/path/to/readline/include` to `flags` and `-L/path/to/readline/lib` to `link_flags`. This can be accomplished by checking for the `READLINE_DIR` variable from `_build/detected-config.sh`.

**Comment by andychu** [comment]
Released, announcement forthcoming - https://www.oilshell.org/release/0.17.0/
