### ISSUE TITLE
--gc-sections not supported by ld on macos

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1658]
This is set as part of `link_flags` in `build/ninja-rules-cpp.sh` but throws an error on macos. Apparently the equivalent option is `-dead_strip`.

**Comment by andychu** [comment]
Hm I wonder what the best way to handle this is

Should `./configure` test if `--gc-sections` is supported and then set  HAVE_GC_SECTIONS?

We already test if a basic C program can be compiled, so probably

A patch would be very welcome!

**Comment by andychu** [comment]
Released, announcement forthcoming - https://www.oilshell.org/release/0.17.0/

Thanks for the patches!
