### ISSUE TITLE
Trying to build CPP release from website, and getting errors from ninja-rules-cpp.sh

### ISSUE THREAD

**Issue by joelatschool** [oilshell/oil#1703]
Hey, I just read about this and sight-unseen decided to try it out, and so tried to install the CPP build from the website. After running `./configure`, I tried running `_build/oils.sh` (according to the instructions) and got the following output:
```
CXX _gen/bin/oils_for_unix.mycpp.cc
CXX _gen/core/runtime.asdl.cc
build/ninja-rules-cpp.sh: line 77: READLINE_DIR: unbound variable
build/ninja-rules-cpp.sh: line 77: READLINE_DIR: unbound variable
```
Is there something I'm doing wrong?

**Comment by bar-g** [comment]
I don't know about that error, some time back an error I got went away after adding RAM space (swap actually) to get to 1GB on an ARM board.

The python based oil-* build seems still better for trying out. Somewhere there are stats of the still failing tests of the new oils build, think they still haven't completely catched up yet.

**Comment by andychu** [comment]
Hi Joel, thanks for trying it and and for the report.  I'm surprised about the $READLINE_DIR  error

- Can you paste the output of `./configure` here?
- And also the output of the `_build/detected-*` files?  I think those should contain $READLINE_DIR

Also @bar-g I'd be interested in bug reports about the RAM.  I think we do have that big single translation unit that can cause  this -- actually there is a thread on Zulip about it

---

It's true the C++ version doesn't yet have YSH completely working, but it does have OSH working.  Hopefully we will remove this awkwardness soon, but we can use help testing the C++ tarball for sure!

**Comment by joelatschool** [comment]
Also, if it matters I'm currently using fish as my main shell, although this occurs even when when in a bash session.

**Comment by andychu** [comment]
Released, thanks for the report!  

 https://www.oilshell.org/blog/2023/09/release-0.18.0.html

(Though note we have a known issue #1731 on OS X / BSD for this release, will be fixed soon)
