### ISSUE TITLE
Fuzz the parser with AFL

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#171]
This should help some of the error cases.

This looks like a good intro:

https://barro.github.io/2018/01/taking-a-look-at-python-afl/

I think the steps are:

- Create a main program like `bin/fuzzable_parser.py`.
  - Since a parser is basically a pure function, this should use one of the "fast modes". 
  - That is, we shouldn't have to fork `bin/oil.py` every time, which would be really slow
  - Also, by fuzzing only the parser and not the runtime (basically `bin/osh -n`), then we avoid
    the problem of the fuzzer making syscalls like `fork()` and so forth.
- Write some shell scripts to automate it.

It would be nice to find a server to do this, but I have at least one at home laying around that could be used.

**Comment by andychu** [comment]
This is an ideal task for anyone who has used these tools before.  It shouldn't require too much understanding of Oil code.   Ping me if interested :)

**Comment by andychu** [comment]
Related to #27 -- this will uncover more errors!

**Comment by andychu** [comment]
Two updates:

1. I separated the parser into its own binary!  So it's a simple stdin/stdout filter: https://github.com/oilshell/oil/blob/master/bin/osh_parse.py

2. There's a new startup which offers automated fuzzing:

https://news.ycombinator.com/item?id=19265377

https://docs.fuzzbuzz.io/getting-started/find-your-first-bug-in-python

I guess the value it adds is a user interface / reporting, and more CPU time.  They say will be free for some projects.  I wonder if the Python algorithm is open source?  It says you can debug on your machine.

**Comment by everestmz** [comment]
Hi, I posted the HN thread :) would be happy to help get this project set up on Fuzzbuzz. Let me know if there's anything I can do!

**Comment by andychu** [comment]
Thanks for the response!

I'm mainly looking for a contributor to help with the integration, since I believe that separating out the parser was the first step.  I posted this on my oil-dev list.

Although honestly now that I look at your docs more closely it looks pretty trivial :)

https://docs.fuzzbuzz.io/getting-started/find-your-first-bug-in-python

I could do it myself, but I think it would be good to have someone on the Oil project babysit it and so forth.  It's a nice intro to the codebase.

The parser is very easy to run:

```
build/dev.sh minimal  # generates some Python code
cat configure | PYTHONPATH=. bin/osh_parse.py  # prints the AST of the configure shell script
```

Although now that I look at your docs, it looks like I should separate it into a function and not use `stdin`, so the fuzzing can be faster. 

----

I do think Oil is probably one of the more interesting fuzz examples:

1. It's a large Python parser, for a real language, which I developed over nearly 3 years!  There are lots of big parsers in C, but fewer in Python.
2. As mentioned, I already test it on over a million lines of shell with every release.  There are no more Python crashes (as of a year ago or more).  There are a few parse errors, which are expected.

I'm a big fan of fuzzing, and it would be cool to write a blog post that talks about dozens of more bugs found by fuzzing, even after all the testing I did.

A lot of people (e.g. on Hacker News, Reddit, lobste.rs) read my posts, e.g. on parsing:

http://www.oilshell.org/blog/tags.html?tag=parsing#parsing

My first experience with fuzzing was running AFL on the toybox project, and it took about a millisecond before it found a C memory error... literally the first thing I tried.  I've been more careful but I am sure that there are many bugs left.

**Comment by icarroll** [comment]
Hi, it's me again! I have been learning about fuzzing recently, AFL in particular, and I think it'd be fun to run fuzzing on Oil's parser. Do you want this done on the fuzzing service, or on a local machine? Both? Don't care?

**Comment by andychu** [comment]
Hi Isaac!  I would go for whatever is easiest to get set up at first.  When I looked at fuzzbuzz docs, it seemed fairly straightforward, but I didn't try it.

I imagine it's similar to Travis... in theory it seems like it should be easy to do our own thing, but in practice Travis seems to produce value, even though their configuration is a little weird -- I don't like shell inside YAML, etc.

----

Some issues I thought of:

- I think to make the fuzzing fast, it needs to be a function and not a binary reading `stdin` as I suspected.  `bin/osh_parse.py` can be adapted to use the StringLineReader instead of FileLineReader on sys.stdin.

- How does fuzzbuzz support data files?  I guess you check them into git?  A better seed would be this big tarball of shell scripts:

http://www.oilshell.org/blob/wild/

which is used for the "wild" tests:

http://www.oilshell.org/release/0.6.pre16/test/wild.wwz/

- Oil is a mix of Python and C.  I assume fuzzbuzz can handle that but I didn't check.  Although there is still a "slow" fallback to use Python instead of C for the parser, i.e. when `fastlex` isn't available.

Anyway, I only used AFL once, so those are my initial thoughts.  I'm open to learning more about it.  Feel free to chat here or on Zulip.

I'm 95% sure it will find something pretty fast, simply because the OSH parser is quite complex.  If it doesn't find something then I will question if the fuzzing is working :)

**Comment by everestmz** [comment]
Hey! Hopefully I can add a bit to this discussion and help answer a couple questions:

> With Travis, I keep most logic in our OWN shell scripts, so in theory it should be pretty to move off of it if we ever have a reason. The travis.yml file is small and I imagine fuzzbuzz's will be too.

That's the right idea, and what we'd like to encourage :) ideally all you need to do for python is run scripts to install your deps, and all other config is selecting which targets in your codebase you'd like to fuzz.

> I think to make the fuzzing fast, it needs to be a function and not a binary reading stdin as I suspected. bin/osh_parse.py can be adapted to use the StringLineReader instead of FileLineReader on sys.stdin.

The standard method of writing a fuzz target is to write a method that consumes a buffer of bytes, and parses/runs computations on that data. So the ideal integration would be with functions, rather than reading from stdin, yes.

> How does fuzzbuzz support data files? I guess you check them into git? A better seed would be this big tarball of shell scripts

You could pull this into the environment during the build steps using `wget` or something similar, since this is a publicly-available file. 

> Oil is a mix of Python and C. I assume fuzzbuzz can handle that but I didn't check. Although there is still a "slow" fallback to use Python instead of C for the parser, i.e. when fastlex isn't available.

Fuzzbuzz uses code coverage to track which inputs produce interesting results, and python code coverage doesn't hook nicely into C/C++ code (so if your python code uses some C bindings, code coverage of the bindings wouldn't be tracked). If you have a significant part of your implementation in C/C++, I'd recommend fuzzing both the python frontend, and writing separate targets in C that exercise that portion of the codebase.

**Comment by icarroll** [comment]
Well, I've started poking at fuzzing the parser using the notes at https://barro.github.io/2018/01/taking-a-look-at-python-afl/

So far all it's done is tell me there are crashes where there aren't any when run without the fuzzer, so clearly something's not right. I will keep working at it though.

**Comment by andychu** [comment]
Hm if you have a public repo I can give it another set of eyes.  We can chat on Zulip too.

I haven't used the Python version, but I have used the C version. I imagine the principles are the same but all the details are different.  It should give you back an input that crashes and the crash should be reproducible without the fuzer.

**Comment by icarroll** [comment]
Ok, now that I've gotten my derp-errors out of the way, I have python afl running using the git scripts as the starting point. Next step will be to change to using persistent mode so it doesn't have to fork each time. Anyway, 125k total execs so far at 450/sec , so I'm going to call that progress.

I have $300 credit on Google Compute from my Malware class where I am learning about fuzzing, so my plan is just to fire up a bunch of fuzzers and let them run for a few days and see what happens.

**Comment by icarroll** [comment]
Ok, 1 million executions on the git scripts failed to find a crash. So that's good but boring. :)

What set of scripts is likely to exercise the strange corners of the parser?

**Comment by andychu** [comment]
Hm so it started with all the git shell scripts here:

http://www.oilshell.org/release/0.6.pre16/test/wild.wwz/

and found nothing?  Maybe it's because they're all test scripts and don't use much of the language.  I would avoid distro/alpine/ and anything autoconf related because they also don't use many corner cases.

I think the shell directory has a lot of weird scripts:

http://www.oilshell.org/release/0.6.pre16/test/wild.wwz/shell/index.html

Maybe one thing to do is insert a crash and see if the fuzzer finds it.  Random example:

https://github.com/oilshell/oil/blob/master/osh/word_parse.py#L182

A slice can have a second arg like `echo ${a:1:1}`.  It should be somewhat greppable in shell scripts -- it is not used very often, but it is used.

If you insert a `raise AssertionError` I wonder how long it will take for the fuzzer to hit that code path, starting from some seed that does NOT ever use that syntax?  

Maybe the Python fuzzer isn't smart enough to synthesize the `:` because that's all done in the lexer?  We're testing for tokens everywhere and not literal characters.

**Comment by andychu** [comment]
Also, one thing is that I just spent a few days statically typing the parser with MyPy.  Surprisingly, I found no bugs, and I needed less than 10 casts.  This is in same `bin/osh_parse` binary, which is somewhere around ~10K lines of code.

I'm a little surprised I found no bugs.  However I will be VERY surprised if fuzzing doesn't find any bugs!

Oil is using algebraic data types unlike any other shell parser, which I suppose proves some things... but still I will be surprised !!!

(On the other hand, I don't have MyPy's strict None checking on.  So maybe there is a `None` crash somewhere.)

**Comment by icarroll** [comment]
A million executions took about 30-40 minutes using the standard fork/exec method.

I like the idea of inserting an exception to see if the fuzzer will find it. I will definitely do that.

I pulled all the shell scripts into a single directory and pointed afl at it, and it spammed me with complaints that files were too big or too small or didn't do this or that. I need to investigate that to see if I'm presenting the files wrong.

I'll make sure the third slice argument gets presented to the fuzzer, and see if there's some way to exercise the None paths.

Once I have the persistent fuzzing figured out and a good corpus of inputs selected, I will turn it loose on a 16cpu beast and let it run overnight and see what happens.

**Comment by icarroll** [comment]
Something I just realized is that AFL has a fairly short default timeout. I will need to make sure it's long enough to allow the parses to complete.

**Comment by andychu** [comment]
Yeah I was thinking that you can try NOT to present the third slice argument, and see if the fuzzer is "smart enough" to find it.  That is, start with a dumb corpus and see how smart it is.  If it can't find that, then it likely can't find other bugs.

In C, AFL is supposed to be able to discover these things on its own, as far as I understand, e.g.:

https://lcamtuf.blogspot.com/2014/11/pulling-jpegs-out-of-thin-air.html

I think not doing fork/exec will make a HUGE difference because the Python interpreter is slow to start up.

Even after that, it's also possible that because the parser is simply much slower in Python that it just takes a long time to find bugs.

The parser is 10-50x slower than bash as measured here:

http://www.oilshell.org/release/0.6.pre16/benchmarks.wwz/osh-parser/

Although it inherently does more work, so it's probably more like 5x to 20x slower if you want a fair comparison.  (This is why I added MyPy types and am trying to do an auto-translation to C++).

1M doesn't sound like very many in 30-40 minutes, even in Python.  I will do some research, but if I had to guess I think you can do more like 100M in that time.  Large files may not be better either.  I think most crashes should be triggerable by 100 bytes rather than a 10,000 byte source file.

**Comment by andychu** [comment]
Also, I'm not sure how much it helps, but there are some small shell fragments in these two files:

https://github.com/oilshell/oil/blob/master/test/parse-errors.sh

https://github.com/oilshell/oil/blob/master/test/runtime-errors.sh

http://www.oilshell.org/release/0.6.pre16/test/other.wwz/parse-errors.txt

http://www.oilshell.org/release/0.6.pre16/test/other.wwz/runtime-errors.txt

**Comment by icarroll** [comment]
I just asked my Malware instructor about strategies for fuzzing large codebases like a parser and his advice was to use grammar fragments as input samples, and fuzz subsystems separately.

Ok. My next test will be to plant a crash in the third slice argument and see if afl will find it without it being explicit in the input.

I will also figure out the persistent testing. I saw a chart that says you can get roughly 17k executions per second rather than 450 the exec way.

Go ahead and assign me to this issue. I'm totally into it. :)

**Comment by andychu** [comment]
@icarroll Did you have any luck getting Python-AFL to hit an artificially inserted bug?

One thing I was thinking might cause problems is that the lexer should be 100% crash-free because it's C code generated by re2c.  re2c generates code with a bunch of goto's and ensures that every control flow path is considered.

So all the crashes should be in the parser.  I don't know if AFL can "see" past the lexer into the parser.

FWIW here is the input file; I don't have the output file handy:

http://www.oilshell.org/blog/2017/12/files/osh-lex.re2c.h.html


-----

Another thing to note is that the lexer can run in pure Python mode, using the Python re module.  However that will likely have the same issue since random inputs will almost certainly not cause it to crash.

**Comment by icarroll** [comment]
I have worked on it a little, but have been busier than usual with end of term stuff, so haven't made as much progress as I'd like. So far I've been unable to make it hit an artificial crash, so I'm sure I'm doing something wrong. I think I'm setting up the fuzzing wrong since it always says 1 path found no matter how long I leave it running. It may have something to do with how the fuzzer treats imported modules.
Next thing I will try is writing a tiny example to find an artificial bug, then expand from there.

**Comment by andychu** [comment]
OK no rush, and I definitely think that inducing a crash in some non-OSH code would be a good idea now.  Just to test that the methodology is right and to see how long it takes.  I think speeding it up by fuzzing a function rather than a process will be a big help.

I was saying that OSH may be hard to fuzz because of it's generated lexer.  Maybe @everestmz can comment on that?

If the lexer is a big bunch of generated C code with no crashes like this, will that cause problems for the fuzzing algorithm?  i.e. it might not be able to explore the parser if it can't understand the control flow of the lexer, with many big switch statements and  gotos ?

http://www.oilshell.org/blog/2017/12/files/osh-lex.h.txt

(This code is generated by re2c.)

**Comment by icarroll** [comment]
The good thing about AFL is that it instruments the code it's fuzzing, so it can see what code paths are getting taken. It has logic to specifically try to activate new code paths as much as possible. The main issue that comes to mind is whether we'll be able to fuzz the C code and the Python code at the same time, or if we'll need to do them separately. Which doesn't sound like that big of a hardship to be honest.

Now that my class is finished I will spend some quality time with AFL and Oil, and see what I can come up with. When would be a good day/time to get a mini brain dump from you about the overall structure of the code? I feel like that would really help me to get started.

**Comment by andychu** [comment]
Oops, I was going through old bugs and I realized I didn't respond to this question :-/

The parser has been translated to C++ now.  That doesn't mean there aren't any bugs of course :)  Crash bugs can persist across the translation process.

http://www.oilshell.org/blog/2020/01/parser-benchmarks.html

Also, fuzzing the whole "pure" interpreter could be interesting.

http://www.oilshell.org/blog/2020/06/release-0.8.pre6.html

Sorry I don't have anything very concrete here.  Always happy to answer questions about the code structure -- it's definitely settled down.  Oil is very strongly typed compared to other shells and other C codebases now due to its use of ASDL.

**Comment by andychu** [comment]
Closing since I think this may not have much bang for the buck in Oil ... or at least we have to figure out a way to "get past" the exhaustive lexer
