### ISSUE TITLE
Str* raw_input(Str*): Assertion `0' failed

### ISSUE THREAD

**Issue by hexagonrecursion** [oilshell/oil#1759]
# Expected behaviour

./configure should fail by default if readline is not detected because oils-for-unix only partially supports running without readline. If someone wants a partially-broken osh that was built without readline, this should be an opt-in (some kind of ./configure flag perhaps)

# Actual behaviour

If oils-for-unix was built without readline, it crashes with a runtime error.

# To reproduce
1. Download oils-for-unix-0.18.0 tarball https://www.oilshell.org/download/oils-for-unix-0.18.0.tar.gz
2. `./configure` - does not fail; does not even print any warnings
3. `_build/oils.sh`
4. `sudo ./install`
5. `osh` - fails with an error
```
osh: mycpp/gc_builtins.cc:428: Str* raw_input(Str*): Assertion `0' failed.
Aborted (core dumped)
```

**Comment by andychu** [comment]
Great bug, thanks for testing!  I will fix this

**Comment by andychu** [comment]
This will be out with the next release, thank you!

**Comment by andychu** [comment]
Fixed awhile ago, late announcment - https://www.oilshell.org/blog/2024/01/release-0.19.0.html
