### ISSUE TITLE
Ctrl-Z to vim launched from OSH suspends but can't be resumed

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#176]
See issue #36.  The fix here is different than Ctrl-C.

It might be easier to fix when we don't have Python's signal handling logic in between OSH and the kernel.

**Comment by andychu** [comment]
The problem is that OSH itself goes into the background!

**Comment by andychu** [comment]
Fixed with http://www.oilshell.org/release/0.6.pre16/

**Comment by jyn514** [comment]
If I suspend from inside vim, I can't do anything else in `osh`, it doesn't respond to any input and I have to close my terminal. `strace` output, starting from just before `vim` opens:

```
strace: Process 28300 attached
select(1, [0], NULL, NULL, NULL)        = 1 (in [0])
rt_sigaction(SIGWINCH, {sa_handler=0x7f338d64d2e0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f338f0c7f20}, {sa_handler=0x55e6c8a22130, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f338f0c7f20}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "\r", 1)                        = 1
write(1, "\n", 1)                       = 1
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
rt_sigaction(SIGWINCH, {sa_handler=0x55e6c8a22130, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f338f0c7f20}, {sa_handler=0x7f338d64d2e0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f338f0c7f20}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f338f0c7f20}, {sa_handler=0x55e6c8a22130, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f338f0c7f20}, 8) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f338f66fa10) = 28335
wait4(-1, 0x7ffccc2ae3bc, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_STOPPED, si_pid=28335, si_uid=1000, si_status=SIGTSTP, si_utime=10, si_stime=2} ---
--- SIGTSTP {si_signo=SIGTSTP, si_code=SI_USER, si_pid=28335, si_uid=1000} ---
```

`clone` comes just as `vim` opens, `SIGCHLD` and `SIGSTP` come just as I suspend it.

**Comment by jyn514** [comment]
I think this might be fixed by using`posix.waitpid` instead of `wait`, see http://man7.org/linux/man-pages/man2/wait.2.html

**Comment by jyn514** [comment]
That worked! Now we just have to implement `fg`, `bg`, and `jobs`. I'll submit a patch for suspending and continuing in the meantime.

**Comment by andychu** [comment]
OK cool!  I was confused about that.  I do see WUNTRACED in dash source code.

Job control in general is quite hairy and OSH doesn't have it yet.  There is a line in APUE by Stevens that says it's a big hack involving the shell and the kernel, but POSIX requires it.  I personally prefer to use tmux or screen than job control, and I think it's a more elegant solution.

I would like to implement a "basic" `fg` and `bg` without job control, but I'm not sure if that even makes sense!  At least the cycle of Ctrl-Z -> fg should work, I would hope.  But again it's a very hairy area.

I think I have a reference for it somewhere ...

**Comment by andychu** [comment]
Yeah I saved this link

https://www.gnu.org/software/libc/manual/html_node/Implementing-a-Shell.html

but I haven't understood it yet.

(from here: https://github.com/oilshell/oil/wiki/ExternalResources

It does not look fun so I was hoping to have something simpler in the meantime... obviously we should fix this bug because it's a bad user experience if Ctrl-Z hoses your "session", but I'm not sure how far to full job control is feasible / desirable right now.

**Comment by jyn514** [comment]
So AFAIK there are a few things that have to be implemented for real job control:

- When we suspend a process, put its PID in a job list so we can resume it later.
- When a process is resumed, wait for it. This is probably the easy part, we can just call `Waiter.Wait` since we shouldn't have more than one direct child in the foreground at once.
- When the shell exits, 
    1. Warn the user that jobs are suspended (bash says 'There are stopped jobs.')
    2. If they continue, send the appropriate signals to all suspended processes. This looks pretty complicated, I found http://curiousthing.org/sigttin-sigttou-deep-dive-linux and an strace of suspended vim shows `SIGTERM`, `SIGCONT`, `SIGTTOU`, `SIGTERM`, and `SIGTERM`, all right after the other. I'll have to look into whether that's handled by us or the kernel.

If we have all that set up, `bg` and `fg` should be pretty simple, we just call `jobs.append(Executor._RunJobInBackground(process))` or `resume(jobs[job_num])` respectively. Note this requires us to refactor `_RunJobInBackground` to take a *process*, not just a syntax tree, because we want to be able to suspend/resume long-running processes without losing our progress.

On a related note, it looks like we've been handling IO for background processes wrong, `python -c 'input()'` should not be able to read stdin since this conflicts with the foreground process. Note `fg` should also let us bring background processes to the foreground.

**Comment by jyn514** [comment]
It looks like there's already a rudimentary `Job` class in `core/process.py`, but we'll need that to be in `osh/Mem.py` so it has access to *all* the currently running jobs.

**Comment by jyn514** [comment]
I'm not sure there's a way to do this part way, since we can't intercept `SIGSTOP` if a process calls it on itself like vim. The good news is I don't think many people use Ctrl-Z as often as I do so it shouldn't be a giant usability issue in the meantime.

**Comment by andychu** [comment]
Hm I am not sure I completely follow, but maybe let's handle some of the "easy" drawing issues first and circle back ...

**Comment by andychu** [comment]
@jyn514 Sorry I just realized I sorta cut off this conversation ... I just put in WUNTRACED in after some head scratching!

Although I suppose some good news is the signal code is cleaner than it used to be, and consolidated in one place at the top of core/process.py.

I am going back and reading your other comments more carefully ...

**Comment by andychu** [comment]
OK I got the basic vim -> Ctrl-Z ->  fg cycle working!  There is still more to do (described on #360 ) but I'm going to leave it for now.  At least it won't "blow up" when trying to do something relatively common.

**Comment by jyn514** [comment]
Just tried this out, it works great!

**Comment by andychu** [comment]
OK awesome!  It did require a lot of restructuring of the code... the abstractions there were pretty incomplete.  But I think the rest of job control is basically putting syscalls in the right place and probably don't require too much restructuring (?)

**Comment by jyn514** [comment]
Don't forget `$!`, I mentioned it in https://github.com/oilshell/oil/issues/360

**Comment by jyn514** [comment]
I've actually used background pipelines (rarely) in the past for stuff like `find | grep "<something>"`. Definitely not a high priority feature though

**Comment by andychu** [comment]
Released: http://www.oilshell.org/release/0.6.pre23/
