### ISSUE TITLE
echo builtin should disallow typed args

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1767]
From #1762 

```
andy@hoover ~/git/oilshell/oil (dev-hoover-9)$ bin/ysh -c 'ls (x)'
  ls (x)
      ^
[ -c flag ]:1: fatal: Undefined variable 'x'
andy@hoover ~/git/oilshell/oil (dev-hoover-9)$ bin/ysh -c 'echo (x)'
  echo (x)
        ^
[ -c flag ]:1: fatal: Undefined variable 'x'
```

**Comment by bar-g** [comment]
Hm, I then noticed some amount of special parsing may be present in bash's echo as well:

```
$ echo ()
>
```
(PS2 Prompt)

and `echo (x)` returns unexpected symbol »x«.

(Whereas both `ls ()` and `ls (x)` give syntax errors in bash.)

No idea if that's a bash feature or a bug with no need to mimic.

**Comment by andychu** [comment]
I believe this is because `echo ()` is starting a shell function named `echo`!

I was confused as why `ls ()` gives a syntax error, but I believe it's because I have an alias `ls` in my bashrc

After alias expansion it's a syntax error

`find ()` behaves like `echo ()`

**Comment by bar-g** [comment]
> I believe this is because echo () is starting a shell function named echo!

Ah, ok, indeed:
```
$ echo ()
> { true; }
$ declare -f echo
echo () 
{ 
    true
}
$
```

Looks like it's the same in osh and ysh and safe from variable expansion:
```
$ x="() { true; }"
$ echo $x
() { true; }
$ declare -f echo
$
```
(Unlike with x='-n' or '-e'.)

----
So it seems this is yet another general echo and write pitfall. But one that can be worked around using quotes to actually successfully echo "( anything in parenthesis )".

Maybe osh and ysh can work around it in non-interactive or not is-main modes?

----


> I was confused as why ls () gives a syntax error, but I believe it's because I have an alias ls in my bashrc

You seem correct. I can confirm, I had, too, and after `unalias ls` I also see the same interactive PS2  prompt entering behavior here for echo, ls, and find (in bash, osh and ysh).

Whereas I wonder why your initial ls and echo example show no difference, while you were saying it's special to echo.

> https://github.com/oilshell/oil/issues/1762#issuecomment-1852831193
> (The reason [for this issue] is that echo uses a special flag parser due to lack of --, and this accidentally made it accept (x))

I got rather the impression now, that currently all seem to "accept", well mostly error on expressions?, in the same way, but only echo (and not sure if write also?) should probably just print them verbatim as strings instead.

----

Another thing that seemed to mix in an bug me here is `=`.
* It can show variables just fine, using `= x` and `= (x)`!
* But it can't display defined functions, yet wouldn't it seem as a good place for doing so. (Much better than 'declare -f' for displaying.)
* I don't see the '=' as a more readable replacement for a "pretty-print" `pp`. For readability `show` seems preferable, `=` is just shorter for interactive environment inspection/debugging, but generally rather an operator not a command.
Worth opening an issue?

**Comment by bar-g** [comment]
> [ `anything... ( )` interpreting, just ] yet another general echo and write pitfall.

For `#!/usr/bin/env sh` code, at least shellcheck seems to detect parens as illegal for echo.

**Comment by andychu** [comment]
Fixed by @AtomsForPeace - https://github.com/oilshell/oil/commit/0acb18e7d21d8813a9087c85453b3bae27cbafb1

**Comment by andychu** [comment]
Released, thanks for testing and contributing!   https://www.oilshell.org/blog/2024/02/release-0.20.0.html
