### ISSUE TITLE
Detect {get,set}pwent() functions at configure time to build on Android Bionic

### ISSUE THREAD

**Issue by Melkor333** [oilshell/oil#1774]
Weird and quite irrelevant:

For fun I tried to build the official oils 0.19.0 tar file on [termux](https://termux.dev/en/) with the instructions from the `README-native.txt`.

It fails with the following error:
```
~/.../oil/oils-for-unix-0.19.0 $ _build/oils.sh
...
CXX _gen/osh/arith_parse.cc
CXX _gen/ysh/grammar_tables.cc
CXX cpp/core.cc
cpp/core.cc:150:3: error: use of undeclared identifier 'setpwent'
  setpwent();
  ^
cpp/core.cc:153:13: error: use of undeclared identifier 'getpwent'
    entry = getpwent();
            ^
2 errors generated.
```

This is due to the android libc alternative bionic [not having the pwent functions](https://en.m.wikipedia.org/wiki/Bionic_(software)#Differences_from_POSIX).

The fix is very easy: comment out all 3 `...pwent` function calls. 🎉
Given I only got the python build working inside a [ubuntu proot](https://github.com/termux/proot-distro) I consider this a great success story!!

AFAIU `complete -A user ...` is the only thing requiring this code block and it just gives an empty result with the functions commented.

Now I'm not sure if/how that could be made to work with something like `#ifdef` or if an eventual termux build should just use a `patchfile` anyway (given the requirement of `libc` isn't met).

**Comment by andychu** [comment]
Oh very interesting, thank you!  Let me think about this

What gets broken when you don't have those calls?

**Comment by Melkor333** [comment]
I *think* it only breaks `complete -A user USERNAME`. Grepping through the code only revealed two uses of this code block in the completion:
```
at 18:59:13 ❯ grep -rn GetAllUsers
core/completion.py:385:        for u in pyos.GetAllUsers():
core/completion.py:1103:                for u in pyos.GetAllUsers():  # catch errors?
grep: core/completion.pyc: binary file matches
core/pyos.py:208:def GetAllUsers():
grep: core/pyos.pyc: binary file matches
cpp/core.cc:146:List<PasswdEntry*>* GetAllUsers() {
cpp/core.h:80:List<PasswdEntry*>* GetAllUsers();
cpp/core_test.cc:328:  List<pyos::PasswdEntry*>* entries = pyos::GetAllUsers();
```

I'm working with the fixed build without any issues right now.

**Comment by andychu** [comment]
Ah OK thanks!

I think we can add a `./configure` option for this

Annoying that Android is not POSIX , but this should be worth it
