### ISSUE TITLE
second operator after and/or should be lazy

### ISSUE THREAD

**Issue by Melkor333** [oilshell/oil#1776]
Found while doing the advent of code :).
The following should work, but fails:

```
ysh ysh-0.19.0$ var x = [1, 2]
ysh ysh-0.19.0$ if (true or x[3]) { echo OK }
if (true or x[3]) { echo OK }
    ^~
[ interactive ]:2: fatal: index out of range
ysh ysh-0.19.0$ if (false and x[3]) { echo OK }
if (false and x[3]) { echo OK }
   ^~
[ interactive ]:3: fatal: index out of range
ysh ysh-0.19.0$
```
otherwise this doesn't work:
```
var x = [1, 2, 3, 4]
var i = 0
while (i < len(x) and x[i] < 5) {
    setvar i = i + 1
}
```
result is:
```
while (i < len(x) and x[i] < 5) {                                           ^~~~~
test.ysh:3: fatal: index out of range
```

**Comment by andychu** [comment]
Oh wow, very good catch!  

```
$ bin/ysh -c 'var i = 0; var L=[]; = i < len(L) and L[i]'
  var i = 0; var L=[]; = i < len(L) and L[i]
                       ^
[ -c flag ]:1: fatal: index out of range
```

**Comment by andychu** [comment]
I just fixed this!

If you like you can download new Python or C++ tarballs here:

http://travis-ci.oilshell.org/github-jobs/5746/

e.g. ovm-tarball or cpp-tarball tasks, and then "Results"

Thanks for testing and catching this !!!

(I think this may have worked at some point, and gotten broken by refactoring ...)

**Comment by Melkor333** [comment]
Thanks! 🎉🎉
IDK what's going on but opening the travis link gives me this (after a certificate error):

![Screenshot_20231229-060644.png](https://github.com/oilshell/oil/assets/6412377/f6b28b07-4c2a-4770-bcd8-473795391452)

**Comment by andychu** [comment]
Oh yeah this domain doesn't have HTTPS, sorry

I need to change it in 2 ways - `build.oils-for-unix.org` probably ?     or `ci.oils-for-unix.org`

Tangent: I've been wondering if `oils-for-unix.org` is too long, I almost want `oils-os.org` even though that's less accurate :-P

**Comment by Melkor333** [comment]
> Oh yeah this domain doesn't have HTTPS, sorry
> 
> I need to change it in 2 ways - `build.oils-for-unix.org` probably ?     or `ci.oils-for-unix.org`
> 
> Tangent: I've been wondering if `oils-for-unix.org` is too long, I almost want `oils-os.org` even though that's less accurate :-P
> 
> 
> 

`oils.li` would still be free :-P
`yshell.io` would be short aswell. :D
or `unix-oils.org`

But this is something for zulip I guess :)
