### ISSUE TITLE
source --builtin 'stdlib/math.ysh' failed: No such builtin file

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1782]
```
ysh ysh-0.19.0$ source --builtin math.ysh

  source --builtin math.ysh
                   ^~~~~~~~
[ interactive ]:122: source --builtin 'stdlib/math.ysh' failed: No such builtin file
  source --builtin math.ysh
  ^~~~~~
[ interactive ]:122: errexit PID 44666: command.Simple failed with status 2
```

**Comment by andychu** [comment]
Oh weird, these files are indeed missing from the Python build (not the C++ build)

These tests are supposed to run against real binary and catch it, but they didn't

https://www.oilshell.org/release/0.19.0/test/spec.wwz/ysh-py/ysh-stdlib-2.html

Thanks for the report!

**Comment by andychu** [comment]
Should be fixed with - https://github.com/oilshell/oil/commit/a752f317955aa8eaef3ebfaca436e2c23c000ed8

Though there are still some other problems with the tarball I need to fix

https://oilshell.zulipchat.com/#narrow/stream/308821-containers/topic/ovm-tarball.20task.20doesn't.20run.20spec.20tests.20against.20tarball

**Comment by bar-g** [comment]
Thanks Andy! I was also quite surprised, and had to do some retries before believing.

**Comment by andychu** [comment]
This latest build is much better than Oils 0.19.0:

http://travis-ci.oilshell.org/github-jobs/5868/

`source --builtin` is fixed, plus there was another UnicodeDecodeError issue in the CPython build (not in 0.19.0, but in between)

**Comment by andychu** [comment]
Released, thanks for testing and contributing!   https://www.oilshell.org/blog/2024/02/release-0.20.0.html
