### ISSUE TITLE
'const c' without null on RHS can be re-declared

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1784]
[EDIT after comments]

need `=> is_empty?` and `=> is_set?` (methods returning bool)

For example, as global variables or constants may need to be shared (potentially later also local variables by "entailing" selected "entailed" vars to dynamic scope maybe) between different code parts (func/proc/module), people need a way to check for them, e.g. to init constants (first and only write).
https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash

Creating a (shared) global from within a module's proc/func with `setglobal` would overwrite it unconditionally, otherwise.

---

[Original quest where this came up was: Robust declaration of a globally shared variable. [It also yielded the more specific #1786 and implement try ( ) in addition to try { } #1787 :]

It can only be re-declared as long as it is of NoneType, but not with empty types.
```
ysh ysh-0.19.0$ const c
ysh ysh-0.19.0$ const c
ysh ysh-0.19.0$ const c = {}
ysh ysh-0.19.0$ const c = {}
  const c = {}
        ^
[ interactive ]:2: fatal: Can't assign to readonly value 'c'
```

It seems problematic that the error is fatal, either way, when empty or filled.

Trying it out, strangely `try` does not even find 'const', though?
```
ysh ysh-0.19.0$ try const c = {}

  try const c = {}
      ^~~~~
[ interactive ]:25: 'const' not found
```

Do you think `try const c = {}`  would be a simple and elegant way to ensure existence of a global, without ever resetting it? (After making it fail gracefully.)

----

In any case, how to manually determine if a global var (or "const" dict) has already been declared, i.e. to avoid resetting the required shared resource after it was already initialized and possibly updated by another script/module?

In the git's chap-type-method.md I found `=> keys()`, but it also fails fatal, 
```
ysh ysh-0.19.0$ try echo @[g => keys()]

  try echo @[g => keys()]
                  ^~~~
[ interactive ]:63: fatal: Undefined variable 'keys'
```

and triggers other strange errors after `try`, `=` or `call`:

```
ysh ysh-0.19.0$ echo @[c => keys()]


ysh ysh-0.19.0$  #  so, dict c is empty
ysh ysh-0.19.0$  try call c => keys()

   try call c => keys()
                     ^
[ interactive ]:52: Space required before (
ysh ysh-0.19.0$ try = c => keys()

  try = c => keys()
      ^
[ interactive ]:39: Unexpected = (Hint: use var/setvar, or quote it)
ysh ysh-0.19.0$ try call @[c => keys()]

  try call echo @[c => keys()]
      ^~~~
[ interactive ]:57: 'call' not found

```

**Comment by bar-g** [comment]
EDIT:

Do you think `try const c = {}` could be a simple and elegant way to ensure existence of a typed global, without ever resetting it? (After making it fail gracefully.)

**Comment by andychu** [comment]
Hm I think the `const c` being redeclared when it's Null is a bug -- and is related to a recent change.  It should always fail

Thanks for testing

---

I think in YSH you're not supposed to test if a `const` was already declared -- You're supposed to choose a different name

(Also we still need `shopt --unset copy_env`, which will move env variables out of the namespace)

I don't even  think in shell people do that?  why would you want to test again?


---

I think YSH will have namespaces/modules to reduce the chance of conflict.  Like Python does

We ran into that when doing the YSH stdlib, so it seems likely



----

The "space required before (" error because `try` doesn't accept any arguments

It's similar to the (misleading) error when the `proc` keyword isn't enabled

It's trying to parse the command line like a command, not an expression

(Come to think of it, it may be possible to implement `try (x -> pop())` in addition to `try { }`.  The `()` would indicate an expression)

**Comment by bar-g** [comment]
> in YSH you're not supposed to test if a `const` was already declared -- You're supposed to choose a different name

Well, I wanted a shared variable here (kind of contrary to namespace isolation), e.g. two different scripts or "modules" using the same variable if both are loaded. So both need to define the same variable (allowing to run stand-alone), but should not do so, nor fail, if the variable already exists.

For this I think it's needed that generally re-declaring causes an error, to prevent undesired conflicts, but then, to still be able to share a variable would need some way to probe, or the re-declaration to fail gracefully within `try`.

---
> I don't even think in shell people do that?

I'm sure it's done every day. (Variables are shared with dynamic scope by default and with exporting, thus people doing checking or blind shadowing with a `local`.)
https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash

---

> (Come to think of it, it may be possible to implement `try (x -> pop())` in addition to `try { }`. The `()` would indicate an expression)

Sounds like a good idea, will that also be able to catch those "fatal" errors?

**Comment by bar-g** [comment]
Oh, the last question I think I answer myself, guess the fatal errors would not (and shouln't) be catchable.

**Comment by bar-g** [comment]
> in addition to `try { }`

Hm, braces actually at least make the parsing work.

```
ysh ysh-0.19.0$ try { = c => keys() }

(List)   []
ysh ysh-0.19.0$ 
ysh ysh-0.19.0$ try { call c => keys() }

ysh ysh-0.19.0$ 
```
Problem (as in the stackoverflow question) how to distinguish "notset" and "empty"?
specific bool methods? `c => is_empty?` and `c => is_set?`

**Comment by bar-g** [comment]
Other good alternative (simple) solution?: Make `var` and `const` declarations generally "return success" even if variable already exists, when they would only assign the current value again (no change).

**Comment by bar-g** [comment]
There is some more broken with `try <command>`, the braces even magically make it find `const`.
```
ysh ysh-0.19.0$ try { const c = {} }

  try { const c = {} }
              ^
[ interactive ]:94: fatal: Can't assign to readonly value 'c'
ysh ysh-0.19.0$ try const c = {}

  try const c = {}
      ^~~~~
[ interactive ]:95: 'const' not found
ysh ysh-0.19.0$ 
```

**Comment by bar-g** [comment]
Creating a (shared) global from within a module's proc/func with setglobal would overwrite it unconditionally, otherwise.

**Comment by bar-g** [comment]
> I think YSH will have namespaces/modules to reduce the chance of conflict. Like Python does
> 
> We ran into that when doing the YSH stdlib, so it seems likely

For isolation, the original shell solution seems to be:

For outwards isolation, function bodies, e.g. of main(), can be defined using ( ) instead of { } (see https://unix.stackexchange.com/a/493838).

And for inwards isolation, add `env -i` to the `fork`?

But again, that's contrary to **_sharing_** a global variable between two distinct, sourced shell code modules.

**Comment by andychu** [comment]
OK I'm going to keep this issue for the `const c` problem, and reply on the other issues

```
ysh ysh-0.19.0$ const c
ysh ysh-0.19.0$ const c
ysh ysh-0.19.0$ const c = null
ysh ysh-0.19.0$ const c = null
  const c = null
        ^
[ interactive ]:7: fatal: Can't assign to readonly value 'c'
```

**Comment by andychu** [comment]
Thanks @AtomsForPeace for fixing this!  Will be out with the next release

This was part of

- #1828

**Comment by andychu** [comment]
Released!  https://www.oilshell.org/blog/2024/03/release-0.21.0.html
