### ISSUE TITLE
[ysh] `->` as explicit "pointer assignment" (i.e. for mutables and place.Value pointers)

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1796]
Uh, coming from the shell-side of things some of the issues I filed actually seem to be caused by inconsistent and unexpected behavior inherited from python.

One problem seems that with the `setvar ... = ...` assignments, the same syntax behaves differently, depending on if the data type is mutable or immutable.

Here is the idea, to make these differences apparent, by example:

```
const globaldict =-> {}
var mydict

setvar mydict = globaldict
#=> Error "mutables" types can only be directly assigned as pointers!
#=>
#=>  You may freeze, copy() or deepcopy() the object to create a
#=>    separate "mutable"  (attention, incomplete and infinite copying!).
#=>  Or, use '=->' if you want to assign a pointer to the mutable value.
#=>
#=>   But if ysh can provide something reliable, maybe ruby's .dup or .clone,
#=>    '=' could use that instead of failing.
#=>   https://www.rubyguides.com/2016/01/ruby-mutability/

setvar mydict =-> globaldict  # ok, obviously creating a pointer mydict pointing to globaldict

proc globset( ; d=->globaldict ; set=[ 'start', 1]) # d is a pointer (python's default), init 
                                                    # should be assigned a new literal (on each function call)
{
  setout d[ set[0] ] = set[1]  # as d is a pointer this behaves like 'setglobal globaldict[ set[0] ] = set[1]'

  setvar set = [ set[0] ++ '_end', set[1] + 1 ]  # redefines only the local variable 'set'
  setout d[ set[0] ] = set[1]  # adds another entry to the referenced globaldict
}

globset     #=> globaldict holds start=1 and start_end=2

globset ( set=[ 'first', 21] )   #=> globaldict now also holds first=21 and first_end=22

# executing globset without any options repeatetly will just (re)set start=1 and start_end=2 every time


# if we wanted globset to keep state and count-up on every execution, starting from
# the default or a passed list,
# the proc definition could explicitly specify a pointer for it, too:
proc globset( ; d=->globaldict ; set=->[ 'start', 1])  # now the local var "set" will be a pointer
                                                              # to a passed list, or the mutable default
```

----

Python note to self:
Dict and List assignments work (i.e. behave) different than with numbers or strings.

Effectively, all "mutables" types assignments don't appear to create new variables but pointers (https://stackoverflow.com/questions/2612802/how-do-i-clone-a-list-so-that-it-doesnt-change-unexpectedly-after-assignment). And consequently, mutables passed into functions behave like global string variables within functions (https://stackoverflow.com/questions/15078519/python-dictionary-passed-as-an-input-to-a-function-acts-like-a-global-in-that-fu and 
https://stackoverflow.com/questions/14323817/global-dictionaries-dont-need-keyword-global-to-modify-them).

**Comment by bar-g** [comment]
On the proc/func call-site it could also be made obvious when a pointer is passed:
```
global globaldict = {}
myproc (globaldict)
#=> Error, myproc signature requires a pointer to a Dict for input: "( ; input={} Dict<-=, name)"
#=>    The '=->' sigel is missing.

myproc (=->globaldict, 'bob' )  # ok

```

**Comment by bar-g** [comment]
Hm, an alternative to a special "pointer assignment" operator for setvar, might be a separate keyword.

`setvar mydict =-> globaldict` or `setpointer mydict = globaldict`

Can you tell from practice how common it is to create additional pointers to mutables?

The `setpointer` keyword could be too similar to `setpoint`, which I think is more important, if mutating referenced points should be more obvious than a type dependent `setvar pointervar = ...` assignment.

At the moment I think only having setvar with optional =-> and setpoint seems cleaner to me.

**Comment by bar-g** [comment]
Hm, probably even cleaner if already the mutable Dict declartion itself would require using the "pointer assignment" syntax.

`const globaldict =-> {}`

**Comment by bar-g** [comment]
Maybe the most surprising inconsistency that a `=->` solves is this:

```
var a = '1'
var x = ['1']

setvar b = a   # assigning a to b
setvar y = x   # this is something different (seting y to point to x)

var b = '2'
append '2' (y)

= a
= x #oops
```

**Comment by bar-g** [comment]
Please list drawbacks, if any, to compare.

**Comment by andychu** [comment]
Yeah so the difference between

```
var a = '1'
var x = ['1']
```

is exactly the **atoms** vs. **mutable containers** issue I pointed out in

- #1793 

I agree it is going to be confusing for shell users, but it does follow from the philosophy of "be consistent with Python and JS"

Those languages are both consistent in this distinction too

---

The mutable containers let you write more "algorithms" in shell .  It does become more like programming.

It enables JSON.

There is a very long language design discussion about garbage collection, data structures, and JSON here:

https://lobste.rs/s/lkxfwn/almost_all_fish_shell_has_been_rewritten#c_20rxzb


e.g. fish doesn't have mutable containers / recursive structures, and it ALSO doesn't have JSON

So this is supposed to be one of the main features of YSH :-)

But when you have more **power**, you defnitely have more chance for confusion

**Comment by andychu** [comment]
So bottom line is that `List` and `Dict` are the two mutable containers.    They are exactly what JSON has

---

Now it may be possible to create some kind of `Sequence` and `Map` that is immutable, but that will cause a whole bunch of work ... also introduces syntactic problems

**Comment by bar-g** [comment]
(I'll add @Melkor333 for this part as well.)

I think that the "more specific assignment operators" of this issue could be the other part of a solution to make the different behaviour of rebinding/mutating vs. copying when passing or assigning a variable apparent!

(The other part I would summarize as "& in signatures and on containers", see: https://github.com/oilshell/oil/issues/1793#issuecomment-1900535921 )

---

>> var a = '1'
>> var x = ['1']
>is exactly the atoms vs. mutable containers

Yes, therefore the idea to require a distinct syntax **by default**, e.g. the "pointer" `=->` proposed above. But it could also be like this:
```
var a = '1'     # =  means the assignment result for 'a' is a value independend from later changes of the right side (copy)
var x = ['1'] 
#=> error: use =& and &* to for letting vars point to mutable containers, or copy/deepcopy before using =

var x =& ['1']  # =& means the assignment result for 'x' is same as what the right side points to (here a new literal List).
var f =* y      # =* means the assignment result for 'f' depends on data type of 'y' (as the old unspecified behavior)

# (same for setvar and setglobal)
```
Requiring users to use the `=&` (or  `=->`) for mutables would make it immediately clear that in the second line the left side remains tied to the right side. (And this syntax distinction for assignments would work no matter the actuall underlying implementation of variables and values. Specifically, for mutable ysh data types just as well as for ysh "places" that refer to immutable "atoms".)

---
(An alternative way to require apparent distinct syntax for rebinding/mutating vs. copying behavior could maybe be to let the assignment keywords require &-sigels for mutables and places on the right side. Similar to when calling procs/funcs defined to only take "&args".)

**Comment by andychu** [comment]
Closing in favor of #1831
