### ISSUE TITLE
Use the same Dict from 2 different files (re-using and stand-alone)

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1806]
[Revised Approach:]

I found a successful approach to allow a group of modules to re-use their variables if existing, and to initialize them stand-alone if they don't exist.

However,
* Not sure if it hard-depends on using `if module shared {...}`, or if it could also work with the planned new name-spaced "modules V2"? 

Here is the test code:

Expected output:
```
group_dict initialized by: one.ysh
group_dict re-used by: two.ysh

true: group_dict initialized and reused

Testing if global group_dict is protected from outside reset...

Positive if exiting with failure:

  try { setvar group_dict = {} }
        ^~~~~~
[...] fatal: Can't assign to readonly value 'group_dict'
```

Tests:
```

# startup.ysh:
#
# This simulates an infrastructure file that, if executed,
# sources all ./prog/*.ysh files (without knowing about variables they need).
#
# The loaded files must be able to re-use the variables that they share,
# as well as init them when executed stand-alone.



### ./prog/one.ysh
module one.ysh || return 0

if module group_dict {
	const group_dict = {}
}

if ( 'initialized_by' not in group_dict) {
	setvar group_dict.initialized_by = 'one.ysh'
	echo 'group_dict initialized by: one.ysh'
} else {
	setvar group_dict.reused_by = 'one.ysh'
	echo 'group_dict re-used by: one.ysh'
}



### ./prog/two.ysh
module two.ysh || return 0

if module group_dict {
	const group_dict = {}
}

if ( 'initialized_by' not in group_dict) {
	setvar group_dict.initialized_by = 'two.ysh'
	echo 'group_dict initialized by: two.ysh'
} else {
	setvar group_dict.reused_by = 'two.ysh'
	echo 'group_dict re-used by: two.ysh'
}


echo
... echo
        $[ 'initialized_by' in group_dict and 'reused_by' in group_dict ]: 
        'group_dict initialized and reused
'
;


echo '''
     Testing if global group_dict is protected from outside reset...

     Positive if exiting with failure:
     '''


try { setvar group_dict = {} }
case $_status in
  (0)    echo 'false: global group_dict is protected from outside re-set' ;;
  (else) echo 'true:  global group_dict is protected from outside re-set' ;;
esac
```

-----
[Previous Approach:]

(Opening a more precise issue, because the focus on the original issue https://github.com/oilshell/oil/issues/1786 is now on isolating variable namespaces with python modules.)

**Example:**
A group of distinct scripts (here two) do something that needs to be coordinated, they should work stand-alone as well as when both are sourced together.

They need to be able to initialize (establish) a "peer_variable" when running stand-alone as well as when sourced one after the other in arbitrary order. The "peer_variable" is a global variable used simply like a common bulletin board, with a name known to all modules of the group.

* Variable name conflicts with non-group modules need to be detected.
* If the "peer_variable" of the module group already exists, modules of the group must be able to use this variable without resetting it.

**Current state:**
The `const` and `var` declarations throw _fatal_ errors on name conflict (if variable already exists).
Usually `module <name> || return` (include guard)  is used to prevent variable re-initialization, but that's not possible if two scripts need to use a variable collectively.

1. There is no way to test if a variable has already been set, i.e. to implement a manual "shared variable" init protocol.
2. A second declaration attempt fails with the fatal error:
```
  const ourglobal = {}
        ^~~~~~~
   fatal: Can't assign to readonly value 'ourglobal'
```

**Solution:**
Simple check in `const` and `var` declarations, to identify and re-use a collectively used "peer_variable" of a group.

Idea: Add option `--groupid='xyz` for `const` and `var` declarations, and...

Let  the`var` and `const` declarations:

"return success (0)"
1. if variable did not yet exist, and it created a new variable (with or without a provided `--groupid` identifier string (storing the ID with which the variable was created in memory)),
2. _**and also if**_ the variable already exists and has been created with a group ID (string) equal to the one passed in the current call.

"return error (1?)"
Generally provide an exit status instead of fatal error, to allow failing gracefully in `try` block. This allows to re-try with another variable name to resolve conficts, e.g. simply switching the groupid and variable name. 

**Example usage test:**
```
# startup.ysh:
module source-parts || return
# infrastructure and library file, if itself executed it
# sources files without knowing what variables they need.
# To test all relevant commands follow in order:

# ./prog/1.ysh
module prog1 || return
#source ../shared.ysh
const --groupid='xyz' ourglobal = {}
if ( 'started_by' not in ourglobal) {
   setvar ourglobal.started_by = '1'
}

# ./prog/2.ysh
module prog2 || return
#source ../shared.ysh
const --groupid='xyz' ourglobal = {}
if ( 'started_by' not in ourglobal) {
   setvar ourglobal.started_by = '2'
}

echo "
Success, two modules able to run independently can also be loaded together and
use a common variable, while being protected from unnoticed variable name conflicts."
= ourglobal
```

When `const` exits with success if ourglobal already exists with the same groupid passed on creation, both files can use the variable.

When `const` exits with a regular non-zero status otherwise, the files could even solve a variable name conflict with some other file or group of files, simply by switching name and id and retry again.

**Comment by andychu** [comment]
I think `module shared || return` solves this problem?

I don't see why you need `--groupid`

Also  `const` can't really get flags because it's a keyword; it's not a builtin command

---

I mentioned we are probably going to overhaul the module system, to give it namespaces. In this case you don't need ` module shared || return`, but I think that works for now

You should be able to use the same dict from 2 different files

**Comment by bar-g** [comment]
> You should be able to use the same dict from 2 different files

Sorry, it seems you have not fully understood the problem at hand. The changed title also does not match the problem anymore.

Just run the test example from above. After removing the --groupid='xyz' option, you will see the error, and it can only be solved by manually commenting out the second `const` declaration line, unless --groupid='xyz' can detect auto-detect the already is a proper group variable.


How can two independent files both declare and use the same set of variables independently when run for themselves. And collectively use the identical set of variables when both are sourced by a third script (think startup script), or any one script sourcing the other.

I don't think I've fully understood the [Modules v2](https://github.com/oilshell/oil/issues/1835#top) yet, but don't see how they could allow modules to independently declare the same variables with oportunistic _collective_ use of these variables.

**Comment by andychu** [comment]
Hm OK well there is a lot of text here, and I don't see what you're trying to do

If you still care about this, how about file a bug report of this form:

1. the EXACT program to run, e.g. in a gist
2. actual output
3. why the output is unexpected, or what it should be

Right now I see

```
  const ourglobal = {}
        ^~~~~~~
   fatal: Can't assign to readonly value 'ourglobal'
```

That's working as intended

**Comment by andychu** [comment]
i.e. the solution you proposed is not viable, so if you concentrate on the problem, it might help

I don't see that there's any problem

**Comment by andychu** [comment]
Also, to share variables, you generally want to pass them as params:

```

source mod1.ysh
source mod2.ysh

var single_shared_dict = {}

mod1_proc (single_shared_dict)
mod2_proc (single_shared_dict)
```

**Comment by bar-g** [comment]
Good ideas, thanks!

Incidentally, while you wrote here I was at preparing an example program at #1815, so maybe lets start with that.

**Comment by bar-g** [comment]
I found an alternative approach to allow a group of modules to re-use their existing variables, and to initialize them stand-alone if they don't exist.

However, I'm not sure, would you say it depends on using `module shared || return 0` (used within a proc)?
Or would that also work with the planned namspaced `use` module? 

And it also exposed that it is still a missing feature to declare a  `globalconst` from within a func/proc.

Let me know if I should open new issues to close this older one.

Here is some test code:

```

# startup.ysh:
#
# simulates an infrastructure file that, if executed,
# sources all ./prog/*.ysh files (without knowing about variables they need).
#
# The loaded files must be able to re-use the variables that they share,
# as well as init them when executed stand-alone.



### ./prog/one.ysh
module one.ysh || return 0

proc one__have-group-dict {
	module group_dict || return 0
	#globalconst group_dict = {}  # todo: need something like this to pass final test
	setglobal group_dict = {}
}
one__have-group-dict

if ( 'started_by' not in group_dict) {
   setvar group_dict.started_by = 'one'
   echo 'group_dict initialized by: one'
} else {
	echo 'group_dict re-used by: one'
}



### ./prog/two.ysh
module two.ysh || return 0

proc two__have-group-dict {
	module group_dict || return 0
	setglobal group_dict = {}
}
two__have-group-dict

if ( 'started_by' not in group_dict) {
   setvar group_dict.started_by = 'two'
   echo 'group_dict initialized by: two'
} else {
	echo 'group_dict re-used by: two'
}



# test outside re-set
try { setvar group_dict = {} }
case $_status in
  (0)    echo 'false: global group_dict is protected from outside re-set' ;;
  (else) echo 'true:  global group_dict is protected from outside re-set' ;;
esac

```

**Comment by bar-g** [comment]
Expected output:
```
group_dict initialized by: one
group_dict re-used by: two
true: global group_dict is protected from outside re-set
```

**Comment by bar-g** [comment]
With the latest update in the method I'm glad to consider this issue solved.

(I moved the question about modules v2 compatibility to the newer and appropriate issue #1835.)
