### ISSUE TITLE
`cd` changes PWD to entered path

### ISSUE THREAD

**Issue by okayzed** [oilshell/oil#182]
```
osh$ pwd
/home/okay/tonka/apps/oil
osh$ cd ..
osh$ pwd
..
osh$
```

**Comment by andychu** [comment]
Hm, I looked into this, but couldn't find an easy fix.

There is some interaction with `cd -P` that I don't quite understand.  (Somebody contributed `cd -P` and `pwd -P`; I never really use it.  Though it is implemented by all shells, even dash.)

Somewhat surprisingly, I think we might need to write some custom code to iterate over path segments and match what bash does:

https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html#Bourne-Shell-Builtins

I looked at dash and it has some nontrivial code to update PWD that I don't quite understand either (in `src/cd.c`).

**Comment by andychu** [comment]
Since this is a really localized problem that doesn't require understanding the rest of the code, I'm labelling it a good first issue.

The task is basically to fix this:

```
test/spec.sh builtins --range 6 --verbose
```

```
test/spec.sh builtins --range 6 --verbose
```

while not breaking the rest of the tests:


```
test/spec.sh builtins 
```

**Comment by BatmanAoD** [comment]
This seems like it should be pretty easy, but I'm getting confused by how the Python path-manipulation functions behave around `..`. The current implementation (mine 😄) doesn't apply *any* path-normalization, so it should be as simple as applying `abspath` or `normpath`.

....but it looks like the current implementation *also* doesn't actually prepend the old working directory...? So I'm not sure if `cd` to a relative path *ever* resulted in a valid `PWD` value.

**Comment by andychu** [comment]
@BatmanAoD I think our general strategy is to avoid `os.path` in Python.  I discovered that while implementing `readlink -f`.  We use `libc.realpath` (our own wrapper) instead of `os.path.realpath()`.

The Python functions don't really have anything to do with what shells like bash do.  So the best bet seems to be to write C in Python, e.g. use `os.symlink()` since that exists in libc.  `strace` helps.

**Comment by okayzed** [comment]
the issue here is that we are using os.chdir() to move the CWD of osh around but we are not updating pwd to reflect that same dir. i think the line we want is `pwd = os.getcwd()`

**Comment by okayzed** [comment]
notice the line: `pwd = libc.realpath(dest_dir) if arg.P else dest_dir` comes after the line `os.chdir(dest_dir)`

I don't see how anything you do with pwd on that line (regarding the -P flag) is affecting the behavior of os.chdir call before.

**Comment by okayzed** [comment]
I take it back. I need to investigate / understand more.

**Comment by okayzed** [comment]
```python
  os.chdir(dest_dir)
  # ...
  pwd = os.getcwd()

  if arg.P:
    pwd = os.path.realpath(pwd)
  else:
    pwd = os.path.abspath(pwd)
     

```

this is what i think the behavior should be closer to. if -P is provided, we resolve the symlinks. if not, we use the abspath (and likely want to also collapse user home to ~)

**Comment by andychu** [comment]
I would just plug this in and run the tests to test the theory... if it passes all the tests, it's pretty likely to be correct.

(There are probably some ways you can get it wrong but it will be better than what we have now.)

**Comment by okayzed** [comment]
it passes the single test for "cd .." (or are there more?)

```
(py2) okay@chalk:~/tonka/apps/oil$ test/spec.sh builtins --range 6 --verbose
builtins.test.sh
case    line    dash    bash    mksh    osh
  6      38     pass    pass    pass    pass    pwd after cd ..
4 passed, 0 ok, 0 known unimplemented, 0 known bugs, 0 failed, 27 skipped

```

**Comment by okayzed** [comment]
@BatmanAoD  re: exception handling: good idea, that plan makes sense.

**Comment by BatmanAoD** [comment]
Huh, I thought I did something like what you've written above, but couldn't get the tests to pass for reasons I didn't understand (the behavior didn't seem to match the code). Possibly my test setup was wrong, or something like that.

@andychu I'm still not sure why we would want to avoid `os.path.abspath` as above; or would we?

**Comment by okayzed** [comment]
Welp. I ran all the tests. the good news is that the -L and symlink test fail. I will look into it more. I'm 50% expecting to give up (out of difficulty)

**Comment by andychu** [comment]
I'm pretty sure this is fixed now.  I rationalized the tests and they all pass.
