### ISSUE TITLE
single backslash \ at end of line could be disallowed within $'...'  (and maybe others)

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1825]
Is it ok to pass the backslash (consumed by command line parsing?) on to the string literal, and it becoming a literal \ even though parse_backslash is off?
```
ysh ysh-0.19.0$ echo $'a\
> b'
a\
b
ysh ysh-0.19.0$
```
And this is a non-identical variation that is printing the same:
```
ysh ysh-0.19.0$ echo $'a\\
> b'
a\
b
ysh ysh-0.19.0$
```

**Comment by bar-g** [comment]
`[ interactive ]:9: 'a\\b' not found` may this actually rather mean:
`[ interactive ]:9: $'a\\b' not found`, i.e. having searched for `r'a\b'`?
 (could make some sense as the prompt is saying `...$`)

For the first example, I guess I would have expected it to fail with "Invalid char escape" (or print `ab` as with double-quotes)

The problem seems to be there is never an "invalid char escape" error with any amount of backslashes before a newline (same in double-quoted strings).

**Comment by bar-g** [comment]
What you say does not explain why the single \ is parsed with parse_backslash off.

It's also against what happens within double-quotes. The newline gets consumed instead of producing "Invalid char escape":
```
ysh ysh-0.20.0$ echo "a\
> b"
ab
ysh ysh-0.20.0$
```

Consuming is consistent with shell:
```
$ string="
        one \
        two \
        three \
       "
$ echo "$string"

        one         two         three 
```

Plus python seems parsing single backslashes in singe- and double-quotes just fine, and there is still a multifold of ways to remaining to denote the same string using \b. 

This makes me ask how well backed up and necessary is the breaking behavior?

And maybe it does make sense, to rather improve uniqueness of denoting strings with a strict_ option forbidding singelton-backslash-pairs -- instead of singleton-backslashes -- to maintain compatibility with shell and python.

**Comment by andychu** [comment]
Oh I see!  Yeah actually that is a good point.

We want backslashes to always be doubled so there is one way of writing it

I'm not sure why it is the way it is

**Comment by andychu** [comment]
This is fixed - we now consistently disallow the single backslash then newline in YSH   (details in commit description)

Will be out with the next release

Great testing, thank you!

**Comment by andychu** [comment]
Released!  https://www.oilshell.org/blog/2024/03/release-0.21.0.html
