### ISSUE TITLE
spec/testdata/ysh-read-0.sh problem?

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1844]
I couldn't reproduce what is "not mixing well" with spec/testdata/ysh-read-0.sh.

After modifying it a bit I don't seem to grasp the error with the sequences. There just seems to be some problem of `read --line` not setting `$_line` for me, which I could isolate and moved to the end of the test results:

```
read -r
$REPLY=1
$REPLY=2

read --line (&line)
$line=1
$line=2

Mixed: read -r and read --line (&REPLY)
$REPLY=1
$REPLY=2
$REPLY=3
$REPLY=4

Isolated: echo "hi" | read --line
   echo \$_line=$_line
                ^~~~~~
40: fatal: Undefined variable '_line'
ysh-0.20.0$
```

Here is my modified code:
```
echo
echo 'read -r'
seq 2 | {
  read -r
  echo \$REPLY=$REPLY

  read -r
  echo \$REPLY=$REPLY
}

echo
echo 'read --line (&line)'
seq 2 | {
  read --line (&line)
  echo \$line=$line

  read --line (&line)
  echo \$line=$line
}

echo
echo 'Mixed: read -r and read --line (&REPLY)'
seq 4 | {
  read -r
  echo \$REPLY=$REPLY

  read -r
  echo \$REPLY=$REPLY

  read --line (&REPLY)
  echo \$REPLY=$REPLY

  read -r
  echo \$REPLY=$REPLY
}

echo
echo 'Isolated: echo "hi" | read --line'
echo "hi" |  read --line
echo \$_line=$_line
```

I was kind of afraid of seeing something like a single `read --line` command slurping up the whole input, similar to
https://mywiki.wooledge.org/BashFAQ/001#How_to_keep_other_commands_from_.22eating.22_the_input

**Comment by bar-g** [comment]
I was trying to understand why you removed `read --line` based on you mentioning this test in https://github.com/oilshell/oil/commit/ac6675964a2865ecf7fc1e7a6283b53f62a0bab7

**Comment by andychu** [comment]
The problem is buffering -- the  problem is that buffered `read --line`  and unbuffered `read -r` don't mix

This is discussed on Zulip

See `man fgetc`


>       It is not advisable to mix calls to input functions from the stdio library with low-level calls to read(2) for the file descriptor associated with the input stream; the results will be undefined and very probably  not  what  you  want.

**Comment by andychu** [comment]
The problem is definitely in the test case, I don't know why you're modifying it.  Changing the test case doesn't mean that the original bug is fixed :)  It's a bug exactly as is

**Comment by bar-g** [comment]
What do you actually see as output from the original test case? (It's TODO in the repo.)

Because I just got the same `Undefined variable '_line'` as from the last command I retained in my shown experiment.

**Comment by bar-g** [comment]
I mean sure I can imagine arbitrary read/write pointer movements disturb buffered state, if they don't proceed compatibly with buffered ones.

Wondering why I don't seem able to see such with the alternate line wise processing of the input in the repo-example, though. (So, still wondering how the error looks for you.)

**Comment by andychu** [comment]
The bug is exactly what you saw

```
$ ysh spec/testdata/ysh-read-0.sh 
read -r
reply=1
reply=2

read --line
    echo line=$_line
              ^~~~~~
spec/testdata/ysh-read-0.sh:15: fatal: Undefined variable '_line'
  seq 2 | {
          ^

```


```
$ osh --version
Oils 0.20.0             https://www.oilshell.org/

Release Date: 2024-02-04 04:37:24+00:00
Arch: x86_64
OS: Linux
Platform: #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08)
Compiler: GCC 12.2.0
Interpreter: OVM
Interpreter version: 2.7.13
Bytecode: bytecode-opy.zip
andy@hoover ~/git/oilshell/oil (dev-hoover-13)$ osh spec/testdata/ysh-read-0.sh 
read -r
reply=1
reply=2

read --line
line=
line=

Mixed
reply=1
reply=2
line=
reply=4
```

**Comment by bar-g** [comment]
Hm, I've put the orig. failing example back in, i.e. below all the working examples. (Updated the code-boxes in the description.)

Please note, that all the mixed tests work well.

It's just the two simple _reply using tests at the bottom that cause "undefined variable" failures.

(As if it's just a remnant issue from the value.Place refactoring, maybe breaking creating and updating $_reply properly.)

**Comment by bar-g** [comment]
`read --line` creates `$_reply` the failing tests use `$_line`

**Comment by andychu** [comment]
OK yes sorry, I didn't get that `_line` was used instead of `_reply`

I fixed the test case and demonstrated the bug

https://github.com/oilshell/oil/commit/091969983fc3e293fd27928c1ef36b51ce8e9ba2


I'm not sure why it doesn't happen in Python, but it happens in C++.

I looked at the CPython code, and it's doing buffered I/O with fgetc() 

In C++ we do it with `getline()` in `gc_mylib.cc`. 

In any case, there is still a design bug in `read --line`, hence removing it

We will probably add a separate `for` loop later to read lines in a buffered way - https://oilshell.zulipchat.com/#narrow/stream/384942-language-design/topic/read.20builtin.20and.20buffering


But for now the idiom is from bash -- `read -r line`

**Comment by bar-g** [comment]
All right, glad things could get cleared up. Thanks and kudos.

So it is actually the mentioned "eating" of the input behavior showing in C++ (like as in bash).

Hm, maybe python .readline() leaves or sets file pointers back to last consumed line break.
