### ISSUE TITLE
`try eval` is inconsistent

### ISSUE THREAD

**Issue by Melkor333** [oilshell/oil#1846]
with the following proc:
```ysh
ysh ysh-0.20.0$ proc try_eval (;;;block) { try eval (block); echo "done!" }
```
The following two calls both print `done!` - the `try` catches the error:
```ysh
ysh ysh-0.20.0$ try_eval { ecco something }
  try_eval { ecco something }
             ^~~~
[ interactive ]:29: 'ecco' not found
done!
ysh ysh-0.20.0$ try_eval { echo ('abc') }
  try_eval { echo ('abc') }
                  ^
[ interactive ]:32: 'echo' got unexpected typed args
done!
```

But the following two abort early:
```ysh
ysh ysh-0.20.0$ try_eval { echo $2 }
  try_eval { echo $2 }
                  ^~
[ interactive ]:30: fatal: Undefined variable '2'
ysh ysh-0.20.0$
ysh ysh-0.20.0$ try_eval { if {ab} }
  try_eval { if {ab} }
                     ^
[ interactive ]:33: Expected word type Id.KW_Then, got Id.Lit_RBrace
ysh ysh-0.20.0$
```

**Comment by Melkor333** [comment]
I just realized it's only relevant for the variable lookups which are weird:

```
ysh ysh-0.20.0$ proc try_eval (;;;block) { var x = 5; try eval (block); echo "done!" }
ysh ysh-0.20.0$ try_eval { write $x }
5
done!
ysh ysh-0.20.0$ try_eval { write $y }
  try_eval { write $y }
                   ^~
[ interactive ]:36: fatal: Undefined variable 'y'
ysh ysh-0.20.0$
```

The `{ if {ab} }` example is actually irrrelevant, as this is an error during initial parsing which fails BEFORE the function call:
```
ysh ysh-0.20.0$ proc try_eval (;;;block) { var x = 5; echo "done!" }
ysh ysh-0.20.0$ try_eval { write $y }
done!
ysh ysh-0.20.0$ try_eval { if {ss} }
  try_eval { if {ss} }
                     ^
[ interactive ]:39: Expected word type Id.KW_Then, got Id.Lit_RBrace
```

**Comment by bar-g** [comment]
Isn't it ok that vars are looked up within the proc and fail fatal?

---
The `if` parsing issue could be: https://github.com/oilshell/oil/issues/1706
With a possible pathway to a solution?: https://github.com/oilshell/oil/issues/1837

**Comment by bar-g** [comment]
It could help if the error message could explicitly mention the scope. For example:
```
fatal: Undefined variable '2' within proc 'try_eval'
```

**Comment by bar-g** [comment]
Hm, your var x = 5 seems to show unsuccessful parsing is handed down to called procs.
Not sure, is that actually inconsistent or a feature?

```
ysh ysh-0.20.0$ a=foo

ysh ysh-0.20.0$ try_eval { echo $a }

foo
done!
ysh ysh-0.20.0$ 
```

Local vars shaddow global and passed ones?
Are there actually more spec tests about this type of proc/func nesting behavior?
Had attempted some: https://github.com/oilshell/oil/issues/1842

**Comment by bar-g** [comment]
The `if` examples seem to work after correcting the if-syntax:

```
ysh ysh-0.20.0$ try_eval { if {ab} { echo hi }  }

  try_eval { if {ab} { echo hi }  }
                ^
[ interactive ]:89: '{ab}' not found
done!
ysh ysh-0.20.0$ try_eval { if {ab} ; then echo hi; fi }

  try_eval { if {ab} ; then echo hi; fi }
                ^
[ interactive ]:90: '{ab}' not found
done!
ysh ysh-0.20.0$ 
```
But it does not say what it is parsing  {ab} as. Outer dict literal in try_eval call?

Or if-clause within?

```
ysh ysh-0.20.0$ try_eval { if ({ab}) ; then echo hi; fi }

  try_eval { if ({ab}) ; then echo hi; fi }
                       ^
[ interactive ]:92: Expected word type Id.KW_Then, got Id.Op_Semi
ysh ysh-0.20.0$ try_eval { if ({ab}) then echo hi; fi }

  try_eval { if ({ab}) then echo hi; fi }
             ^~
[ interactive ]:93: fatal: Undefined variable 'ab'
```

I think the error messages could show more context.

**Comment by bar-g** [comment]
```
ysh ysh-0.20.0$ try_eval { if ({ab}) { echo hi } }

  try_eval { if ({ab}) { echo hi } }
             ^~
[ interactive ]:94: fatal: Undefined variable 'ab'
ysh ysh-0.20.0$ 
```

**Comment by andychu** [comment]
OK yes I noticed this same bug, this is #1785 

It's on the list for Oils 0.21.0 - #1828 

I will fix it, thanks for the report!

**Comment by bar-g** [comment]
Hm, didn't find any different behavior with these, though:
```
proc try_eval (;;;block) { try {  eval (block)  } ;       echo "done!"   }
proc try_eval (;;;block) {     try {  eval (block) ; echo "done!" }      }
```

So, nothing wrong? Just too easy to get confused as long as error messages don't mention some more of their parsing / evaluation context?

**Comment by andychu** [comment]
Released!  https://www.oilshell.org/blog/2024/03/release-0.21.0.html
