### ISSUE TITLE
Typed args and block arg can get confused

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1849]
I think the problem is that I wanted to have this syntax for block args:

```
var b = ^(echo hi)
cd (b)
```

Instead of the more consistent

```
cd (; ; b)
```

So what I did was make the block arg **"kinda like"** the first typed arg

However this causes confusion

**Comment by andychu** [comment]
Let's define

```
$ proc p (...words; ...typed; ...named; block) { pp line (words); pp line (typed); pp line (named); pp line (block) }
```

Then these two cases work fine, everything is passed as expected:

```
ysh ysh-0.20.0$ p a b c { echo hi }
(List)   ["a","b","c"]
(List)   []
(Dict)   {}
(Block)   <Block 0x7ff4973d0d20>
```

and


```
ysh ysh-0.20.0$ p a b c (x=42) { echo hi }
(List)   ["a","b","c"]
(List)   []
(Dict)   {"x":42}
(Block)   <Block 0x7ff4974394b0>

```

**Comment by bar-g** [comment]
I think with the "shell-command-style" from #1837 the syntax you want `var b = ^(echo hi); cd (b)` would be it:

    cd (b)
* Parens without any comma => it's "shell-command-style".
* As (b) is the only typed arg, so it's always the first (no matter the type).
* Ab b is of type block its the first (and last) block.
* `cd` may take the block from left or right (first/last), but that would only matter for conflict resulution with parsing on nesting levels here.

---
Also for the error case from above:

      ysh ysh-0.20.0$ p a b c ('pos') { echo hi }
      (List)   ["a","b","c"]
      (List)   [<Block 0x7ff4973d0d20>]
      (Dict)   {}
      (Str)   "pos"

* no comma in parens => shell-command-style as well

Without any other params defined for proc p, the splats are equal to the per-type "positionals" (arg lists), and the "positionals" (arg lists) should resolve to:

* `pp line (WORDV)`  (List)   ["a","b","c"]
* `pp line (TYPEDV)` (Str)   "pos"
* `pp line (NAMEDV)`  {}
* `pp line (BLOCKV)`  [<Block 0x7ff4973d0d20>]

**Comment by glyh** [comment]
This doesn't seem to work for me at all:
```sh
$ ls -la
total 0
drwxr-xr-x  3 lyh  lyh    60 Apr  5 00:04 .
drwxrwxrwt 24 root root 1600 Apr  5 00:04 ..
drwxr-xr-x  2 lyh  lyh    40 Apr  5 00:04 def
$ var b = ^(echo def); cd (b)
def
$ pwd
/tmp/abc
```

**Comment by bar-g** [comment]
@glyh in your example I don't see the problem, I think that example is working as intended

 (cd only changes dir during block execution, and the example does not change it, nor print it)

Here is an example that changes and prints the dir:
```
ysh ysh-0.21.0$ cd /tmp
ysh ysh-0.21.0$ pwd
/tmp
ysh ysh-0.21.0$ var b = ^(pwd)
ysh ysh-0.21.0$ cd / (b)
/
ysh ysh-0.21.0$ pwd
/tmp
ysh ysh-0.21.0$ cd / { pwd }
/
ysh ysh-0.21.0$ pwd
/tmp
ysh ysh-0.21.0$ 

```

`cd { pwd }` should return the same as `echo $HOME`

**Comment by glyh** [comment]
Yeah this make sense.

**Comment by andychu** [comment]
> cd { pwd } should return the same as echo $HOME

 I think we should actually disallow this, it's confusing

The block can only be passed if you also pass a directory name

I'll file another bug

But Let me know if you disagree

**Comment by andychu** [comment]
could use help on this

- #1924

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/06/release-0.22.0.html
