### ISSUE TITLE
ctx api and doc

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1863]
There is good room to make clearer what `ctx` is and does, so that it's quicker to grasp (also for shell users).

some suggestions:

---

api suggestion:

* use wording that tells what `ctx` does in the block *for the user* (not on the implentation side)
   (Note: for the user it's rather flat namespace, there is no nesting like with dynamic scope, the user can only modify a single dict, which is replaced. The internal push-stack is only the equivalent of the nested blocks replacing the outer block, and ensures that behavior.)
* make the differences in the commads apparent (set vs. emit is kind of arbitrary and vague)

```
ctx modify (var) {          # possibly 'update'
  ctx key (mykey='value')    # "key a value" into the modified dict (set could be anything)
  ctx list mylist (a)        # "list a value" in the modfied var
                             #   possible alternative: append (implies list), but its different from ysh-append
}
```
---

docs suggestion:
> ctx
> Execute a block with a shared "context" that can be updated using the ctx built-in. 

Execute a block with a shared "context" dictionary that can be modified using the `ctx` built-in. 
* No need to pass the `modify`-dictionary to each proc within the block.
* Add a value to the `modify`-dictionary using a:
  * `ctx key (key_name=value)`
  * `ctx list list_name (value)` (appends value to list)

Modifying a ctx dict is a contained alternative to shell's side-effect prone dynamic scope.

A nested `ctx` block can only modify its own context dictionary.

**Comment by bar-g** [comment]
@PossiblyAShrub, guess you could be interested, too.

**Comment by bar-g** [comment]
Hm, this is actually very related to
* #1763

`ctx` kind of selectively "entails" variables, as envisioned there.

But `ctx` puts them in a separate namespace, and introduces new var access syntax.

Do you see possibilities to integrate here?

**Comment by bar-g** [comment]
This would be more consistent:

      ctx key  mykey  (value)
      ctx list mylist (a)

Hm, but modifying the args would actually also allow:

      ctx set mykey to (value)
      ctx list (a) in mylist

**Comment by bar-g** [comment]
oh, 'in' is a keyword, so:

      ctx set mykey to (value)
      ctx append (a) to mylist

**Comment by andychu** [comment]
There is a relation to dynamic scope, though it's not exact

https://www.oilshell.org/release/0.21.0/doc/ref/toc-ysh.html#builtin-cmd

I'm pretty happy with the names

"emit" is maybe not super obvious, but it's intended to have a "streaming" connotation, like write/emit are common in streaming systems

Rather than writing a string, you're emitting typed data in a specific "channel"

----

Probably the main thing is to be integrated with Hay

- #1834

**Comment by andychu** [comment]
Also I forgot to say on some of the other threads, I think one issue is that you're not on Zulip

The design discussion took place in February - https://oilshell.zulipchat.com/#narrow/stream/384942-language-design/topic/Idea.3A.20ctx.20builtin.20for.20building.20up.20data.20-.20flag.20parsing.20.2F.20Hay

It's not to say that things are locked down after release.  We are still definitely changing things

But the naming discussions largely happen on Zulip, and it's not always productive to go through it again

But some of the feedback you have had is very good, and have led and will lead to concrete changes, e.g. with procs, etc.

There are like a zillion threads about `#language-design`, including at least 10-20 design issues that are still in progress (modules, Hay, etc.)

---

I think it's actually good to wait  until release to get certain feedback, after we write user facing docs, like the proc-func doc, and YSH regex API doc, etc.  Some things are not baked yet

I do think ctx  is pretty baked, though certainly it can be tested more, and I appreciate all the testing

A good piece of feedback would be to write some **new code** with `ctx`, and then show if there is a deficiency that can be improved.

**Comment by andychu** [comment]
Ideally there would be more docs about `ctx`, but we have to prioritize it with everything else

The docs about **flag parsing** are actually more important, because that's what people will commonly use

`ctx` is a little lower level.  It is user facing but it's more for "advanced" users who want to write an ergonomic API

**Comment by bar-g** [comment]
`push` was the most disturbing, sure it matches the implementation, but not as good relaing to the block,
where `ctx modify (x) {... ctx set (key='val')...}` could kind of say it all.

**Comment by bar-g** [comment]
Currently ctx "contexts" seem like the only savior from global vars and all the dict passing trouble with its issues and failing tests I posted.

So I think ctx is very much user appreciated, once well enough explained, and self-explanatory.

**Comment by andychu** [comment]
Hm I think of it as more level, not for "normal" scripts.  It's mainly to make the little `parser (&p) { .. } ` block look nice

I actually think it can be an "anti-pattern" if used throughout an entire program.  How do you keep track of what's in the context?

But yeah I appreciate any **real** code samples that show code done 2 ways.

I believe you can do everything with normal procs.

That is another piece of feedback on feedback -- synthetic examples are useful for **bugs**, but if you want to make an argument about design, then **real** code is more useful to make a design judgement

**Comment by bar-g** [comment]
> it's better just to pass lists and dicts around as parameters

Hm, if it would just work. I remember I found problems and provided test example code, unfortunately you renamed it into a doc issue referring to I think to only one of different problems.

* #1842

> but if you want to make an argument about design, then real code

Readability is built from smaller parts. I don't think it can get any better by any larger examples used for real.

I think the `ctx` context thing here is obvious, `modify` and `list` are plain english words that can be used here with their real meaning and describe better what ctx does from the user perspective.

(It's not always easy for devs (well entrenched in the implenentation) to switch into the "simple" user's perspective, I know.)

With "flags" it's simmilar I think. Exaggerating to make it obvious: Why talk about defining colorful wavy things, when simply dealing with parsing CLI **options** within args of a command. Just using the proper english name tends to avoid creating many unnecessary (mis)understanding problems. (Flag can be seen as a specific type of option, but if you really want to lump them together they are not all flags, but they really are all options.)

**Comment by bar-g** [comment]
I do see that the `list` case could still be improvable, though, maybe `listadd`?

Or simply `add`, because it's later simple to iterate over multiple 'added' key "entries" by using mydict.key[i]

```
ysh ysh-0.21.0$ var a = {}
ysh ysh-0.21.0$ ctx push (a) { ctx emit key ('one'); ctx emit key ('two') }
ysh ysh-0.21.0$ = a.key[0]
(Str)   "one"

```


To still have a practical example to compare :

`ctx emit args ({name, help})`
`ctx add args ({name, help})` 

---

Hm, with `ctx modify (mydict)`, the `ctx set` versus `ctx add` contrast could even become good (self-explaining) enough? (Rather than creating more questions?)

**Comment by andychu** [comment]
e.g. I'm still confused about what you're saying with #arg

> > it's better just to pass lists and dicts around as parameters
> 
> Hm, if it would just work. I remember I found problems and provided test example code, unfortunately you renamed it into a doc issue referring to I think to only one of different problems.
> 
>     * [[YSH] Document idiom for mutable default params (setvar param = param or default doesn't work with empty containers) #1842](https://github.com/oilshell/oil/issues/1842)


OK I still don't understand what the problem is there... there's too much code, and it's not in context.

What did you expect to happen, and what happened?  For a specific case

There was one case where `setvar param = param or {}` doesn't work.   You have to make it `if (param !== null)` .  But I don't see what the other case is.

A real example would help there too, to see what you are actually intending.  But synthetic is OK too if it's a bug

**Comment by bar-g** [comment]
`ctx add to args ({name, help})`

**Comment by bar-g** [comment]
> what you're saying with #arg

Concerning this issue I probably referred to the readabilitly of:
https://github.com/oilshell/oil/blob/master/stdlib/args.ysh

**Comment by andychu** [comment]
Sorry there was a typo there.  I wasn't referring to args.ysh

You're saying there  is some issue passing around typed parameters, but I don't know what it is.

The only issue I know of is

- #1849 

And you also pointed out the "pass through" issue, e.g. whether you do

```
myproc @all_args
```

or

```
myproc @stringargs (...typed; ...named)
```

**Comment by bar-g** [comment]
closing in favor of
* #1865
