### ISSUE TITLE
Bug: expansions won't work with globs

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1871]
The following will create `/tmp/~/a/`, `/tmp/~/b/` and `/tmp/~/c/`
```sh
cd /tmp
mkdir ~/{a,b,c}
```

**Comment by andychu** [comment]
What version did you try with?  I think this was just fixed with Oils 0.21.0

- #1854 

https://github.com/oilshell/oil/commit/7438c3a6af3690936a1bdf0404c2391c34a48e62
