### ISSUE TITLE
Osh Does Not Print Newline on ^D

### ISSUE THREAD

**Issue by ric-sc-gr** [oilshell/oil#189]
For example:
```
granttrec@home:~/projects/oil$ ./bin/osh
osh$ echo hello
hello
osh$ granttrec@home:~/projects/oil$ 
```
It would be nice to display a sign for exiting like `^D` or `exit` to give the user some idea.

**Comment by andychu** [comment]
OK, it looks like bash prints `exit`, mksh prints `^D`, and dash and zsh don't print anything.  This would be a fine change although some care has to be taken for the interactive vs. non-interactive case.

**Comment by andychu** [comment]
@ric-sc-gr Hm sorry this sat in the queue for awhile.  Please clone master and try it out, and let me know if it works for you.  The fix ended up being pretty simple.
