### ISSUE TITLE
[ FR ] allow unicode literal / ascii literal in double quoted strings. 

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1911]
Basically

```
= "\u1234"
```

**Comment by andychu** [comment]
In YSH, double quoted strings are compatible with OSH

So we add J8 strings:

https://www.oilshell.org/release/0.20.0/doc/j8-notation.html#quick-picture

```
= u'\u{1234}'
```

`\u1234` has a utf-16 legacy we don't want

This kind of question is better for Zulip
