### ISSUE TITLE
Test contributing setup (wedges) on Arch Linux

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1923]
@glyh uses Arch Linux apparently

https://github.com/oilshell/oil/pull/1922

I recommend doing this rather than Nix

It is a lot simpler -- it compiles a bunch of packages from scratch, like python2, re2c, etc.

**Comment by andychu** [comment]
We can put it in the sourcehut CI like Debian and Alpine

http://travis-ci.oilshell.org/srht-jobs/git-88e09dce0870b4019eb470372746e75ff5b594a0/

**Comment by glyh** [comment]
Some information:

- Python 2 is dropped on Arch because it's EOL, [reference](https://wiki.archlinux.org/title/python#:~:text=python2AUR%20(-,unmaintained,-)). 

- AUR packages are unmaintained:
  - [Last update](https://aur.archlinux.org/packages/python2-bin) to python2-bin is in 2022.
    - Won't work if you install it: 
	```
	Could not find platform independent libraries <prefix>
	Could not find platform dependent libraries <exec_prefix>
	Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
	ImportError: No module named site
	```

    - [Last update](https://aur.archlinux.org/packages/python2) to python2 is in this year but it requires compiling the whole package.

**Comment by glyh** [comment]
I have tried this in the first place and it doesn't work. Let me try it again.

**Comment by glyh** [comment]
Also python 2 package retriving from python's official source is apparantly extremely slow in China, about 5KB/s. I modified it to another source and managed to run this script and get errors. I'll try to see if waiting for 30min from python's official source will actually solve the issue.

![image](https://github.com/oilshell/oil/assets/12870742/cc7aa6e8-5064-4462-aab7-27be2165212f)

eta 28min, crazy/

**Comment by andychu** [comment]
To be clear this is the part you should run

https://github.com/oilshell/oil/wiki/Contributing#full-python-build-buildpysh-all


```
build/deps.sh fetch  # re2c, CommonMark, etc.
build/deps.sh install-wedges
```

That's it

It works on Debian and Alpine.  I would like to know if it works on Arch

Only problem is it requires root for `/wedge`, but you can `sudo rm -r -f /wedge ~/wedge` and it will remove everything that we installed

It's only 2 dirs

**Comment by glyh** [comment]
That's exactly what I run.

**Comment by andychu** [comment]
OK that is a bit surprising python.org is that slow in China

We sometimes mirror tarballs -- we could move it here if it's an issue

https://www.oilshell.org/blob/testdata/


Also I heard about this `git scalar` command -- you can put  big files in git now, so we could have a git repo with all the source tarballs for bootstrapping the dev environment

https://lobste.rs/s/mdvuyq/really_large_repositories

**Comment by glyh** [comment]
I have 500K/s from oilshell.org. I guess we can opt-in to pull from oilshell.org.

**Comment by andychu** [comment]
OK I filed

- #1925

I want to put more stuff in git -- even CI results and release tarballs can be in git

---

I kinda want to move to this `#distributed-shell` model where everything is in git, or a file hashed from git

So that syncing and compute are separate

Networks are always a source of flakiness in distributed computing, and this is an example we hit ourselves!  :-/

`build/py.sh fetch` is separate though, I did kinda separate the part that does network from the part that does computation

But it's not obvious what the end result is

---

that issue also relates to fallout from the xz backdoor -- we have to test that tarballs build on sourcehut and Github actions are EXACTLY the same

**Comment by glyh** [comment]
I guess hashing would help.

**Comment by glyh** [comment]
Okay it works. How do I add the dirs to PATH automatically then? For now it's 

```
PATH=$PATH:/wedge/oils-for-unix.org/pkg/python2/2.7.18/bin bin/ysh
```

**Comment by andychu** [comment]
Oh good point

I think you can do `. build/dev-shell.sh` -- maybe we need `direnv` to activate this inside `oilshell/oil` ?


I should take that out of my $PATH and use `build/dev-shell.sh` probably

**Comment by andychu** [comment]
I guess for now doing `. build/dev-shell.sh` manually is OK

then you can use all the tools like `re2c` as well, if you want to poke at them

**Comment by glyh** [comment]
This only works for bash. I think we'd better have some kind of direnv support as it's compatible across shells.
