### ISSUE TITLE
Allow setting mirrors for python tarball in deps pulling

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1927]
I'll test if tarball form python.org and the mirror I use in China are actually the same. If they are the same, it makes sense to let user using some env var to set mirror address.

Related: https://github.com/oilshell/oil/issues/1925

**Comment by andychu** [comment]
This one isn't user facing, so I think it's OK to close it

Plus we didn't document it :-)  So I guess it's an `#oil-dev` thing, not mentioned on release notes
