### ISSUE TITLE
[ FR ] allow redirecting on arbitrary blocks

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1933]
Some nice sugars:
```
try {
  ls $fd_info
  ls $something_else
} 2>&1 > /dev/null
```

**Comment by andychu** [comment]
We don't want more sugar right now -- the language and parser are already complex.  We are aiming for a very simple language anyone can learn.

That said, `try` is a builtin, so you can use prefix style

```
try >out { echo hi }
```

simple commands in shell always support redirects, but it comes before the block.   We could document this better probably
