### ISSUE TITLE
[ FR ] Allow setting referenced type as default value.

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1934]
```
const D = {} 
func a (d={}) { echo 1 }
```
The above code should be allowed, but I got
```
fatal: Default values can't be mutable, got Dict
```

**Comment by glyh** [comment]
I have to write this:
```
  {
    call chan.methods.out_pipe()
  } <&$[chan.pipe]
```

**Comment by bar-g** [comment]
You don't seem to show an error, or say where you want to use the dict as default param.

Is it maybe related to the messy type interaction (also) brought up in these?:
* https://github.com/oilshell/oil/issues/1791
* https://github.com/oilshell/oil/issues/1815
* https://github.com/oilshell/oil/issues/1842
* https://github.com/oilshell/oil/issues/1866

All leading up to:
https://oilshell.zulipchat.com/#narrow/stream/384942-language-design/topic/integrating.20value.2EPlace.20hack

**Comment by glyh** [comment]
Yeah I should have clarify a bit, but as I write the std code I run into multiple frictions so I kinda just keep them down here. Probably better be a zulip thread? I'll make it more detailed.

**Comment by bar-g** [comment]
If it's an issue I don't think piling on to that zulip pile of stuff would help. Discussion stuff isn't a public issue tracker.

**Comment by glyh** [comment]
Looks like this is just #1791
