### ISSUE TITLE
[ BUG ] unexpected token in expression mode

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1935]
```
  call chan.methods.in_pipe() > &$[chan.pipe]
```

stdlib/draft-sync.ysh:81: Unexpected token in expression mode (Id.Left_DollarBracket)

**Comment by glyh** [comment]
{
    call chan.methods.out_pipe()
  } <&$[chan.pipe]

**Comment by andychu** [comment]
This is intended right now -- expressions don't have redirects, only commands

`call` takes an expression on the right

---

BTW in YSH you can do

```
fopen <& $[chan.pipe]  {
  call chan.methods.out_pipe()
}
```

I like the prefix style better than suffix

**Comment by andychu** [comment]
This one is not really a bug, so could have gone on Zulip

Or it's OK to use github, but I wouldn't assume it's a bug
