### ISSUE TITLE
question about dynamic scoping - shvar, shvarGet

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1936]
Basically something like
```bash

proc do-my-job() {
  echo "doing job as $WORKER"
}
proc my-worker(data) {
  echo I am $WOKER
  echo I got $data
  do-my-job
}

echo $data | WORKER=1 my-worker
```

**Comment by glyh** [comment]
Oh I realize this is just dynamic scoping.

**Comment by andychu** [comment]
This is what `shvar` is meant for, though it might need typed args

You can do `shvar PATH=: { mycommand }`

And then in `mycommand` you can do `shvarGet('PATH')` to look up the stack

**Comment by glyh** [comment]
Looks like this isn't a bug then. Thanks
