### ISSUE TITLE
OpenBSD `ln` and `install` do not have `-v` flag

### ISSUE THREAD

**Issue by dontlaugh** [oilshell/oil#1943]
### System Details

- OpenBSD 7.5 GENERIC.MP#138 arm64
- oils-for-unix release tarball 0.21.0

### The Problem

Neither `ln` nor the `install` utility have a `-v` flag on OpenBSD.

This had consequences for the `./install` script, for example here:

https://github.com/oilshell/oil/blob/master/install#L93

And also in the generated build script **_build/oils.sh**, down at the bottom. Ninja generates it in `ShellFunctions`

https://github.com/oilshell/oil/blob/master/build/ninja_main.py#L229

**Comment by andychu** [comment]
Thanks for the report!  This shouldn't be too hard to fix

**Comment by andychu** [comment]
This is now fixed, you can test a tarball from the CI

http://travis-ci.oilshell.org/github-jobs/6794/cpp-tarball.wwz/_release/oils-for-unix.tar

Thanks for testing!

**Comment by dontlaugh** [comment]
Success!

```
% doas ./install 
  + install -d /usr/local/bin
  + install _bin/cxx-opt-sh/oils-for-unix.stripped /usr/local/bin/oils-for-unix
    Installed /usr/local/bin/oils-for-unix
    Created 'osh' symlink
    Created 'ysh' symlink
  + install -d /usr/local/share/man/man1
  + install -m 644 doc/osh.1 /usr/local/share/man/man1
    Installed man page
```

**Comment by andychu** [comment]
I have a script that collects these for release notes, so it's OK to leave it open for now

thanks for testing!

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/06/release-0.22.0.html
