### ISSUE TITLE
Write something like re2c to produce a smaller state machine from the lexer

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#197]
There are 14 lexer modes in the OSH lexer [1], and some of them share significant logic, e.g. `_VARS`, `_LEFT_SUBS` and `_C_STRING_COMMON`.

re2c is necessarily **ignorant** of this sharing.  We expand the common lexing rules before it sees them.

This is an open question: can we produce a smaller state machine?  Right now our lexer is 16K lines of generated C code!  Although this is not as bad as it sounds, because every state transition takes 256 lines or so because of `case 'a', case 'b', ...`.

Regular expressions with derivatives could provide a way to do this?  But re2c also uses advanced algorithms?

https://research.swtch.com/yaccalive

> A much more recent paper by Owens, Reppy, and Turon, titled “Regular-expression derivatives reexamined,” returned to the original Brzozowski paper and considered the effect of using Brzozowski's simplification rules in a regular expression engine that cached states (what textbooks call a DFA). There, the simplification has the important benefit that it reduces the number of distinct states, so that a lexer generator like lex or a regular expression matcher like grep can reduce the necessary memory footprint for a given pattern. Because the implementation manipulates regular expressions symbolically instead of the usual sets of graph nodes, it has a very natural expression in most functional programming languages. So it's more efficient and easier to implement: win-win.

[1] https://github.com/oilshell/oil/blob/master/osh/lex.py

[2] http://www.oilshell.org/release/0.6.pre5/metrics.wwz/line-counts/nativedeps.txt

**Comment by andychu** [comment]
NOTE: This is more of a "fun" nice-to-have optimization (and learning exercise), whereas issue #192 is more practical.  We need it to support extended globs on non-GNU systems.

**Comment by andychu** [comment]
FWIW it looks like it should be pretty easy to express with `br_table`, which has "local" jump targets?   The whole DFA just lives in a single block I suppose?

https://webassembly.github.io/spec/core/syntax/instructions.html#control-instructions

**Comment by andychu** [comment]
Someone pointed me at libfsm, and it does look interesting.  Although my impression is that it largely does the same thing as re2c (at least as far as Oil is concerned).

There are several lexers both big and small in frontend/lex.py if you want something to play with.

The lexer is the biggest function in the Oil binary at 26K (`MatchOshToken`), although it doesn't appear to be an issue right now.  There are probably 5 or 10 other perf problems to tackle first!

http://www.oilshell.org/release/0.6.pre13/metrics.wwz/native-code/overview.txt

**Comment by pstef** [comment]
I thought re2c is more or less equivalent to kate's [re(1)](https://github.com/katef/libfsm/blob/master/doc/tutorial/re.md#generating-code). I was thinking specifically about libfsm, kate's library to manipulate NFAs and DFAs.

**Comment by andychu** [comment]
Out of scope now
