### ISSUE TITLE
command -v "$emptyvar" returns zero

### ISSUE THREAD

**Issue by oguz-ismail** [oilshell/oil#1974]
```
osh-0.21.0$ x=
osh-0.21.0$ command -v "$x"

osh-0.21.0$ echo $?
0
osh-0.21.0$
```
No other shell does this.

**Comment by andychu** [comment]
Thanks for testing!   I reproduced it and it was indeed a bug, though it was fixed several weeks ago as part of this commit:

https://github.com/oilshell/oil/commit/1bd884195ec732f1f9effb03e2407296da86943d

This will be out with the next release!

**Comment by andychu** [comment]
If you like, the CI creates a tarball on every commit, which is easy to download and install


http://travis-ci.oilshell.org/github-jobs/6976/

cpp-tarball -> make-tar -> results

http://travis-ci.oilshell.org/github-jobs/6976/cpp-tarball.wwz/_release/oils-for-unix.tar

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/06/release-0.22.0.html
