### ISSUE TITLE
Reason about UNIX signals / Write a representative demo

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#198]
I posted an open-ended (and maybe naive) question  here about TLA+ and Unix signals.

https://lobste.rs/s/oznngs/practical_tla_now_available#c_tu3sxe

I googled for "unix signals" "tla+" and didn't find much.  Maybe the idea doesn't make sense but I think some formalism would be useful.

This is one of the trickier areas in shell implementation.  Although note that we are omitting job control which makes it less difficult.

**Comment by andychu** [comment]
This issue is a vague wish, but this might be relevant.  It's based on xv6, which I think has some primitive signals.  I hacked on it a few years ago.

[Hyperkernel – A push-button approach to building provably correct OS kernels](https://news.ycombinator.com/item?id=17952472)

**Comment by andychu** [comment]
There have been a bunch of bugs regarding signals cropping up, like #305 and #292.

Part of the problem might be that we have the extra layer of the Python intepreter now.

But I also think it makes sense to rethink the architecture from first principles.  We need to at least specify the problem, if not

Relevant dimensions:

- interactive shell or not
- is the OSH process currently performing a syscall
- is the OSH process currently executing another process?
- is the syscall "interruptable" ?  I forget how this works exactly
- Handling EINTR.  That is done with retries typically?

**Comment by emdash** [comment]
Do you have any ideas wondering what resources one should consult on the subject?

**Comment by andychu** [comment]
APUE by Stevens is my "goto" book for the Unix API, and it has a good section on signals.

Thinking about this a bit more, I think the right thing to do would be to write a tiny C program that only knows how to do 4 things:

- uses GNU `readline()` to get one of a few commands:
- `proc` -- spawns an external process called `record_process_state_and_sleep FILE SECONDS`
- `busy` -- does some computation in a busy loop
- `read` -- execute a system call
- maybe: `proc-async` -- to simulate `sleep 1 &`.  I'm not sure if that case is really different.
- maybe: `trap` builtin -- user signal handlers.  The body should run in the main thread.

Those 3-4 things basically capture all of what a shell does as far as signals are concerned.

And then we would catalog all the signals that the shell and send them to that process at different times.  I don't think that test matrix is very big.

It might depend on the terminal too -- I'm not sure if this test can be fully automated.  Well I'm sure it can, but it's not clear how easy that is.

This isn't a small task but it would help the correctness of Oil a lot!  There are a bunch of smaller tasks on the issue tracker if you want to dip your toes in first.

**Comment by andychu** [comment]
I did mark it "good first issue" though since it requires essentially no understanding of the Oil codebase.  It basically requires C, Unix, and probably learning how GNU readline works.

**Comment by emdash** [comment]
Makes sense, and it can see something like that being generally useful.

As for testing, I have a lot of ideas. Too many. 

Python has a couple of different ways to let you run a command in its own ptty, at different levels of abstraction. There's _pexpect_ package, which I have used, that mainly uses it as a way to trick programs into thinking they're not being scripted. https://pexpect.readthedocs.io/en/stable/. You can also allocate ptty's directly via at least two different models.

I know there are ways to inject key events into x11 programs, and failing that one could possibly create fake `evdev` devices.

There is also a terminal _library_ out there which I came across recently, which was originally intended to support a "user-space virtual console" (i.e. replacing the in-kernel VTs with a user-space process that talks directly to fbdev or libdrm. But the key piece there is it provides the entire terminal state machine _as a stand-alone library_, which means in combination with pttys you can have _headless_ mocks for testing, emulating arbitrary terminals, from arbitrary initial states. I will have to dig up the link.

**Comment by andychu** [comment]
Yes `pexpect` and similar packages are along the lines of what I'm thinking!  I honestly don't know very much about terminals.

I did use both `script` and `ttplay` ... I think to figure out what readline and zsh actually I do.  I should have written a blog post about those, to remember exactly what I did :-/

https://github.com/oilshell/oil/blob/master/demo/tty.sh

This piece of code was useful:

https://github.com/haberman/vtparse

It basically parses the terminal escape sequences and shows you what happens.

---

I'm not sure how `script` and `ttplay` compare to pexpect, which I've also heard of.  But yes I'm **very** interested in this because I think it's one of the things missing from Oil's testing strategy.

For example, while implementing history, I thought of a good property to test:

- If the command parses, then we add it to the history.  If it's a syntax error then we don't.

This is hard to automate because history is only used in interactive mode.  Well it might be automatable with a plain shell script with `bin/osh -i` , but I haven't done it yet.

**Comment by andychu** [comment]
https://www.python.org/dev/peps/pep-0475/

```
This behaviour is system-dependent: on certain systems, using the SA_RESTART flag, some system calls are retried automatically instead of failing with EINTR. Regardless, Python's signal.signal() function clears the SA_RESTART flag when setting the signal handler: all system calls will probably fail with EINTR in Python.
```


Relevant to #292

**Comment by andychu** [comment]
What will probably help is to write a new `signals.SignalState()` class, which is passed into:

- initialization
- InteractiveLineReader, because it messes with signals
- `Trap()` builtin in `osh/builtin.py`
  - note: I think _SigIntHandler here is obsolete!  And proves that we need a central place for it.

This higher level interface could also ease porting to C?  Instead of porting a direct `signal()` wrapper as Python has.  (Isn't sigaction() newer anyway?)

**Comment by drwilly** [comment]
Possibly interesting read on signals/selfpipe: https://skarnet.org/software/skalibs/libstddjb/selfpipe.html

**Comment by andychu** [comment]
Ah OK this is basically done now that we have `test/stateful` with pexpect, formerly `test/interactive` !

http://www.oilshell.org/blog/2022/01/notes-themes.html

It took a few bugs to really get this sorted out!
