### ISSUE TITLE
Setting up GNU readline history

### ISSUE THREAD

**Issue by dezren39** [oilshell/oil#1999]
how does one enable automatic history retention on ysh start? i would guess some sort of default .config/ysh folder that has a history file or something? how would you recommend implementing? same question for osh too i suppose, though its compatible with shell so i think i saw issues for using mcfly and stuff.

**Comment by andychu** [comment]
Does this help?

```
mkdir -p ~/.local/share/oils
```

Yeah that is a bit hidden here

https://www.oilshell.org/release/0.22.0/doc/getting-started.html
