### ISSUE TITLE
Make spec tests pass against a known version of all shells

### ISSUE THREAD

**Issue by kootenpv** [oilshell/oil#2]

**Comment by andychu** [comment]
The examples are all in the tests here:

https://github.com/oilshell/oil/tree/master/tests

which I talk about here

http://www.oilshell.org/blog/2016/11/21.html

Unimplemented features have failing tests; I plan to change that to a different system to prevent regressions.

**Comment by andychu** [comment]
This is done on at least one machine... still need to figure out the environment/version issue.

http://lists.oilshell.org/private.cgi/oil-dev-oilshell.org/2017-March/000004.html

**Comment by andychu** [comment]
bash/dash/mksh/zsh

**Comment by andychu** [comment]
issue #42 is more specific about this
