### ISSUE TITLE
Access shell script AST. API; CLI

### ISSUE THREAD

**Issue by bvberkum** [oilshell/oil#200]
Hi all, I found the Oil project in the last weeks looking for a static analysis tool of shell scripts. I tried various libraries [1], but none was up to it. I've only seen one minor issue with the oil.py frontend.

My question more than issue is about the AST API and exposing it. Not having spent much time looking at its exact implementation, I can easily write some CLI frontend for AST query routines.
But is oil a place for such things?

What format is the AST text representation supposed to be anyway? Is maybe adding a JSON, YAML-esque or other machine parsable variant an option?

I looked at the existing asdl/visitor.py but suppose that is used for CPP only. I just started hacking for two variants that allow me to analyse var. script snippets.

[1] https://github.com/bvberkum/user-scripts/wiki/main#static-analysis
[2] https://github.com/bvberkum/oil/blob/feature/ast-visitor-cli/asdl/shvisitor.py

**Comment by andychu** [comment]
Are you trying to bundle up a shell script into a container?  If so that is something I'm interested in for Oil, and in fact I already started.  See the command below [1].

There are necessarily some heuristics and I haven't worked them all out yet.  But in general the `bin/oshc deps` command is supposed to do some static analysis for dependencies.

For the other questions:

- The AST representation is mainly for debugging, but you can make it more verbose/consistent with the `--ast-format text` flag

`bin/osh --ast-format text -n -c 'echo hi' `

- `asdl/visitor.py` is actually a visitor for the ASDL schema itself, not shell code!  Take a look at `tools/deps.py` to see how I visit the shell AST.

Anyway if there is a concrete use case you have in mind to package up dependencies, we can probably get Oil working on it.


[1]

```
$ bin/oshc deps configure
Couldn't statically evaluate (CompoundWord
  parts: [
    (SimpleVarSub token:(token id:VSub_Name val:'$TMP' span_id:898))
    (LiteralPart token:(token id:Lit_Chars val:/print_expr span_id:899))
  ]
)
cc
expr
mkdir
cat
```

**Comment by bvberkum** [comment]
The objective of the analysis would be making call graphs and track variable dependencies, for documentation and code repacking/dist. All from a devops and CI/CD viewpoint initially.

I came upon the same issue with static analysis and "dynamic" multipart compound words with variables etc. Getting visitor modes for that will take a bit of thought and work, I think that is a small use-case though for potentially complex heuristics. Would it not be simpler to evaluate or step over the commands using a mode of the engine itself, I'd think so.

Since the analysis is done on well known files/functions and I take them apart to small bits (ie. lines and functions) I can trim the simple AST visitor results exactly to suit my needs I think.

Finished two rough initial visitors that'll use. Also poked a bit at building it into a container, but I'm not familiar enough with the scope of the project. Instead first got some other shells into an image [bvberkum/docker-heirloom-sh] and poked a bit at the Travis job and builder image.

My intention is to repackage a bunch of my shell function libraries (ie. like [erichs/composure] but more ambitious), and have them tested on various shells. I've always shunned to use any Bash, but there's some things I want to do a bit easier now. Like per distribution I may want to change things; dependencies, syntax. Maybe do a bit of pre-processing or transpiling so I can write 'my-function' but use my_function in bourne shell mode.

Speaking of testing, I would like to be able to write unit-tests in a framework that would allow me to mock file-streams, executables etc. So that I can write proper unittests for my shell scripts. It would seem to me that something oil can do, is it?

**Comment by bvberkum** [comment]
I see, thats neat.

I kinda "forgot" to look at the `oshc deps` setup you mentioned, that is I had something running. You are right about the test-framework setup ofcourse. I will use deps as a point to dig in a little more later.

**Comment by bvberkum** [comment]
OK. Thank you for the input. We're a week later and I have tested ``oshc deps`` a bit, and done some more research. 

I can't believe I missed the DepsVisitor while git grep'ing the source, my apologies but that may caused a bit of confusion. I also missed the deeper README about Zephyr ASDL (http://asdl.sourceforge.net/ links to offline virginia.edu, last online https://web.archive.org/web/20110821132420/http://www.cs.virginia.edu:80/zephyr/)

That was what I was looking for--I think, I'll be digging through that next. Besides coupling (pre-requisite cmds and shell routines) I want to determine ie. cyclomatic complexity among other stats. I will look into applying McCabe's algo (never done that) and others later. 

There's some more thoughts I'm having on the topic, but nothing on my end that should keep this issue open. 

I do see the oilshell syntax part of it now; using ``oshc translate``. Again neat. I was not looking at all to replace Sh at all, but on that unrelated subject: Have you ever tried Directed Graph Shell [dgsh] or thoughts on parallelism?
https://www2.dmst.aueb.gr/dds/sw/dgsh/

PS. I found this curated list
https://github.com/mre/awesome-static-analysis

And made a commit to add oilshell there, I would accept directions if you would want to request any.
https://github.com/mre/awesome-static-analysis/compare/master...bvberkum:master

**Comment by andychu** [comment]
I haven't tried dgsh, but I have a link to it on this page: https://github.com/oilshell/oil/wiki/ExternalResources

If you have any experience with it or any other alternative shells, please feel free to send feedback.  I am looking for successful "real" uses of alternative shells.

Static analysis of shell scripts is within scope for Oil... so let me know if you make any progress there.  We can also discuss on https://oilshell.zulipchat.com/ .
