### ISSUE TITLE
test builtin arithmetic operators fail with negative integers

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#2158]
Both builtins `[` & `test` do not seem to accept negative integers (bash/zsh/busybox/dash support it).
```sh
$ osh -c 'test -1 -eq 1'
  test -1 -eq 1
       ^~
[ -c flag ]:1: (test) Invalid integer constant '-1'
```

Works fine with `[[` keyword.

---
Version for reference
```sh
$ osh --version
Oils 0.24.0             https://www.oilshell.org/

git commit = 81eb7d89b0bcd46ff1ddaf28e8ca7d8607f2f686
```

**Comment by andychu** [comment]
Yes, this was fixed a few weeks ago!

https://github.com/oils-for-unix/oils/commit/144e1968379262a49ca1a22bfcaa9cd998e99f82

https://github.com/oils-for-unix/oils/commit/dc4f811557717e2d7405a9cb0d2b88b3a906c0fc

If you want to test with the fix you can grab a tarball here:

https://op.oilshell.org/uuu/github-jobs/8535/

https://op.oilshell.org/uuu/github-jobs/8535/cpp-tarball.wwz/_release/oils-for-unix.tar


Thanks for the report!
