### ISSUE TITLE
FYI: Python'2 compiler port to Python3[.5]

### ISSUE THREAD

**Issue by pfalcon** [oilshell/oil#220]
For reference, I was referred to Oil from https://github.com/darius/tailbiter/issues/1 .

FYI, I'm working on porting Python2 "compiler" package to Python3: https://github.com/pfalcon/python-compiler . Specific immediate goal is fully matching CPython3.5 bytecode output. (It hopefully should be clear why: in CPy3.6, the switch to wordcode happened, waving bye-bye to nice and clean bytecode).

Currently, I'm down to only ~5 miscompiles on CPython3.4's Lib/ dir.

**Comment by andychu** [comment]
Thanks for the notification.  I am using the compiler package but it might be obsolete soon due to speed requirements.
