### ISSUE TITLE
MacOS ld does not support `--gc-sections`

### ISSUE THREAD

**Issue by wolverian** [oilshell/oil#224]
The line https://github.com/oilshell/oil/blob/fe184e1f5cddcd9513daaf8ee2286ac7b69ad8fa/build/compile.sh#L160 contains an ld flag `--gc-sections`, which `ld` does not support on macOS. The equivalent flag might be `-dead_strip`.

**Comment by wolverian** [comment]
I created a test Homebrew tap for Oil: https://github.com/wolverian/homebrew-oil

**Comment by andychu** [comment]
Thank you for trying it!  I had planned to get rid of these flags (inserted a few releases ago), since I believe they now make things a bit slower.

BTW issue #192 also affects OS X.  Basically GNU libc has the extended glob syntax, while OS X doesn't, and completion scripts use that syntax.

**Comment by wolverian** [comment]
Thanks! To be slightly more helpful, this is the `ld` version on my macOS 10.14.3:

```
~% ld -v
@(#)PROGRAM:ld  PROJECT:ld64-409.12
BUILD 17:47:51 Sep 25 2018
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 10.0.0, (clang-1000.10.44.4) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 10.0.0 (tapi-1000.10.8)
```

I'll test the patched version ASAP.

**Comment by andychu** [comment]
Thanks, you can wait until I release the 0.6.pre14 tarball.  The repo itself doesn't work on OS X either, but the end-user tarball should.

**Comment by andychu** [comment]
Released, thanks for the report: http://www.oilshell.org/blog/2019/02/18.html

**Comment by wolverian** [comment]
Thank you!
