### ISSUE TITLE
$HOSTNAME not set

### ISSUE THREAD

**Issue by tyxieblub** [oilshell/oil#230]
Even though it is not in the environment, bash sets the `$HOSTNAME` variable, but osh does not. Is it by choice?

**Comment by andychu** [comment]
I prioritize features based on scripts that use them, and I didn't happen to hit `$HOSTNAME.`  But I imagine that's pretty common, so it probably should go in OSH.  Where did you encounter it?

**Comment by andychu** [comment]
OK I added it!  This will be in OSH 0.6.pre15.  (I already released pre14 but have yet to announce it)

**Comment by tyxieblub** [comment]
Thanks!
I had the same .bashrc on two machine and I used `$HOSTNAME` intstead of `$(hostname)` to change the color of the prompt. I don't remember why, though...

**Comment by andychu** [comment]
Released with 0.6.pre15

http://www.oilshell.org/blog/2019/02/18.html
