### ISSUE TITLE
Build error on Arch Linux when Clang is present

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#237]
Due to dsymutil being used, which is meant for OS X only

https://lobste.rs/s/y8noui/osh_0_6_pre15_does_not_crave_chaos#c_wouaea

```
real	1m17,246s
user	1m12,306s
sys	0m4,116s
~/.local/tmp/oil-0.6.pre15
strip -o _build/oil/ovm-opt.stripped -S _build/oil/ovm-opt
dsymutil _build/oil/ovm-opt.stripped -o _build/oil/_build/oil/ovm-opt.stripped.dSYM
Stack dump:
0.	Program arguments: dsymutil _build/oil/ovm-opt.stripped -o _build/oil/_build/oil/ovm-opt.stripped.dSYM
LLVMSymbolizer: error reading file: No such file or directory
#0 0x00007fdab2905b4b llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/bin/../lib/libLLVM-7.so+0x900b4b)
#1 0x00007fdab2903fa4 llvm::sys::RunSignalHandlers() (/usr/bin/../lib/libLLVM-7.so+0x8fefa4)
#2 0x00007fdab290412e (/usr/bin/../lib/libLLVM-7.so+0x8ff12e)
#3 0x00007fdab1ce9e00 __restore_rt (/usr/bin/../lib/libc.so.6+0x37e00)
#4 0x0000556bb3b423dd (dsymutil+0x113dd)
#5 0x00007fdab1cd6223 __libc_start_main (/usr/bin/../lib/libc.so.6+0x24223)
#6 0x0000556bb3b449ae (dsymutil+0x139ae)
make: *** [Makefile:142: _build/oil/ovm-opt.stripped] Segmentation fault (core dumped)
make: *** Deleting file '_build/oil/ovm-opt.stripped'
```

**Comment by kseistrup** [comment]
**PS:** I am the person who posted the segfault on lobste.rs. I haven't been able to compile any of the 0.6-pre series.

ArchLinux uses gcc per default, but I have both gcc and clang installed. I have no idea whether it was gcc or clang that produced the segfault above.

**Comment by andychu** [comment]
Great thanks, it looks like the problem is the feature detection of `dsymutil`.  I think we need feature detection for `objcopy` first?

Can you run

`command -v objcopy; echo $?` on your machine?

I think the issue is that my build first builds unstripped binaries so we have symbols, and then strips them.  Most people build stripped binaries in the first place, which is more portable.

There's apparently no portable way to do the former.  It depends on whether you're using Clang or GCC.

**Comment by kseistrup** [comment]
```sh
$ command -v objcopy; echo $?
/usr/bin/objcopy
0
```

and

```sh
$ pajig owns /usr/bin/objcopy
/usr/bin/objcopy is owned by binutils 2.31.1-4

$ gcc --version
gcc (GCC) 8.2.1 20181127
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by kseistrup** [comment]
I just tried explicitly with `CC=gcc` and `CC=clang` before doing the configure+make, and confirmed that `gcc` and `clang` were actually used: Both ended with a segfault.

**Comment by andychu** [comment]
Cool, can you try this temporary tarball and see if it works?

https://www.oilshell.org/share/oil-0.6.temp16.tar.gz

I changed the Makefile to only rely on objcopy if it's there.

**Comment by kseistrup** [comment]
With temp16 the build process runs successfully and produces a working binary.

**Comment by andychu** [comment]
Great, thanks for trying it!  That was a definite improvement to the Makefile.

**Comment by andychu** [comment]
This is out now with 0.6.pre16:

http://www.oilshell.org/release/0.6.pre16/

Announcement forthcoming:

**Comment by hv15** [comment]
can confirm that it compiles and runs fine, thanks @andychu!
