### ISSUE TITLE
Can't build on ubuntu 18.04

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#249]
```
$ ./configure
./configure: Wrote _build/detected-config.sh and _build/detected-config.h
$ make
test -d _build/opy && \
  build/actions.sh app-deps opy /home/joshua/Documents/Programming/unchanged/oil bin.opy_
build/actions.sh: line 71: _devbuild/cpython-full/python: No such file or directory
test -d _build/oil && \
  build/actions.sh app-deps oil /home/joshua/Documents/Programming/unchanged/oil:/home/joshua/Documents/Programming/unchanged/oil/vendor bin.oil
build/actions.sh: line 71: _devbuild/cpython-full/python: No such file or directory
test -d _build/hello && \
  build/actions.sh app-deps hello build/testdata hello
build/actions.sh: line 71: _devbuild/cpython-full/python: No such file or directory
make: *** No rule to make target '_build/oil/app-deps-c.txt', needed by '_build/oil/all-deps-c.txt'.  Stop.
```

**Comment by jyn514** [comment]
By the way I noticed https://github.com/oilshell/oil/blob/master/Makefile#L71, the 'right' way to do this is with [order-only prerequisites](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html)

**Comment by jyn514** [comment]
I missed https://github.com/oilshell/oil/wiki/Contributing

**Comment by jyn514** [comment]
It would be nice to have `./configure && make && ./install` work though

**Comment by andychu** [comment]
The tarball works with the normal `configure; make install` process, but the repo doesn't.  Instead it uses the build process described on that wiki page.  The rationale is related to the "Three kinds of builds" section.

This post might be useful as well:

http://www.oilshell.org/blog/2017/05/05.html

I hope to simplify this, but that's a long story ...
