### ISSUE TITLE
Output from "source" unclear on parse error

### ISSUE THREAD

**Issue by lheckemann** [oilshell/oil#25]
Given a script `foo.sh` which osh cannot parse, `source foo.sh` gives much less helpful information than `osh foo.sh`, simply outputting the contents of the script rather than describing the errors.

```
$ cat foo.sh
declare -a foo
$ result/bin/osh -c 'source foo.sh'
Error parsing code 'declare -a foo\n'
$ result/bin/osh foo.sh
Line 1 of 'foo.sh'
  declare -a foo
          ^~
Invalid variable name '-a'
---
Line 0 of '<unknown>'
  <no position info for token>
Error parsing AndOr in ParseCommandTerm
---
```

**Comment by andychu** [comment]
Thanks for the bug reports!  Keep them coming.

I just fixed the first two but this one might take a little longer.

There are two bugs here:

1. `declare -a` shouldn't be parsed statically, or it should handle the `-a` flag correctly
2. the error message should be better, as you point out

**Comment by andychu** [comment]
OK I fixed the error messages in:

https://github.com/oilshell/oil/commit/d42256554d36ddf1fe1064adc1dfd6148f8ae78f

Example:

```
$ bin/osh -c 'source bad.sh'
osh error: Parse error in 'bad.sh':
Line 1 of 'bad.sh'
  echo >
        ^
Expected word after redirect operator
---
```

There's still work to do on this, but I'll track it in issue #26 and issue #27.

Thanks for the report!

**Comment by lheckemann** [comment]
Thanks!
