### ISSUE TITLE
Error building & running on macOS High Sierra

### ISSUE THREAD

**Issue by ron-wolf** [oilshell/oil#250]
#### Action

```bash
git clone https://github.com/oilshell/oil.git
cd oil
build/dev.sh minimal
bin/osh
```

#### Outcome

The `libc.so` and `bin/osh` files are generated. However, I get a couple of error messages: one from the build process and the generated executable, and one from the operating system as a dialog box. The short description in the dialog box states, “Python quit unexpectedly while using the `libclang_rt.asan_osx_dynamic.dylib` plug-in.”

This may have something to do with my use of Xcode Beta, so I’m willing to retest with a different configuration. Note that the error occurs regardless of what shell I use, though `fish` happens to be my primary.

#### Program log
```
dyld: warning, LC_RPATH @executable_path in /PATH_TO/oil/libc.so being ignored in restricted program because of @executable_path
==82483==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
"interceptors not installed" && 0
```

#### OS log

<details>
<summary>Click to toggle</summary>
<pre>
Process:               Python [81710]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.10 (2.7.10)
Code Type:             X86-64 (Native)
Parent Process:        fish [79794]
Responsible:           Python [81710]
User ID:               501
</pre>

<pre>
PlugIn Path:             /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
PlugIn Identifier:       libclang_rt.asan_osx_dynamic.dylib
PlugIn Version:          ??? (1001.0.37.7)
</pre>

<pre>
Date/Time:             2019-03-18 14:39:52.201 -0400
OS Version:            Mac OS X 10.14.2 (18C54)
Report Version:        12
Anonymous UUID:        XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
</pre>

<pre>
Sleep/Wake UUID:       XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
</pre>

<pre>
Time Awake Since Boot: 100000 seconds
Time Since Wake:       5700 seconds
</pre>

<pre>
System Integrity Protection: enabled
</pre>

<pre>
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
</pre>

<pre>
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
</pre>

<pre>
Application Specific Information:
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
abort() called
==81710==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
</pre>

<pre>
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib              0x00007fff5824923e __pthread_kill + 10
1   libsystem_pthread.dylib             0x00007fff582ffc1c pthread_kill + 285
2   libsystem_c.dylib                   0x00007fff581b21c9 abort + 127
3   libclang_rt.asan_osx_dynamic.dylib  0x000000010b0680e6 __sanitizer::Abort() + 70
4   libclang_rt.asan_osx_dynamic.dylib  0x000000010b067a64 __sanitizer::Die() + 196
5   libclang_rt.asan_osx_dynamic.dylib  0x000000010b061cb9 __sanitizer::MaybeReexec() + 1065
6   libclang_rt.asan_osx_dynamic.dylib  0x000000010b050bcb __asan::AsanInitInternal() + 331
7   dyld                                0x000000011263dcc8 ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 518
8   dyld                                0x000000011263dec6 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
9   dyld                                0x00000001126390da ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 358
10  dyld                                0x000000011263906d ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 249
11  dyld                                0x0000000112638254 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 134
12  dyld                                0x00000001126382e8 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 74
13  dyld                                0x000000011262ad20 dyld::runInitializers(ImageLoader*) + 82
14  dyld                                0x000000011263475f dlopen_internal + 609
15  libdyld.dylib                       0x00007fff580f55f3 dlopen + 200
16  org.python.python                   0x00007fff3535b961 _PyImport_GetDynLoadFunc + 306
17  org.python.python                   0x00007fff35346fe9 _PyImport_LoadDynamicModule + 89
18  org.python.python                   0x00007fff35345db8 0x7fff352b0000 + 613816
19  org.python.python                   0x00007fff353459dd 0x7fff352b0000 + 612829
20  org.python.python                   0x00007fff35344ab6 PyImport_ImportModuleLevel + 696
21  org.python.python                   0x00007fff3532acdf 0x7fff352b0000 + 503007
22  org.python.python                   0x00007fff352b99a7 PyObject_Call + 97
23  org.python.python                   0x00007fff35335158 PyEval_CallObjectWithKeywords + 159
24  org.python.python                   0x00007fff35332730 PyEval_EvalFrameEx + 12174
25  org.python.python                   0x00007fff3532f588 PyEval_EvalCodeEx + 1540
26  org.python.python                   0x00007fff3532ef7e PyEval_EvalCode + 32
27  org.python.python                   0x00007fff35343619 PyImport_ExecCodeModuleEx + 212
28  org.python.python                   0x00007fff353462ee 0x7fff352b0000 + 615150
29  org.python.python                   0x00007fff35345db8 0x7fff352b0000 + 613816
30  org.python.python                   0x00007fff35345bed 0x7fff352b0000 + 613357
31  org.python.python                   0x00007fff35344b6b PyImport_ImportModuleLevel + 877
32  org.python.python                   0x00007fff3532acdf 0x7fff352b0000 + 503007
33  org.python.python                   0x00007fff352b99a7 PyObject_Call + 97
34  org.python.python                   0x00007fff35335158 PyEval_CallObjectWithKeywords + 159
35  org.python.python                   0x00007fff35332730 PyEval_EvalFrameEx + 12174
36  org.python.python                   0x00007fff3532f588 PyEval_EvalCodeEx + 1540
37  org.python.python                   0x00007fff3532ef7e PyEval_EvalCode + 32
38  org.python.python                   0x00007fff3534e069 0x7fff352b0000 + 647273
39  org.python.python                   0x00007fff3534e110 PyRun_FileExFlags + 130
40  org.python.python                   0x00007fff3534dc8f PyRun_SimpleFileExFlags + 719
41  org.python.python                   0x00007fff3535f6fc Py_Main + 3176
42  libdyld.dylib                       0x00007fff58109ed9 start + 1
</pre>

<pre>
Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00000001126db5c0  rcx: 0x00007ffee55d9ae8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee55d9b20  rsp: 0x00007ffee55d9ae8
   r8: 0x000000010b2f5a30   r9: 0x0000000000000049  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x00007fb07ef07114  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff5824923e  rfl: 0x0000000000000206  cr2: 0x00007fff8aef0188
</pre>

<pre>
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
</pre>

<pre>
Binary Images:
       0x10a623000 -        0x10a624fff  org.python.python (2.7.10 - 2.7.10) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
       0x10a6bb000 -        0x10a6bcff3  time.so (109.200.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/time.so
       0x10a6c3000 -        0x10a6c4fff  cStringIO.so (109.200.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cStringIO.so
       0x10a74a000 -        0x10a74dff7 +libc.so (0) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /Users/USER/Documents/*/libc.so
       0x10afec000 -        0x10b08dfef +libclang_rt.asan_osx_dynamic.dylib (1001.0.37.7) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
       0x112625000 -        0x1126a3a67  dyld (640.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/dyld
    0x7fff2ae8d000 -     0x7fff2b2daff7  com.apple.CoreFoundation (6.9 - 1561) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff352b0000 -     0x7fff3539fff7  org.python.python (2.7.10 - 2.7.10) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /System/Library/Frameworks/Python.framework/Versions/2.7/Python
    0x7fff551cc000 -     0x7fff551cdff7  libDiagnosticMessagesClient.dylib (107) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff5557e000 -     0x7fff5557fffb  libSystem.B.dylib (1252.200.5) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/libSystem.B.dylib
    0x7fff557d8000 -     0x7fff5582fff7  libc++.1.dylib (400.9.4) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/libc++.1.dylib
    0x7fff55830000 -     0x7fff55845fff  libc++abi.dylib (400.17) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/libc++abi.dylib
    0x7fff56494000 -     0x7fff566f7ffb  libicucore.A.dylib (62109.0.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/libicucore.A.dylib
    0x7fff57025000 -     0x7fff577abfe7  libobjc.A.dylib (750.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/libobjc.A.dylib
    0x7fff57f08000 -     0x7fff57f1affb  libz.1.dylib (70.200.4) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/libz.1.dylib
    0x7fff57f8b000 -     0x7fff57f8fff3  libcache.dylib (81) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libcache.dylib
    0x7fff57f90000 -     0x7fff57f9aff3  libcommonCrypto.dylib (60118.220.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libcommonCrypto.dylib
    0x7fff57f9b000 -     0x7fff57fa2fff  libcompiler_rt.dylib (63.4) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libcompiler_rt.dylib
    0x7fff57fa3000 -     0x7fff57facff3  libcopyfile.dylib (146.200.3) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libcopyfile.dylib
    0x7fff57fad000 -     0x7fff58031fdf  libcorecrypto.dylib (602.230.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libcorecrypto.dylib
    0x7fff580b8000 -     0x7fff580f2ff7  libdispatch.dylib (1008.220.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libdispatch.dylib
    0x7fff580f3000 -     0x7fff58122ff3  libdyld.dylib (640.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libdyld.dylib
    0x7fff58123000 -     0x7fff58123ffb  libkeymgr.dylib (30) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libkeymgr.dylib
    0x7fff58131000 -     0x7fff58131ff7  liblaunch.dylib (1336.220.5) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/liblaunch.dylib
    0x7fff58132000 -     0x7fff58137fff  libmacho.dylib (921) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libmacho.dylib
    0x7fff58138000 -     0x7fff5813affb  libquarantine.dylib (86.220.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libquarantine.dylib
    0x7fff5813b000 -     0x7fff5813cff3  libremovefile.dylib (45.200.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libremovefile.dylib
    0x7fff5813d000 -     0x7fff58154ff3  libsystem_asl.dylib (356.200.4) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_asl.dylib
    0x7fff58155000 -     0x7fff58155fff  libsystem_blocks.dylib (73) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_blocks.dylib
    0x7fff58156000 -     0x7fff581defff  libsystem_c.dylib (1272.200.26) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_c.dylib
    0x7fff581df000 -     0x7fff581e2ff7  libsystem_configuration.dylib (963.200.27) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_configuration.dylib
    0x7fff581e3000 -     0x7fff581e6ff7  libsystem_coreservices.dylib (66) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_coreservices.dylib
    0x7fff581e7000 -     0x7fff581edffb  libsystem_darwin.dylib (1272.200.26) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_darwin.dylib
    0x7fff581ee000 -     0x7fff581f4ff7  libsystem_dnssd.dylib (878.230.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_dnssd.dylib
    0x7fff581f5000 -     0x7fff58241ff3  libsystem_info.dylib (517.200.9) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_info.dylib
    0x7fff58242000 -     0x7fff5826aff7  libsystem_kernel.dylib (4903.231.4) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_kernel.dylib
    0x7fff5826b000 -     0x7fff582b6ff7  libsystem_m.dylib (3158.200.7) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_m.dylib
    0x7fff582b7000 -     0x7fff582dbff7  libsystem_malloc.dylib (166.220.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_malloc.dylib
    0x7fff582dc000 -     0x7fff582e7ff3  libsystem_networkextension.dylib (767.220.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_networkextension.dylib
    0x7fff582e8000 -     0x7fff582effff  libsystem_notify.dylib (172.200.21) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_notify.dylib
    0x7fff582f0000 -     0x7fff582f9fef  libsystem_platform.dylib (177.200.16) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_platform.dylib
    0x7fff582fa000 -     0x7fff58304fff  libsystem_pthread.dylib (330.230.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_pthread.dylib
    0x7fff58305000 -     0x7fff58308ff7  libsystem_sandbox.dylib (851.230.3) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_sandbox.dylib
    0x7fff58309000 -     0x7fff5830bff3  libsystem_secinit.dylib (30.220.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_secinit.dylib
    0x7fff5830c000 -     0x7fff58313ff7  libsystem_symptoms.dylib (820.237.2) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_symptoms.dylib
    0x7fff58314000 -     0x7fff58329ff7  libsystem_trace.dylib (906.220.1) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libsystem_trace.dylib
    0x7fff5832b000 -     0x7fff58330ffb  libunwind.dylib (35.4) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libunwind.dylib
    0x7fff58331000 -     0x7fff58361fff  libxpc.dylib (1336.220.5) &lt;XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&gt; /usr/lib/system/libxpc.dylib
</pre>

<pre>
External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 59355
    thread_create: 0
    thread_set_state: 0
</pre>

<pre>
VM Region Summary:
ReadOnly portion of Libraries: Total=236.3M resident=0K(0%) swapped_out_or_unallocated=236.3M(100%)
Writable regions: Total=58.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=58.6M(100%)
</pre>

<pre>
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        2 
MALLOC                            36.2M        9 
MALLOC guard page                   16K        5 
Memory Tag 99                      100K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                       2048K        7 
__DATA                            16.0M      141 
__LINKEDIT                       216.2M        8 
__TEXT                            20.1M       49 
__UNICODE                          564K        2 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            355.2M      221 
</pre>
</details>

**Comment by andychu** [comment]
This isn't expected to work now; there is some explanation here: https://github.com/oilshell/oil/wiki/Contributing

Let me know if it's unclear.  OSH itself should work for end users, the the dev process involves many Linux dependencies and tools.

Someone did start a patch to make OSH development work on OS X, but it didn't get landed.  I would suggest working in a VM unless you're up for a whole bunch of yak shaving :-/  I use Ubuntu on Virtualbox when I'm on a Mac.

**Comment by ron-wolf** [comment]
@andychu Thanks for your response. If I’m to understand correctly, at least some part of any OSH build process requires Ubuntu to work properly, then the rest can be done on macOS. Is this correct?

**Comment by andychu** [comment]
You can download the tarball and try it on OS X, but you can't build the tarball itself.

Sorry I realized the README was unclear, so I just updated it to make it clear that what you tried is a "developer build" that only works on Linux.

https://github.com/oilshell/oil/blob/master/README.md
