### ISSUE TITLE
Prompt evaluator needs to understand \[ and \]

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#252]
If a command line goes off the edge of the screen, we should add a newline before the continuation; currently it overwrites the start of the line and looks very strange. Screenshot:

![image](https://user-images.githubusercontent.com/23638587/54577012-841c8e80-49d0-11e9-8745-ea37d27dcf41.png)

**Comment by andychu** [comment]
Yes thanks, this is the #1 thing I notice now when using the shell!

However I am not sure if this fixable with GNU readline :-(    I may have to revert back to bash's behavior where it scrolls the screen and redraws the prompt every time you hit TAB :-(

I like how zsh and fish do it, and OSH is trying to do it that way, but they have their own line editing libraries.  (That would be a huge task for OSH.  Related: #185 and #228 )

----

I also notice  #247,  I'm not sure of the cause of.  At the bottom of the screen, sometimes things get messed up.

**Comment by andychu** [comment]
BTW one way I've tried to figure out what zsh and fish do when the line wraps is:

    $ zsh
    % echo $$

then in another window

    sudo strace -p <PID>

Although I'm not sure exactly what's going on.

Also, this blog has some good info about terminals:

http://ballingt.com/blog/

**Comment by jyn514** [comment]
`zsh` is doing this on a line continuation: 

```
_IO_putc('\033', 0x55f7f95604e0)                         = 27
_IO_putc('[', 0x55f7f95604e0)                            = 91
_IO_putc('K', 0x55f7f95604e0)                            = 75
_IO_putc('\033', 0x55f7f95604e0)                         = 27
_IO_putc('[', 0x55f7f95604e0)                            = 91
_IO_putc('A', 0x55f7f95604e0)                            = 65
_IO_putc('\033', 0x55f7f95604e0)                         = 27
_IO_putc('[', 0x55f7f95604e0)                            = 91
_IO_putc('9', 0x55f7f95604e0)                            = 57
_IO_putc('2', 0x55f7f95604e0)                            = 50
_IO_putc('C', 0x55f7f95604e0) 
```
which more readably is `"\033[K" "\033[A" "\033[92C"`, which according to https://stackoverflow.com/questions/7342529 and http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html means 'erase to end of line, move the cursor up 1 line, move the cursor 92 columns to the right. That in a terminal looks like this:

![image](https://user-images.githubusercontent.com/23638587/54607169-18641100-4a24-11e9-8edb-6e5ae4ae932f.png)


Possibly related: hitting the up arrow messes up the prompt until we get ann

**Comment by jyn514** [comment]
I can replicate this pretty well in python, not sure how to handle backspace though:

```
from __future__ import print_function
import tty
import termios
import sys

tty.setcbreak(sys.stdin.fileno(), termios.TCSANOW)
i = 0
while True:
    c = sys.stdin.read(1)
    sys.stdout.write(c)
    i += 1
    if i % 3 == 0:
        print("\n\r\033[K", end='')
```

**Comment by jyn514** [comment]
I can't find the code for this, I'm debugging with gdb and the last function call before I lose symbols is `rl_callback_ read_char` at `https://github.com/oilshell/oil/blob/master/native/line_input.c#L1087`, after that function returns we get the wrong line wrapping behaviour. I think this is related to `./Python-2.7.13/Parser/myreadline.c` somehow because the default implementation of `readline` doesn't have this issue (you can test with `input` or `raw_input` in python).

**Comment by andychu** [comment]
Hm the weird thing is that it sometimes wraps and sometimes doesn't, at least for me.

Oh I think I see what's happening.  We are handling SIGWINCH but the READLINE library also needs to handle it!  Doh.  It only seems to happen if you change your terminal width?

That might also be the cause of the issue in #245.

I recorded an asciinema screencast but it didn't show the issue... it doesn't handle terminal resizing I guess.

**Comment by andychu** [comment]
Also, as an aside, `make _bin/oil.ovm-dbg` and `misc/bin.sh` which creates `_bin/osh-dbg` may be helpful in debugging... although it's not something I do very often!

**Comment by jyn514** [comment]
Oh interesting, it only happens when I set a custom prompt. This reproduces with %100 consistency: `PS1='\[\033[01;34m\]\w\[\033[00m\] ▶️'`

**Comment by andychu** [comment]
Oh OK I know why that is.   It's because readline has to know the **width** of the prompt.

Right now in OSH I use `len(prompt_str)`, but this is not correct because of the escape sequences.

OSH has to understand `\[` and `\]` in the prompt, which let you "ignore" the escape sequences when calculating the length!

**Comment by jyn514** [comment]
Found this in https://github.com/oilshell/oil/blob/master/core/comp_ui.py#L44, I can take a stab at it

**Comment by andychu** [comment]
OK cool!  I think two things need to happen:

- `\[` and `\]` need to be turned into `\0x01` and `\0x02` so readline can calculate the width

https://github.com/oilshell/oil/blob/master/core/comp_ui.py#L26

- SetLastPrompt() needs to take a length, and then length should be computed and returned from `self.prompt_ev.FirstPromptEvaluator()` in the InteractiveLineReader.

(There is some refactoring I want to do there so it's not so stateful, but I think this change will be fine without that.)

The core issue is that BOTH readline AND OSH need to know the width of the prompt... A similar issue is that they both need to know the terminal width, which is the cause of some related bugs.

I think it should be easy to make readline and OSH agree on the prompt width.  I'm still thinking about what to do for the terminal width.

**Comment by jyn514** [comment]
I made a few changes which set the length correctly, but the bug doesn't seem to be fixed. I'm running through readline with gdb and it's still saying `prompt_visible_length` is 44 when it should be 31.

(very ugly code, just trying to get it to work before I make it maintainable)

```
diff --git a/core/comp_ui.py b/core/comp_ui.py
index 51e06201..02dbafea 100644
--- a/core/comp_ui.py
+++ b/core/comp_ui.py
@@ -29,6 +30,8 @@ PROMPT_BOLD = '\x01%s\x02' % _BOLD
 PROMPT_RESET = '\x01%s\x02' % _RESET
 PROMPT_UNDERLINE = '\x01%s\x02' % _UNDERLINE
 PROMPT_REVERSE = '\x01%s\x02' % _REVERSE
+# https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python#14693789
+ANSI_ESCAPES = re.compile(r'\x1B\[[0-?]*[ -/]*[@-~]')
 
 
 class PromptState(object):
@@ -40,8 +43,10 @@ class PromptState(object):
 
   def SetLastPrompt(self, prompt_str):
     self.last_prompt_str = prompt_str
-    # TODO: We should figure out the length WITHOUT ANSI codes!
-    self.last_prompt_len = len(prompt_str)
+    print("prompt len:", len(prompt_str), file=sys.stderr)
+    print("len without ANSI escapes:", len(ANSI_ESCAPES.sub('', prompt_str)),
+            file=sys.stderr)
+    self.last_prompt_len = len(ANSI_ESCAPES.sub('', prompt_str))
@@ -284,7 +289,7 @@ class NiceDisplay(_IDisplay):
     # because the screen may have scrolled.  Instead we have to keep track of
     # how many lines we printed and the original column of the cursor.
 
-    orig_len = len(self.comp_state.line_until_tab)
+    orig_len = len(ANSI_ESCAPES.sub('', self.comp_state.line_until_tab))
```

**Comment by andychu** [comment]
It looks like you're setting a length in OSH only?  I was saying that readline ALSO calculates the length using `\x01` and `\x02`.

The way I understand it: 

1. we pass readline the prompt through `raw_input()`  (going through some layers of indirection)
2. it looks for `\x01` and `\x02` and tries to calculate the length.   It does this so it knows when you've reached the last column, i.e. when you've typed `(terminal_width -  prompt_width)` chars.

In parallel, OSH also needs to know the prompt width and terminal width.  But fixing OSH doesn't fix readline -- at least 2 things need to happen.

**Comment by jyn514** [comment]
This seems to have fixed it, I'll turn it into a proper patch when I have some time

```
diff --git a/osh/prompt.py b/osh/prompt.py
index 5703d766..dfcea2ae 100644
--- a/osh/prompt.py
+++ b/osh/prompt.py
@@ -6,6 +6,7 @@ User interface details should go in core/ui.py.
 """
@@ -117,9 +118,11 @@ class Evaluator(object):
 
       elif id_ == Id.PS_LBrace:
         non_printing += 1
+        ret.append('\x01')
 
       elif id_ == Id.PS_RBrace:
         non_printing -= 1
+        ret.append('\x02')

```

**Comment by andychu** [comment]
OK cool.  Yeah I think that is the important bit.  We don't need to remove ANSI escapes ourselves.  The user is responsible for using `\[` and `\]`. 

It's a hack, but it's easy to implement... for Oil we could try to be smarter, but for now it's OK to do what bash does.

BTW `line_until_tab` should only have the user text, which is unlikely to contain any ANSI escapes.  The prompt is what often has ANSI escapes.

I'm going to look at the SIGWINCH issue and then circle back to this ...

**Comment by andychu** [comment]
Released with http://www.oilshell.org/release/0.6.pre17/

Let me know if you see any more problems with a color prompt... it's definitely possible there are further issues.
