### ISSUE TITLE
Control+C doesn't print a newline if another command is running

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#258]
Expected behaviour:

```bash
$ rm -i LICENSE.txt 
rm: remove regular file 'LICENSE.txt'? ^C
$
```

Actual behaviour:

```
osh$ rm -i LICENSE.txt 
rm: remove regular file 'LICENSE.txt'? ^Cosh$ 
```

**Comment by andychu** [comment]
Yes, I reproduced this.  Not sure exactly what's going on as it doesn't appear to ALWAYS miss a newline.

**Comment by jyn514** [comment]
It doesn't? Can you give an example when it prints a newline after an interrupt?

**Comment by andychu** [comment]
If you just hit Ctrl-C at an empty prompt it does the right thing.

```
$ bin/osh
...
[osh] lisa ~/git/oilshell/oil$ ^C
[osh] lisa ~/git/oilshell/oil$ ^C
[osh] lisa ~/git/oilshell/oil$ ^C
```

However I played around with this last night, I noticed last night that OSH is NOT the one printing ^C in the `rm` case, but it IS in the above case.

You can change ^C to [^C] in OSH, but it doesn't change the `rm` case`.

So basically I don't understand who is printing ^C :-/  I guess it's `rm` ?  But then I don't understand why OSH behaves differently than bash.  You could put a newline BEFORE the prompt, but that would mess up the "normal" case.

BTW the same thing happens with `cat`.  OSH is missing a newline...

**Comment by andychu** [comment]
In other words, OSH is only printing ^C in one place, and changing that doesn't affect the behavior ... maybe I'm thinking about it wrong.

**Comment by jyn514** [comment]
Ok I think I know what's going on. `strace` reports neither bash, osh, nor cat print `^C`, so I think that's being printed by the terminal emulator or kernel somehow and we don't have to worry about it. However, bash *does* print the newline if it gets `SIGCHILD` from the kernel. I think I could add this to `core/process.py` without too much trouble, we just have to set a handler for `SIGCHILD` and check if it exiting because of an interrupt or not.
