### ISSUE TITLE
Implement $(< file)

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#273]
This is basically equivalent to `$(cat file)` in Bash but with builtins.

**Comment by andychu** [comment]
Hm it looks like this case triggers a bug:

```
osh$ $(< INSTALL.txt)
Warning: SimpleCommand or Assignment has no location information
```

**Comment by jyn514** [comment]
I can reproduce this without command substitution: `> f`. This should create (and possibly overwrite) `f`exactly as if run with `c > f` where c has no output.

**Comment by andychu** [comment]
OK I fixed the location error.

I'm not sure about  `$(< file)` being like `cat` though.  dash doesn't implement it, but bash, mksh, and zsh do.

Is it commonly used in scripts, or does POSIX require it?

**Comment by Crestwave** [comment]
> OK I fixed the location error.
> 
> I'm not sure about `$(< file)` being like `cat` though. dash doesn't implement it, but bash, mksh, and zsh do.
> 
> Is it commonly used in scripts, or does does POSIX require it?

No, it's not POSIX. It's used to read a file by people who know of it; e.g., Neofetch uses it.

**Comment by andychu** [comment]
Background: https://unix.stackexchange.com/questions/189749/understanding-bashs-read-a-file-command-substitution/368663#368663

**Comment by andychu** [comment]
An interesting thing about this is that zsh supports an extended version of it.  I think bash is just literally special casing `$(< file)` to mean something different?

```
echo $(<file)  # works in both
echo $(< file; echo hi)      # zsh respects the meaning of < file, but bash doesn't
```

Also, zsh extends the meaning to process subs, like

```
cat < <(<file; echo hi)       # a confusing way of doing it, but it works
```

**Comment by andychu** [comment]
And it also doesn't support pipelines and subshells:

```
(< file)    # doesn't cat the file

< file | wc -l  # doesn't work, nothing goes to stdout
```

**Comment by bb010g** [comment]
> And it also doesn't support pipelines and subshells:

See Zsh's `NULLCMD` options & [section "Redirections with no command" of zshmisc(1)](https://man.archlinux.org/man/zshmisc.1#REDIRECTIONS_WITH_NO_COMMAND).
