### ISSUE TITLE
Implement read -s

### ISSUE THREAD

**Issue by ghost** [oilshell/oil#276]
This [tetris game script](http://read.pudn.com/downloads99/sourcecode/game/404711/tetris.sh__.htm) will be useful for testing osh, however it requires that the '-s' option be added to the `read` builtin. To test the script write the `usleep` code in the comment box to a file and modify the script so that the resulting binary can be found.

**Comment by ric-sc-gr** [comment]
Interesting to note, using `termios` to disable echo works however, only if run from the osh interpreter itself, but not by passing the script as an argument like so `osh script`

**Comment by ric-sc-gr** [comment]
E.g
```
ubuntu@just-lizard:~/oil$ bin/osh
osh$ /home/ubuntu/testprog/asksure 
Are you sure (Y/N)? 
osh$ ^D
ubuntu@just-lizard:~/oil$ 
```

as against

```
ubuntu@just-lizard:~/oil$ bin/osh ~/testprog/asksure 
Are you sure (Y/N)? y

ubuntu@just-lizard:~/oil$ 
ubuntu@just-lizard:~/oil$ cat ~/testprog/asksure
```

with the snippet from bash hackers wiki

```sh
#! /bin/bash

asksure() {
  echo -n "Are you sure (Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done

  echo # just a final linefeed, optics...

  return $retval
}
```

**Comment by ric-sc-gr** [comment]
From further investigation it seems this change will only be noticed if the controlling interpreter is the same as the script. This is noticed by ksh and mksh having the same effect.

**Comment by jyn514** [comment]
I can grab this one. The documentation for termios actually has an example of doing exactly this: https://docs.python.org/3.6/library/termios.html#example

**Comment by jyn514** [comment]
Not sure how to write a spec test for this. I can check that it works the same as `read` without the `-s`, but I don't know how to tell if it's echoing to the terminal (since that's not part of stdout or stderr).

**Comment by andychu** [comment]
Oh OK I wrote some suggestions here: https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Tests

Basically would just write in the commit description how to manually test it, and then maybe make a spec test that uses `-s` even though it doesn't behave differently.  It can be still useful as a sanity check, i.e. it implicity checks status 0, showing that the shell didn't crash, etc.

Sometimes I put manual tests in `demo/` although it's not strictly necessary.

**Comment by andychu** [comment]
And @ric-sc-gr already posted a patch there though I haven't seen a PR for it yet.

**Comment by jyn514** [comment]
I can defer to his patch, he seems to reset the terminal state on exceptions which is probably the right way to do things

**Comment by ric-sc-gr** [comment]
@jyn514 If you have a working solution then go ahead, I won't be able to work on mine till Thursday.

**Comment by andychu** [comment]
This was done awhile ago
