### ISSUE TITLE
Implement `ulimit` builtin

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#280]
Found this while investigating https://github.com/oilshell/oil/issues/279 - we don't implement `ulimit`. There's a man page at https://ss64.com/bash/ulimit.html, `strace` shows that bash is using [`prlimit64`](https://stackoverflow.com/questions/8869229/prlimit64-linux-function). Python has this in a library: https://docs.python.org/3.5/library/resource.html#resource.prlimit

```
$ ulimit -u
prlimit64(0, RLIMIT_NPROC, NULL, {rlim_cur=1000, rlim_max=1000}) = 0
write(1, "1000\n", 5)
$ ulimit -u 999
prlimit64(0, RLIMIT_NPROC, NULL, {rlim_cur=1000, rlim_max=1000}) = 0
prlimit64(0, RLIMIT_NPROC, {rlim_cur=999, rlim_max=999}, NULL) = 0
```

**Comment by andychu** [comment]
Yes good point.  This would be a great contribution for someone since it's self-contained and AFAIK is a wrapper for the syscall :)

It may have side effects that aren't easily testable, but in those cases I think simply testing that it "doesn't crash" is fine first the first pass.  I also sometimes add manual demos in `demo/`.

**Comment by andychu** [comment]
Another user hit this in #161 

https://gist.github.com/wertercatt/5820fe28f9e107a55d6f28929c919c8f

**Comment by gardenappl** [comment]
Found this during Java development: `gradlew` uses `ulimit`.

Osh prints an error, but apparently the `gradlew` script can handle this, so it just shows "Could not query maximum file descriptor limit" and keeps on going.

**Comment by kseistrup** [comment]
As of Oils 0.21.0 (commit cc2f68315a18a69be9f8c94bc97c655f5d50bdc2) the `ulimit` command is still missing:

```sh
$ osh -c 'ulimit -n 1024'
  ulimit -n 1024
  ^~~~~~
[ -c flag ]:1: 'ulimit' not found
```
`bash` scripts that attempt to use `ulimit` will fail.

**Comment by kseistrup** [comment]
PS: See also #1914

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/06/release-0.22.0.html
