### ISSUE TITLE
No error indication when trying to assign to a bare closing parenthesis

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#301]
```bash
$ var=)
$ printf '%s\n' "$?"
0
$ printf '%s\n' "$var"


```

**Comment by andychu** [comment]
Thanks, I'm not sure what's going on here, but that is a bug!

**Comment by andychu** [comment]
OK this is fixed.  Somehow we specifically ignored `)` at the end of any interactive line.  The bug didn't show up in batch mode, which meant it avoided a lot of our test coverage!

I think it was related to handling `)` as the end of a command sub, but we're doing something more principled about that now.

Thanks for the report!

**Comment by andychu** [comment]
Released with version 0.6.pre20! http://www.oilshell.org/release/0.6.pre20/
