### ISSUE TITLE
allow use as library

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [oilshell/oil#31]
this would allow python tools that provide toy-ish shell subsets (like tox for example)
to provide a real shell language without implementing an own

**Comment by andychu** [comment]
Oil might be a library at some point, but it won't be a Python library.  There are a series of blog posts around April that give the rationale for this:

http://www.oilshell.org/blog/2017/04/25.html

A C library would be nice, and could be used from Python, but that's pretty far off unfortunately.

But I'm looking for Python programmers to help accelerate it!

Also, at least one other person asked for a library, but the use cases were pretty vague.  There are at least a few different ways to expose it as a library, depending on the use case.

**Comment by andychu** [comment]
This is really far in the future, and the implementation language is going to change, so I'm going to close it.  It's definitely on the radar; in fact I mention it at the end of this blog post:

http://www.oilshell.org/blog/2018/01/28.html

(LLVM analogy)

**Comment by RonnyPfannschmidt** [comment]
thanks for the update
