### ISSUE TITLE
missing span ID exposed while running osh-runtime:yash benchmark

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#313]
Not sure where this is coming from yet.

**Comment by andychu** [comment]
Also just got this

```
[osh] lisa ~/git/oilshell/oil$ ~/bin/argv "$x"
Warning: span_id undefined in SetCurrentSpanId

```

**Comment by lhoursquentin** [comment]
Also reproducible with any of the following three commands:
`> file`
`>> file`
`2>&1`

**Comment by andychu** [comment]
Thanks, this is also #273 ... looks like many people have been running into this.
