### ISSUE TITLE
runtime issues with OSH, bash_profile, etc.

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#37]
- [x] `test -r` (and `-w`)
- [x] `$UID` and `$EUID`

@icarroll I just implemented -r and -w here:

https://github.com/oilshell/oil/commit/89a89be9fd1ed5109e1631b327223e206cfda228

Let's use this thread to keep track of all the issues you encounter.

I believe issue #36 is also related, since you said the SSH connection closes on Ctrl-C.

**Comment by icarroll** [comment]
What shell variables are specified by posix? Bash sets a large number of them, but I don't know how much shell code out in the wild depends on them being present.

**Comment by andychu** [comment]
My strategy has been to implement on demand (as long as they are sane).  On issue #26 I implemented a lot of things for Nix.

Do you have a link to RedHat scripts and WSO2IS scripts, like this?

https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L318

Then I can just 'source' them and see what happens.

**Comment by icarroll** [comment]
I'm sure they're available somewhere. If nothing else I can make my own fork here on github.

**Comment by andychu** [comment]
OK great, it would be nice to have a configuration that we can both run.

It's easier to improve the error messages that way too.

**Comment by icarroll** [comment]
I haven't been able to find the right repos on github so I'll just create a new repo and commit the relevant files.

**Comment by andychu** [comment]
Closing this since it's been dormant for awhile.  Feel free to file new issues based on any problems you encounter.
