### ISSUE TITLE
IFS splits non variables

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#372]
Modifying the `IFS` should only affect non quoted variables splitting, but seems like both non variable commands and arguments are affected by the `IFS` value:
```bash
$ osh -c 'IFS=b; echo abc'
a c
```
```bash
$ osh -c 'IFS=o; echo abc'
  IFS=o; echo abc
         ^~~~
[ -c flag ]:1: Can't execute 'ech': No such file or directory
```

**Comment by andychu** [comment]
Good catch!  Not sure what's going on yet, but hopefully it won't be too hard to fix.

**Comment by andychu** [comment]
Hm, the other two were easy to fix, but this has been broken for a long time (I guess always) and is sort of fundamental.

It used to be that each word part had a separate boolean flag for "do_split" and "do_glob", but I combined them in January 2018, which was wrong.  Not sure if it worked before that.

https://github.com/oilshell/oil/commit/34d0edaf56df40f5c92081519de39be059ce54d6

Unquoted words need glob expansion, but they don't do splitting.

Anyway I will work on this.  Thanks for the testing, and keep the bug reports coming!

**Comment by andychu** [comment]
OK that wasn't too bad!  I hadn't touched that code in a long time and I was worried it would need a lot of attention, but it was pretty clean.

**Comment by andychu** [comment]
Released: http://www.oilshell.org/release/0.6.pre23/
