### ISSUE TITLE
"$*" does not follow POSIX when IFS is unset

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#374]
When the `IFS` is unset, `osh` joins all positional parameters without any separator, they should be instead separated by spaces.

From the [SCL](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_02)
> the initial fields shall be joined to form a single field with the value of each parameter separated by the first character of the IFS variable if IFS contains at least one character, or separated by a \<space\> if IFS is unset, or with no separation if IFS is set to a null string.

```bash
$ osh -c 'unset IFS; set a b c; echo "$*"'
abc
```
```bash
$ bash -c 'unset IFS; set a b c; echo "$*"'
a b c
$ dash -c 'unset IFS; set a b c; echo "$*"'
a b c
$ zsh -c 'unset IFS; set a b c; echo "$*"'
a b c
$ ksh -c 'unset IFS; set a b c; echo "$*"'
a b c
$ mksh -c 'unset IFS; set a b c; echo "$*"'
a b c
```

**Comment by lhoursquentin** [comment]
Thanks for the quick fix!
On the other hand if `IFS` is set but empty we should have `abc`:
```bash
$ osh -c 'IFS=; set a b c; echo "$*"'
a b c
$ bash -c 'IFS=; set a b c; echo "$*"'
abc
```

**Comment by andychu** [comment]
Duh, thanks!  I just fixed this.

**Comment by andychu** [comment]
Released: http://www.oilshell.org/release/0.6.pre23/
