### ISSUE TITLE
Redirection corner case 2&>1

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#377]
With the single line below:
```bash
2&>1
```
`osh` returns **1** without any output, it also creates a file named `1` which is **empty**.

It should probably behave like what it does with:
```bash
a&>1
```
Which returns **127** and creates a file named `1` which contains:
```
  a&>1
  ^
[ -c flag ]:1: Can't execute 'a': No such file or directory
```

For reference `bash` returns **127** and `1` contains as expected:
```
bash: 2: command not found
```

**Comment by andychu** [comment]
Yes, `&>` was parsed incorrectly.  I was confused by this report until digging in ... Nice find!

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.6.0/
