### ISSUE TITLE
What should I use instead of printf %x?

### ISSUE THREAD

**Issue by Screwtapello** [oilshell/oil#378]
I use an editor called [Kakoune](http://kakoune.org/), which uses POSIX shell as its plugin scripting language. As you can imagine, portability is a problem, so I thought I'd try running it with OSH to see if OSH's stricter parsing and linting reported any issues.

# Steps to reproduce

    osh -c 'printf U+%04x\\n 65'

# Actual outcome

      U+%04x\n
           ^
    (source.ArgvWord word_spid:2):1: osh printf doesn't support 'x' (because it implies unsigned integers)

# Expected outcome

Same as bash:

    $ bash -c 'printf U+%04x\\n 65'
    U+0041

# Notes

This comes from a Kakoune config snippet I use to display the Unicode codepoint under the cursor in my status bar; for example, `U+0041` is the typical notation for the codepoint named LATIN CAPITAL LETTER A.

I understand that `printf %x` is unportable because the output for negative numbers depends on the machine architecture, but rejecting `%x` entirely is also unportable. If you're going to be unportable anyway, why not make it signed hexadecimal instead of unsigned, like Python 3?

    $ python3 -c "print('U+%04x' % -65)"
    U+-041

That way regular, portable uses of `%x` work unmodified, and unportable uses produce a somewhat useful result.

**Comment by andychu** [comment]
Thanks for testing it, and for the detailed bug report!

I think we should do something for `%x`.  I only implemented `printf` a few weeks ago and I wasn't sure what to do about %x so I just punted on it :)  But I will look at again since it sounds like you have a very realistic use case.

**Comment by andychu** [comment]
@Screwtapello Would your script work if I simply disallowed negative numbers with `%x` etc.?

- Printing `-041` is possible, but it's incompatibile with other shells.
- Giving a runtime error is implementing a "subset", which is different than incompatibility.  (It can be relaxed later if we want.)
- And yes I don't like the behavior of existing shells because it depends on the machine architecture

**Comment by Screwtapello** [comment]
Yes, disallowing negative numbers would be fine.

Thanks for looking into it!

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.6.0/
