### ISSUE TITLE
Redirecting a file descriptor to itself fails

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#380]
Another edge case:
```bash
echo >&1
```
Fails with:
```
  echo >&1
       ^~
[ -c flag ]:1: 1: Bad file descriptor
```
Same for `1>&1`, `0>&0`, `<&0` (and I'm guessing same for new ones created with exec).

The most interesting one is `2>&2` which has the same issue, but no error output, `strace` shows the error message is attempted to be written in an invalid fd and is followed by what looks like a python backtrace (visible in `strace` too).

**Comment by andychu** [comment]
I verified this, but I'm not sure what's going on yet ...

Thanks for all the reports, keep them coming!

**Comment by andychu** [comment]
Looks like this was fixed at some point, more testing welcome
