### ISSUE TITLE
osh gives spurious I/O error on winsizechange

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#384]
Steps to replicate: `sleep 10` then resize the terminal window.
Expected output: no output
Actual output: `osh I/O error: Interrupted system call`

This gets a little weirder for commands that have output, here's `cargo build`:

```
   Compiling bootstrap v0.0.0 (/home/joshua/Documents/Programming/unchanged/rust/src/bootstrap)
osh I/O error: Interrupted system call==========================>      ] 36/40: rustdoc(...
(osh) ~/.../unchanged/rust ▶️     Building [==================================================    Building [======================================================>  ] 39/40: bootstrap(bin
(osh) ~/.../unchanged/rust ▶️ 
(osh) ~/.../unchanged/rust ▶️     Finished dev [unoptimized] target(s) in 1m 41s
```
I think `osh` 'forgets' about the command on EINTR instead of calling `Waiter.wait` again.

**Comment by andychu** [comment]
Hm what version is this?  I thought I just fixed that, but it's possible there is an unhandled EINTR somewhere.  But I wouldn't expect it to be in the Waiter.

**Comment by jyn514** [comment]
Oh I hadn't updated in a week or so, that's probably the issue.

```
Oil version 0.6.pre22
Release Date: -
Arch: x86_64
OS: Linux
Platform: #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019
Compiler: GCC 7.3.0
Interpreter: CPython
Interpreter version: 2.7.15rc1
Bytecode: -
```

**Comment by jyn514** [comment]
No, this still occurs on master.
