### ISSUE TITLE
${var#*} and ${var%*} remove a char

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#385]
For both single `%` and `#` parameter expansion, the smallest suffix/prefix should be removed.
In the case of a unique `*`, the smallest is **nothing**.

However `osh` removes one character:
```bash
osh$ var=abc
osh$ echo "${var%*}"
ab
osh$ echo "${var#*}"
bc
```

bash/dash/ksh93/mksh do **not** remove anything:
```bash
bash-4.4$ var=abc
bash-4.4$ echo "${var%*}"
abc
bash-4.4$ echo "${var#*}"
abc
```

`zsh` removes one char for the suffix case but not for the prefix one, not sure if this is a bug or not (but seems like one).

**Comment by andychu** [comment]
Thanks, another good catch!  Looking back on the code, it was pretty silly... I think Python's `range()` is awkward for this problem because it's a half-open range.  So a plain loop is a lot clearer.

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.6.0/
