### ISSUE TITLE
exit from sourced file does not exit caller

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#395]
An `exit` call in a sourced file only exits from the sourced file, not from the script that sourced it.

```bash
$ cat /tmp/foo
echo sourced pre-exit
exit
echo sourced post-exit
```
```bash
$ osh -c '. /tmp/foo; echo main'
sourced pre-exit
main
```
This `exit` should also exit the main process immediately:
```bash
$ bash -c '. /tmp/foo; echo main'
sourced pre-exit
```

**Comment by andychu** [comment]
Released with 0.7.pre1: https://www.oilshell.org/release/0.7.pre1/
