### ISSUE TITLE
spec tests should automatically start with $PWD of $TMP

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#396]
instead of doing `cd $TMP` at the beginning

and instead of polluting the repo dir and then cleaning it up (which can fail after Ctrl-C)

**Comment by jyn514** [comment]
Note that this throws off `$SH` since it's a relative path, you'll need to use `realpath`. See https://github.com/oilshell/oil/pull/365/files#diff-581b070df23fa5b14c4af5722b7f71ed.

**Comment by andychu** [comment]
Yeah in retrospect this would have been nice, but it would also require a pass over the tests to fix the ones relying on $PWD == repo_root.  Instead I just made a note here:

https://github.com/oilshell/oil/wiki/Spec-Tests

And I changed the `source` tests to `cd $TMP`.  The `rm` at the end isn't as nice because you could Ctrl-C, which would leave temp files in the repo.  (And unfortunately that may make more tests fail.)

https://github.com/oilshell/oil/commit/7df76b2ac61753b21a197adc59b81fbc25c7c5ce
