### ISSUE TITLE
Add -c and -d options to history

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#399]
Sometimes I type in my password to the shell instead of `sudo` by mistake. It would be nice to have an option to delete it with `history -c` instead of having to find the history for osh and delete it manually. From `help history` in bash:

```
history: history [-c] [-d offset] [n] or history -anrw [filename] or history -ps arg [arg...]
    Display or manipulate the history list.
    
    Display the history list with line numbers, prefixing each modified
    entry with a `*'.  An argument of N lists only the last N entries.
    
    Options:
      -c        clear the history list by deleting all of the entries
      -d offset delete the history entry at position OFFSET.
```

**Comment by andychu** [comment]
Yes, I recall seeing this in some programs, maybe it was fzf #322

**Comment by andychu** [comment]
FWIW #562 and #358 are user requests for `history` flags/features.  I guess people use this builtin a lot more than I do!

**Comment by andychu** [comment]
Fixed: https://www.oilshell.org/release/0.8.pre2/
