### ISSUE TITLE
test our find and xargs

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#417]
cc @drwilly , I will try this:

- See if `test/wild.sh` runs with our `find`.  That was our bigger test case.
- See if `test/spec.sh` and `tets/wild.sh` runs with our `xargs`

If those work, that's a really good sign.

Were there any concurrency problems left with xargs?  I filed #326 but I'm not sure how necessary it is.

I think I wanted to stop polling... but I think it's better to get the "outside" tests working before refactoring on the inside, for efficiency, dependencies.

Our build of Python doesn't have the `subprocess` module, etc.

**Comment by andychu** [comment]
Original bug is #85

**Comment by drwilly** [comment]
Outside of SIGUSR1+2 for jobcontrol parallel invocation should work as expected.

**Comment by jyn514** [comment]
`find` should accept a path as the first argument. Not taking it is actually a GNU extension, BSD find requires it.

Current behavior:
```
tools/find/run.sh find-demo /tmp

--- /tmp ---

Traceback (most recent call last):
  File "/home/joshua/src/oil/tools/find/find.py", line 111, in <module>
    main(sys.argv)
  File "/home/joshua/src/oil/tools/find/find.py", line 68, in main
    parse_root = parser.ParseTree(tokens)
  File "/home/joshua/Documents/Programming/oil/tools/find/parser.py", line 27, in ParseTree
    opmap=opmap
  File "/home/joshua/src/oil/pgen2/driver.py", line 88, in PushTokens
    if p.addtoken(type_, opaque, ilabel):
  File "/home/joshua/src/oil/pgen2/parse.py", line 181, in addtoken
    raise ParseError("bad input", typ, opaque)
pgen2.parse.ParseError: bad input: type=0, opaque=('', '', (1, 0))
```
Expected behavior: shows all files starting from the `/tmp` directory

**Comment by andychu** [comment]
I'm still interested in `find` and `xargs`, but I'm cutting down issues per

http://www.oilshell.org/blog/2020/01/making-plans.html

**Comment by andychu** [comment]
Closing since no takers
