### ISSUE TITLE
Release tags missing

### ISSUE THREAD

**Issue by AMDmi3** [oilshell/oil#424]
Tags corresponding to releases (http://www.oilshell.org/releases.html) are missing from the repository. These are crucial for packaging.

**Comment by andychu** [comment]
Are the branches sufficient?  There is one for every release:

https://github.com/oilshell/oil/branches

I haven't really used tags in git.  Is there a difference vs. using a branch?  Branches identify a commit.

The changelogs also somewhat identifies a commit, e.g.

http://www.oilshell.org/release/0.6.0/changelog.html

**Comment by AMDmi3** [comment]
Branches do not identify a fixed point in time, although you seem to use them for this purpose. Using tags instead would be using proper tool for the purpose, would make releases visible on GitHub and for all tools which naturally expect tags, and for people who would never guess that they should look for releases in branches.

**Comment by andychu** [comment]
Are you trying to package Oil for a particular platform?  As far as I can tell, most people have been able to do so with the tarballs, e.g.

https://github.com/oilshell/oil/wiki/Oil-Deployments

**Comment by AMDmi3** [comment]
> Are you trying to package Oil for a particular platform?

Not really. If I were (I do package software for FreeBSD), it'd be problematic as I'd want to use GitHub tarball, while using branches for this purpose is explicitly disallowed.

In my case however I just wanted to verify that 0.6.0 was an actual release for https://repology.org/project/oil-shell/versions, and saw no tags.

**Comment by andychu** [comment]
There are no Github tarballs.  The repository is significantly different than the tarballs to avoid Python dependencies.  Some details here:

https://github.com/oilshell/oil/wiki/Contributing

If you need help packaging it for a particular platform, let me know.

**Comment by AMDmi3** [comment]
There are always Github tarballs, automatically provided for every commit and tag. These are strongly preferred over manually packaged tarballs.

**Comment by nckx** [comment]
> ~~[autoballs] are strongly preferred~~

Even in context, this should be ‘I prefer…’ or maybe ‘FreeBSD prefers…’.  As it stands it's misleading. Such tarballs can't even be verified with hashes (as done on the Oil download page) or signatures, since they are silently regenerated by GitHub at will.

Creating properly bootstrapped and immutable releases, as done here, is absolutely the right way to do it.

**Comment by AMDmi3** [comment]
> Even in context, this should be ‘I prefer…’ or maybe ‘FreeBSD prefers…’.

It's not just me or FreeBSD, it's common practice. [Debian](https://wiki.debian.org/UpstreamGuide#Generated_files) explains it quite well, for instance.

> tarballs can't even be verified with hashes (as done on the Oil download page) or signatures, since they are silently regenerated by GitHub at will

This is absolutely not true. For FreeBSD ports, they are verified by SHA256s, and there has been not a single case of checksum change, even when repositories are renamed and moved between GH accounts, since the very moment we began using GH tarballs.

> Creating properly bootstrapped <...> is absolutely the right way to do it

Now this should've been "in my opinion", especially if you demand it from others.

In my 10+ years of packager experience, what you call bootstrapping has done much more evil than good. The most common scenario is that generated files bitrot (for instance, configure does not expect two digit FreeBSD version, so build fails on FreeBSD 10, or cython generated files fail to build after python update), causing breakages affecting users. Then maintainer _has_ to switch back to regenerating them which also discards a huge part of prior porting work (e.g. patches to generated files) which should then be redone and retested. So the "absolutely right way" is to discard all the bootstrapping from the beginning. It is also very practical to base on raw repository contents to be able to use patches/commits retrieved directly from the repository, and to be able to bisect git, test master branch or forks, when it's needed.
