### ISSUE TITLE
Revisit the exit code of assignments

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#425]
From #423 

cc @lhoursquentin

Somewhat hacky commit that may not have gone far enough:

https://github.com/oilshell/oil/commit/ba772f081056beb08fd25d8db4190076f25f20b2

We should probably be entirely compatible (if shells in fact agree) or entirely "rationalized" with the compatible behavior under `set -o posix`

-----

One issue is that OSH uses a "functional" style for `$?` rather than an imperative style.  So an assignment NEEDS an exit code.

If we want to keep the functional style, maybe we need `status = Command(int) | Pipeline(int*) | None`

**Comment by andychu** [comment]
FWIW one reason for the incompatibility is because I didn't like the difference between:

```
set -o errexit
x=$(false)  # status is 1, will exit
local x=$(false)  # status is 0, won't because local is a builtin that SUCCEEDS
```

Under most shells, the latter is better written:

```
local x
x=$(false)
```

I'm not sure if there were any other reasons for the incompatibility.

But `strict-errexit` will check the command sub before the command sub ends, so maybe this isn't even a reason to be incompatible.

**Comment by andychu** [comment]
And yes from a recent discussion with @mgree, these two cases are the same:

1. assignment `x=1` (no builtin)
2. empty argv

So it does make sense that you brought them up both at once.  Again I think it's confusing that `readonly x=$(false)` behaves differently, but probably what should happen is to implement everything compatibly, and then add an option to for better behavior.  I think it's a bit off from that now.

I decided to characterize options as `strict` and `sane`.  The former removes behavior, and the latter changes existing behavior.

- `shopt -s all:strict`  is currently implemented, and turns on all the strict options.
- `shopt -s all:sane` is not implemented, but the exit code of assignment builtins could be one of the changes.

**Comment by andychu** [comment]
Related thread with idea: `COMSUB_STATUS`, which means you don't lose the exit code, but it also doesn't break anything, and doesn't introduce new modes

https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Ultimate.20errexit.20guide/near/194408788

**Comment by andychu** [comment]
@lhoursquentin    I'm revisiting all the exit codes right now.

I think the philosophy has changed somewhat -- we are going to be compatible with POSIX / bash quirks for exit codes, but we also implement a few of our own options:

- `process_sub_fail` -- analogous to `pipefail`
- `strict_errexit` -- disallow dangerous `if myfunc` and more
- `command_sub_errexit` -- fail more often

The rules about assignment are quirky, but I think the real solution is to switch to Oil assignment like `var x = 42` if you don't want the exit codes.

I am not there's a reason to make a silently incompatible exit code semantics for shell assignment.  

Does this make sense?  The original thread was over a year ago so my memory could be hazy.

As best I remember, the problem was the difference between `x=$(false)` and `declare x=$(false)`.   That is confusing but I think it should stay for compatibility.

`var x = $(false)` and `setvar x = $(false)` won't have the same issue

----

https://github.com/oilshell/oil/issues/423#issuecomment-511080621

> This is getting further and further from the original point but on that same topic I would expect declare a=$(false) to return 1 too, especially since you treat assignment builtins as close as possible as the standard assignment, though in that case it would differ from all other shells, but this could make sense IMO.

> I remember a thread on bug-bash (link) about builtin assignment error having special parsing rules but not being fatal in case of error, I guess this could be something to think about.

**Comment by andychu** [comment]
FWIW this is the behavior in Oil:

```
$ bin/oil -c 'var x = $(false)'
  var x = $(false)
            ^~~~~
[ -c flag ]:1: fatal: Exiting with status 1 (command in PID 8964)
  var x = $(false)
          ^~
[ -c flag ]:1: fatal: Command sub exited with status 1 (command.Simple)
```

It fails right away because of a bunch of `shopt` options that are on.  I think this makes sense.

**Comment by lhoursquentin** [comment]
Yes this makes sense to keep the POSIX behavior as is and add `var` as a "safer" alternative.

But how will `var` come into play with `export`/`readonly`/`declare -i` etc.? If you need to do a two step declaration then what's the point of using `var`/`setvar`?

```sh
export foo
setvar foo = $(false) # failure
```
vs
```sh
export foo
foo=$(false) # failure
```
What's the advantage to use `setvar` here?

But if `var` had the same options as `typeset`/`declare` to declare and export/set as readonly etc. in a single command then that would indeed be an ideal replacement:
```sh
var -x foo = $(false) # failure, nice
```
but
```sh
declare -x foo=$(false) # no failure
```

**Comment by andychu** [comment]
Good questions.  Short answer: I expect `export` to be the only shell assignment builtin used in idiomatic Oil.

There are only 3 flags: readonly, exported, and nameref.  In Oil, the **values** are typed, not "cells", so we flags for types.  

https://www.oilshell.org/release/latest/doc/known-differences.html#values-are-tagged-with-types-not-cells

The other non-type flags are stuff like lower case and uppercase, which I view as a ridiculous feature :)  So far those haven't been needed to run any programs.  I think someone mentioned it once.  I also think they are bash-specific.

The repr command can show you the internal representation of variables.  So shell builtins and Oil keywords operate on the **exact same data structure**.

```
$ export FOO=bar
$ repr FOO
FOO = (cell exported:T readonly:F nameref:F val:(value.Str s:bar))
```


But basically we have `var` and `const` for readonly, and "out params" and `setref` for `nameref` (which I haven't fully implemented yet).

Exporting can be done with a single export invocation, or you can use `var` and then `export`.

-------------

The advantage of using Oil assignment is that you have typed expressions on the right.  For `x=$(false)` there's no real advantage.  But for `x = 1 + a[i] * f(x)`, there is a much richer language on the RHS.

So the idea is to to "deprecate" all  shell assignment, except `export`.  Does that make sense?

Of cousrse some people might want to stay in the shell world for compatibility, and that's OK.

**Comment by lhoursquentin** [comment]
Got it, so in the end this isn't really about changing assignment exit codes anymore, you're fixing the `local var=$(false)` return value confusion by proposing the superior `var`/`setvar` combo, but not for `export`.
I guess that's fine, there's a limit of what you can actually fix without changing everything about the language.

---
> The other non-type flags are stuff like lower case and uppercase, which I view as a ridiculous feature :)

yeah agreed :+1: , are you planning to support `declare -i` at some point though? I think it's an interesting feature, even though I do not use it.

```sh
osh$ var g = 2
osh$ g+=1
osh$ echo "$g"
1                          <---- value overwritten without warning, a bit confusing
osh$ g+=1
osh$ echo "$g"
11
osh$
```

```sh
bash$ declare -i g=1
bash$ g+=1
bash$ echo "$g"
2
bash$ h=1
bash$ h+=1
bash$ echo "$h"
11
bash$
```

But I guess `setvar` fills the gap for this, pretty neat!

```sh
osh$ var g = 2
osh$ setvar g += 3
osh$ echo "$g"
5
```

**Comment by andychu** [comment]
Yes exactly, `var` has real integers on the right, so you can use `+=`.  There's no need for the equivalent of an `-i` flag!

These are different, like in Python/JS:

```
var x = '42'  # string
var y = 42  # integer
```

But you did find a bug -- recorded it here, thanks!

https://github.com/oilshell/oil/issues/840

Related to #815  .  I'd be interested in feedback on those rules at some point.  Basic idea:

- `+ -` and arithmetic will convert from string to integer if valid.  Will throw an exception if the string doesn't look like an integer.
- `<`, `>` only apply to numbers, not strings.  They never mean lexicographical ordering.  They will also convert.
- For equality, we don't convert with `==`.  However there is a special `~==` operator where `42 == '42.0'`, etc.

Maybe I should implement / document it first before we talk about it...  but that's the general idea.  It's a significant divergence from Python to get Awk-like functionality.  We don't require explicit conversions, but we also have explicit errors.
