### ISSUE TITLE
Efficient `popen` using `clone` trickery (or `posix_spawn`)

### ISSUE THREAD

**Issue by taktoa** [oilshell/oil#43]
Not sure how relevant this is to `oil`, but I figured it was worth pointing out.

[This article](https://blog.famzah.net/2009/11/20/a-much-faster-popen-and-system-implementation-for-linux/) describes a way to write `popen`/`system` in terms of `clone` + `execve`, which is more efficient than the typical implementation in terms of `fork` + `execve`. According to the comments, the `posix_spawn` function in `glibc` seems to be implemented this way, but apparently has API issues (e.g.: it supposedly doesn't allow you to close all open file handles).

EDIT: [this repo](https://github.com/famzah/popen-noshell) is made by the same person, and seems relevant

**Comment by andychu** [comment]
Hm interesting, I didn't know about this technique.  It's not really clear to me why it's faster though.

There are some other Linux kernel features I want to explore, like `vmsplice()`, but it will be probably be a long time before Oil acquires Linux-specific optimizations... like at least a year or two.  There is still a ton of work to minimize the Python VM dependency and so forth.

I plan to develop some end-to-end benchmarks of build processes and boot processes.  I expect the bottlenecks won't be in starting processes over and over again, although certainly there are some shell scripts that do such things.

Thanks for the info though.
