### ISSUE TITLE
Line is not deleted on failed readline completion

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#432]
Current behavior:
```
# press Ctrl-R
(failed reverse-i-search)`doesn't work': sudo vim /usr/bin/bats
# press left or right arrow key
(osh) ~/.../Programming/oil ▶️ sudo vim /usr/bin/batssr/bin/bats
```

Expected behavior:
```
# press Ctrl-R
(failed reverse-i-search)`doesn't work': sudo vim /usr/bin/bats
(osh) ~/.../Programming/oil ▶️ sudo vim /usr/bin/bats
```

**Comment by jyn514** [comment]
Bash does this too!!

**Comment by andychu** [comment]
OK yeah I see what you mean.  It seems to leave stuff on the prompt when you press arrow.

I guess you can hit Ctrl-U to clear the line.  Ctrl-C also cancels it and prints a new prompt.  So there are a few ways to back out and the arrow key apparently isn't one of them.

**Comment by lhoursquentin** [comment]
Pressing arrow up or down during Ctrl-r and showing another history line doesn't strike me as a bug.
Side note: the usual binding to abort a search (successful or not) is by pressing Ctrl-g and seems like osh handles it properly.

**Comment by jyn514** [comment]
@lhoursquentin  the issue isn't up and down, it's left and right. It leaves part of the completion on the line and makes it hard to read.

**Comment by lhoursquentin** [comment]
Ok understood thanks the clarification

**Comment by andychu** [comment]
Since we don't have any real control over this, I'm closing it.

I would like Oil to build with other line editing libraries.  I filed #185, but `libedit` like Python might be a better first step.
