### ISSUE TITLE
implement printf %d \'c to print the numeric value of char c

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#435]
Basically, `printf %d \'a` should print 97. It's a pretty obscure feature, but it's used in BF interpreters and such.

**Comment by andychu** [comment]
Wow that is a truly bizarre feature!  It took me awhile to find in POSIX.  All shells appear to implement it.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/printf.html#tag_20_94

> If the leading character is a single-quote or double-quote, the value shall be the numeric value in the underlying codeset of the character following the single-quote or double-quote

**Comment by Crestwave** [comment]
This should actually be pending-release, not closed, no?

**Comment by andychu** [comment]
Released with 0.7.pre6 : https://www.oilshell.org/release/0.7.pre6/
