### ISSUE TITLE
./install should respect $DESTDIR

### ISSUE THREAD

**Issue by drwilly** [oilshell/oil#456]
https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by andychu** [comment]
I think @timetoplatypus might have run into this for the Arch Linux package?

Maybe this is a good thing to add although I'm not sure of the details now.

> If your installation step would normally install /usr/local/bin/foo and /usr/local/lib/libfoo.a, then an installation invoked as in the example above would install /tmp/stage/usr/local/bin/foo and /tmp/stage/usr/local/lib/libfoo.a instead. 


Also, this might be related to #136 .

I thought the underlying cause of that is our weird "app bundle" system which I wanted to go away by now, but probably won't for awhile ... I will have to look in more detail.

**Comment by andychu** [comment]
from Zulip:

> but is it OK if the binary does NOT run in the temp dir??
> I don't see how it can work because under Unix paths are hard-coded.

@drwilly :

> nothing is ever run in that image area
> stuff just gets copied there and then either tared or moved to /

**Comment by andychu** [comment]
@drwilly  I consolidated usages of $DESTDIR as mentioned.  It should behave the same way still.  Let me know if it doesn't :)

https://github.com/oilshell/oil/commit/7e7c1496b2aa88b35db1893ee274450bd6b6add6

**Comment by andychu** [comment]
Or if you think it's ready for a release, let me know.  There are a few other changes that could also go out.

**Comment by drwilly** [comment]
```
#  tree /var/tmp/portage/app-shells/oil-0.7_pre3/image/
/var/tmp/portage/app-shells/oil-0.7_pre3/image/
└── usr
    ├── bin
    │   ├── oil.ovm
    │   ├── osh -> oil.ovm
    │   └── oshc -> oil.ovm
    └── share
        └── man
            └── man1
                └── osh.1.xz

5 directories, 4 files
```
looks good
