### ISSUE TITLE
./configure should warn about unknown arguments, but not die

### ISSUE THREAD

**Issue by drwilly** [oilshell/oil#457]
some rationale [here](https://www.gnu.org/prep/standards/html_node/Configuration.html), but the main reasoning is that in helps running configure from automated build-tools such as gentoo-portage.
Unknown arguments could also be silently ignored, but I guess a warning is a nice compromise.

**Comment by andychu** [comment]
OK as mentioned on Zulip, I'm convinced about  `--with-*` and `--enable-*` since the GNU standards mention it.

Not yet convinced about ALL flags.

> basically it fails during configure, because gentoo (by default) just throws all --host, --target, etc options at the configure script

Maybe we should add `--host` and `--target` then as explicit no-ops ?

**Comment by drwilly** [comment]
Actually adding the unused "standard" options as noops (or warns?) might be a good idea
