### ISSUE TITLE
Disambiguate between OpenSolaris Bourne shell "osh" vs. oilshell "osh"

### ISSUE THREAD

**Issue by mcandre** [oilshell/oil#46]
For backwards compatibility, ancient versions of the pre-bash, pre-POSIX Bourne shell, AKA the OpenSolaris Bourne shell, AKA "osh", is available on Linux systems today. The "osh" name for oilshell conflicts with this legacy shell, and so may confuse text editors and other systems. Would it be possible to select another name for the oilshell binary?

**Comment by andychu** [comment]
I didn't know about this shell, but if it's pre-POSIX, then I feel little need to defer to it.

If there are any other name conflicts as people start packaging Oil then I'll think about it, but right now this feels theoretical.

BTW the binary for Oil will be `oil` and `osh` is for the bash-compatible shell.  So if the project succeeds then the name conflict will go away over time :)
