### ISSUE TITLE
provide 'checked' wrapper for grep, test, etc.

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#474]
This is for pedantic error handling

```
checked-grep() {
  shopt -u errexit {  # Make sure it's not set
    grep "$@"  
  }
  local status=$?  # note: shopt with block should return with status of block
  eval "$saved"
  case $status in
    0|1) return $status ;;   # keep same exit code
    *) die "grep failed fatally" ;;    # die is a function which prints a message and calls `exit`
  esac
```

Based on Zulip conversation with Ilya Sher:

https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Overhauled.20errexit.20behavior

Portably:

```
  local saved=$(shopt -p -o errexit)
  grep "$@"  
  local status=$?
  eval "$saved"
```

**Comment by andychu** [comment]
example:

```
if checked grep foo $file {  # will fail FATALLY if file not found
  echo "found"
}
```

**Comment by drwilly** [comment]
> `grep` and `test` are the main useful examples I can think of.

Another example for you to consider:
```
set -C
if echo $$ >"$PIDFILE"
then # dispatcher starting
        trap "rm -f -- '$PIDFILE'" EXIT
        trap "rm -f -- '$PIDFILE'; trap -  INT EXIT; kill -s  INT $$"  INT
        trap "rm -f -- '$PIDFILE'; trap - QUIT EXIT; kill -s QUIT $$" QUIT
        trap "exit 0" HUP TERM
elif xargs <"$PIDFILE" kill -0
then # another dispatcher already running
        fatal "Dispatcher instance already running."
        exit 0 # exit success because all we care about is a running dispatcher
else
        die "Dispatcher failed to start"
fi
```
As you can probably tell, it's part of a POSIX pidfile/lock-code. Most notably here is the atomic file creation via `echo`+`noclobber` and the `kill -0`.

**Comment by andychu** [comment]
OK interesting I had never seen a "real" use of noclobber.  It isn't implemented in Oil, see test case 28 here:

https://www.oilshell.org/release/0.7.pre4/test/spec.wwz/redirect.html

I would love some help with this!  It should be a tiny change.  Let me file another bug for it.

**Comment by andychu** [comment]
Another example I just used:

```
if command -v objcopy; then 
  # ... do GNU toolchain stuff, skipped on OS X
fi
```

**Comment by andychu** [comment]
```
{ busybox || true; } | head
```

https://oilshell.zulipchat.com/#narrow/stream/202008-oil-documentation/topic/shell.20trivia.3A.20how.20to.20command.20sub.20retaining.20newline/near/194232742


or something like:

https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Things.20that.20surprised.20me.20about.20shell/near/194233364


```
no-sigpipe() {
  "$@"
  case $? in
    (141) return 0 ;;  # ignore sigpipe
    (*) return $? ;;
  esac
}

no-sigpipe busybox  | head -n 1
```

**Comment by andychu** [comment]
I think this is obviated by:

- `try --allow-status-01` to make code 2 a fatal error
- `shopt -s sigpipe_status_ok`
