### ISSUE TITLE
Turning off aliases  in Oil

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#482]
An idea that came out of this thread:

https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Space.20Sensitivity

This option is ON by default, unlike in bash:

```
shopt -s expand_aliases
```

However if you do `shopt -s all:oil`, then you get:

```
shopt -u expand_aliases
```

Or maybe you can just turn it off by default like bash???  It will have to be in each person's `.bashrc`.

I guess that would make Oil non-POSIX though?

----

Another issue: There is this weird set/unset inversion.

Although maybe we don't care about keeping consistency with bash's `expand_aliases`.  We can just all it `no_aliases`.

**Comment by andychu** [comment]
The alternative to this is that people should run:

```
osh -O all:oil -O all:nice -n foo.sh
```

manually to detect syntax errors.

**Comment by jyn514** [comment]
I would like `expand_aliases` to be off by default, but I know I'm the odd one out here. Could you explain again why aliases prevent static parsing? You mention it in https://github.com/oilshell/oil/issues/462#issuecomment-522068862 but I'm not quite sure why.

**Comment by andychu** [comment]
Static parsing means you can't execute anything to parse.  But `alias` is a builtin, which means the args including actual alias substitution requires substitution:

```
alias foo="echo I can $(echo do) anything here $((1+2*3))"
foo 8 9 10
```

output: `I can do anything here 7 8 9 10`

In other shells, you can do stuff like:

```
$ alias myfor=for
$ myfor x in 1 2 3; do echo $x; done
1
2
3
```

or even

```
$ alias myfor='for x in'
$ myfor 1 2 3; do echo $x; done
1
2
3
```

Those DEFINITELY require expanding the alias before parsing.  And expanding the alias implies execution of arbitrary code.  Which precludes the parser giving you good syntax errors instantly -- you would have to wait for an arbitrary program to execute, and that program might delete your hard disk, etc.

(OSH implements a more limited form of alias, but it's still very powerful.)

**Comment by andychu** [comment]
Here are the test cases it passes:

https://www.oilshell.org/release/0.7.pre4/test/spec.wwz/alias.html

This reminded me that alias expansion is defined to be recursive by POSIX.  (It's actually both recursive on word 1, and iterative on words 2,3,4 -- it's quite complicated.)

And OSH supports that.  So I'm pretty sure that even though OSH doesn't support the `for` loop example above (in which you MUST expand `for` to know how to parse it correctly), aliases in OSH also make parsing undecidable.  (i.e. you have to execute arbitrary code to parse)

**Comment by andychu** [comment]
Anyway bottom line is that I don't think it's too hard to turn off alias and statically parse Oil -- IF the parser is faster!

But the ASDL changes we're discussing right now will enable progress on that.  I'm pretty happy with these developments!

And yeah I could still turn off `expand_aliases` by default in OSH, because bash has it off.

I believe most Linux distros turn on `expand_aliases` in their system's `/etc/profile`.  But I guess OSH could force them to do the same thing.

All of these weird aliases are honestly corner cases.  Most files should be statically parseable even if you disregard aliases.  The most common case is something like

`alias ls=ls -l`

which isn't a problem at all.  So yeah maybe we should turn it off.

**Comment by andychu** [comment]
Hm I guess the argument for it being on is that it's POSIX ??

bash turns it on for `set -o posix`.  OSH doesn't have `set -o posix` right now.

https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html

**Comment by andychu** [comment]
Aliases are now off in Oil.  This enables parsing up front with `oil -n`.  (But we still do the line-by-line method during execution, which is OK)

**Comment by andychu** [comment]
https://www.oilshell.org/release/0.8.4/
