### ISSUE TITLE
CSP style asynchronous commands

### ISSUE THREAD

**Issue by suhr** [oilshell/oil#5]
It's so nice to see that *somebody*  **finally** designs and implements a proper shell! I absolutely must say that you're awesome and your work is great.

But this issue is not about that but some nice feature of [rc shell](http://man.cat-v.org/plan_9/1/rc):

> `<{command}`
> `>{command}`
> The command is executed asynchronously with its standard output or standard input connected to a pipe.  The value of the argument is the name of a file referring to the other end of the pipe.  This allows the construction of non-linear pipelines.  For example, the following runs two commands old and new and uses cmp to compare their outputs
> `cmp <{old} <{new}`

It works fine when used like `foo <{bar} >{baz}`, but when you try to assign `<{bar}` or `>{baz}` to variables to use later, problems occur. Also, rc provides no way to create a *bidirectional* stream.

So I wonder, if can shell have CSP-like streams? Like Go channels or Erlang processes. It would be a really nice feature to have, though I haven't figured out how exactly should it look like.

**Comment by andychu** [comment]
Hi, thanks for bringing this up.  Moving to reddit so other people can comment on it: https://www.reddit.com/r/oilshell/comments/5whyac/csp_style_asynchronous_commands_issue_5_github/
