### ISSUE TITLE
Put dev dependencies in Nix or Guix

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#513]
Would subsume #135 and #159 

* spec tests: bash/dash/mksh/zsh/busybox
  * and possibly smoosh
* static analysis
  * mypy binary 
  * mypy library for mycpp
  * maybe: pyannotate
  * pep8 to lint
* binary
  * re2c  
* doctools
  * CommonMark shared library (build dependency on CMake, gah)
* benchmarks
  * ocaml configure, etc.  This is just source though.
* C deps
  * libreadline-dev
  * python headers for bootstrapping
* shell deps
  * gawk, time
* big one: Clang for ASAN and other sanitizers (even though GCC has some)
  * Clang for coverage too

**Comment by andychu** [comment]
Or for portability:

https://github.com/phusion/holy-build-box

Or maybe rootless containers:

https://rootlesscontaine.rs/

I guess the difference is whether you have one libc or many libc's.

**Comment by andychu** [comment]
I'll accept any pull request that makes `build/dev.sh minimal` work in Guix or Nix (or some other system)!

All it does is build a Python extensions module against Python 2.7 headers.

**Comment by andychu** [comment]
crazy idea: re2c and CommonMark are "pure" filters and have no dependencies, so they could be compiled for WebAssembly.

And technically gawk and Clang too ...

We mostly use shells as filters, though I would want to test the "real" binary and not a custom build.

MyPy and pep8 need more of a "container" or package repo since they depend on CPython.

**Comment by ryanprior** [comment]
I've got a Guix package for osh here: https://github.com/ryanprior/guix-packages/blob/master/testing/osh.scm

It works, in that it builds, the smoke tests pass, and it installs and runs on my system. So that's neat!

With this file you can run `guix environment -l /path/to/osh.scm` to get a dev environment for osh. If you want a minimal build environment you can `guix environment --pure -l osh.scm` and that can tell you if you've added any sneaky dependencies that will mess up the build.

I'm interested in submitting this package upstream the next time you cut a stable-ish release. What do you think?

**Comment by ryanprior** [comment]
I'm also going to work on a manifest containing other things listed above in addition to the package deps. I'm not sure if there's a mechanism for distributing manifests but we could put it in this repo like the nix shell file.

**Comment by andychu** [comment]
Hm yeah I think #803 is a more realistic strategy

**Comment by ryanprior** [comment]
Do you have a list of all your dev dependencies? I can hopefully put together a Guix manifest that we can commit here and devs can load them all with one command.

**Comment by andychu** [comment]
Mateusz is working on something similar in Zulip, with Nix flakes:

https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Trying.20to.20write.20a.20Nix.20expression.20for.20oil.20tarball

That discussion has a lot of color; feel free to chime in.

Note that I think #803 is the right solution and doesn't involve Guix or Nix.  But I encourage these experiments because I would like to see how well Guix and Nix fit the problem

I think they only solve part of the problem.  The high level problem is "Make it easy for anyone to change Oil's code".  Like "reduce time to working and tested PR"

**Comment by andychu** [comment]
I removed the labels because there was already an experiment by @abathur that taught us a lot.

So while I encourage experiments in this area, I would have to be convinced it moves the project forward (i.e. makes it easy for people to contribute)

**Comment by andychu** [comment]
Looks like #803 is on the horizon
