### ISSUE TITLE
Add type annotations for the rest of the codebase

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#518]
`types/osh-parse travis` already checks the front end, which is several thousand lines of code. 

We want to check all of the codebase.  Adding annotations is semi-automated with pyannotate and `types/pyann_driver.py`

If anyone is interested in helping, let me know!  It will take some "setup" work and then I think it should go smoothly.  It may help other contributors get to know the codebase.

**Comment by HERBOD7** [comment]
@andychu I can do it.

**Comment by andychu** [comment]
OK great!  I used these scripts back in April to annotate the whole front end:

https://github.com/oilshell/oil/tree/master/types

I have to refresh my memory about how it works :)  We should start a wiki page about how to do it.  We can chat on https://oilshell.zulipchat.com/ about it.

My memory of the process is that it was pretty smooth with pyannotate.  There might have been a few refactorings it triggered, but I don't remember at the moment.

**Comment by andychu** [comment]
For anyone else following along, I expanded type checking coverage to `osh/glob_.py` and linked some example commits here:

https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Adding.20Type.20Annotations

**Comment by andychu** [comment]
`types/run.sh need-typechecking` shows our progress.  (files totalling 14,384 lines left to type check, which means we're more than 50% done)

**Comment by andychu** [comment]
This is on the critical path for #569 , making Oil fast and production quality.  Help is still appreciated!  Aaron has done a lot of work on this and both of us can help.

**Comment by andychu** [comment]
Mostly done except for `core/completion.py` and other such code

**Comment by andychu** [comment]
This is pretty much done, the remaining parts are not risky
