### ISSUE TITLE
Implement `test -v` and `test -k`

### ISSUE THREAD

**Issue by BatmanAoD** [oilshell/oil#537]
I discovered `test -v` isn't implemented, and couldn't find an existing issue for it.

Here's a table of the "primary expressions" that Bash's `test` supports:

http://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html#tab_07_01

Of the unary primary expresions (such as `-v VAR`), `-v` is the only one that prints an error saying that it isn't implemented, but `test -k foo` prints:

```
(test) Expected unary operator, got '-k' (2 args)
```

**Comment by andychu** [comment]
Did you encounter a script that uses these?  Or were you just testing?

All this stuff should be eventually implemented, but unless it adds something here [1] it wouldn't be at the top of my TODO list.

My strategy now is to make Oil faster / usable / desirable and hopefully users will be motivated to fill out all the corners :)  Patches are accepted :)

[1] https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

**Comment by BatmanAoD** [comment]
I have `-v` in [my personal config setup](https://github.com/BatmanAoD/public-config/blob/e2772da0123b3d6b63784aec67dde7274d8b1d90/bash_bootstrap#L10) (because [the alternative](https://stackoverflow.com/a/13864829/1858225) is ugly and confusing), but I'll remove it. I haven't yet encountered `-k`, but I thought it might be helpful to just run through the table quickly.

Keeping this low-priority is absolutely fine with me! I expect `-v` would be nearly trivial to implement, but I don't have a source check-out at the moment, just a release tarball.

**Comment by BatmanAoD** [comment]
In case you're interested, here are some other errors from trying to source my Bash setup: https://github.com/BatmanAoD/PublicPaste/blob/master/OshWithPubConfig.log

As you can see at the bottom, it fails to source most of my setup, so I'm sure there's quite a bit more that's missing.

**Comment by andychu** [comment]
OK thanks, that looks about what I'd expect.

* a bunch of shell options not implemented (sometimes we stub these out.  We could do that, although I'm not sure if that's the best havior)
* `${=1}` is actually a zsh thing, but OSH does static parsing and finds the invalid syntax!  It's possible we could special case that since I know git-completion is all over the place.
* I thought we had a stub for the `bind` builtin, but it's limited
* The extended globs only work in patten matching (`fnmatch`), not glob.  That one is actually a bit hard to change.

**Comment by BatmanAoD** [comment]
>     * The extended globs only work in patten matching (`fnmatch`), not glob.  That one is actually a bit hard to change.

That's unfortunate; that's probably the only feature of the ones listed that I would actually miss, because I use negative matching in my shell from time to time.

**Comment by andychu** [comment]
`test -k` and `test -v` will be out with the next release

@akinomyoga

**Comment by andychu** [comment]
Fixed: http://www.oilshell.org/blog/2020/03/release-0.8.pre3.html
