### ISSUE TITLE
implement compgen -A builtin

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#544]
Apparently this is used in homebrew. 

https://oilshell.zulipchat.com/#narrow/stream/119655-new-members/topic/Testing.20osh

This should be a simple issue for first-time contributors -- Please chat with me about it here or on Zulip :)

**Comment by viveknshah** [comment]
Hi @andychu where can I read up more on the expectations here?

**Comment by andychu** [comment]
Thanks for asking, I just checked and it looks like this is still unimplemented

Basically it should print out all the builtins that start with a certain prefix.  But I don't remember more than that at the moment.  I can look more a little later.

```
$ bash -c 'compgen -A builtin c'
caller
cd
command
compgen
complete
compopt
continue

$ osh -c 'compgen -A builtin c'
  compgen -A builtin c
  ^~~~~~~
[ -c flag ]:1: 'compgen' Invalid action name 'builtin'
andy@spring:~$ 

```

**Comment by andychu** [comment]
Like most of OSH, spec tests are important for implementing something like `compgen -A builtin`.

It might already be covered -- one thing I do is `grep compgen spec/*` -- i.e. just grep all the spec files for a certain string.

Resources on spec tests, feel free to ask questions:

https://github.com/oilshell/oil/wiki/Contributing

https://github.com/oilshell/oil/wiki/Spec-Tests

**Comment by andychu** [comment]
Released awhile ago
