### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by cup** [oilshell/oil#554]
I see no GitHub releases:

https://github.com/oilshell/oil/releases

or even Git tags:

https://github.com/oilshell/oil/tags

despite over 3,000 commits. Can this please be resolved? If you need some
guidance, please reference basically any popular Python repo, or frankly any
popular repo. Here are some examples:

- https://github.com/django/django
- https://github.com/jakubroztocil/httpie
- https://github.com/keras-team/keras
- https://github.com/pallets/flask
- https://github.com/ytdl-org/youtube-dl

**Comment by andychu** [comment]
The releases live here: http://www.oilshell.org/releases.html
