### ISSUE TITLE
Make Oil a native binary

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#569]
In other words, turn the `oil-native` release into `oil`.  This is a big task, here are some subtasks

 `libosh` tasks:

- [ ] Finish translating the rest of the interpreter
  - [x] with mycpp
  - [x] with custom translators
    - for `help` builtin, to synchronize with docs
- [ ] Rewrite all the I/O so it can be plugged into the translated interpreter
  - [ ] `native/posixmodule.c` -- `fork()`, `exec()`, `pipe()`, etc.
  - [ ] signal handling -- we won't have `KeyboardInterrupt`, etc
  - [ ] GNU readline binding -- `native/line_input.c`

Oil language:

- [ ] Generate C++ parse tables with pgen2 (#594)
- [ ] Glue `py_object_main` to the translated interpreter
- [ ] Hook up `yajl` to the native interpreter.  Won't need `py-yajl` anymore.  This is under the Oil language because OSH doesn't have recursive data structures!

Benefits of libosh alone:

- `shopt -s simple-word-eval`
- `errexit` fixes?  Still need to do that.  I've been going too "wide".
- pluggable history, completion, etc. if we can do that.  But I wanted Oil to be written in Oil, not C.  But it's probably worth doing.  It depends on how many people express interest.
- blocks: not done.  modules: not done.

bare minimum: shell I can use, with no library interface.  Runs existing scripts.

**Comment by david-a-wheeler** [comment]
I'm just an observer, but have you considered rewriting this in another language like Go for the long run?

Trying implement a Python compiler seems like a lot more work.

That said, there's no need to take this comment seriously. If the goal is to quickly prototype, please carry on. I think there's a lot interesting here!!

**Comment by andychu** [comment]
The mycpp translator wasn't too much work, although it's the most hacky part of the code for sure.  Demo here:

http://www.oilshell.org/blog/2019/12/09.html#oil-native-shows-how-well-optimize-oil

And I've made 2 or 3 more releases since then, so the code continues to work in both modes.  On every `/release/` page there's an `oil-native` tarball, which is just the parser.  But it's a pretty big program -- more than 10K lines of Python translated to C++. 

-----

Very related: you can't write a POSIX shell in portable Go because of it's threaded runtime:

https://lobste.rs/s/hj3np3/mvdan_sh_posix_shell_go#c_qszuer

http://www.oilshell.org/blog/2020/02/good-parts-sketch.html#the-alternative-shell-challenge

If you were willing to do a bunch of work for each platform, you might be able to do it, but personally I wouldn't want to go there.  Someone with Go expertise might be able to do it faster.

----

Oil could also be translated to other languages, as I write here:

http://www.oilshell.org/blog/2020/01/blog-roadmap.html#backup-plans

I think C++ is the best choice, but I'd like for others to pursue those options in parallel... It's definitely possible that someone with a different perspective / skill set could get it done faster!  Especially since a lot ot groundwork like the lexer and syntax tree will save a huge amount of time.

**Comment by andychu** [comment]
Subtask: #785 to deallocate memory

**Comment by andychu** [comment]
List of special cases, corresponding to:

- Python extensions that have to be rewritten 
- DSLs like pgen2
- unusual control flow like `yield` and signals`

------

- `pgen2` - #594 
- `py-yajl` - #838 
- `native/line_input.c` -- GNU readline
- the `yield` issue for completion

**Comment by andychu** [comment]
Related:

- #568 
- #1091

**Comment by andychu** [comment]
Done!  https://www.oilshell.org/blog/2024/03/release-0.21.0.html
