### ISSUE TITLE
sbp script doesn't work in oil

### ISSUE THREAD

**Issue by dflock** [oilshell/oil#572]
[Simple Bash Prompt (sbp)](https://github.com/brujoand/sbp) doesn't work in oil.

If you install sbp using the default setup, you get this in bash:

![Screenshot_2020-01-14_13-58-16](https://user-images.githubusercontent.com/47756/72386270-f3890a80-36d5-11ea-8e1e-e89316904e0d.png)

and this in oil:

![Screenshot_2020-01-14_13-55-44](https://user-images.githubusercontent.com/47756/72386198-d2281e80-36d5-11ea-9c69-1de9d02fba15.png)

the oil errors are:

```
  _sbp_set_prompt
  ^~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):1: '_sbp_set_prompt' not found
  _sbp_set_prompt
  ^~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):1: fatal: Exiting with status 127 (command in PID 28466)
```

This is hooked to `PROMPT_COMMAND`, with something like this in the `.bashrc`:

```sh
# Setup & run sbp
export sbp_path=~/bin/sbp
source "$sbp_path/sbp.bash"
PROMPT_COMMAND="_sbp_set_prompt"
```

This is with 0.7.pre11:

```
oil --version
Oil version 0.7.pre11
Release Date: 2020-01-11 05:21:38+00:00
Arch: x86_64
OS: Linux
Platform: #27~1576774585~18.04~c7868f8-Ubuntu SMP Thu Dec 19 20:37:47 UTC 
Compiler: GCC 7.4.0
Interpreter: OVM
Interpreter version: 2.7.13
Bytecode: bytecode-opy.zip
```

**Comment by andychu** [comment]
Thanks for trying it!

Did you copy those three lines into `~/.config/oil/oshrc` ?  

Oil doesn't source the `.bashrc` on purpose.  Also `bin/oil` sources `oilrc` while `bin/osh` sources `oshrc`.  I need to document that more.

Some docs here: https://www.oilshell.org/release/0.7.pre11/doc/osh-manual.html#startup-files

**Comment by andychu** [comment]
#498 is related (only `osh` respects `PROMPT_COMMAND` now, not `oil`, but you should still be able to test.)  Let me know what happens!

**Comment by dflock** [comment]
Ah, OK. I hadn't done anything about `~/.config/oil/oshrc` at that point, so I guess it was inheriting `PROMPT_COMMAND` from the bash shell I started it from, but not getting anything else.

If I put this into my newly created `~/.config/oil/oshrc`:

```
# Setup & run sbp
export sbp_path=~/bin/sbp
source "$sbp_path/sbp.bash"
PROMPT_COMMAND="_sbp_set_prompt"
```

I get this:

![Screenshot_2020-01-14_17-22-23](https://user-images.githubusercontent.com/47756/72396732-8041c180-36f2-11ea-9f3b-083c7b7202be.png)

the text of which is:

```
      command_ended=$(( SHELL_BIRTH + SECONDS ))
                                      ^~~~~~~
/home/dlock/bin/sbp/sbp.bash:56: warning: Undefined value in arithmetic context
      command_time=$(( command_ended - command_started ))
                                       ^~~~~~~~~~~~~~~
/home/dlock/bin/sbp/sbp.bash:58: warning: Invalid integer constant 'clear'

 
 ➜ 
```

**Comment by dflock** [comment]
Actually, these are the full list of errors you get from sbp when you start OSH:

```
/home/dlock/bin/sbp/functions/log.bash:13: 'export' doesn't accept flag -f
  export -f log_info
         ^~
/home/dlock/bin/sbp/functions/log.bash:14: 'export' doesn't accept flag -f
  SHELL_BIRTH=$(( $(date +'%s') - SECONDS ))
                                  ^~~~~~~
/home/dlock/bin/sbp/sbp.bash:21: warning: Undefined value in arithmetic context
  export -f _sbp_timer_start
         ^~
/home/dlock/bin/sbp/sbp.bash:35: 'export' doesn't accept flag -f
  export -f _sbp_timer_tick
         ^~
/home/dlock/bin/sbp/sbp.bash:36: 'export' doesn't accept flag -f
```

The ones above are the ones that appear the first time you rune `clear` after starting OSH - after that you stop seeing these errors and sbp _sort of_ works, with a mostly empty prompt:

![Screenshot_2020-01-14_17-35-41](https://user-images.githubusercontent.com/47756/72397316-643f1f80-36f4-11ea-8559-215dae08c20b.png)

**Comment by andychu** [comment]
Wow I haven't seen `export -f` anywhere before.  This is a bash misfeature that caused the famous  ShellShock bug 5 years ago:

https://en.wikipedia.org/wiki/Shellshock_(software_bug)

It looks like they changed it so that there's now a `BASH_FUNC_` prefix, which may make it safer. 

```
BASH_FUNC_foo%%=() {  echo hi
}
```

I feel like there is always a simple workaround for avoiding `export -f`, but I don't know how this script works.  Are you maintaining it or just a user?

----

And it looks like there's another issue with `$SECONDS` not implemented here.  That one makes sense for Oil.

**Comment by dflock** [comment]
> Are you maintaining it or just a user?

I'm mostly just a user, although I've submitted some patches for it in the past. It's maintained by @brujoand. I guess the workaround would be to `source` the file containing the functions wherever you need them, instead of using `export -f`?

**Comment by andychu** [comment]
Yes exactly, I intend to add an error message suggesting `source` !

**Comment by andychu** [comment]
OK I separated everything into other issues and fixed some, and labelled some for contributors.  (will be out with next release)

I think `sbp` is going to be a difficult in the near term, but it was a good test case and resulted in some improvements.  If you have time definitely send more bug reports like this :)
