### ISSUE TITLE
stub out shopt options (was 'shopt' got invalid option 'cdable_vars')

### ISSUE THREAD

**Issue by dflock** [oilshell/oil#574]
`shopt` doesn't appear to support `cdable_vars` option:

```
  shopt -s cdable_vars
  ^~~~~
/home/dlock/bash/bash_env.sh:79: 'shopt' got invalid option 'cdable_vars'
```

**Comment by andychu** [comment]
Are you using this functionality, or does it just happen to be in your `bash_env` ?  I'm not sure what this one does.

Generally Oil can run batch scripts unmodified, but interactive scripts require patching.  I will document that somewhere.

**Comment by andychu** [comment]
I started a wiki page about this.

https://github.com/oilshell/oil/wiki/What-Is-Expected-to-Run-Under-OSH

Other people have run their `.bashrc` and run into this long tail of `shopt` options.  It wasn't clear to me if they are used or copied around (which appears to be common.)

I've stubbed some of them out to remove the error, but I'm not sure if that's a good idea in general... I guess it will get people past some errors so it might be worth it.

Yeah all of these are no-ops so I could add to the list of no-ops.

https://github.com/oilshell/oil/blob/master/osh/state.py#L243

**Comment by dflock** [comment]
> Are you using this functionality, or does it just happen to be in your bash_env ? I'm not sure what this one does.

I am using it, yes. It lets to `cd` to any variable that contains a path. I use it like this:

```sh
#
# Allow directory variables
#
shopt -s cdable_vars
export work="/home/duncan/Documents/work/"
# etc...
```

You can then say `cd work` from anywhere and it'll take you to "/home/duncan/Documents/work/", like a shortcut. I only use this with statically defined vars as above, and I only have eight setup on this machine.

**Comment by dflock** [comment]
> Other people have run their .bashrc and run into this long tail of shopt options. It wasn't clear to me if they are used or copied around (which appears to be common.)

I think 95% of bashrc files are copied from somewhere, some of that's going to be cargo-culting, but hard to say how much.

**Comment by andychu** [comment]
OK thanks for the explanation.  I filed #578 to keep track of that.

I'm going to stub them all out for the next release, but keep track of the ones that people actually use.  So if there are any others you use please file a bug about it.

I'm going to mark the others as dupes of this but if you use it feel free to reopen.

**Comment by andychu** [comment]
Released with https://www.oilshell.org/release/0.7.0/
