### ISSUE TITLE
 'shopt' got invalid option 'autocd'

### ISSUE THREAD

**Issue by dflock** [oilshell/oil#575]
`shopt` doesn't appear to support `autocd` option:

```
  shopt -s autocd
  ^~~~~
/home/dlock/bash/bash_env.sh:79: 'shopt' got invalid option 'autocd'
```

**Comment by andychu** [comment]
I will stub this out to remove the error per #574 , but if you use it please reopen

**Comment by dflock** [comment]
I'm not actually using this any more, so I'm going to remove it from my env. For reference:

```sh
# typing the foldername cd's into it.
shopt -s autocd
```

So, this means that instead of typing `cd ..` you can just type `..`
