### ISSUE TITLE
Run rustup

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#577]
https://rustup.rs/

It looks like everyone gets their Rust toolchain this way and it has a bunch of shell. 

Might be interesting to trace what it's doing as well.

----

I'd be interested to know if any part of it runs and if not, what the error message is!

**Comment by jyn514** [comment]
Just tried this out with 0.7pre11, rustup works great :)

**Comment by andychu** [comment]
Thanks for trying it!  After inspecting it, it does look like 435 lines of reasonable bash.

One thing I think would be cool is to run a lot of these `curl | sh` installers under a special OSH trace mode... and publish the results to see what they are doing.

You can sort of do it with `curl | sh -x` but it's not that friendly.

**Comment by jyn514** [comment]
What would you have instead of `sh -x`? At the end of the day shells run lot of code, I'm not sure there's a way to make that prettier...

**Comment by andychu** [comment]
I'd say I have two "levels of ambition"

1. At the very least `sh -x` should print the commands in an unambiguous format that you can parse.  It's related to #582 which I can explain a bit more if interested.

A really simple query would be like: "what are all the external tools  this runs" (as opposed to builtins).  I feel like you should be able to postprocess the `sh -x` output to answer that.  And it's mildly interesting from a security POV.

"What are all the files it opens" is a related question which is a bit harder to answer.


2. It would be nice to provide some other scripts to make a big report from a trace.  Maybe something like:

https://www.phoronix.com/scan.php?page=article&item=ubuntu_boot_perf&num=2

I'm not sure how interesting it would be for `curl | sh` installers.  But I definitely have big shell scripts for builds and data pipelines that start hundreds of processes.

Oil already have some extra debugging features that I'd like to document and expose, like `--debug-file`  and so forth.

**Comment by andychu** [comment]
I think a lot of people are doing this kind of stuff with kernel tracing and eBPF these days.  The kernel is in a better position to trace processes, since it has to start thema ll.  But that's Linux only... and maybe we can do some similar stuff in user space.  It's mostly an idle though...

I think the first step is to make a better interface than `$PS4` for the trace prefix string.

That's analogous to #498, which is to do something better than `$PS1` for the prompt.

**Comment by jyn514** [comment]
I think this can be closed in favor of https://github.com/oilshell/oil/issues/583.

**Comment by andychu** [comment]
Yup makes sense
