### ISSUE TITLE
Support declare for checking for function definition

### ISSUE THREAD

**Issue by travisbhartwell** [oilshell/oil#59]
I use the following bashism to determine if a function I need from a dynamically sourced script is available:

```
    if ! declare -f choose_env > /dev/null; then
        echo "Must have choose_env defined"
        return 1
    fi
```

However, when I try to run a script that uses this idiom with the 0.3 release, I get the following error:

```
Unexpected error in execvpe('declare', ['declare', '-f', 'choose_env'], ...): [Errno 2] No such file or directory
```

It looks like osh doesn't recognize declare as a built-in.

**Comment by andychu** [comment]
Thanks, I think this should be pretty easy, and I should be able to get it for the next release!

**Comment by travisbhartwell** [comment]
Looking through code I've written recently, I've also seen the following uses of declare:

1. Declaring a variable as an array, with or without setting the value:

```
# filenames is an array
declare -a filenames
# foo is an array with one element, b
declare -a foo=( b )
```

2. Declaring a variable read-only and an array:

```
declare -ar foo=( b )
```

3. Declare a string as only upper case or only lower case:
```
declare -u upper_region_name="${region}"
declare -l lower_region_name="${region}"
```

Related, I've used `local` and `readonly` similarly:

```
function() {
    local src="$1"
    local -r read_only_src="$2"
}

# Read only file-level variable
readonly MY_EMAIL=foo@bar.com

# Only set ENV_NAME if it isn't already
: "${ENV_NAME:='MyEnvironment'}"
# Make it read-only
readonly ENV_NAME
```

**Comment by andychu** [comment]
Hi Travis, I'm starting to look at this now.  Just curious what you use `-u` and `-l` for?

It shouldn't be hard to implement them.  I'm a little wary about checking extra flags on every assignment, since it could more or less be written:

   $ foo=xyz
   $ foo=${foo^^}
   $ echo $foo
   XYZ

**Comment by travisbhartwell** [comment]
No, no reason they are preferable. I didn't know about case modification as part of parameter expansion. I can't remember where I saw the flag. These are not variables that are set more than once, so making the variable always be upper or lower aren't requirements, I can use the parameter expansion versions instead.

**Comment by andychu** [comment]
OK great thanks for letting me know!  I landed these changes on the master branch.  If you want to try it on your code, you can clone and make a "dev build", which should take 30 seconds if you have an Ubuntu machine:

https://github.com/oilshell/oil/wiki/Contributing

It's somewhat dependent on the environment, there are few dependencies.

Still aiming for a 0.4 release by the end of the month, maybe early next month.  I've been working on `trap` as well.

**Comment by andychu** [comment]
0.4.alpha1 release is here: http://www.oilshell.org/releases.html

I'm closing this for now -- please test and reopen if there are issues :)
