### ISSUE TITLE
Run bocker (docker in bash)

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#596]
This script seems to use a whole bunch of bash features

https://news.ycombinator.com/item?id=22244706

**Comment by glyh** [comment]
This software is not maintained, when I run it with bash with no args, it bump into errors:
```
./bocker: line 116: $1: unbound variable
```
I guess it would not be a good test suite.

**Comment by andychu** [comment]
Yeah I actually dug this up and mentioned it here recently.


https://oilshell.zulipchat.com/#narrow/stream/266575-blog-ideas/topic/Rant.3A.20User.20Space.20Container.20Tools.20Are.20Designed.20Poorly

While I think we could get it to run, I have a lot of other things to do around containers, and am less interested in this now

Thanks for looking at it!
