### ISSUE TITLE
Contributing uses ssh git url

### ISSUE THREAD

**Issue by yumaikas** [oilshell/oil#6]
Right now the contributing doc uses the ssh git URL instead of the https URL. Is this done for any particular reason? I had trouble pulling due to public key permissions, but could pull using the https URL.

**Comment by andychu** [comment]
No reason!  You can change it on the Wiki.  Feel free to add any notes there as you encounter them.

As you see from the mailing list there is sort of an unresolved versioning issue... I have to think about that.

**Comment by yumaikas** [comment]
Done. I'll take further notes on a page that tracks what osh depends on.
