### ISSUE TITLE
bash allows [[ x =~ (regex with space) ]] but Oil doesn't

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#606]
I think it special cases `()` and `[]` pairs and allows spaces within them.

Examples here:

https://gist.github.com/floam/f535842a16226e77d014d67bade2b2f3#file-bashrc_apple_terminal-L172

 @abathur reported this

https://www.oilshell.org/release/0.7.0/test/wild.wwz/osh-to-oil.html#esoteric/make-a-lisp-bash/reader.sh

https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/regex.20parse.20failure.20(Circular.20namerefs)

**Comment by andychu** [comment]
As mentioned in the Zulip thread, bash doesn't even like its own rules, and suggests the alternative

```
pat='(regex with space)'
[[ x =~ $pat ]]
```


in the manual:

https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html#Conditional-Constructs

But if a lot of people run into this, it's probably possible to implement with lexer modes.

In fact I reserved the `lex_mode_e.BashRegexChars` mode to handle this.  It's currently unused / undefined

https://github.com/oilshell/oil/blob/master/frontend/types.asdl#L19

**Comment by andychu** [comment]
https://github.com/drwetter/testssl.sh which is a 21K line shell script uses this.

```
$ time osh -n testssl.sh |wc -l                                                                                                                                                                                
       if [[ "$(head -1 "$FNAME")" =~ ( -oG )(.*) ]] || [[ "$(head -1 "$FNAME")" =~ ( -oA )(.*) ]] ; then
                                        ^~~
testssl.sh:20062: Expected ]]

```

(Although I would say the workaround is trivial -- extract a var -- so I'm not sure how high priority this is)

**Comment by abathur** [comment]
I ran into what looks like [another instance](https://github.com/TheLocehiliosan/yadm/blame/master/yadm#L1313) of this (in the fairly-popular yadm dotfile manager):

```
$ osh -n $(type -p yadm)
Wed Apr 01 2020 13:21:46 --> 
    [[ "$1" =~ (\/\.|\.\.|[~^:\\ ]|\/$|\.lock$) ]] && return 1
                                 ^
/nix/store/w7c2238hda8piw4k68vlwlkjsc1m3lf4-yadm-2.4.0/bin/yadm:1313: Expected ]]
```

**Comment by andychu** [comment]
Yup that is it, thanks for the report.  I hope to convince people to apply the trivial workaround by making Oil in better respects, but it's also possible to implement, if annoying...

**Comment by abathur** [comment]
I haven't quite decided how to handle this specific case, but I'll try to remember to link here or otherwise let you know if I try to push for an upstream change, so you can see how the convincing goes :)

**Comment by abathur** [comment]
@pedrohlc [found](https://github.com/NixOS/nixpkgs/pull/173885/files#r879843589) another instance of this (https://github.com/v1s1t0r1sh3r3/airgeddon/blob/c58bb8f086ab47cf918399f019bd502dbd430b76/airgeddon.sh#L13062). Not sure if I'll pursue upstream yet.

**Comment by andychu** [comment]
Done!    https://www.oilshell.org/blog/2024/06/release-0.22.0.html
