### ISSUE TITLE
failed command lookups in core/process_test.py

### ISSUE THREAD

**Issue by abathur** [oilshell/oil#621]
The first 20 lines of output from core/process_test.py have a number of command lookup failures:
```
.  uniq -c
  ^~~~
process_test.py:1: 'uniq' not found
pipe_status: [-1, -1, -1, 127]
.  head
  ^~~~
process_test.py:1: 'head' not found
  cat
  ^~~
process_test.py:1: 'cat' not found
  ls
  ^~
process_test.py:1: 'ls' not found
  head
  ^~~~
process_test.py:1: 'head' not found
  sort --reverse
  ^~~~
process_test.py:1: 'sort' not found
EEEdate returned 0
```

I suspect that the actual failures are coming from the `_CommandNode()` invocations in `testPipeline` and `testPipeline2`.

**Comment by andychu** [comment]
Triaging old issues -- I think this was probably a PATH issue that was resolved?  If not please re-open!
