### ISSUE TITLE
Quoting of associative array subscripts in assignments (ble.sh)

### ISSUE THREAD

**Issue by akinomyoga** [oilshell/oil#646]
Oil requires the quoting of the associative array subscripts in left hand side of assignments but doesn't require it in the keys of the designated initializer. Is there rationale on this behavior? I feel it is natural not to require quoting also in assignments.

```console
$ bin/osh -c 'declare -A d; d[a]=123'
  declare -A d; d[a]=123
                ^~
[ -c flag ]:1: fatal: Associative array keys must be strings: $x 'x' "$x" etc.
$ bin/osh -c 'declare -A d=([a]=123)'
$
```

Note that Zsh also behaves differently from Bash here. Zsh accepts quoteless subscripts in assignments like Bash, but it doesn't remove `""` in the subscripts in assignments.

```console
$ zsh -c 'declare -A d; d[a]=1; declare -p d'
typeset -A d=( [a]=1 )
$ zsh -c 'declare -A d=([a]=1); declare -p d'
typeset -A d=( [a]=1 )
$ zsh -c 'declare -A d; d["a"]=1; declare -p d'
typeset -A d=( ['"a"']=1 )
$ zsh -c 'declare -A d=(["a"]=1); declare -p d'
typeset -A d=( [a]=1 )
```

**Comment by andychu** [comment]
Yes this is intentional behavior:

https://www.oilshell.org/release/0.8.pre2/doc/known-differences.html#strings-vs-bare-words-in-array-indices

http://www.oilshell.org/blog/2016/10/20.html
