### ISSUE TITLE
Implement printf %*s and %.*s

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#650]
This basically uses the first argument as a replacement for the asterisk, i.e. `printf '%*s' 10 foo` should be equivalent to `printf %10s foo` and `printf '%.*s' 2 bar` should be equivalent to `printf '%.2s' bar`.

**Comment by andychu** [comment]
OK interesting, which programs use it?  That will help prioritize things, e.g. we want to fill out more of:

https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

**Comment by Crestwave** [comment]
Well, um, it *was* used in `pfetch`, but I found out that it wasn't POSIX and reported it so now it doesn't. I also use it in `shmenu` and it's also used in `fff`, though.

**Comment by andychu** [comment]
#653 also mentioned `printf %()T` and these could be tackled together

**Comment by andychu** [comment]
https://github.com/oilshell/oil/commit/cde3f101b05134e03d9e65ec57b58ff3bee159af

**Comment by andychu** [comment]
Fixed: http://www.oilshell.org/blog/2020/03/release-0.8.pre3.html
