### ISSUE TITLE
cell sublanguage: unset -v 'a[0]' (ble.sh)

### ISSUE THREAD

**Issue by akinomyoga** [oilshell/oil#651]
I use this construct in ble.sh. I could find some test case for this [here](https://github.com/oilshell/oil/blob/06d659783438aaf3a50217409d008387a2f41a27/spec/builtin-vars.test.sh#L379) and also some mentions on `unset a[0]` [here](https://github.com/oilshell/oil/issues/208#issuecomment-435786735), but it doesn't work with the current Oil. Is this a regression?

```console
$ bin/osh -c 'a=(x y z); unset "a[1]"'
  a=(x y z); unset "a[1]"
                   ^
[ -c flag ]:1: 'unset' got invalid variable name 'a[1]'
[ble: exit 2]
$ bin/osh -c "a=(x y z); unset 'a[1]'"
  a=(x y z); unset 'a[1]'
                   ^
[ -c flag ]:1: 'unset' got invalid variable name 'a[1]'
$
```

**Comment by andychu** [comment]
OK we may need to do dynamic parsing of `a[const]` within several constructs:

- `unset`
- `${!ref}`
- `declare -n` (nameref)

And maybe a few other places... @abathur also used this with `-n`.

It will parse `a[const]` but not `a[1+2]` since the latter would parse arbitrary code.

**Comment by andychu** [comment]
#608 is the feature for nameref

**Comment by andychu** [comment]
note: marked with two stars on #653

**Comment by andychu** [comment]
May relate to IR in #604 ,  e.g. `sh_lhs_expr`

**Comment by andychu** [comment]
@akinomyoga   Another thing I wanted to ask is if you're using only indexed arrays for

`unset -v a[0]`

Or if you're also using associative arrays?  The latter is trickier

```
$ declare -A A=(['foo']=bar)
$ echo ${A[@]}
bar
$ unset -v "A['foo']"
-bash: unset: A['foo']: bad array subscript

$ unset -v "A[foo]"
$ echo ${A[@]}
(empty)
```

It doesn't like the quotes, and prefers bare word syntax, which is inconsistent with the rest of Oil (and bash to some extent)

**Comment by akinomyoga** [comment]
Thank you.

> Another thing I wanted to ask is if you're using only indexed arrays

Yes, I searched in ble.sh source and it seems unset is currently only used for indexed arrays. But that's not intentional and I'm not sure if I will never use it forever. And, it is a little bit awkward that there is no means to remove a key from associative arrays.

> It doesn't like the quotes,

Which version of Bash do you use? I tried with versions of Bash and found that the behavior was changed since 4.4. I think it was a bug of Bash.

```bash
$ bash --norc # bash-4.4 or 5.0
$ declare -A A=(['foo']=bar)
$ declare -p A
declare -A A=([foo]="bar" )
$ unset -v "A['foo']"
$ declare -p A
declare -A A=()
```

The safe way for unsetting an associative array element in Bash that should work with an arbitrary key is the following. I think Oil can support this form.

```bash
$ declare -A d
$ key="a]b'c[d"   # A key containing special characters
$ unset -v 'd[$key]'
```

**Comment by andychu** [comment]
OK yes, I was testing on my machine which is bash 4.3.  I did it through the spec tests and bash behaves consistently with associatve arrays for `unset -v`, `declare -n`, and `${!ref}` ( see the last 3 test cases in commit above).

So I think we can probably do it, though I might start with just `a[0]` and see what we can get to run first.

**Comment by andychu** [comment]
OK this can be tested from master... Looking at #640 now (which is different than #648 in Oil)
