### ISSUE TITLE
set -o vi and emacs should be have differently while interactive

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#659]
```
$ bash   --rcfile /dev/null -i -c ' test -o emacs; echo $?; test -o vi; echo $?'
0
1
andy@lisa:~/git/oilshell/oil$ bin/osh --rcfile /dev/null -i -c ' test -o emacs; echo $?; test -o vi; echo $?'
1
1
```

> By the way, the line-editing can be turned off in interactive sessions of Bash. The setting is set +o emacs. This is the reason why set +o emacs doesn't imply set -o vi in Bash unlike in Oil.

**Comment by andychu** [comment]
From #653

**Comment by andychu** [comment]
@akinomyoga I made it behave more like bash, passing a test with `-i`,  but I didn't do a lot more testing.

I think the problem is that GNU readline has some state, and bash has some state, and they have to be synchronized.  But there is not a great way of testing GNU readline state in batch mode, as far as I know...

**Comment by akinomyoga** [comment]
Thank you! I have tested. I removed a workaround from `ble.sh/osh` branch for this.

> FWIW: I learned that mksh has set -o emacs on both 

Oh, really. I haven't tried `ble.sh` on other shells, so I didn't know that.

**Comment by andychu** [comment]
Fixed: http://www.oilshell.org/blog/2020/03/release-0.8.pre3.html
