### ISSUE TITLE
error message for $(( a )) doesn't have location

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#664]
### 14.2 Empty variables in arithmetic expressions

The second most type of warnings is this.

```console
$ osh -c 'a=; echo $((a))'
[??? no location ???] warning: Invalid integer constant ''
```

_Originally posted by @akinomyoga in https://github.com/oilshell/oil/issues/653#issuecomment-599177874_

**Comment by andychu** [comment]
BTW this behavior could be relaxed,  e.g. hidden behind `shopt -s strict_arith`.  It depends how many programs are broken by it.

But it is probably better to get through the high priority (double star) issues on #653 before working on that.

**Comment by andychu** [comment]
After fixing the location.  I think the EXIT and RETURN need to be turned into associative arrays, not indexed arrays?

```
$ ~/git/oilshell/oil/bin/osh -O parse_unimplemented
[osh] lisa ~/git/wild/ble.sh$ source out/ble.osh
    ((!fail))
       ^~~~
out/ble.osh:224: warning: Invalid integer constant ''
    ((!fail))
       ^~~~
out/ble.osh:224: warning: Invalid integer constant ''
      _ble_builtin_trap_signames[index]=$name
                                 ^
[ array LValue in out/ble.osh ]:1833: warning: Invalid integer constant 'EXIT'
      _ble_builtin_trap_signames[index]=$name
                                 ^
[ array LValue in out/ble.osh ]:1833: warning: Invalid integer constant 'RETURN'
      builtin printf -v ret '%d' "'${1:$2:1}"
                                       ^~
out/ble.osh:4619: warning: Invalid integer constant ''
      builtin printf -v ret '%d' "'${1:$2:1}"
                                       ^~
out/ble.osh:4619: warning: Invalid integer constant ''
      builtin printf -v ret '%d' "'${1:$2:1}"
                                       ^~
out/ble.osh:4619: warning: Invalid integer constant ''
      builtin printf -v ret '%d' "'${1:$2:1}"
                                       ^~
out/ble.osh:4619: warning: Invalid integer constant ''

```

**Comment by akinomyoga** [comment]
> After fixing the location. I think the EXIT and RETURN need to be turned into associative arrays, not indexed arrays?

Thank you for the report! But `EXIT` and `RETURN` must not appear here in original `ble.sh`. It seems there are some problems in upstream of the code, which causes the wrong values of `$index`.

Ah, this is caused by the format difference of `trap -l` between Bash and Oil. Looking at Oil `trap -l` outputs, `ble.sh` considers `EXIT` to be the number of `ERR` and `RETURN` to be the number of `DEBUG`.

```bash
bash$ builtin trap -l
 1) SIGHUP       2) SIGINT       3) SIGQUIT      4) SIGILL       5) SIGTRAP
 6) SIGABRT      7) SIGBUS       8) SIGFPE       9) SIGKILL     10) SIGUSR1
11) SIGSEGV     12) SIGUSR2     13) SIGPIPE     14) SIGALRM     15) SIGTERM
(snip)

osh$ builtin trap -l
   EXIT
   ERR
   RETURN
   DEBUG
 1 HUP
 2 INT
 3 QUIT
(snip)
```

**Comment by andychu** [comment]
Fixed: http://www.oilshell.org/blog/2020/03/release-0.8.pre3.html
