### ISSUE TITLE
${@:0:1} evaluates to ${@:0}

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#688]
```bash
osh$ set a b c
osh$ echo "${@:0:1}"
osh a b c
osh$ echo "${@:0:2}"
osh a
```

```bash
$ set a b c
$ echo "${@:0:1}"
bash
$ echo "${@:0:2}"
bash a
```

This was found while toying around, not from a real script. I was testing if `${@::1}` would return `$1` or `$0`, as the Bash manual says "Substring indexing is zero-based unless the positional parameters are used, in which case the indexing starts at 1 by default." but `${@::1}` evaluates to `$0`, anyway. :/

**Comment by andychu** [comment]
Good catch, thanks for testing!  I fixed this and simplified the code a bit.
