### ISSUE TITLE
"${#:+\e}" should evaluate to \e, not e

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#695]
Required for #679. I haven't checked any manuals, but I think that backslashes in quoted + parameter expansion should only be interpreted if preceding a special character.

```bash
$ echo "${#:+\$}"
$
$ echo "${#:+\e}"
\e
```

```
osh$ echo "${#:+\$}"
$
osh$ echo "${#:+\e}"
e
```

**Comment by andychu** [comment]
Thanks, great catch!  All shells appear to agree on this except yash: the special character within double quotes are `$ " backtick \`.
