### ISSUE TITLE
${!1:-foo} fails with no positional parameters instead of substituting for foo

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#697]
Required for #679. This is pretty weird, though, as it fails if it is set to an empty string or with an unset variable; perhaps Neofetch should be patched instead.

```bash
$ echo "${!1:-foo}"
foo
```

```bash
osh$ echo "${!1:-foo}"
  echo "${!1:-foo}"
           ^
[ interactive ]:1: fatal: Bad indirect expansion: ''
````

**Comment by andychu** [comment]
Yeah I remember thinking about this case when implementing `${!ref}` recently... it is possible to emulate bash but it seemed like it could also catch programming errors.

The issue is that `''` is not a valid variable name, but bash has a "silent" default for that...

**Comment by Crestwave** [comment]
Dylan has agreed to fix this on their end. I'll leave it up to you whether to close this issue or not

**Comment by andychu** [comment]
Encountered here too https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/assertion.20error.2C.20maybe.20missing.20token.2Fpart.20tag.3F

**Comment by andychu** [comment]
Hm this got fixed at some point

```
$ osh -c 'echo ${!1:-foo}'
foo
```

(although I think there is still a related bug with confusing it with history substitution in interactive shells)
