### ISSUE TITLE
1 ? (a=42) : b shouldn't require parentheses

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#727]
Yeah according to the precedence table, `?` is higher precedence than `=`.  But it also has this footnote:

https://en.cppreference.com/w/c/language/operator_precedence

>  The expression in the middle of the conditional operator (between ? and :) is parsed as if parenthesized: its precedence relative to ?: is ignored.

Shell specifies that its arithmetic is identical to C arithmetic, so I guess this is a bug.

So I am not sure right now how to fix this using the TDOP parsing algorithm, but it can probably be done.  It sounds like it's a special case in C, which was originally done with the shunting yard algorithm... not sure if that matters or not.

_Originally posted by @andychu in https://github.com/oilshell/oil/issues/712#issuecomment-617933002_

**Comment by andychu** [comment]
@akinomyoga I fixed this :)

**Comment by akinomyoga** [comment]
Oh, instantaneous fix! Thank you!

**Comment by andychu** [comment]
Released: http://www.oilshell.org/blog/2020/05/translation-progress.html
