### ISSUE TITLE
build/dev.sh {minimal,all} cannot work due `posix_.so` not existing yet

### ISSUE THREAD

**Issue by o11c** [oilshell/oil#742]
For `minimal`, this can be avoided by running `build/dev.sh posix_` first, but there is no workaround for `all`.

Specifically:

* `all` and `minimal` call `_minimal`
*  `_minimal` calls `build/codegen.sh arg-mypy-gen`
* `arg-mypy-gen` calls `frontend/arg_gen.py`
* `frontend/arg_gen.py` fails during imports with the following traceback:

```
Traceback (most recent call last):
  File "frontend/arg_gen.py", line 11, in <module>
    from frontend import arg_def
  File "/home/ben/src/oil/frontend/arg_def.py", line 12, in <module>
    from frontend import args
  File "/home/ben/src/oil/frontend/args.py", line 66, in <module>
    from core.pyutil import e_usage
  File "/home/ben/src/oil/core/pyutil.py", line 10, in <module>
    from pylib import os_path
  File "/home/ben/src/oil/pylib/os_path.py", line 5, in <module>
    import posix_ as posix
ImportError: No module named posix_
```

Methinks you have too many paths through the build system.

**Comment by andychu** [comment]
Sorry master was broken.  That was apparent from the continuous builds since this morning.  It should be fixed now.

http://travis-ci.oilshell.org/jobs/

https://travis-ci.org/github/oilshell/oil/builds

At some point we should switch to pre-merge C-I so this doesn't happen... I will try to keep things more green.

**Comment by andychu** [comment]
The build is green now: http://travis-ci.oilshell.org/jobs/

(`dev-all-nix` is expected to fail, that could be disabled if nobody is interested in running Nix, which doesn't quite work yet)

It's green here which means the overall build is green.  Our own dashboard just gives more fine-grained details and logs.

https://travis-ci.org/github/oilshell/oil/builds
