### ISSUE TITLE
Support \D{} in PS1 and PS0

### ISSUE THREAD

**Issue by o11c** [oilshell/oil#748]
I use the following to keep track of when commands started and finished:

```
PS0='vvv \D{%F %T%z}\n'
PS1='^^^ \D{%F %T%z}\n'"$PS1"
```

**Comment by andychu** [comment]
Similar to #962

**Comment by andychu** [comment]
Released! https://www.oilshell.org/blog/2021/11/release-0.9.4.html

Thanks for the testing and feedback!
