### ISSUE TITLE
Unsetting the last element of an array and appending an element behaves differently than bash

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#768]
```bash
osh$ shopt -s eval_unsafe_arith
osh$ a=(0 1 2)
osh$ unset a[-1]
osh$ a+=(2)
osh$ declare -p a
declare -a a=(); a[0]=0 a[1]=1 a[3]=2
```

```bash
$ a=(0 1 2)
$ unset a[-1]
$ a+=(2)
$ declare -p a
declare -a a=([0]="0" [1]="1" [2]="2")
```

**Comment by andychu** [comment]
Ah yes good point!  This should be an easy  fix ...

**Comment by Crestwave** [comment]
Does `mksh` really behave differently here? I mean, sure, it interprets negative elements differently (from 4294967295 to be exact), but the base behavior is the same:

```sh
$ a=(0 1 2 3 4 5)
$ echo "${#a[@]}"
6
$ unset a[0]
$ echo "${#a[@]}"                                                              
5
$ a+=(6)
$ typeset -p a
set -A a
typeset a[1]=1
typeset a[2]=2
typeset a[3]=3
typeset a[4]=4
typeset a[5]=5
typeset a[6]=6
$ unset a[6]
$ a+=(6)                                                                       
$ typeset -p a                                                                 
set -A a
typeset a[1]=1
typeset a[2]=2
typeset a[3]=3
typeset a[4]=4
typeset a[5]=5
typeset a[6]=6
```

Also, it's cool that more of these pure Bash type of programs are being run; what JSON parser are you referring to? [`nosj`](https://github.com/dylanaraps/nosj) still doesn't run;  let me know if you want me to report the issues.

**Comment by andychu** [comment]
Oh maybe all the test differences are that mksh doesn't support `a[-1]` but also doesn't give an error?

https://github.com/oilshell/oil/blob/master/spec/array.test.sh#L111

If you can narrow down the bug with `nosj`, I would appreciate it!  Finding the root cause definitely helps a lot.

I have 2 JSON parsers here:

https://www.oilshell.org/release/0.8.pre5/test/wild.wwz/esoteric/index.html

- JSON.sh already ran as of the last release
- j doesn't run, I think because Oil doesn't respect `LANG=C` and always uses utf-8.

**Comment by Crestwave** [comment]
Well, technically `mksh` does seem to support `a[-1]`—which is why it doesn't throw an error—but as I mentioned, it starts from the actual end of the array that is allotted (`2**32-1`):

```sh
$ a[-1]=foo
$ typeset -p a
set -A a
typeset a[4294967295]=foo
$ a[4294967296]=bar
$ typeset -p a
set -A a
typeset a[0]=bar
typeset a[4294967295]=foo
```

But yes, that's what's causing the test differences.

I've already gotten `nosj` to run with a patch; pretty minor overall: https://github.com/Crestwave/snippets/blob/master/nosj.patch

**Comment by andychu** [comment]
Geez that is a super weird behavior!

Thanks for the testing on nosj!  We should definitely implement negative indices because it looks a lot uglier now :)
