### ISSUE TITLE
Support read -N, etc.

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#770]
Used by `nosj`; I'm honestly not sure if there's any reason to use this over `-d '' -n`, though.. I'll ask Dylan

**Comment by andychu** [comment]
OK yeah I'm not familiar with that flag either, but it's good to know about

**Comment by andychu** [comment]
`read -N` and `-s` mentioned here too

https://lobste.rs/s/ct9kgg/oil_0_8_pre6_pure_bash_c#c_0xysjm

https://github.com/joshuarli/icd/blob/master/ports/icd-bash

**Comment by joshuarli** [comment]
Oh, I don't really remember if there was a reason I specifically chose `-N` over `-n`. I might honestly just have lifted it from an earlier version of `fff`, lol.

`-s` would be nice to support, though.

**Comment by andychu** [comment]
See #776 for more `read` flags to implement

**Comment by Melkor333** [comment]
Hit this while [testing bashtop](https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Bashtop.20testing)!

**Comment by andychu** [comment]
@PossiblyAShrub  just implemented this!

woohoo is was an old bug :-)

**Comment by andychu** [comment]
Fixed awhile ago, late announcement - https://www.oilshell.org/blog/2024/01/release-0.19.0.html
