### ISSUE TITLE
EXIT trap doesn't run after explicit 'exit' (tldr-bash-client)

### ISSUE THREAD

**Issue by pepa65** [oilshell/oil#777]
After reading lots about the oil shell, I decided to try to help test. The first thing I tried was a moderately short bash script I have here: https://github.com/pepa65/tldr-bash-client
After installing the latest osh (oil-0.8.pre6) and changing the first line of `tldr` to `#!/usr/bin/env osh` I ran it under osh. It gave errors like `'local' doesn't accept flag -l` so I removed the `-l` flag and made sure the variable concerned was manually converted to lowercase.

But after that it just didn't output anything. No idea what is wrong. I would expect the help function would work at least.

**Comment by andychu** [comment]
Thanks for testing!  I reproduced this.  Not sure what's going on yet.  `osh -x` shows it stops unexpectedly

**Comment by andychu** [comment]
OK I debugged it some more and this is a bug in the EXIT trap implementation.   I tickled it with the failing spec test (see diff)

Great report, thank you!

**Comment by andychu** [comment]
Fixed, will be out with the next release :)  Keep the reports coming!

**Comment by pepa65** [comment]
It would be great if you can implement the `-l` flag on declare/local etc. as well. ;-)

**Comment by andychu** [comment]
Yes that's issue #764

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.8.pre7/
