### ISSUE TITLE
My buildnano script doesn't run

### ISSUE THREAD

**Issue by pepa65** [oilshell/oil#778]
This script at https://4e4.win/buildnano seems to get stuck earlier on. (I just replaced bash with osh on the first line, running with oil-0.8.pre6.)

**Comment by andychu** [comment]
Hm if you can narrow it down that would be useful.  What I do is a combination of `set -x`, `PS4`, and adding `echo`, and/or deleting parts of the script.

Off the top of my head, `bind` does nothing in OSH, so if the script relies on that, then it probably won't work.  It is possible that this is the difference?

**Comment by pepa65** [comment]
No, all the (`un`)`bind`s are part of a here-document.
In line 237 the variable `pkgs` gets assigned the output of `dpkg -l` (a formatted output of all the installed packages) and then the for loop checks with the grep on `pkgs` as a here-string if the packages listed in the `req` variable are installed. It looks like the here-string is not working well.

**Comment by Crestwave** [comment]
What do you mean by "it looks like the here-string is not working well"? Does it work if you pipe it with `echo` instead? Does the contents of the variable match when running in Bash?

I haven't actually run the script, but one issue I noticed from reading it is that the tilde doesn't expand in `gitdir=${GITDIR:=~/git}` on OSH

**Comment by pepa65** [comment]
It just hangs indefinitely on the grep command when using a here-string as input.

**Comment by Crestwave** [comment]
So what happens if you pipe `echo` instead? Or if you replace `grep` with `cat`? Can you make a minimal reproduction like:

```bash
foo="\
bar
baz"
cat <<<$foo
```

I've tried running stuff like this and actually running your script until the here-string under another user, but I couldn't reproduce the issue.

**Comment by pepa65** [comment]
How about `for v in 12 4334 656 323; do grep -q 3 && echo $v; done`

**Comment by andychu** [comment]
Can you give an example?  I don't see a difference, e.g.

```
$ cat t.sh 
cat <<< "one
two"

$ bash t.sh 
one
two

$ osh t.sh 
one
two

```

**Comment by pepa65** [comment]
OK, it seems hard to pin it down... Is there some subtle difference running it in a script versus running things directly on the commandline? If I include `set -vx` on the second line of the script, it outputs the expansion of $(dpkg -l), and then the lines
```
+ (lvalue.Named name:inst spids:[584]) = (value.Str s:'')
+ grep -q '^ii  pkg-config[ :]'
```
It seems to hang indefinitely at this point. The actual command in the script is `grep -q "^ii  $p[ :]" <<<$pkgs`
Is the <<< part cut off?? In bash, the set command causes `for p in $req
do grep -q "^ii  $p[ :]" <<<$pkgs || inst+=" $p"; done` to be displayed.

**Comment by Crestwave** [comment]
Yes, I think it's normal for the here string to be cut off in the xtrace output. When I run the script on my machine with an exit after the loop, it correctly goes through it and doesn't freeze; again, can you try to trim down the script and remove its system-dependence?

For example, you could get the output of `dpkg -l` and make the script directly set the variable to your output instead of running the command itself.

**Comment by pepa65** [comment]
So is it something particular in the setup between your machine and mine? When I put an exit after the loop it never gets there. Like I said, the `pkgs` variable has `\n` instead of newlines in the xtrace, but if I do a hexdump, it does actually have newlines, and looks like it's supposed to look. And if I put a line with `grep "^ii  gettext[ :]" <<<$pkgs` before the loop, it gets it. But if I put `grep -q "^ii  gettext[ :]" <<<"$pkgs" && echo Installed` then it doesn't dislpay `Installed`... So the interaction of <<< and && maybe? (But only on my system???)

**Comment by Crestwave** [comment]
Again, what is `$pkgs`? The output of `dpkg -l` is system-dependent

**Comment by pepa65** [comment]
Sorry, I am realizing the help you require is way more than I can commit to right now. I'll have to revisit this later.

**Comment by andychu** [comment]
OK no problem, thanks for the reports!  If you have time later please reopen.
