### ISSUE TITLE
read is still line-buffered when a delimiter is specified

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#783]
I'm honestly having trouble reproducing this in a non-interactive script (if you can, do let me know how!), but you can simply run `read -d a` and press a. In Bash, `read` will immediately exit, but on OSH, it still waits for a newline. This is required to run pxltrm

**Comment by andychu** [comment]
Ah good point, right now we do something special for `read -n 3` but not `read -d a`.  It should be easy to make it apply to `read` whenever it's a terminal

**Comment by andychu** [comment]
@Crestwave This is on `master` now if you want to try it out.  Sorry I forgot about it for the 0.8.pre8 release last night

**Comment by Crestwave** [comment]
Great; I've gotten [pxltrm](https://github.com/dylanaraps/pxltrm) to run now! [Here's](https://github.com/Crestwave/snippets/blob/master/pxltrm.patch) my rough patch. Essentially, it's #262, `eval_unsafe_arith`,`read -p`, and `${arr}`.

**Comment by andychu** [comment]
OK nice!  `read -p` sounds easy enough to add to minimize the patch

The other changes look good

**Comment by andychu** [comment]
I did a basic version of `read -p` ... If it doesn't allow you to remove the patches let me know :)

**Comment by Crestwave** [comment]
Okay, it seems to work, although the patch isn't much smaller because I found some more uses of `$_` that account for some edge cases. I've opened a pull request: https://github.com/dylanaraps/pxltrm/pull/18

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.8.pre9/
