### ISSUE TITLE
`test/unit.sh all` requires commonmark and so fails if you did a minimal build

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#790]
It's recommended to run on the contributing the page: https://github.com/oilshell/oil/wiki/Contributing#quick-start, but the recommendation comes _before_ the instructions for `build/dev.sh all`.

```
[doctools/cmark_test.py]
Traceback (most recent call last):
  File "doctools/cmark_test.py", line 10, in <module>
    import cmark  # module under test
  File "/home/joshua/src/oil/doctools/cmark.py", line 34, in <module>
    cmark = ctypes.CDLL(libname)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: _deps/libcmark.so: cannot open shared object file: No such file or directory

*** doctools/cmark_test.py FAILED ***

xargs: test/unit.sh: exited with status 255; aborting
```

**Comment by andychu** [comment]
Great point, I fixed up the shell script and edited https://github.com/oilshell/oil/wiki/Contributing

It's still a bit complex, but at least it's not wholly inaccurate.  Not sure if we should get rid of the minimal build ...
