### ISSUE TITLE
Roundtrip tests for cmark fail

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#792]
Not sure what I did wrong. There's probably something up with my local environment.
```
$ doctools/cmark.sh build
... lots of spew ...
78% tests passed, 2 tests failed out of 9

Total Test time (real) =   2.23 sec

The following tests FAILED:
	  2 - html_normalization (Failed)
	  5 - roundtriptest_library (Failed)
... more spew ...
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/joshua/src/oil/_deps/cmark-0.29.0/test/roundtrip_tests.py", line 45, in <module>
    do_test(converter, test, args.normalize, result_counts)
  File "/home/joshua/src/oil/_deps/cmark-0.29.0/test/spec_tests.py", line 48, in do_test
    passed = normalize_html(actual_html) == normalize_html(expected_html)
  File "/home/joshua/src/oil/_deps/cmark-0.29.0/test/normalize.py", line 189, in normalize_html
    parser.feed(chunk.group(0))
  File "/usr/lib/python3.8/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/lib/python3.8/html/parser.py", line 171, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python3.8/html/parser.py", line 345, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "/home/joshua/src/oil/_deps/cmark-0.29.0/test/normalize.py", line 69, in handle_starttag
    self.output += ("=" + '"' + cgi.escape(v,quote=True) + '"')
AttributeError: module 'cgi' has no attribute 'escape'
<end of output>
Test time =   0.12 sec
----------------------------------------------------------
... more spew ...
```

**Comment by andychu** [comment]
I'm not sure yet, but I suspect a Python 2 vs. 3 issue?  You're on Arch Linux, where python is python3?  On my Ubunt box, python is python2.

This is "upstream", but we can probably fix it.  Thanks, good report!

```
$ python
Python 2.7.12 (default, Apr 15 2020, 17:07:12) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

**Comment by jyn514** [comment]
Yes, `python` is 3.8.2 on my machine. Maybe the tests just need a `#!/usr/bin/env python2` shebang?

I'm actually on Ubuntu 20.04 but I got tired of opening python to do some math and `3/2` being 1 😆

**Comment by andychu** [comment]
I traced it partially to:

```
~/git/oilshell/oil/_deps/cmark-0.29.0/build$ cat CTestTestfile.cmake 
# CMake generated Testfile for 
# Source directory: /home/andy/git/oilshell/oil/_deps/cmark-0.29.0
# Build directory: /home/andy/git/oilshell/oil/_deps/cmark-0.29.0/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(src)
subdirs(api_test)
subdirs(man)
subdirs(testdir)

```

- I'm not sure how `ctest` works ...
- I see `python3` in most places, not just `python`, so not sure if that's it

**Comment by andychu** [comment]
Ahh geez this is a Python version issue

https://github.com/trustedsec/social-engineer-toolkit/issues/721

`cgi.escape` in Python 3.8 is `html.escape`.  So I guess cmark doesn't work on 3.8.  Maybe we can upgrade?

**Comment by andychu** [comment]
Also, there is an obvious problem here:

- we're USING cmark under Python 2, via `ctypes`
- the tests explicitly run with Python 3

So in some sense it would make sense to DISABLE the tests and write our own via Python 2 `ctypes`.   The tests are testing for stuff we're not using.  We should test what we're using.

Yeah I think that's what needs to be done.

**Comment by andychu** [comment]
OK I disabled the tests -- we should run through it once again.  Should be able to make a screencast
