### ISSUE TITLE
No instructions for installing `pygments` for a full build

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#793]
I ran all the steps for installing commonmark (ignoring the test failures from #792). Then I try and run a full build:

```
$ doctools/cmark.sh demo-ours
<p><em>hi</em></p>
Traceback (most recent call last):
  File "doctools/cmark.py", line 353, in <module>
    main(sys.argv)
  File "doctools/cmark.py", line 335, in main
    Render(opts, sys.stdin, sys.stdout, use_fastlex=not opts.disable_fastlex)
  File "doctools/cmark.py", line 272, in Render
    html = oil_doc.HighlightCode(html)
  File "/home/joshua/src/oil/doctools/oil_doc.py", line 373, in HighlightCode
    plugin.PrintHighlighted(out)
  File "/home/joshua/src/oil/doctools/oil_doc.py", line 273, in PrintHighlighted
    from pygments import lexers
ImportError: No module named pygments
```
Ok, let's install pygments:
```
$ pip install pygments
Requirement already satisfied: pygments in /usr/lib/python3/dist-packages (2.3.1)
```
Oh right, pip on my machine means python3, and oil uses a fork of python2.
```
$ pip2 install pygments

Command 'pip2' not found, did you mean:
....
$ python2 -m pip install pygments
/usr/bin/python2: No module named pip
```
Oops, pip2 wasn't in the setup instructions. Let's just give up on pip and use the package manager:
```
$ sudo apt install python-pygments
[sudo] password for joshua: 
... spew from apt ...
```
Now it works!
```
$ doctools/cmark.sh demo-ours
<p><em>hi</em></p>
<div class="highlight"><pre><span></span>code
block
</pre></div>
<!-- done pygments -->

<pre><code class="language-oil">code
block
</code></pre>
<p><a href="/cross-ref.html?tag=re2c#re2c">click here</a></p>
<p>Test spacing out:</p>
<pre><code>echo one
echo two
</code></pre>
<p>Another paragraph with <code>code</code>.</p>
```

**Comment by andychu** [comment]
Yeah I remember being broken / confused by pygments awhile ago!

Around December / January, I added the `oil_doc.py` stuff, which depends on CommonMark and now pygments, and it indeed "rotted" the build process a bit...  Thanks for bringing it up!  Let me think about what to do

I think I'm only using pygments for the blog :-/    Although there is some possibility of using it in the `/release/$VERSION/doc/` tree

**Comment by andychu** [comment]
Yup I found these curses from May:

https://github.com/oilshell/oil/blob/master/doctools/cmark.sh#L20

So yeah there is a problem here but not sure exactly how to address it

**Comment by andychu** [comment]
OK, I made it optional, so I believe oil developers should never have to mess with it.  (The Oil blog uses it, but the Oil docs don't, and devs only need to be able to build the docs.)

We should walk through it again to make sure though.  Please reopenn if you have any other problems
