### ISSUE TITLE
Implement fast command sub: ${.myproc arg1} and @{.myproc 'a' "$b"}

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#799]
I think Quentin mentioned ksh93 does this

Use cases:

```
$(dirname $x)
$(basename $x)
$(hostname)
$(pwd)  # instead of $PWD
```

while remaining POSIX compatible.  NOT

```
$dirname(x)
$basename(x)
```

-----

And

```
for i in @(seq 3) {
  echo $i
}
```

without forking.

Should this be an option?

```
shopt -s avoid_forking {
  var x = $(pwd)
}
```

Or can it have a different syntax  to make sure you don't write something slow under other shells?

```
var x = $$(pwd)
```

**Comment by andychu** [comment]
Idea: Maybe an explicit syntax that says this **must** be optimized?  

- `$(echo 1; echo 2)` may or may not be optimized.  It depends on the setting of `shopt --set fast_command_sub`
  - does fast_command_sub have to optimize the first word?
- `$+(echo 1; echo 2)` is ALWAYS optimized.

Is `fast_command_sub` always on in Pulp, etc.?  Config files?

**Comment by andychu** [comment]
Other explicit syntax ideas:

- `$<echo hi>`  -- since redirects are not allowed, this might be OK
  - though turning $< into a token is technically a breaking change, as `$<in>out` is valid shell!


Related to running WebAssembly #848

**Comment by andychu** [comment]
Implementation strategy:

- hidden `shopt --set write_buffer` with `${.myproc $arg1}`
- the write buffer is used by
  - `echo`, `write`, and `printf`.  (What about pp cell etc.?  Probably not?  What about declare?)
  - the wasm output buffer
- it could be `$_write_buffer` or `$_buf`
- after evaluation of `${.myproc $arg1}`, it's replaced with `$_buf`, and `$_buf` is reset

**Comment by andychu** [comment]
What I settled on:

- `${.myproc arg1 arg2}`
- If we have that, then we also need `@{.myproc arg1 arg2}` for consistency.  Relates to #800

**Comment by andychu** [comment]
I think it makes sense to require changing syntax when we change semantics.  But you can imagine some option like `shopt set optimize_command_sub` or something?  So you could do `$(echo hi)` transparently?

**Comment by andychu** [comment]
Also call this "builtin sub", analogous to variable/expression/command sub

**Comment by andychu** [comment]
This doesn't need new syntax; it should just be `var x = builtin_sub(^(echo hi))` I think

**Comment by bar-g** [comment]
Would that be different from `var x = eval(^(echo hi))` and `var x = eval('echo hi')` and `$[ eval("myproc $arg") ]`?

What about directly substituting a block literal?
`command $^(myproc $arg)` and `var x = "$^(myproc $arg)"`?
