### ISSUE TITLE
Fix leak of lines/spans in Arena (new Token/Line/Source representation)

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#812]
Because we want them to be freed by the garbage collector.

Question: do we still have span IDs?  Or are those now pointers?

**Comment by andychu** [comment]
From notes:

```

data Token {
  id Id         // maximum 2^16 IDs.  To make decisions quickly
  span_id Int   // hack: maximum 2^16 IDs PER LINE
  line Line     //
}

data Line {
  line_num Int
  val Str
  source Source
  span_ends List<int>  // corresponds to each span_id
}

- So when you tokenize, you just append to span_ends

- And then you have TokenVal(tok) which is normal


4H + 4 + 8 + 8 + 8 = 32

- Then instead of span_ids, how do you decorate the AST?  with pointers I
  think
  - You let the GC do its work
  - integers cause problems!!

Toks instead of Spids
---------------------

TODO: Get rid of the osh2oil translator after this!  Or maybe we can port it,
not sure.  We need that PrintUntil thing...  and we attach tokens instead of
span IDs

Instead of this:

      left_spid = word_.LeftMostSpanForWord(words[0])
      assign.spids.append(left_spid)  # no keyword spid to skip past

- Just get LeftMostTokenForWord?
  - TokenForWord, TokenForCommand, TokenForArith?
  - hm not sure
  - yeah maybe you have a homogeneous representation where node.toks[0] is
    always the blame location like $(, toks[1] is an OPTIONAL end location
    and then the rest are filled in for translation, reformatting, etc.
    These are in homogeneous order?

```

**Comment by andychu** [comment]
Note: consider not storing:

- line number
- column number
- token length !  (you can relex!)

Can they be recomputed with a fast routine in C++?

This talk mentions that:

https://media.handmade-seattle.com/practical-data-oriented-design/

However shell is very much line-based, so I think we can't just store the offset in the file.  I think we'll apply the analogous optimizations on a line level.

Also, the shell has more of a complex graph structure than a simple tree structure, and we use garbage collection to manage this (which is good!)


-----

 I mentioned it here several months ago:

https://old.reddit.com/r/ProgrammingLanguages/comments/mrifdr/treewalking_interpreters_and_cachelocality/

However also note the caveat in the video: this is only in the self-hosted compiler, which hasn't really shipped (it's not the default, much like `oil-native`)

**Comment by abathur** [comment]
Do you have a sense of what the timeline might be? 

It might be productive to discuss since resholve depends on some of the details here, but I think it's ideal to wait until it is *ripe*?

**Comment by andychu** [comment]
I'd say we should finish the whole C++ translation before doing this, because then we can actually measure the real memory usage.  So I would not expect it for a long time :)  

I just watched the video which got me thinking about it, and It is tagged #essential because it's really a memory leak ... but that doesn't mean soon :-/

I will consult with on the tools side before doing this.  I think it might be useful to have some kind of basic formatter (e.g. that just indents your code properly) in the tree, so we don't inadvertently break the tool use case, which is important.

----

It is true though that tools  naturally have a different memory management scheme.  In that case I would just load everything by file.

The runtime is a bit harder because you can redefine functions, delete them, source stuff interactively, etc.  And just hitting TAB invokes the parser, which produces a ton of objects, etc.

**Comment by andychu** [comment]
FWIW a rewrite of the Token/Line/Span representation is  probably coming up in a month or so ...  We have a basic GC and need to optimize by allocating fewer elements
  
https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/New.20Token.20Representation

**Comment by andychu** [comment]
Slight optimization ?

```
data Token {  // 8 byte header
  line Line     // 8 byte pointer
  id Id            // could be 2 bytes, but most likely 4
  start_index Int   //  index into line.val -- to find the end

   // NO end index or length
}

data Line {  // 8 byte header
  line_num Int
  val Str
  source Source
}
```

- the end index or length can be "uncached" -- you recompute it with the token ID, line, and start index
- you only need it to print error messages, which doesn't have to be fast

**Comment by andychu** [comment]
Fixed !

https://github.com/oilshell/oil/commit/692de000c348805051b02a96208904edc190c051

**Comment by andychu** [comment]
Released a few weeks ago - https://www.oilshell.org/blog/2023/06/release-0.16.0.html

This was a big deal!
