### ISSUE TITLE
--json-str alternatives to --qsn

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#842]
Simply because JSON strings are very popular, and have encoders/decoders everywhere.

* `read --json-str` always succeeds.  It has to understand surrogate pairs, and re-encode them as UTF-8.
  * it looks for the presence of a leading `"`, just like QSN looks for a leading `'`
* `write --json-str` has to **decode** UTF-8, and will fail if it can't be decoded.
  * we can reuse the QSN logic for utf-8 decoding.

**Comment by andychu** [comment]
Problem: what if a stream has mixed `"` and `'` ?  That could be very confusing ...

Should we provided a `--quoted` flag that decodes both?  Or just have `--json-str` and `--qsn` active at the same time?


The `write` builtin should only emit one or the other.

**Comment by meenakshi0910** [comment]
Hello @andychu , can I work on this?

**Comment by andychu** [comment]
Everything is up for grabs although I think the JSON library we're using and the Python/C++ split may make this a little hairy.  All questions about that are welcome

This change would involve spec tests too -- it might be worthwhile to pick a simple issue to familiarize yourself with spec tests.  Some docs here:

https://github.com/oilshell/oil/wiki/Spec-Tests

**Comment by andychu** [comment]
- #1146

**Comment by andychu** [comment]
Obsolete now J8 strings replace QSN - #1426
