### ISSUE TITLE
Can't run dev build on Ubuntu 20.10

### ISSUE THREAD

**Issue by nobozo** [oilshell/oil#845]
This is on a fresh install of Ubuntu 20.10 with a fresh git clone of Oil (ver 0.8.3).

jonf@ubuntu20-10:/usr/local/src/oil$ ./configure
./configure: Wrote _build/detected-config.sh and _build/detected-config.h
jonf@ubuntu20-10:/usr/local/src/oil$ make
test -d _build/opy && \
  build/actions.sh app-deps opy /usr/local/src/oil:/usr/local/src/oil/vendor bin.opy_
build/actions.sh: line 69: _devbuild/cpython-full/python: No such file or directory
test -d _build/oil && \
  build/actions.sh app-deps oil /usr/local/src/oil:/usr/local/src/oil/vendor bin.oil
build/actions.sh: line 69: _devbuild/cpython-full/python: No such file or directory
test -d _build/hello && \
  build/actions.sh app-deps hello /usr/local/src/oil/build/testdata:/usr/local/src/oil/vendor hello
build/actions.sh: line 69: _devbuild/cpython-full/python: No such file or directory
make: *** No rule to make target '_build/oil/app-deps-c.txt', needed by '_build/oil/all-deps-c.txt'.  Stop.

**Comment by andychu** [comment]
OK so you're trying to make the "dev build".  That does **not** involve running configure or make!

Please try this: https://github.com/oilshell/oil/wiki/Contributing

I mentioned the dev build vs. release build here.  But I think I need to make it even more clear, and maybe `configure` should ABORT if you have a `.git` directory.

https://github.com/oilshell/oil/blob/master/README.md#quick-start-on-linux

Thanks for trying it!  Let me know what happens.

**Comment by andychu** [comment]
OK I updated this page:

https://github.com/oilshell/oil/blob/master/README.md

and this one: https://github.com/oilshell/oil/wiki/Contributing

Let me know if it's still unclear, or if you have problems.  (And you're far from the first person to be confused by that :) )
