### ISSUE TITLE
`exit` doesn't end OSH session

### ISSUE THREAD

**Issue by timetoplatypus** [oilshell/oil#87]
Just realized while tinkering with #86, running `exit` in OSH doesn't terminate the session.
```
$> osh --version
Oil version 0.4.0
Release Date: 2018-02-03 07:15:16+00:00
[...]
$> osh
$osh> exit
$osh>
```
Running `exit` doesn't throw an error or anything, it just doesn't do anything. Running with OVM_VERBOSE set to 1 doesn't print any other information either.

After doing to a clean build from git as well (the alpha 0.5 version), I get the same behavior.

**Comment by andychu** [comment]
Oops, I think I broke that when I was changing `exit` to use exceptions rather than sys.exit().  Let me look into it!  Thanks!

**Comment by andychu** [comment]
OK thanks, I fixed it.   (This problem was only in the interactive loop, not batch mode.)
