### ISSUE TITLE
Error building on macOS

### ISSUE THREAD

**Issue by ghlecl** [oilshell/oil#901]
I have tried to build version 0.8.7 on macOS using the tarball provided here:
  https://www.oilshell.org/release/latest/

I got an error for some missing function declarations.  It seemed to specifically complain about the btowc.  I have found where it is used and it is in the Python-2.7.13/Include/pyport.h file.

I have added #include <wchar.h> with some includes just above the use of the function (approx line 726) and oil seems to build.  I have not tested the build though (not sure I can) and my solution might not be valid, but I thought I would at least report.

macOS 10.15.7
Xcode 12.4
readline from macports

Hope this is useful.

**Comment by andychu** [comment]
Thanks for the report!  I removed the usage of `btowc()` in `pyport.h`.

I'm not sure why this caused a problem since other people have been able to run on OS X.  But I think this should fix it as of the next release.

If you see other problems please let  me know!

**Comment by andychu** [comment]
Released: https://www.oilshell.org/blog/2021/03/release-0.8.8.html
