### ISSUE TITLE
tab completion just moves cursor

### ISSUE THREAD

**Issue by rsteube** [oilshell/oil#911]
When installed in `cimg/go:1.15` (`Ubuntu 20.04.1 LTS (Focal Fossa)`) docker image tab completion just moves the cursor further right (by a tab), eg:
```sh
ls <TAB>
ls          <CURSOR>
```
see [here](https://github.com/rsteube/carapace/blob/master/Dockerfile#L33)

This works in the `ubuntu` container though (`20.04.2 LTS (Focal Fossa)`), so i'm not sure what causes this.

Locally on `manjaro` it works as well but i am getting a different error when the completion script is executed:
```sh
SystemError: Invalid locale for LC_CTYPE
FATAL: couldn't import from app bundle '/usr/bin/osh' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```
`file` says it is indeed stripped, but that is the same for the binary in the `ubuntu` container where the error does not occur.

**Comment by andychu** [comment]
Thanks for trying it!

I think the first one is a symptom of not having GNU readline on the system.  You can tell if it detected GNU readline like this:

```
$ ./configure 
./configure: Wrote _build/detected-config.sh and _build/detected-config.h

$ cat _build/detected-config.sh
READLINE_DIR=
HAVE_READLINE=1
PREFIX=/usr/local
DATAROOTDIR=/usr/local/share

```

Do you have a repro for the Manjaro issue?  How do you build it, start it, and what is the completion script?

There could be some locale issues  since Oil prefers UTF-8; I wouldn't be surprised if we had to change something there

**Comment by rsteube** [comment]
I'm using the [osh](https://aur.archlinux.org/packages/osh/) package and start it with osh.
The completion script currently looks like this:
```sh
#!/bin/osh
_example_completion() {
  local compline="${COMP_LINE:0:${COMP_POINT}}"
  local IFS=$'\n'
  mapfile -t COMPREPLY < <(echo "$compline" | sed -e "s/ \$/ ''/" -e 's/"/\"/g' | xargs example _carapace oil "_")
  [[ "${COMPREPLY[@]}" == "" ]] && COMPREPLY=() # fix for mapfile creating a non-empty array from empty command output
  [[ ${COMPREPLY[0]} == *[/=@:.,] ]] && compopt -o nospace
}

complete -F _example_completion example
```
Lemme have a look regarding the rest...

**Comment by rsteube** [comment]
Jup, readline is missing in the container so that might be it:
```
circleci@62d7fb358c01:~/project/oil-0.8.8$ cat _build/detected-config.sh
READLINE_DIR=
HAVE_READLINE=
PREFIX=/usr/local
DATAROOTDIR=/usr/local/share
```
Will try it that out. Any specific version? And is it just needed for the compile step or for the runtime?

Here's my locale:
```
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.utf8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.utf8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by rsteube** [comment]
Works again in the container, thanks.

**Comment by rsteube** [comment]
Managed to reproduce the locale error: #912 
Closing this as the problem related to readline is solved.
