### ISSUE TITLE
Prefix Notation

### ISSUE THREAD

**Issue by dahonick** [oilshell/oil#913]
Hello Andy,

I saw the project on Hacker News and I thought it was an interesting idea. I think that using prefix notation for Oil could address the dual requirement for interactive sessions and more complex scripts. Prefix notation coupled with a stack would provide a key feature that I think is worth switching for. For more info on prefix notation see S-expressions.

**The story**
Let's compare prefix with infix notation in a series of four challenges. For the purposes of this example let's say $1, $2, $3 ... are references to the stack (something like $!!)

**Challenge one - entering quick commands:**
Prefix defining the arguments explicitly, making punctuation unnecessary for most basic command. This allows Prefix style commands to be entered more easily. Examples `set a = 5` vs `= a 5` or `rstrip($var, ".txt")` vs `rstrip $var ".txt"`.

**Challenge two - decomposing commands**
Without a stack, the command `((9 + 4) * (3 – 6 )) / $var > file.txt` can be decomposed as shown:
```
$ read var
$ set tmp1 = 9 + 4 
$ set tmp2 = 3 - 6
$ set tmp3 = $tmp1 * $tmp2
$ $tmp3 / $var > file.txt
```
The equivalant command for Prefix is `write / * (+ 9 4) (- 3 6) $var file.txt`. Note that the brackets can be removed as the arguments are explicit. With a the addition of a stack, this can be decompose into the following:
```
$ read var 
$ + 9 4 
$ - 3 6
$ * $1 $2  # assume $1 gives us the last item on the stack ie -3
$ / $1 $var
$ write $1 file.txt
```
Technically either approach could use a stack so this round is a draw

**Challenge three - easy to learn** 
Infix takes the lead here with more familiar mathematical syntax:
```
$ (9 + 4) * (3 - 6)
$ ls . | grep ".txt"
```
Prefix is not far behind however, with syntax that is otherwise understandable.
```
$ * (+ 9 4) (- 3 6)
$ grep (ls .) "*.txt"
```

**Challenge four - scripting :**
Consider this script from one of the Oil examples
```
git branch --merged | while read --line {
  var line = _line.strip()
  # The * prefix means the branch is unmerged
  if (line != 'master' and not line.startswith('*')) {
    echo $line
  }
} | readarray -t :branches
```
Prefix is able to build the equivalent script interactively.
```
$ proc {strip $ARG1}
$ proc {if and (!= ($1 $ARG1) "master) (!startswith "*" ) { echo $line}}
$ $1 "*branch" # run process with first argument "*branch"
> ""
$ pop
$ $1 "branch"
> "branch"
$ pop
$ proc {readarray while read (git branch --merged) --line {$1})} "merged" 
$ = :branches $1
```
Here is the punchline: Prefix can then automatically generate a script based on the last command of this interactive session.
```
$ to_script $1 # substitute all lines referenced by $1 into a script. 
> proc merged() {
>    while (read (git branch --merged) --line) {
>        var1 = strip _line
>         if and (!= $var1 "master") (!startswith $var1 "*" ) {
>             echo $var1
>         }
>    }
> = :branches merged
```
**Conclusion**
The benefits of using prefix notation are:
1. Faster to type interactively (especially for common/simple things) 
2. More consistency between scripts and single line commands
3. Simpler automatic generation of scripts from interactive sessions

At the expense of:
1. Less familiar syntax 
2. bigger change from bash
3. other things I'm not thinking of right now.

I realize I have taken some liberties and glossed over a number of things but I hope this is enough to get you thinking about the possibilities. 

Thoughts?

**Comment by andychu** [comment]
Thanks for the feedback, but this is very at odds with Oil's design goals (be familiar to Python, JS, Ruby programmers), and there are actually a bunch of shells with prefix notation already:

Elvish:

https://elv.sh/learn/cookbook.html#language-recipes

And I think an earlier version of Oh, although maybe it changed since I last looked:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/michaelmacinnis/oh/master/doc/comparison.html

There are more here, including scsh, etc.

https://github.com/oilshell/oil/wiki/Alternative-Shells

https://github.com/oilshell/oil/wiki/Internal-DSLs-for-Shell

**Comment by andychu** [comment]
BTW there are four documents under "language design" here that may give a feel for why I quickly reject this:

https://www.oilshell.org/release/0.8.8/

It's not a bad idea but it's not for Oil; others have explored and are exploring this

**Comment by dahonick** [comment]
Right, yea I see where you're coming from. Shell improvements are long over due and it may just be that you have the right approach here. Thanks for clarifying.
