### ISSUE TITLE
oilshell escapes completion candidates

### ISSUE THREAD

**Issue by rsteube** [oilshell/oil#915]
Oil escapes special characters in the completion view which makes descriptions a bit harder to read.
Btw. is there no pager for completions?

```sh
osh$ gh issue view
 1023\ \(Allow\ editing\ the\ commit\ message\ when\ squash-merging\ a\ PR\)
 1247\ \(gh\ repo\ fork\ cannot\ fork\ to\ org\)
 1262\ \(Automatic\ WinGet\ pkg\ update\)
 1303\ \(Support\ aliases\ deeper\ than\ top\ level,\ e.g.\ \`gh\ pr\ co\`\)
 1450\ \(Select\ commit\ email\ when\ merging\ PR\)
 1575\ \(HTTP\ 414:\ Request-URI\ too\ large\)
 1634\ \(Add\ command\ to\ watch\ running\ Github\ Action\(s\)\ in\ repo\)
 1646\ \(Support\ \`gh\ pr\ create\ --browse\ --copy\`\ as\ in\ hub\ to\ open\ and\ copy\ PRs\)
 1735\ \(Skip\ certificate\ warning,\ using\ internal\ enterprise\ CA\ \"certificate\ signed\ by\ unknown\ authority\"\)
 1745\ \(Repo\ commands\ assume\ non-enterprise\ auth\ and\ fail\ trying\ to\ auth\ against\ github.com\)
 1798\ \(Installation\ failed\ on\ Kali\)
 ... and 89 more
```

```sh
bash$ gh issue view
Display all 100 possibilities? (y or n)
1023 (Allow editing the commit message when squash-merging a PR)
1247 (gh repo fork cannot fork to org)
1262 (Automatic WinGet pkg update)
1303 (Support aliases deeper than top level, e.g. `gh pr co`)
1450 (Select commit email when merging PR)
1575 (HTTP 414: Request-URI too large)
1634 (Add command to watch running Github Action(s) in repo)
1646 (Support `gh pr create --browse --copy` as in hub to open and copy PRs)
1735 (Skip certificate warning, using internal enterprise CA "certificate signed by unknown authority")
1745 (Repo commands assume non-enterprise auth and fail trying to auth against github.com)
1798 (Installation failed on Kali)
```

**Comment by andychu** [comment]
- Hm this was sort of intentional since bash's output is ambiguous when you have multiple candidates on a line (is the space within a candiate).  But I see how in this case it makes it less readable.  If we can do it within the constraints of readline, I'd be open to changing it, or have an option to change it.
- Unfortunately I don't see a way to do a pager with  GNU readline.

Basically I ran into a lot of problems doing what I want with GNU readline.  It may be that we have to go back to bash-style completion with scrolls the screen, and has the annoying "Display 100 candidates?" prompt.

And then we provide APIs so people can write stuff like ohmyzh or ble.sh in Oil -- issue #663

**Comment by rsteube** [comment]
It's  just something i noticed as other shells don't do this.
The ambigouity is probably less of a problem when you have menu completion.
Not a fan of scrollers and questions as well - e.g. powershell asks if completions should be shown if they exceed a specific number even though it has menu completion.
Seems nushell and ion use [rustyline](https://github.com/kkawakam/rustyline).

**Comment by andychu** [comment]
Yeah there are a lot of other choices, issue #460  is related.  Unfortunately we need contributions for all the interactive stuff; I'm still focused on the language mainly.

`native/line_input.c` is a Python wrapper for GNU readline (forked from Python's owner wrapper).  If we had a similar wrapper for other line editing libraries that would enable some experimentation with the UI and so forth.

I'm not sure if there are fancy ones in C/C++ -- I think zsh and fish have them tightly integrated and not reusable.

But in theory we can reuse one in Rust if it exposes a shared library interface.

**Comment by andychu** [comment]
Hi @rsteube , we just noticed the   https://github.com/rsteube/carapace-bin project over on the Oil Zulip:

https://oilshell.zulipchat.com/#narrow/stream/146045-shell-autocompletion/topic/caraspace.20--.20A.20project.20that.20implements.20completions.20for.20te.2E.2E.2E

I wonder how it's going and if this escaping issue is still a problem?  Glad to see this effort

I haven't thought about it that much, but I just did some stuff with GNU readline, so maybe we can figure out a solution ...

**Comment by rsteube** [comment]
Well it's not really a problem, but yes it still has this behaviour. Descriptions are kinda ["hacked in"](https://stackoverflow.com/questions/7267185/bash-autocompletion-add-description-for-possible-completions/10130007#10130007) anyway.

Recently learned about [ble.sh](https://github.com/akinomyoga/ble.sh) which managed to replace readline in pure bash :open_mouth: :
[![asciicast](https://asciinema.org/a/470338.svg)](https://asciinema.org/a/470338)

**Comment by andychu** [comment]
In that screenshot, is that the default ble.sh, or is that running with some of your enhancements?

And yes ble.sh is almost certainly the biggest shell program in the world!  We've been working on it on #653  and #1069

https://github.com/oilshell/oil/wiki/The-Biggest-Shell-Programs-in-the-World


----

I've never seen the stackoverflow trick for descriptions ... So does it actually work with OSH?

**Comment by rsteube** [comment]
Default ble.sh with [starship](https://asciinema.org/a/470338) prompt - just enhanced with the completions.
Btw. it's an asciicast: https://asciinema.org/a/470338

**Comment by andychu** [comment]
Sorry for the long delay on this -- we had sort of lost steam on completion, and are now back to it, for YSH

So OSH is more compatible now


Released - https://www.oilshell.org/blog/2023/09/release-0.18.0.html
