### ISSUE TITLE
Quick Reference link is broken

### ISSUE THREAD

**Issue by ilyash** [oilshell/oil#920]
Page: https://www.oilshell.org/release/0.8.8/doc/osh-manual.html
Broken link: "Quick Reference" - https://www.oilshell.org/release/0.8.8/doc/osh-quick-ref.html

**Comment by andychu** [comment]
Thanks, fixed!

**Comment by andychu** [comment]
http://www.oilshell.org/blog/2021/04/release-0.8.9.html
