### ISSUE TITLE
Hi, I am curious how does this differ to fish

### ISSUE THREAD

**Issue by Joe23232** [oilshell/oil#961]
Hi, I am curious how does this differ to fish? What are some of the pros and cons to fish shell?

**Comment by andychu** [comment]
Answered in the FAQ!  Please reopen if this doesn't answer your question :)  The whole FAQ is useful too.  Basically Oil is starting out more as a language for automation, but it can **grow** into an interactive UI like fish eventually.  It's not there yet.

https://www.oilshell.org/blog/2021/01/why-a-new-shell.html#whats-the-difference-between-oil-and-fish
