### ISSUE TITLE
Support \A in PS1

### ISSUE THREAD

**Issue by RobSykes** [oilshell/oil#962]
This is for time in 24hr format.

With oil-0.8.12 osh: <Error: \A not implemented in $PS1>

**Comment by andychu** [comment]
Thanks for trying it, this is within scope for sure!  But we're a bit short on hands right now.

Does your PS1 use this or is it just something you noticed?  We prioritize making

https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

including actual PS1s ...

**Comment by RobSykes** [comment]
Yes my PS1 uses \A (time in 24hr format is commonly used round here).  I was following the "Gradually Upgrading Shell to Oil" and started by sourcing my standard .bashrc in osh.

**Comment by andychu** [comment]
Released! https://www.oilshell.org/blog/2021/11/release-0.9.4.html

Thanks for the testing and feedback!
