### ISSUE TITLE
Var ref to array doesn't match bash behavior (array == array[0])

### ISSUE THREAD

**Issue by happysalada** [oilshell/oil#964]
The following small snippet will give a different result in bash and osh
```
array=(one two three)
elementRef=two
ref=array
for el in "${!ref:-}[@]"; do
    echo "el: $el"
    if [[ "$el" = "$elementRef" ]]; then
        echo "success"
        return 0
    fi
done
```

Is osh the array is expanded, in bash it's not.
I think if you try you will see exactly what I mean.
The snippet is convoluted and I'm not sure you want to fix the bug. I'm just reporting it for information.

**Comment by andychu** [comment]
Hm I reproduced this, that is not expected!  I'm not sure what's going on yet, but thanks for the report.

**Comment by andychu** [comment]
Ah  this can be reproduced just with `echo ${!ref}`.

bash gives `one` while OSH gives `one two three`.

A core difference is that ${a} means ${a[0]} in bash but not OSH.  

https://www.oilshell.org/release/latest/doc/known-differences.html#array-references-must-be-explicit

I guess it should be a runtime error?


I'm not sure yet if that should apply to indirect expansions ...

---

Is this based on real code?     I think `${!ref[0]:-}` would be better than `${!ref:-}`, but I'd have to see the context.

Thanks for the report!

**Comment by happysalada** [comment]
it comes from some convoluted code in NixOS. I tried for a fix, it worked when I tested it with Osh, I assumed it worked with bash but ended up not working.
Like I said, this is really convoluted and so far, it comes from me misusing the language, so feel free to ignore!

**Comment by andychu** [comment]
No I think this is important to sort out... we tr to avoid "reverse breakage", especially on features like `${!ref}` that are not idiomatic in Oil.  Those are bash features so they should behave more or less like bash.

"Reverse breakage" is what happened -- when you develop a script with bash features under OSH, and then it doesn't work in bash!   That is bad

**Comment by happysalada** [comment]
My opinion is that it's not a very high priority, I'll let you handle it how you think best!
Thank you for taking a look!

**Comment by andychu** [comment]
Running to `a[i]` issue, which is similar to #881 nameref.

Need to respect `eval_unsafe_arith`

`declare -n ref=a` also has the same `array[0] == array` issue

Probably do that with compat_array

**Comment by andychu** [comment]
Forgot to close this over  a month ago: https://www.oilshell.org/release/0.9.0/
 (didn't blog about this)
