### ISSUE TITLE
`fork` builtin not working.

### ISSUE THREAD

**Issue by wizard-28** [oilshell/oil#975]
I was following the [Oil Language Idioms](https://www.oilshell.org/release/latest/doc/idioms.html), and found out that the `fork` builtin doesn't actually work in the shell right now.

I ran:
```bash
fork { sleep 1; echo one; sleep 2 }
```

and it gives me this error
```bash
  fork { sleep 1; echo one; sleep 2 }
       ^
[ interactive ]:28: 'fork' got unexpected argument '{'
one
sleep: invalid time interval ‘}’
Try 'sleep --help' for more information.
```

This is my `osh` version
```monospace
Oil version 0.9.0
Release Date: 2021-07-18 06:49:53+00:00
Arch: x86_64
OS: Linux
Platform: #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC
Compiler: GCC 9.3.0
Interpreter: OVM
Interpreter version: 2.7.13
Bytecode: bytecode-opy.zip
```

**Comment by andychu** [comment]
Oh are you running `bin/oil` or `bin/osh`?  It should work with the former.  I should probably mention this in the docs, and also `osh --version`, which now says "Oil"

**Comment by wizard-28** [comment]
Yeah, it's working in `bin/oil` thanks

**Comment by andychu** [comment]
OK great, let me know if there are any problems, and general feedback is welcome :)
