### ISSUE TITLE
`eval "$(ssh-agent)"` not working in `oil`

### ISSUE THREAD

**Issue by wizard-28** [oilshell/oil#976]
I ran:

```bash
eval "$(ssh-agent)"
```

And I get this error:

```bash
  SSH_AUTH_SOCK=/tmp/ssh-zkcbuIAxIjvP/agent.214239; export SSH_AUTH_SOCK;
  ^~~~~~~~~~~~~~
[ eval at line 1 of (source.Interactive) ]:1: name=val isn't allowed when shopt 'parse_equals' is on.
Hint: add 'env' before it, or spaces around =
  eval "$(ssh-agent)"
  ^~~~
[ interactive ]:1: fatal: Exiting with status 2 (command in PID 214237)
```

My `oil` version:

```monospace
Oil version 0.9.0
Release Date: 2021-07-18 06:49:53+00:00
Arch: x86_64
OS: Linux
Platform: #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC
Compiler: GCC 9.3.0
Interpreter: OVM
Interpreter version: 2.7.13
Bytecode: bytecode-opy.zip
```

This command works in `bash`, so what is it's `oil` equivalent?

**Comment by andychu** [comment]
Ah so this will work in osh but not oil.

Right now I use OSH interactively and Oil as a language for scripting.   The idea is that Oil is a better language for when your scripts get big and unwieldy.  You can use it interactively too but these kind of compatibility issues are fundamental

(Also it's possible we might relax the `parse_equals` rule.)

**Comment by wizard-28** [comment]
> The idea is that Oil is a better language for when your scripts get big and unwieldy

I am rewriting my `bash` script in `oil`

---

> (Also it's possible we might relax the parse_equals rule.)

How to do it?

**Comment by andychu** [comment]
Hm good question, I think this should work:

```
# running with bin/oil

shopt --unset oil:all {
  eval "$(ssh-agent)"  # will respect bash syntax
}
```

**Comment by andychu** [comment]
And what I meant is that `shopt --set parse_equals` is part of `oil:all`.  It's mainly for config files and I'm not sure if we need it in `bin/oil`, e.g.

```
myconfig {
  root  = '/www'
  port = 80
}
```

instead of

```
myconfig {
  const root  = '/www'
  const port = 80
}
```

This is sort of in the future but I reserved space for it.  But maybe the breakage isn't worth it (although let me know if the `shopt` block solves your problem)
