### ISSUE TITLE
This repository is US property now.

### ISSUE THREAD

**Issue by lk-geimfari** [oilshell/oil#981]
## Reasoning

You named it oil.

<img width="434" alt="Screenshot 2021-09-02 at 23 27 02" src="https://user-images.githubusercontent.com/15812620/131911514-24015ab7-1f09-4b39-92bb-8ba69e41c74c.png">

## Expected behavior

To be the property of the USA.

**Comment by tux2603** [comment]
![image](https://user-images.githubusercontent.com/45047084/131920032-b31c2f14-7585-4c37-b922-780272f513c2.png)
They have oil

**Comment by andrenevesgomes** [comment]
![image](https://user-images.githubusercontent.com/48434290/131928538-7d043baa-17e7-4cc5-a873-30c9656c932d.jpeg)
