### ISSUE TITLE
Set PS1 in interactive shells

### ISSUE THREAD

**Issue by andersk** [oilshell/oil#982]
A [common idiom](https://www.gnu.org/software/bash/manual/bash.html#Is-this-Shell-Interactive_003f) in shell startup scripts is to test whether the shell is interactive using `[ -z "$PS1" ]`, but this doesn’t work with `osh`, which doesn’t set `PS1` by default. An interactive `osh` should set `PS1='osh\$ '` or something.

**Comment by andychu** [comment]
Sorry for the delay and thanks for the report!  It took me awhile to repro this one, apparently `--rcfile /dev/null` is not the same as `--norc`!

```
$  bash --norc --noprofile -i -c 'echo $PS1'
\s-\v\$
```

**Comment by andychu** [comment]
Released! https://www.oilshell.org/blog/2021/11/release-0.9.4.html

Thanks for the testing and feedback!
