### ISSUE TITLE
Idea for enhanced case statement

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#983]
The shell case statement accepts globs; I realized Oil could accept expression conditions, similar to Go's switch statement.  This gives richer functionality without using more keywords, which is nice.

shell:

```
case $name in
  (*.py) echo Python ;;
  (*.sh) echo shell ;;
esac
```

Oil style for globs:

```
case $name {
  (*.py) echo Python ;;
  (*.sh) echo shell ;;
}
```

New case statement:

```
const test_pat = / dot* '_test.' ('py' | 'sh') /

case {  # no variable here, like Go switch
  (suffix == '.py')
    echo Python ;;
  (suffix == '.sh')
    echo shell ;;
  (fnmatch(filename, '*.rb')
    echo Ruby ;;  # no ~~ operator?
  (filename ~ test_pat)
    echo Test ;;
}
```

**Comment by andychu** [comment]
This makes it roughly consistent with the #955 syntax, e.g. `where (size > 10)`

**Comment by andychu** [comment]
I guess this is how you match efficiently against an integer?

```
var x = 42

case {
(x == 0)
  echo zero ;;
(x == 1)
  echo one ;;
(2 < x < 5)
  echo 'between two and 5' ;;
(true)
  echo otherwise ;;
}
```

Maybe you could have a `case (x)` variant?  That might be too clever.

TODO: write a grammar out.

**Comment by andychu** [comment]
On the other hand, this is just sugar for `if-elif`, so maybe it's not worth it:

```
if (x == 0) {
  echo zero
} elif (x == 1) {
  echo one
} else {
  echo 'other'
}
```

**Comment by andychu** [comment]
It's probably best to save this for the Tea language -- Python just has if/elif and it's fine

If anything the `case` should have something for types rather than strings, but even that is not obviously required / better

**Comment by andychu** [comment]
I think if we could somehow get rid of `;;`, this might be worth it in the distant future.  

But otherwise it is probably too much of a bikeshed syntax optimization

**Comment by andychu** [comment]
Other punctuation

```
case $x {
  <build> echo build ;;
  <*.py> echo python ;;
}
```

**Comment by andychu** [comment]
https://reasonml.github.io/docs/en/pattern-matching

```
case $x {
  | build > echo build ;;
  | *.py > echo python ;;
  | * > echo defaut ;;
}
```

**Comment by andychu** [comment]
```
var x = 42
case (x) {
  | (0) 
    echo zero
  | (1)
    echo one
  | ()   # special token that's like |*> 
    echo any
}
```

**Comment by andychu** [comment]
Summary:

- The thing to match can be a string or type:
  - case $x
  - case (x)
  - and maybe eventually `case {`, which means it's just a list of booleans, like Go
- There can be 3 different modes with `|` patterns
  - list of glob words, like shell.  `| *.cc *.h >`
  - eggex: `| / dot* '.py' /`
  - expression:  `| (42)`

**Comment by qubidt** [comment]
Have you seen [this post](https://soc.me/languages/unified-condition-expressions) ("Language Design: Unified Condition Expressions"), perchance? To quote:

> Replace the different syntactic forms of
> * if expressions,
> * pattern matching and pattern guards,
> * if-let constructs
>
> with a single, unified condition expression that scales from simple one-liners to complex pattern matches.

...

> The condition can be split between a common discriminator and individual cases.
> * This requires doing away with mandatory parentheses around the conditions.
> * This strongly suggests using a keyword (then) to introduce branches, instead of using curly braces, based on readability considerations.
>
> The keyword if is chosen over other options like match, when, switch or case because it is keyword the largest number of developers are familiar with.


I've been considering it since I saw it and it seems solid enough (and only slightly radical), though I'm out of my depth w/ language design.

**Comment by andychu** [comment]
(very late reply, after thinking about this issue again) I had read that post !  

I think it is nice, though shell has 2 unique issues:

1. the string-ish style vs. the typed style.  Most languages don't have this.
2. Backward compatibility with shell syntax.  That is what a lot of the problem here is!

**Comment by andychu** [comment]
Note: I tried the lookahead to `|` at some  point, to get rid of `;;` -- I'm pretty sure it doesn't work, although I don't remember why right now

Oh maybe it had to do with the last closing `}` ?  Not sure


```
case $x {
  | *.py >
     echo python
  | *.sh >
    echo shell
}
```

**Comment by andychu** [comment]
New proposal to get rid of `;;` and unbalanced `*.h|*.cc)`:

https://oilshell.zulipchat.com/#narrow/stream/325160-oil-discuss-public/topic/New.20Case.20Statement.20Ideas

```
case (x) {
  *.h | *.cc { echo C++ }
  *.py       { echo Python }
}
```

**Comment by andychu** [comment]
Not completely implemented, but we know how it should behave now

Released a few weeks ago - https://www.oilshell.org/blog/2023/06/release-0.16.0.html
