### ISSUE TITLE
Confusing errors with PS1 is inherited (from bash etc.)

### ISSUE THREAD

**Issue by NoahTheDuke** [oilshell/oil#989]
I installed oil using homebrew, which says is on 0.9.2. When I run `oil` in bash, even tho I have a completely blank `~/.config/oil/oshrc`, I see errors related to my bash set up:
```
noah@Noahs-MBP ~
$ oil
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
                                  ^
(source.PromptCommand spid:-1):2: Invalid char escape in double quoted string
oil$
```
According to the docs, neither `.bash_profile` nor `.bashrc` should be loaded. If I comment out or rename them, then `oil` opens normally when run from a fresh process. Now that I've written this out, does `oil` inherit this stuff? If I comment out/rename those files, but don't reload my current bash process, `oil` throws the above error.

I don't know exactly what's happening, so any help would be great.

**Comment by andychu** [comment]
`oil` will run `~/.config/oil/oilrc` and `osh` will run `~/.config/oil/oshrc` -- maybe that's the problem?

Generally speaking `osh` is better to try interactively right now.

`oil` works interactively but it's probably more useful as a REPL like `python` (i.e. it gives more strict errors)

**Comment by NoahTheDuke** [comment]
Oops, I should have run `osh`. However, that gives me the following:
```
noah@Noahs-MBP ~
$ osh
  __bp_precmd_invoke_cmd
  ^~~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):1: '__bp_precmd_invoke_cmd' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
  ^~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '_direnv_hook' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
               ^~~~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '__posh_git_ps1' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '__iterm2_prompt_command' not found
  __bp_interactive_mode
  ^~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):3: '__bp_interactive_mode' not found
<Error: unbalanced \[ and \]>
```

If I restart my terminal session (which then doesn't load `.bash_profile` or `.bashrc`), this goes away.

**Comment by andychu** [comment]
Ah can you do `echo $PS1` and paste the output here?  Before you start `osh` and after if possible

I think the problem might be that `osh` is inherting a `$PS1` from bash or zsh.  And then those functions aren't defined.

The error message needs to be better, the `(source.PromptCommand` stuff should be replaced with something pointing to the real location

**Comment by NoahTheDuke** [comment]
Here you go!
```
noah@Noahs-MBP ~
$ echo $PS1
\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w \[\e[1;34m\]\n$\[\e[0m\]
noah@Noahs-MBP ~
$ osh
  __bp_precmd_invoke_cmd
  ^~~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):1: '__bp_precmd_invoke_cmd' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
  ^~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '_direnv_hook' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
               ^~~~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '__posh_git_ps1' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '__iterm2_prompt_command' not found
  __bp_interactive_mode
  ^~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):3: '__bp_interactive_mode' not found
<Error: unbalanced \[ and \]> echo $PS1
\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w \[\e[1;34m\]\n$\[\e[0m\]
  __bp_precmd_invoke_cmd
  ^~~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):1: '__bp_precmd_invoke_cmd' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
  ^~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '_direnv_hook' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
               ^~~~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '__posh_git_ps1' not found
  _direnv_hook;__posh_git_ps1 "\\[\[\e[0;32m\]\u@\h \[\e[0;33m\]\w " " \[\e[1;34m\]\n\$\[\e[0m\] ";__iterm2_prompt_command
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):2: '__iterm2_prompt_command' not found
  __bp_interactive_mode
  ^~~~~~~~~~~~~~~~~~~~~
(source.PromptCommand spid:-1):3: '__bp_interactive_mode' not found
<Error: unbalanced \[ and \]>
```

and with a blank `.bash_profile` & `.bashrc`:
```
Noahs-MBP:~ noah$ echo $PS1
\h:\W \u\$
Noahs-MBP:~ noah$ osh
osh$ echo $PS1

osh$
```

**Comment by andychu** [comment]
OK yeah the issue is that it is being inherited.

If you do

```
PS1=''  # reset it first
osh
```

then you can avoid having to change `.bash_profile` or `.bashrc`.

I can see how this is confusing.  The way it works is that environment variables like `PS1` are inherited.  

Maybe we can make Oil not inherit, but that's a separate issue #498 

I think it will help if the errors are better, or maybe a section of the manual should say to reset `PS1`

**Comment by andychu** [comment]
Thanks for trying it and sending feedback!  I'll think about what to do here, but for now I think `PS1=''` should let you get past this error.   Let me know what else happens; I would like to put more things on this page:

https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

**Comment by NoahTheDuke** [comment]
excellent, thank you for the help!

**Comment by andychu** [comment]
(notes)

2 issues with source locations that would make some of the errors better

- PROMPT_COMMAND doesn't have span ID
- PS1 is apparently not attributed to anything, needs an `alloc.ctx_Location`

**Comment by andychu** [comment]
Improving the error messages:

https://github.com/oilshell/oil/commit/7c577c8746fe1f4a3a12bce6485884c4a04abb7a

Part of #993

**Comment by andychu** [comment]
Released last month https://www.oilshell.org/release/0.9.3/
